### ISSUE TITLE
Maps: Remove lat/lon and zoom customization options

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1005]
as a maps user, when i try to configure the options for the map, it's unclear what the options do. 

I assume they are to set the lat/lon and zoom defaults. If that's the case, we need to add additional text to clarify that. Instead of just "Latitude", we can say "Starting Latitude" and same for Longitude and Zoom.

![image](https://user-images.githubusercontent.com/4805997/112861792-fae1cd00-9069-11eb-9c6d-511f13a93432.png)

**Comment by Palakp41** [comment]
We highly recommend to remove this, it's the easiest and fastest option and least technically demanding.

**Comment by russorat** [comment]
let's remove these for now.
