### ISSUE TITLE
i would like to see the value of the marker on the map graph

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1006]
as a maps user, when i hover over a marker on the graph, i would like to see a hover legend of the data for that marker.

This would be helpful to understand the data at that point. for example, the magnitude of an earthquake or the information about a truck.

I see the ability to display a legend in the giraffe storybook: 
![image](https://user-images.githubusercontent.com/4805997/112862384-8fe4c600-906a-11eb-8ac8-e59aebd43f54.png)

**Comment by Palakp41** [comment]
Closed by: https://github.com/influxdata/ui/pull/1150
