### ISSUE TITLE
Maps: I'm unsure how the radius of the circle is configured

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1008]
as a maps user, when i select the circle configuration option, it isn't clear to me how the radius of the circle is generated. 

given i have a dataset that is compatible with maps
when i configure the circle map type
then i am able to choose a field to use as the size of the circle
then i am able to select the max number of pixels to use as the circle

# notes
we do not need to support a manual mapping of the size of the circle (the toggle from auto to manual in the screenshot below)

![image.png](https://images.zenhubusercontent.com/5b3fe490ebfac043864dcd28/fb4c29c9-f5aa-40ef-8d15-97fb90f6bdce)

![image](https://user-images.githubusercontent.com/4805997/112875857-9464ab00-9079-11eb-86a9-d419c25db85b.png)

**Comment by kristinarobinson** [comment]
Removing from MVP.  No circle or heatmap in MVP

**Comment by jzahnd** [comment]
@kristinarobinson do we want to keep this?

**Comment by wdoconnell** [comment]
Closing as removed from MVP for this feature.
