### ISSUE TITLE
Maps: I would like to configure the colors of the map markers based on a value

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1009]
as a maps user, when i define a set of points to use in the maps, i would like to configure a threshold to support colors in the markers.

the use case here is that i have geo data for earthquakes, and the magnitude of the earthquake is in the data, then i would like to show earthquakes < 2 as green, < 5 as orange, and > 5 as red.

GIVEN i have geo data in a compatible format
WHEN i open the maps graph options
THEN i can configure the color thresholds based on a value

**Comment by kristinarobinson** [comment]
Removing from MVP

**Comment by Palakp41** [comment]
Design from Bonitoo server: (Choosing Marker color threshold)
[Uploading... Screen Shot 2021-05-02 at 7.02.40 PM.png]
