### ISSUE TITLE
Multi-User Org Deletion

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#1012]
Given I am owner in an Org with more than one user
When I delete my org
Then the org is deleted
And all owners and members are notified

Remove myself:
Given: I am owner in an Org with more than one user
When: I view the team on the /user page
Then: I can remove myself from the Org
And: Other owners are notified that I've removed myself from the team

**Comment by wdoconnell** [comment]
User self-removal was added in [#4060](https://github.com/influxdata/ui/pull/4060)


Org deletion already existed for free accounts, and was added for contract and PAYG in the multi-org epic. https://github.com/influxdata/ui/pull/6379



![Image](https://user-images.githubusercontent.com/91283923/222761613-0c033fee-137a-482d-8ad4-a523494978bb.png)



![Image](https://user-images.githubusercontent.com/91283923/222761628-12326164-9b35-44ef-a4c2-e3f5897a91a0.png)
