### ISSUE TITLE
Local Storage fails when keys don't exist

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#1018]
### Background
When a new key is added to the redux store, it appears that the corresponding localState key doesn't get added properly. This is causing issues on tools with annotations enabled.

When Adam ran into this, I was able to inspect his local storage, and his `userSettings` didn't have the proper key `showAnnotationsControls`. It didn't exist. Because of this, react crashes when trying to access it.

![image.png](https://images.zenhubusercontent.com/5c33b08d24dda4712ef4ae10/0d1a9874-7d92-4325-8517-17b52bce9187)

**Comment by ChitlangeSahas** [comment]
[WIP] Current progress:

I'm able to reproduce this by:

1. clearing my localStorage in the browser console: `localStorage.clear()`
2. going to `src/userSettings/reducers/index.ts` and commenting out code that adds the new `showAnnotationsControl` key to the local storage.

**Comment by kristinarobinson** [comment]
@ShmuelLotman -- was this fixed?

**Comment by hoorayimhelping** [comment]
closed with https://github.com/influxdata/ui/pull/1020
