### ISSUE TITLE
Maps:  add the ability to select the field name to use for lat/lon

### ISSUE THREAD

**Issue by Palakp41** [influxdata/ui#1027]
as a user with geo data in my instance, the data might be stored as fields with different names than the maps widget expects.

Lat Lon Stored as ~Tag Values or~ Field Values
given i have data with latitude/longitude stored as fields
when I attempt to display that data as a map
then i would like the ability to choose the fields that contain that lat/lon data

~given i have data with latitude/longitude stored as tags~
~when i attempt to display that data as a map~
~then i would like the ability to choose the tags that contain the lat/lon data~

If the Lat Lon is not provided by the user, maps should display a friendly error and direct user to use customization options.

**Comment by kristinarobinson** [comment]
Removing from MVP
