### ISSUE TITLE
Maps: Ability to select tag for s2_cell_id 

### ISSUE THREAD

**Issue by Palakp41** [influxdata/ui#1029]
S2_cell_id stored as tag value ~or field values~
given i have data with the s2_cell_id calculated and stored as a tag value
when i attempt to display that data on a map
then i would like the ability to choose that s2_cell_id to use as the lat and lon values

~given i have data with the s2_cell_id calculated and stored as a field value~
~when i attempt to display that data on a map~
~then i would like the ability to choose that s2_cell_id field to use as the lat and lon values~

**Comment by kristinarobinson** [comment]
Removing from MVP
