### ISSUE TITLE
Community Template Import - bad url reloads data from previous import into popup values

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/ui#104]
### Build details

OSS Nightly build 

```
ts=2020-09-25T07:06:10.371504Z lvl=info msg="Welcome to InfluxDB" log_id=0PT1B8Gl000 version=2.0.0-beta.16 commit=838b3ea1b9 build_date=2020-09-25T05:17:55Z
```
Borwser: Chrome 85

### Steps to reproduce

In OSS

1. Open Settings > templates.
2. Paste the Docker url into the Community template Github URL input, look it up and import it (https://github.com/influxdata/community-templates/blob/master/docker/docker.yml)
3. Now Paste an invalid or broken URL into the Gitub URL Input. e.g. (https://github.com/influxdata/community-templates/blob/master/jenkins/jenkinz.yml)
4. Click "Lookup Template"

### Expected behavior

That the popup would load with empty  or zeroed values for Dashboards, Telegraf Confs, Buckets, etc.
That the header in the popup would not be green and would include information that the URL or file is not valid
That the Install Template button in the popup would be disabled

### Current behavior

The Template Installer popup contains data for the previously run Docker template import, and the Install Template button is green.  There is an indication that the URL or File is bad is in the notifications on the top right, but the popup values and controls do not reflect the same state. 

### Screencast

![CommunityTemplatesBadUrl01](https://user-images.githubusercontent.com/25881301/94281797-5d3d0200-ff4f-11ea-85fb-4b042c35826d.gif)

**Comment by jzahnd** [comment]
Closing due to age, we can reopen if needed.
