### ISSUE TITLE
Another CSP issue - can't read readme for community templates

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#1067]
I installed the earthquake community template, and when I click on 'view readme' I get an error in the Javascript console: Refused to connect to 'https://raw.githubusercontent.com/influxdata/community-templates/master/earthquake_usgs/readme.md' because it violates the document's Content Security Policy.

**Comment by russorat** [comment]
dupe of: https://github.com/influxdata/idpe/issues/9952
