### ISSUE TITLE
Flows: Fix the metric selector focus issue

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#111]
We tried to remove a scroll trap (where the page scrolls differently depending on where your mouse is) in the interface by hiding the  metric selector schema results when the panel loses focus. This was not the correct solution.

the solution here is open to interpretation. ideally we can solve both problems by picking from the raw data view ux and add some in memory pagination with a page resizer to the schema results, but i have no idea what's involved in that so just reverting that fix and adding the scroll trap back is also an option. 

Figure out a plan and go tell someone about it.

**Comment by desa** [comment]
This is no longer an issue
