### ISSUE TITLE
move k8s-idpe & monitor-ci tests to a separate pipeline

### ISSUE THREAD

**Issue by genehynson** [influxdata/ui#1112]
Currently the k8s-idpe tests in our CI are failing. This is because team-deployments revoked our ability to clone the k8s-idpe repo. Reason being because we were cloning a private repo in a public repo's CI.

The goal of this issue is to create a "private" instance of our circle-ci tests where k8s-idpe and monitor-ci can run the UI tests. The tricky part is that the results of these tests need to be visible to our open source contributors. 

_Note: The tests in question here are specifically the UI cypress tests which live [in the UI repo](https://github.com/influxdata/ui/tree/master/cypress). These are public tests but depend on monitor-ci & k8s-idpe to be run in an "e2e" capacity. We want to hide the usage of monitor-ci & k8s-idpe but provide visibility to test results._ 

Circle CI has a decent API available to us. I think we can use this to start the private pipeline, poll for status of private pipeline, and get the artifacts from the private pipeline. 

Here are some requirements to think about:
- failure of private pipeline should cause failure of public pipeline
- retrying a job in the private pipeline won't cause the public pipeline to report success automatically so it should be fast and easy to retry the public pipeline's failed job and have it "search" for a successful private pipeline before starting a new one
- if the private pipeline fails, the name of the failed job and its associated artifacts should be available to the public pipeline

**Comment by rbetts** [comment]
> if the private pipeline fails, the name of the failed job and its associated artifacts should be available to the public pipeline

 I'm unsure about the above requirement - a private test might have customer data or other private content (like unreleased / unannounced roadmap content, embargoed security issues, etc.).  
 
 If we're going to expose the private artifacts to the public pipeline anyway, what's the value of separating the pipelines?

**Comment by drdelambre** [comment]
the immediate value is that we can separate out the definition of the testing infrastructure from the code defining the service. currently, having those live next to each other in the open source repo means that we need to put ourselves in a position where we could potentially leak deployment keys and the like through pull requests. As k8s-idpe grows in complexity in a more distributed ownership model, it feels like that probability increases.

as far as private artifacts coming out of the pipeline, our current thinking is that the developer contributing to the repo would find value in knowing that their change on line 37 in component.file.tsx broke something somewhere else in the codebase. Should we be filtering / gating that information somehow? At what granularity should we be thinking about this?

**Comment by rbetts** [comment]
We should not / must not reveal private code or test artifacts to the public. To do so, we'd need to review what's there now, redact anything that's private, and then set a policy for engineers to not add new private information to the private test cases.

I know this hurts the OSS user experience and overall utility of CI for OSS contributors. However, we can't expose anything from our private repos without substantial auditing and process education.

**Comment by genehynson** [comment]
Totally agree! We don't want to expose any private tests or artifacts to the public audience.

The tests we're talking about here are explicitly the UI cypress tests which live in the open source UI repo. They have no private or customer data in them whatsoever. The "artifacts" in this case are simply the videos that cypress produces of its test failures.

Please correct me if I'm wrong but I don't see any harm in exposing the results of these tests which currently are publicly visible https://github.com/influxdata/ui/tree/master/cypress . We just want to hide the use of monitor-ci and k8s-idpe, not the execution of the tests

**Comment by genehynson** [comment]
Updated my original issue description to hopefully help make the scope of this work clearer

**Comment by rbetts** [comment]
@genehynson Ah - okay. That makes sense. I'm fine with that - let's remind cypress test authors not to use customer names / customer data, though :-)

**Comment by genehynson** [comment]
Absolutely, will do! So sorry for the confusion. The original description of this issue was confusing - my bad!
