### ISSUE TITLE
Deprecated v1.fieldsAsCols() in UI Check

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/ui#1114]
Hello all, 
When generating a threshold or deadman check through the UI, the underlying tasks contains the deprecated v1.fieldsAsCols() instead of [schema.fieldsAsCols()](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb-schema/fieldsascols/). 

```
curl -X GET \
  https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/checks/074bb...my_check_ID...000/query \
  -H 'authorization: Token OeRbD….my_token...WbOh8Bg==' \
```
Escaped json result of query: 
```
package main 
import "influxdata/influxdb/monitor"
import "influxdata/influxdb/v1"

data = from(bucket: "telegraf")
|> range(start: -5s)
|> filter(fn: (r) =>(r["_measurement"] == "cpu"))
|> filter(fn: (r) =>(r["_field"] == "usage_system"))
|> filter(fn: (r) =>(r["cpu"] == "cpu-total"))
|> aggregateWindow(every: 5s, fn: mean, createEmpty: false)

option task = {name: "CPU Check", every: 5s, offset: 0s}
check = {_check_id: "074bba32a48c3000", 
  _check_name: "CPU Check",
  _type: "threshold",
 tags: {},}

crit = (r) =>r["usage_system"] > 5.0)
messageFn = (r) =>("Check: ${ r._check_name } is: ${ r._level }")

data
|> v1["fieldsAsCols"]()
|> monitor["check"](data: check, messageFn: messageFn, crit: crit)
```

**Comment by russorat** [comment]
the UI doesn't actually generate the flux for these, although there are a few tests that should get updated.

i've opened issues in the other repos where the code is actually generated.

**Comment by kristinarobinson** [comment]
We do actually use v1.fieldsAsCols in the deadman check code.  Here is the link:
https://github.com/influxdata/ui/blob/784b7d4b698e9542624f7e4f25c5bd5c01adb6dc/src/alerting/utils/customCheck.ts#L74

Also there is one unit test for this file as well that should be updated.
