### ISSUE TITLE
Notebooks: Export to dashboard presents randomly-ordered list of dashboards

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#1116]
[I thought I filed this on Friday but can't find it, so if this is duplicate, please close it.]

In notebooks, select 'export to Dashboard', then 'Update Existing', then 'Choose a dashboard'.  The list of dashboards is in random order. In an environment like tools, where there are a ton of dashboards, it makes it really hard to find the one you want. Would be better if the list was in alphabetical order.

**Comment by genehynson** [comment]
This PR resolved this issue: https://github.com/influxdata/ui/pull/1457
