### ISSUE TITLE
When hover legend is long, it's really hard to click on the annotation

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#1119]
I have a graph with a very long tooltip.  When I try to select the annotation, it's hard to select it because the tooltip gets in the way.  See screenshot (or you can see it in the tools cluster in Barbara's test dashboard, on the Api Request Totals cell.
![Screen Shot 2021-04-05 at 12 28 13 PM](https://user-images.githubusercontent.com/13143006/113624059-07d76100-9614-11eb-8542-1187d68ab574.png)

**Comment by jrenee42** [comment]
work around is to turn the hover legends off; now that we have that capability.

is this sufficient?  because fixing this (setting the z values) may be non-trivial)

@russorat; please comment.
