### ISSUE TITLE
Flows: Data Exploder

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#112]
As an early access flows user, I want to start playing with data as soon as possible and don't yet know the available cell types or how to add them.

GIVEN I am on the flows index page
WHEN I click `Create Flow`
THEN I see a new flow that already has a `Input from Bucket` cell and a `Visualization Cell`

We got feedback from user testing!

there's a bit of a hurdle when we drop a user into a new flow. once they see how it works, they seem to get it, it's just that first jump is too big of a divide. There's two things that need to happen for this.

1) when a user creates a flow, prepopulate it with a metric selector with nothing selected in it, and a visualization pipe with all the defaults it already contains.

[Design Mock](https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=885%3A6)

**Comment by alexpaxton** [comment]
Created this issue to handle explaining flows to first time users (instead of a markdown cell): https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/ui/144

**Comment by drdelambre** [comment]
this one keeps getting blocked for the same reason... here's the context:
we need ids for each of the pipes. we can either keep the crud super simple and have the ui
 1. create the notebook
 1. create a metric selector pipe and attach it to the notebook
 1. create a visualization pipe and attach it to the notebook

_or_

1. allow for the creation of a notebook with pipes defined, and have the backend create those object for you, sending back a populated notebook object with all the ids populated in it.

needs to be brought up with whoever is working on influxdata/idpe#8685 to make sure whatever choice that is made is captured within the acceptance criteria for the api, and not just in the frontend implementation.

**Comment by mnorriswalker** [comment]
To start, let's do an object graph and dump it into a single field.
