### ISSUE TITLE
Annotations: Fails silently if text is too long

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#1120]
Create an annotation with the following string:
This is a very long annotation - let's see what happens. This is a very long annotation - let's see what happens. This is a very long annotation - let's see what happens. This is a very long annotation - let's see what happens. This is a very long annotation - let's see what happens. This is a very long annotation - let's see what happens. This is a very long annotation - let's see what happens. This is a very long annotation - let's see what happens. 

You will get no error, but the annotation will not appear.  In the javascript console I see:

```
createError.js:16 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.h.onreadystatechange (xhr.js:62)
e.exports @ createError.js:16
e.exports @ settle.js:17
h.onreadystatechange @ xhr.js:62
async function (async)
(anonymous) @ thunks.ts:40
(anonymous) @ index.js:8
e @ view.tsx:188
onSubmit @ AddAnnotationOverlay.tsx:21
onSubmit @ AnnotationForm.tsx:38
onSubmit @ Form.tsx:67
s @ react-dom.production.min.js:14
h @ react-dom.production.min.js:15
(anonymous) @ react-dom.production.min.js:15
S @ react-dom.production.min.js:17
M @ react-dom.production.min.js:18
A @ react-dom.production.min.js:18
E @ react-dom.production.min.js:21
xn @ react-dom.production.min.js:84
js @ react-dom.production.min.js:250
Ye @ react-dom.production.min.js:39
Mn @ react-dom.production.min.js:86
(anonymous) @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ns @ react-dom.production.min.js:251
Tn @ react-dom.production.min.js:85
Object.isExtensible.Object.isExtensible.e.___hb.e.___hb @ honeybadger.js:466
```

**Comment by ChitlangeSahas** [comment]
The longest I could go is 

`Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one!`

**Comment by hoorayimhelping** [comment]
fixed with: https://github.com/influxdata/ui/pull/1127
