### ISSUE TITLE
Annotations: Multiline messages get un-multilined

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#1124]
### Background
When writing a multiline annotation, the text gets flattened to a single line.

More generally, text formatting seems to be stripped.

What is the expected behavior here?

**Comment by daviddkkim** [comment]
Chatted with Bucky but writing down here for the sake of documentation:
- We explored the option of defining a static width around 200~300px, long texts becoming multiline texts. 
- Markdown formatting maybe being a future implementation rather than mvp (?)
