### ISSUE TITLE
Security: Upgrade Immer from v1 to V8

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#1142]
This PR is failing:

https://github.com/influxdata/ui/pull/907

We're 7 major versions behind the latest. We need to upgrade because of high security vulnerabilities.

**Comment by zoesteinkamp** [comment]
I can actually see gene is working on this from this pr 

https://github.com/influxdata/ui/pull/907/files

Gene feel free to delete this if its a duplicate issue

**Comment by kristinarobinson** [comment]
Fixed.
