### ISSUE TITLE
Individual cell/chart search and opening

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#1162]
I’d love to have a search for charts/cells by name. I.e. I can prefix search across all dashboards for a particular cell. Then I can open the containing dashboard OR just open that cell & flux perhaps in explore, to avoid loading a whole dashboard when I just want a part of it.

**Comment by kristinarobinson** [comment]
Going to be addressed in the Query experience intiative.

**Comment by philjb** [comment]
> Going to be addressed in the Query experience intiative.

@kristinarobinson do you have a link to the initiative?
