### ISSUE TITLE
I would like to add a telegraf input configuration to an existing telegraf config

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1170]
GIVEN that i am on a telegraf data sources page (/orgs/:id/load-data/telegraf-plugins/activemq for example)
WHEN i see the example telegraf config
THEN i have an option to add that to an existing telegraf config

![image](https://user-images.githubusercontent.com/4805997/114244343-20f94e00-9943-11eb-85d8-962355508b85.png)

**Comment by kristinarobinson** [comment]
Replacing with more detailed issues, based on wireframes: 
https://app.zenhub.com/workspace/o/influxdata/ui/issues/1555
https://app.zenhub.com/workspace/o/influxdata/ui/issues/1556
https://app.zenhub.com/workspace/o/influxdata/ui/issues/1557
