### ISSUE TITLE
I would like to create a new telegraf configuration from a telegraf data sources page

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1172]
GIVEN that i am on a telegraf data sources page (/orgs/:id/load-data/telegraf-plugins/activemq)
WHEN i see the example configuration
THEN i am able to create a new telegraf configuration based on that input
THEN i am taken to a page to edit the config that contains the input plugin, the output config for my cloud instance
THEN the name of the new configuration is the name of the Input plugin

**Comment by kristinarobinson** [comment]
Replaced by issues:
https://app.zenhub.com/workspace/o/influxdata/ui/issues/1555
https://app.zenhub.com/workspace/o/influxdata/ui/issues/1556
https://app.zenhub.com/workspace/o/influxdata/ui/issues/1557
based on figma:
https://www.figma.com/file/hMUcxA5RdoEhdJLvClWWB7/Agent-Configuration?node-id=0%3A1
