### ISSUE TITLE
I would like a way to select a bucket to use for a new telegraf configuration

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1173]
GIVEN that i am on the telegraf load data source page (/orgs/:id/load-data/telegraf-plugins/activemq)
WHEN i create a new telegraf config from that page
THEN i am able to select a bucket to use for that configuration

**Comment by kristinarobinson** [comment]
Reducing scope of issue to just bucket, and creating another for token (https://github.com/influxdata/ui/issues/1547).

**Comment by kristinarobinson** [comment]
Ended up replacing with Telegraf Refresh: Add Bucket--From Plugin, Create Mode
 https://app.zenhub.com/workspace/o/influxdata/ui/issues/1555
