### ISSUE TITLE
Display bucket selection and all Telegraf plug-ins as options for Create Config dialog on Telegraf page.

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1174]
In the modal that opens when you create a new telegraf config, we show these 5 options.

![image](https://user-images.githubusercontent.com/4805997/114245201-d973c180-9944-11eb-8470-be5968580384.png)

GIVEN i am on the telegraf config page
WHEN i click the create telegraf button
THEN i am presented with the same list of plugins as the data sources page, with System as the first option, and the rest listed in alphabetical order AND an option to choose a bucket.

https://www.figma.com/file/hMUcxA5RdoEhdJLvClWWB7/Agent-Configuration?node-id=263%3A179

**Comment by kristinarobinson** [comment]
Replaced with Telegraf Refresh: Select Bucket and Plugin --Create from Telegraf Page:
https://app.zenhub.com/workspace/o/influxdata/ui/issues/1739
