### ISSUE TITLE
Retriggering CircleCI Pipeline from Failed State Blocks Merging

### ISSUE THREAD

**Issue by subirjolly** [influxdata/ui#1178]
Github/CircleCI blocks merging when the pipeline fails and you run the pipeline from the failed state and the pipeline succeeds.

**Expected behavior:**
Github/CircleCI should allow merging when the pipeline succeeds after being retriggered from the failed state.

**Comment by genehynson** [comment]
This shouldn't be the case. This sounds like a CircleCI bug to me. Do you have an example of this happening @subirjolly? @gaughen have you seen this behavior or heard of others complaining about it?

**Comment by gaughen** [comment]
I'd love to get a pointer to the circle job where you saw this.  (I'm assuming this is the UI CI not idpe).  I have not had reports of this. In IDPE we've had issues where folks restart from fail but it's not the job that circle is watching, so we've attempted to improve our flow and also error messages to make it more clear.

**Comment by subirjolly** [comment]
I had this issue with the [PR I merged today](https://github.com/influxdata/ui/pull/1160). But in that PR, later on retriggering the pipeline worked fine and github identified as a successful job. So, it might be a github hiccup.

We should be able to close this for now and if we see this behavior again then we can reopen it.

**Comment by gaughen** [comment]
Thanks Subir!
