### ISSUE TITLE
Change Circle pipeline to use containers rather than VMs where applicable

### ISSUE THREAD

**Issue by genehynson** [influxdata/ui#1186]
CircleCI config uses `machine` rather than `docker`. This is expensive and slow. Our e2e tests might need their own VM, but jobs like `build-image`, `build-oss-image`, `cloud-lighthouse`, etc probably can run in a container just fine. Let's test it and find out!

https://circleci.com/docs/2.0/executor-types/#docker-benefits-and-limitations
https://circleci.com/pricing/#comparison-table

**Comment by wdoconnell** [comment]
Closing - this was resolved by https://github.com/influxdata/ui/pull/1311, which removed the references to `machine`.
