### ISSUE TITLE
404 page has an accessibility issue with its H1

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#119]
### Issue
The 404 page has an `h1` that says 404. The `h1` here is an accessibility issue since it conflicts with another `h1` that should take precedence.

### Acceptance Criteria
- the NotFound page's heading is an H2 or smaller
- the NotFound page is hidden from screen readers and automated tools
  - [`aria-hidden`](https://www.accessibility-developer-guide.com/examples/sensible-aria-usage/hidden/) might be viable
  - changing the logic to render nothing, rather than a hidden 404 page might be better

**Comment by drdelambre** [comment]
the 404 shows when we hit a page level error boundary as well, so totally for fixing the issue of it being on the page, but i'm gonna go out on a limb here and say this will be the least of someone's worry if they try to use a time series visualization app on a screen reader. is there a bigger story here we're trying to surface to product or should we change the acceptance criteria to "only show the 404 when we have a malformed url"?
