### ISSUE TITLE
logout passes through 404 page before reloading to login

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/ui#120]
as a user, attempting to logout, the UI cycles through a 404 page before actually logging out. 

![Kapture 2020-09-28 at 17 42 25](https://user-images.githubusercontent.com/10937678/94499951-d5efc880-01b2-11eb-8f10-12025dcf2eee.gif)

**Comment by drdelambre** [comment]
doesn't seem to be happening anymore, at least on us-west
![Screenshot from 2021-03-03 09-50-30](https://user-images.githubusercontent.com/1434802/109849311-17731c80-7c06-11eb-972e-33b2648f4097.png)
