### ISSUE TITLE
I would like to quickly jump to a resource by id

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1217]
We are limited in pagination from our APIs, but we can quickly build urls and jump to specific resources.

This issue would add the ability to enter an ID into the existing filter boxes, and jump directly to editing that resource.

We should add this anywhere there is a filter box in our app, starting with the following pages:

- Buckets
- Tasks
- Checks
- Dashboards

If we detect a user has entered a resource id (16 characters, hex) then we attempt to build a url for that resource and check that it exists. if it does, we provide a link to that resource.

**Comment by kristinarobinson** [comment]
Superseded by pagination implementation.
