### ISSUE TITLE
Epic: Annotation Range, Additional Graph Types, Notifications

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#1244]
### Target Customer / Background data / Context / Market Size
The application builder trying to highlight deployment or outages to their team members.

### Goals
The goal here is to complete the custom annotation story by adding ranged annotations, custom colors, and support for additional graph types.

### Acceptance Crit
- As a user, I would like to create an annotation with a start and a stop time.
- As a user, I would like to edit an annotations start or stop time
- As a user, I would like the format of the stop time to match the format of the start time
- ~As a user, I would like to customize the color of the annotation~
- As a user, I would like to add a single or ranged annotation to Graph plus Single Stat, XY-plot, and Stacked
- As a user, when i click on a graph type that is not supported, I would like to see a notification telling me it is not supported

### Design Notes
- ~Leverage the same color picker as used in labels~
- The area between the start and stop lines should be lightly shaded, similar to the "shade under lines" option
- Range should be selected by a click and drag motion, similar to zooming in on a graph today.
- A slight highlight should be shown in real time, similar to zooming in on a graph today.
- The modal should have the option to add an end time when editing a single point. If an annotation is started with the click to drag motion described above, the user should be able to uncheck that box and convert it to a single point.

### Release Plan
Release internally behind a feature flag for testing, then enable for all cloud users.

### Team
 - Anchor / Dev Champion: @hoorayimhelping 
 - Product Manager: @russorat 
 - Design: @daviddkkim

**Comment by daviddkkim** [comment]
Using the same colorpicker as the label sounds good. We can provide them a slightly different pre-defined palette to fit the theme of annotations

**Comment by daviddkkim** [comment]
The range selection motion will be an interesting consideration. The most intuitive one is probably the click and drag but that one coincides with our "zoom" motion. Other motions I can think of is dragging while pressing command.

**Comment by daviddkkim** [comment]
https://www.figma.com/file/AQk0tUthLFepRhFUibvzMI/Annotations?node-id=783%3A963 
annotation range
