### ISSUE TITLE
Tokens and Secrets UI

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#1262]
### Target Customer / Background data / Context / Market Size
TBD

### Goals
Allow users to easily access and edit tokens and secrets with a clean and intuitive UI.

### Acceptance Criteria
TBD

### Release Plan
TBD

### Team
 - Anchor / Dev Champion: @joelfried 
 - Product Manager:  
 - Design:

**Comment by russorat** [comment]
@jzahnd can we use this Epic? https://github.com/influxdata/ui/issues/777

**Comment by russorat** [comment]
And this epic: https://github.com/influxdata/ui/issues/805
