### ISSUE TITLE
Annotations: Timestamp format should be the same on create and edit screens

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1264]
The timestamp format should be the same format the user sees in the hover legend, and it should respect the Local vs UTC option the user has selected.

This is the format on create:
![image](https://user-images.githubusercontent.com/4805997/115493345-6ad21600-a218-11eb-84f6-1a844575992a.png)

and this is the format on edit:
![image](https://user-images.githubusercontent.com/4805997/115493360-76254180-a218-11eb-9ad3-09f8e0cee218.png)

**Comment by hoorayimhelping** [comment]
closed with #1232
