### ISSUE TITLE
Annotations: Attempting to edit the time results in invalid date

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1266]
I tried to edit the time in an annotation, and anytime i made a change, it moved my cursor to the end of the time. Then i tried to delete a space, and the entire date was replaced with the text "invalid date"

The expectation is that the data should be editable and the validation should happen when the user tries to save the annotation or when the focus moves to another input.

![Kapture 2021-04-20 at 20 56 49](https://user-images.githubusercontent.com/4805997/115494689-ff3d7800-a21a-11eb-8e3e-23e68259a02c.gif)

**Comment by ChitlangeSahas** [comment]
This was closed in #1282
