### ISSUE TITLE
Epic: Account Switching

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#1287]
**Goal**
Allow User to Select Between Existing Accounts

Assumptions:
Default Account is provided

**Accept Criteria**
As a user, I want to be able to see a `Switch Account` button on the `Account Page`, when I click `About` Accounts, only if I have more than one account.

As a user, I want to be able to see a list of all accounts, when I click on the `Switch Account` button.

As a user, I want to be able to determine which of my accounts is the default by seeing an indicator.

As a user, I want to be select a new account to view from my list of accounts.  This will reload all resources in the UI from the new account (which may be redirected to and loaded from a different cluster).

As a user, I want to be able to change the default account.

As a user, I want to see the Billing Page from the Accounts Nav Page.

**Design Considerations**
https://www.figma.com/file/MP95t0O5zSKUVQ7vwrkOaj/Design-Cycle-Q2?node-id=1048%3A8448

Large Epic for Account Switching:
https://app.zenhub.com/workspaces/applicationui-5e3b05772922e316b3a210a4/issues/influxdata/influxdb/21222

Large Epic for UI Multi-User/Multi-Account UI:
https://app.zenhub.com/workspaces/applicationdumplings-60a80d872533670017a6b107/issues/influxdata/ui/1626

**Team**
Dev Lead: Jill Pelavin
Design: John Corrigan/David Kim
Product: Gunnar Aasen

**Comment by corriganjohn** [comment]
"As a user, I want to be able to view my accounts by clicking on the Account item from the Account Nav Bar menu, **only if more than one account is available**."

The 'Workspace' (account) navigation will need to be ALWAYS visible (NOT 'only when more than one account is available). We will have additional functions in that navigation that need to be accessible even when the user is only associated (currently) with one workspace/account.

- 'Create new workspace' function 
- (?) /Billing page navigation may need to move here -- this now becomes an account-level function, not an organization-level function

**Comment by jrenee42** [comment]
note: changed the design figma link to: https://www.figma.com/file/MP95t0O5zSKUVQ7vwrkOaj/Design-Cycle-Q2?node-id=1048%3A8448
was: https://www.figma.com/file/MP95t0O5zSKUVQ7vwrkOaj/Design-Cycle-Q2?node-id=966%3A8364

in consultation with @daviddkkim
