### ISSUE TITLE
I would like to create an annotation with a start and a stop time

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1295]
GIVEN i am on a dashboard with one click annotations enabled
WHEN i click and drag across a supported graph type
THEN i am presented with a modal that contains a start time, stop time, and a blank field for a message
THEN the start and stop time are filled in with the timestamps of the start and stop of the click and drag motion rounded to the nearest point

Design Notes
 - The stop time should not be displayed if i have clicked on a single point on the graph. There should be a way to convert a single point annotation to a ranged annotation and back again.
 - The timestamps of the start and end time should match the timestamps of the graph

**Comment by daviddkkim** [comment]
@russorat Click and drag motion coincides with our "Zoom in" motion. I think we will have to do "click an existing annotation and drag across"

**Comment by kristinarobinson** [comment]
fulfilled by giraffe#585 & ui#1417
