### ISSUE TITLE
I would like to edit an annotations start or stop time

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1296]
GIVEN i am on a dashboard with a ranged annotation
WHEN i click on the ranged annotation
THEN i am presented with a modal that allows me to edit the start, stop or message of the annotation

### Design Notes
- The timestamps in the modal should be formatted the same as the graph axis
- The timestamps should be validated when focus moves away from them or when the annotation is saved.

**Comment by kristinarobinson** [comment]
fulfilled by ui#1417
