### ISSUE TITLE
I would like to customize the color of the annotation

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1297]
GIVEN that i am on a dashboard with one click annotations enabled
WHEN i click to add a single or ranged annotation
THEN i am able to customize the color of the annotation

WHEN i click on an existing annotation to edit it
THEN i am able to customize the color of the annotation

### Design Notes
- The color picker should be similar to the lable color picker
- A default color should be selected (same green as now is ok)

**Comment by kristinarobinson** [comment]
Won't fix.  Aging out.
