### ISSUE TITLE
when i click on a graph type that is not supported, I would like to see a notification telling me it is not supported

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1300]
GIVEN that i have one click annotations enabled
WHEN i click on a graph type that is not supported
THEN i am shown a temporary notification that the graph type is not supported yet.

### Design Notes
- This should remove the static text in the annotation bar in favor of the notification being fired.
- We should ensure this doesn't block the ability to copy text from a table graph or static legend

**Comment by kristinarobinson** [comment]
close as dupe of #1431
