### ISSUE TITLE
Dashboard Auto-Refresh Only Runs Every 10 Minutes

### ISSUE THREAD

**Issue by centja1** [influxdata/ui#1331]
Steps to reproduce:
List the minimal actions needed to reproduce the behavior.

1. Open or create a dashboard with a query in a cell
2. Set auto-refresh to an interval

Expected behavior:
Expect all cells on the dashboard to refresh the time window and query in the specified interval

Actual behavior:
The visualization itself appears to refresh and extend the x-axis, but no new data appears.  Watching the Firefox debugger window, the queries appear to refresh every 10 minutes, regardless of the interval specified.

The auto-refresh appears to function appropriately when using Data Explorer

Environment info:

* System info: Docker 20.10.6, Ubuntu 20.04.2
* InfluxDB version: 2.0.5

**Comment by ShmuelLotman** [comment]
https://github.com/influxdata/ui/pull/1569 and the PR's before it that worked on auto-refresh should address this issue. I've tested in OSS and ive been able to select my desired rate, and confirmed it refreshes at that rate. Hoping once this makes it into Prod we can confirm that for the end users experiencing this issue.

**Comment by centja1** [comment]
This appears to be resolved in the 2.0.7 docker image.  Thanks for the help!
