### ISSUE TITLE
Notebooks: I can see all the options for a panel in a side menu

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#1337]
When: I have click on a notebook cell
Then: I see the notebook cell highlighted with an active stroke
And: A side menu with options that are specific to that panel

### Design Notes

Work in Progress:
https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=2236%3A3

Spreadsheet of panel content:
https://docs.google.com/spreadsheets/d/1pYjS8CJhnFoNxtNzREOoSDQrhJAYyPdOEYsXW7L3OYA/edit#gid=0

Dropdown component for reference: https://influxdata.github.io/clockface/?path=/story/components-dropdowns-family--dropdownmenu

Icons used in Panel Menu: 
`Export`
`Cog Solid`
`Eye Open`

Panel selection interaction:
- Any click event in the child of the DOM should bubble up to the parent
- A child click event should be able to make the entire panel active and trigger the panel menu
- We would need to remove any explicit no click event Javascript overrides if there are any, such as stop propagation or prevent default

**Comment by drdelambre** [comment]
can we see more design encompassing the visualization configuration (view options, aggregate selections, etc)? I'm having a hard time structuring the navigation hierarchy of the more complex panel types.

**Comment by mnorriswalker** [comment]
@drdelambre yep! We actually broke out [visualization configuration settings ](https://github.com/influxdata/ui/issues/1339)and `[inject functions panel](https://github.com/influxdata/ui/issues/1338)` as separate issues for the submenus. We're planning to do more design on the visualization one specifically. That's why it has the `needs/design` tag

**Comment by juliajames12** [comment]
@drdelambre After speaking with the rest of the design team, they provided some suggestions on how to handle the panel selection interaction. I just added some notes on it at the end of this issue. Let me know if you think this approach will work!
