### ISSUE TITLE
Notebooks: I can see dashboard setting in a submenu

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#1339]
Given: I have a notebook with a visualization panel
When: I click `customize` on the panel menu
Then: I can see the options to customize my visualization type in a submenu

When: I see the customization submenu
Then: I fixed height relative to the panel (~600-900 px)
And: I can scroll to see all options

When: I click back
Then: I got to the panel menu

#### Design Notes

Prototype
https://www.figma.com/proto/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=2715%3A3&scaling=min-zoom&page-id=1915%3A0

Working File
https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=2502%3A12290

**Comment by drdelambre** [comment]
this work is done outside of the `Then: I fixed height relative to the panel (~600-900 px)` part, which i dont understand

**Comment by mnorriswalker** [comment]
@drdelambre awesome sauce! We got some feedback that the side menus go too long and so we just though to do a fixed height and have the side menus scroll. If it doesn't make sense - ignore! And we can just pair on the interaction if needed.
