### ISSUE TITLE
UI: api/v2 routes are exposed

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#1348]
navigating to https://us-west-2-1.aws.cloud2.influxdata.com/api/v2

Exposes the available routes: ![Screen Shot 2021-05-03 at 4.27.47 PM.png](https://images.zenhubusercontent.com/5c33b08d24dda4712ef4ae10/03935c67-7c37-4b15-af4b-d605cb22a7d1)

it should show a 404 page like  https://us-west-2-1.aws.cloud2.influxdata.com/api/

**Comment by russorat** [comment]
This page shouldn't 404. These are all public APIs and this is a way to discover them.
