### ISSUE TITLE
Community Templates: replace honeybadger calls with event calls

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#1359]
### Background
Honeybadger hasn't been super helpful in community templates. Using the frontend metrics system will server us just as well.

### Acceptance Criteria
- Replace the calls to honeybadger with `event`. This could be through the existing event system or through a new system such as amplitude. 
- Text currently used in the honeybadger calls, what should these be changed to?
  - [`The community template getTemplateDetails failed`](https://github.com/influxdata/ui/blob/master/src/templates/containers/CommunityTemplatesIndex.tsx#L255)
  - [`The community template fetch stack failed`](https://github.com/influxdata/ui/blob/master/src/templates/components/CommunityTemplatesInstalledList.tsx#L68)
  - [`The community template delete failed`](https://github.com/influxdata/ui/blob/master/src/templates/components/CommunityTemplatesInstalledList.tsx#L98)
  - [`The community template fetch for preview failed`](https://github.com/influxdata/ui/blob/master/src/templates/components/CommunityTemplateInstallOverlay.tsx#L103)
  - [`Failed to install community template`](https://github.com/influxdata/ui/blob/master/src/templates/components/CommunityTemplateInstallOverlay.tsx#L128)
  - [`The community template rename failed`](https://github.com/influxdata/ui/blob/master/src/templates/components/CommunityTemplateInstallOverlay.tsx#L149)

**Comment by kristinarobinson** [comment]
Link this to new epic for adding Amplitude event.

**Comment by wdoconnell** [comment]
Closing this, as Amplitude has been removed now. https://github.com/influxdata/ui/pull/6471
