### ISSUE TITLE
Flaky Test: can create an annotation that is scoped to a dashboard cell

### ISSUE THREAD

**Issue by genehynson** [influxdata/ui#1370]
the test **can create an annotation that is scoped to a dashboard cell** is flaky.

Source: https://github.com/influxdata/ui/blob/master/cypress/e2e/cloud/annotations.test.ts#L252

Example:
- https://app.circleci.com/pipelines/github/influxdata/monitor-ci/773/workflows/8c06d1f7-4034-46ea-9af0-59b4afd5824b/jobs/6692
- https://app.circleci.com/pipelines/github/influxdata/monitor-ci/769/workflows/1cd146bd-53a0-4e0c-8c90-786d3e6ae345/jobs/6663
- https://app.circleci.com/pipelines/github/influxdata/monitor-ci/998/workflows/3c8c1405-c7eb-4f62-bfab-b9f25413adca/jobs/8690
- https://app.circleci.com/pipelines/github/influxdata/monitor-ci/1204/workflows/28a750a5-8f34-4c7a-a996-b42096ba2e23/jobs/10243/artifacts

![image](https://user-images.githubusercontent.com/6411855/117337318-13f05180-ae52-11eb-907d-74286cdc5201.png)

**Comment by ShmuelLotman** [comment]
Reopening - still seeing the failures on this test: https://app.circleci.com/pipelines/github/influxdata/monitor-ci/1799/workflows/f321cd0c-d5b2-409c-875a-8ae461c4eed3/jobs/15198

**Comment by genehynson** [comment]
Another failure: https://app.circleci.com/pipelines/github/influxdata/monitor-ci/1928/workflows/a887c6e9-a2d8-47e2-862b-9950f1efec1f/jobs/16254
