### ISSUE TITLE
Notebooks: I can see last modified on the notebook list item

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#1379]
We would like the ability to view the last modified time on a notebooks list item. This would apply to each notebook in the current notebooks list and would use the existing list item UX. 

(ignoring last completed at and the id in this example)
![image.png](https://images.zenhubusercontent.com/5fdbca6b688d8a81424e922b/03b728a7-48cc-4bac-90f1-5e5d8cd3b607)

### Acceptance Criteria

- When viewing the notebooks list page, every notebook list item has a 'Last modified' time.

**Comment by jzahnd** [comment]
Closing this issue in favor for new upcoming UX.
