### ISSUE TITLE
Notebook: I can add labels on the notebooks list item

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#1380]
We would like the ability to add labels to a notebooks list item from with in the notebooks list view. We can reuse the current list and label UX from other list views in the application. 

![image.png](https://images.zenhubusercontent.com/5fdbca6b688d8a81424e922b/92e757f2-60c0-46a3-be0a-59b86a713a17)

### Acceptance Criteria

- Users may add labels to any notebook list item in the notebook list view.

**Comment by jzahnd** [comment]
We need to engage team compute to address this issue as we need notebooks to be a resource to add labels.

**Comment by russorat** [comment]
@jzahnd could you connect the issue blocking this work?
