### ISSUE TITLE
Flaky Test: should populate and load populated Alerts Activity dashboard

### ISSUE THREAD

**Issue by genehynson** [influxdata/ui#1400]
The test `should populate and load populated Alerts Activity dashboard` is flaky.

Source: https://github.com/influxdata/ui/blob/master/cypress/e2e/cloud/home.test.ts#L31

Examples:
- https://app.circleci.com/pipelines/github/influxdata/monitor-ci/930/workflows/5f6573af-5db4-4f35-b4e4-847d30fb5aef/jobs/8143/parallel-runs/8
- https://app.circleci.com/pipelines/github/influxdata/monitor-ci/942/workflows/b24562ec-16c9-40f8-b333-60c75a5fad1d/jobs/8279
- https://app.circleci.com/pipelines/github/influxdata/monitor-ci/998/workflows/3c8c1405-c7eb-4f62-bfab-b9f25413adca/jobs/8690/parallel-runs/8?filterBy=FAILED

![image](https://user-images.githubusercontent.com/6411855/118015060-ba33cf80-b308-11eb-9ee7-abe5748cea42.png)

<img width="1573" alt="Screen Shot 2021-05-12 at 10 04 07 AM" src="https://user-images.githubusercontent.com/6411855/118015816-8ad19280-b309-11eb-98b3-347586ca5b67.png">

**Comment by drdelambre** [comment]
i think subir started looking into this yesterday, so i updated all of the tags.

**Comment by subirjolly** [comment]
I tried debugging this a lot. In monitor CI it was working all the time. It was not working most of the times in k8s. Not sure what is going on and I could not get any success yesterday. I might continue working on this on Monday. If anybody wants to pick this up today, feel free to pick it up.

**Comment by genehynson** [comment]
Looks like it's failing in monitor-ci too: https://app.circleci.com/pipelines/github/influxdata/monitor-ci/1930/workflows/78dcad57-6508-4c41-aca4-81dca6875112/jobs/16276

**Comment by genehynson** [comment]
@subirjolly has resolved this, closing
