### ISSUE TITLE
Change Telegraf agent settings for default system config for free tier users

### ISSUE THREAD

**Issue by sjwang90** [influxdata/ui#1406]
GIVEN that I am a free tier cloud user on the default Telegraf system data source page  (/orgs/:id/load-data/telegraf-plugins/default)
WHEN i create a telegraf config 
THEN the agents settings will be set as `interval = 20s ` so I don't immediately go over the free tier

GIVEN that I am a paid cloud user on the default Telegraf system data source page  (/orgs/:id/load-data/telegraf-plugins/default)
WHEN i create a telegraf config 
THEN the agents settings will continue to be the same as they are currently/how they exist in the default [telegraf.conf](https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf)

**Comment by TCL735** [comment]
There is a relatively easy way to do this on the frontend, but it may be better to do this on the backend. Will investigate.

**Comment by TCL735** [comment]
We can do this in one of two ways:
- use the backend to insert the agent settings according to the user's tier
  - this is fairly difficult and requires significant re-working of the backend api to check the user's tier when we handle an api call to create a new telegraf configuration. harder solution of the two options
- use the frontend to update the agent settings during creation according to the user's tier
  - this is fairly easy but adds another responsibility to the frontend for the maintenance of correct telegraf configuration creation, although relatively minor. easier solution of the two options

**Comment by TCL735** [comment]
We will proceed with the frontend option.
