### ISSUE TITLE
Auto-refresh enhancements and UI feedback

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1413]
### Target Customer / Background data / Context / Market Size
Developers who want to keep a dashboard up and refreshing throughout the day

### Goals
The goal of this epic is to polish some of the UX with the auto-refresh feature so that we can turn it on for production.

### Acceptance Crit
- as a user, i would like auto refresh to pause if the dashboard page is not visible on the screen (hidden tab, window covered, browser minimized).
- as a user, i would like to view the current auto refresh settings when auto refresh is enabled.
- as a user, i would like to edit the current auto refresh settings when auto refresh is enabled.
- as a user, i would like the ability to manually refresh if needed while auto refresh is enabled.
- as a user, i would like more granular options for inactivity timeout. 
- as a user, i would like more options for auto-refresh rates
- as a user, i would like to view the entire end time in the modal
- as a user, i would like the refresh frequency to default to 1m when the modal is opened.

### Notes
- for the inactivity timeout and auto refresh rates, let's use a similar pattern as the window interval for data explorer. There is a list of pre-defined options but the user can also enter a custom option:
- 
![image](https://user-images.githubusercontent.com/4805997/118156272-04cb4f80-b3ce-11eb-933c-f3210f6a406b.png)

### Team
 - Anchor / Dev Champion - @ShmuelLotman 
 - Product Manager - @russorat 
 - Design

**Comment by barbaranelson** [comment]
One other minor nit.  When a cell is paused, can you change the text to 'resume'. Right now, you have to notice the icon to figure out if the current state is paused or not as the text always says pause.

**Comment by ShmuelLotman** [comment]
https://github.com/influxdata/ui/pull/1480 addresses all of these changes, which is why i removed the epic label - this shouldn't need to be a separate epic

**Comment by russorat** [comment]
@ShmuelLotman should we close this?
