### ISSUE TITLE
add ranged annotations to graph and graph+ single stat

### ISSUE THREAD

**Issue by jrenee42** [influxdata/ui#1417]
add ability to add ranged annotations 

1.  change button text from 'enable 1-click annotations'  to 'annotation write mode'
     a.  change this to 'on' by default
2.  when the toggle button is on; can add point annotations or ranged annotations
3.  when the toggle button is off, can zoom into the graph (cannot do both)
4. DON"T ADD:  just snap to times for now.   add a checkbox (or toggle?) to the annotation bar saying if the annotations snap to the nearest times available (for both ranged and point)
      a.  if off, use exact times that are clicked on the graph
      b.  if on, use the nearest time signatures
      c.  this will be on by default
5.  integrate the dragging code with the 'single click' code, since the way the dragging code is written, they need to be integrated (since we wrote our own, it interferes with the 'onClick' listener.  currently, when you zoom; after you finish the zoom the 'add annotation' popup occurs if the 'enable 1-click annotations' is enabled; which is NOT behavior we want
6.  add an 'end' field to the create/edit annotations dialog/overlay
7.  make sure this works on both graph and graph + single stat
8.  make sure editing and deleting works for ranged annotations

>>>>>>>>>>
already have most of #5 done.

**Comment by jrenee42** [comment]
#5 is done at this point.

**Comment by genehynson** [comment]
Hey @jrenee42 ! I was looking through some of the skipped cypress tests and found these two:
