### ISSUE TITLE
Graph X-Axis control

### ISSUE THREAD

**Issue by wanchunchen** [influxdata/ui#1428]
Hi,
I submitted Query and Table shows only 5 days of data are selected OK. But when I put Graph,
the X-Axis end tick is always like now().  The plot is squeezed on the left with too much margin on the right.
<img width="1917" alt="influxdb_snaphot_x_axis" src="https://user-images.githubusercontent.com/28786295/118398798-350e2a80-b628-11eb-8f6c-c9fc4ab8ddb2.png">

How to Zoom-in X-axis so that end tick is what I need?
I already tried "Customize" set number of Ticks, Start Tick and Tick Interval", but does not work.
The only thing I can do is to use Mouse to drag the plot to do Zoom-in.

Can you add X domain Control for Graph?   Graph has Y-Axis domain control, but X-Axis does not have it.

I am using this version:
https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.6-linux-amd64.tar.gz

Thank you very much,
-Tom

**Comment by TCL735** [comment]
Closing this in favor of https://github.com/influxdata/ui/issues/2482 - please follow there.
