### ISSUE TITLE
Annotations should be able to toggle between point and range

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#1436]
### Background
When we support ranges in Giraffe, the UI should support the ability to toggle between ranges and point annotations during editing.

If a user creates a range, and decides they only want a point, they should be able to switch the type, and vice versa.

Ideally this would be non-destructive until you saved. So if you switched from a range to a point, then got cold feet and switched back, your stop date should not have changed.

![Screen Shot 2021-05-17 at 4.43.44 PM.png](https://images.zenhubusercontent.com/5c33b08d24dda4712ef4ae10/075c1798-69f8-4c49-a6d1-a11579962e0f)

See: https://www.figma.com/file/AQk0tUthLFepRhFUibvzMI/Annotations?node-id=783%3A963

### Acceptance Criteria
- The annotation form overlay allows toggling of annotation types
- A brush event will set the state of the overlay to range, while a mouse click and release will set the state of the overlay to point
- The UX doesn't make me want to hit my teeth with a hammer

**Comment by daviddkkim** [comment]
Component to be used for the toggle : 
https://influxdata.github.io/clockface/?path=/story/components-selectgroup-examples--note-editor-mode-toggle 

Example usages in the application:
![Screen Shot 2021-06-03 at 1.27.51 PM.png](https://images.zenhubusercontent.com/604f76d7b2c0ce7a06471654/9df8e752-b43c-4abd-8cf4-b96642525923)
![Screen Shot 2021-06-03 at 1.27.43 PM.png](https://images.zenhubusercontent.com/604f76d7b2c0ce7a06471654/ab23fea0-408e-4def-ac69-6446a0ec9388)
