### ISSUE TITLE
Link to adding a Template from inside the Dashboards page

### ISSUE THREAD

**Issue by 8none1** [influxdata/ui#1451]
**Proposal:**
I wanted to add the cardinality explorer Template to my personal account.  It's great that you can add a template via a URL from a section in settings but finding that option was non-obvious.  I think it would be really good to add a link to that page from the dashboards page itself.  In Dashboards you have a Create a Dashboard drop down - I think adding a Create from Template option in that drop down which directs you to the Templates tab in Settings would really boost discoverability.

**Current behavior:**
If you want to add a Template you have to navigate to Settings -> Templates. 

**Desired behavior:**
Link to Settings -> Templates from the "+ Create Dashboard ↓" button on the Dashboards page

**Alternatives considered:**
None

**Use case:**
The most visible aspect of any Template is the Dashboard that comes with it.  I think it's natural for people to look to add Templated dashboards from the Dashboards page, not from the Settings page (this is exactly what I did).  Luckily another Influxer pointed me at Anais' blog post on this topic, otherwise I wouldn't have found where to add the dashboard myself.

**Comment by russorat** [comment]
Seems like a quick fix. For reference, this issue would add (back) an option on this drop down to install from a template. this would link you over to the templates page: 
![image](https://user-images.githubusercontent.com/4805997/118860975-d7c8e200-b890-11eb-951b-e55845dedcb7.png)
