### ISSUE TITLE
Notebooks: Collapse and Open Panel Menu

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#1485]
As a Notebooks user I can collapse the panel menu so that I can expand the panel view.

Scenario 1: Collapsing panel menu
Given I have selected a Notebook panel
When I want to expand the panel view and don't need to take any action in the panel menu
Then I have the option to collapse the panel menu
And clicking anywhere within the panel doesn't open the panel menu

Scenario 2: Opening panel menu
Given I have collapsed the panel menu
When I want to see the panel menu options again
Then I have the option to open the panel menu

#### Design Notes
[Prototype](https://www.figma.com/proto/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=2845%3A14642&scaling=min-zoom&page-id=2845%3A13770)
https://images.zenhubusercontent.com/279622976/6c7ba000-03d0-491d-9668-edeee36cb990/screen_recording_2021_05_21_at_11_32_24_am.mov

#### Technical Notes
Will we be able to open the panel menu on first click of the panel, but prevent the panel menu from opening if clicking anywhere in the panel except the panel menu button after it's been collapsed?

**Comment by jzahnd** [comment]
Given that we are switching to a drop down panel menu, is this task still relevant?

**Comment by juliajames12** [comment]
@jzahnd You're right, this task is no longer relevant. I'll close it.
