### ISSUE TITLE
Notebooks: Panel activity

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#1486]
As a Notebooks user I can view a Notebook's activity history so that I can understand who, when, and what changes were made

When I want to see who, when, and what changes were made
Then I can select View History in the Notebook's main navigation OR panel menu (TBD)
And I can see Activity history in the sub-menu

#### Design Notes
![Screen Shot 2021-05-21 at 11.56.36 AM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/11668fa0-6a03-4933-b222-7bb3b56deb22)

#### Technical Notes
We will need to wait on the backend to fetch this info until we can implement this capability (see Blocked)

**Comment by jzahnd** [comment]
Closing due to age and current focus
