### ISSUE TITLE
Annotations: Visually differentiate ranged annotations and point annotations when they overlap

### ISSUE THREAD

**Issue by daviddkkim** [influxdata/ui#1501]
Background
Currently, if a user were to add an annotation on a time that there exists a ranged annotation for, there is no visual distinguished that separates the two. 

Acceptance Criteria

Overlapping annotations are visually distinguishable. (This is separate from them being clickable, which will require a re-write of how the lines are stacked on z-index) 

This can be done by lowering the opacity of all our annotation click targets. Partner with @daviddkkim to get the right % of opacity and color.

![Screen Shot 2021-05-24 at 4.53.39 PM.png](https://images.zenhubusercontent.com/604f76d7b2c0ce7a06471654/2d443ed6-383a-44e3-802c-231ba9dfedfc)

**Comment by kristinarobinson** [comment]
Solution: always render ranges first, and point on top of ranges.
