### ISSUE TITLE
Add numbering or arrows on alerts page to guide the user to complete all 3 configurations

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/ui#1505]
Thank you for suggesting an idea to improve InfluxData UI.

**Proposal:**
Include arrows or numbers on the alerts page to help users understand that they must complete all 3 tasks in order to generate an alert. Perhaps even include an icon that indicates that an alert is now completed once all 3 items have been completed. The three items being:
1) configured check
2) configured notification endpoint
3) configured notification rule

**Current behavior:**
No obvious indication that a user must complete all three configurations in order to receive an alert. 

**Desired behavior:**
Perhaps include arrows or numbers to indicate progress. Perhaps include some text that greyed out that becomes highlighted when a user has generated all three steps. I think the old panel view was a little bit more intuitive for users. 
<img width="1600" alt="Screen Shot 2021-05-25 at 11 51 52 AM" src="https://user-images.githubusercontent.com/30506042/119538064-55d52f00-bd50-11eb-85d1-9e4eb4b4d4d2.png">

**Use case:**
Users are having trouble understanding that they have to configure a notification rule and notification endpoint in order to get an alert. 
https://community.influxdata.com/t/alerts-not-working/20029/4

**Comment by kristinarobinson** [comment]
Will be redesigned.  Closing for now.
