### ISSUE TITLE
Legend Orientation needs disambiguation for tooltip vs. static legend

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#1512]
Thank you for reporting a bug in InfluxData UI.
- Please ask usage questions on the Influx Community site.
  - https://community.influxdata.com/
- Please add a :+1: or comment on a similar existing bug report instead of opening a new one.
  - https://github.com/influxdata/ui/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+is%3Aclosed+sort%3Aupdated-desc+label%3Akind%2Fbug+
- Please check whether the bug can be reproduced with the latest release.
- The fastest way to fix a bug is to open a Pull Request.
  - https://github.com/influxdata/ui/pulls

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. For any plot type that supports static legend, click on Customize.
2. Under Legend, click Horizontal or Vertical.

**Expected behavior:**
Describe what you expected to happen.
1. For any plot type that supports static legend, click on Customize.
2. Under Legend, click Horizontal or Vertical.
3.  Only Tooltip orientation changes.
4. (Optional) There is an additional control under Static Legend to change the orientation of its data.

**Actual behavior:**
Describe What actually happened.
1. For any plot type that supports static legend, click on Customize.
2. Under Legend, click Horizontal or Vertical.
3.  Both Tooltip and Static Legend orientation changes.

**Environment info:**
- Tools, Prod (with feature flag staticLegend : true)

Vertical
<img width="1017" alt="Screen Shot 2021-05-25 at 3 54 20 PM" src="https://user-images.githubusercontent.com/70343856/119567234-b0cb4e00-bd71-11eb-8406-15410f09699a.png">

Horizontal
<img width="960" alt="Screen Shot 2021-05-25 at 3 54 54 PM" src="https://user-images.githubusercontent.com/70343856/119567246-b5900200-bd71-11eb-8ef8-712cfc7f4fca.png">

**Comment by TCL735** [comment]
This was addressed in separate work for the Static Legend. Both Hover and Static Legend now use their own options. Closing this.
