### ISSUE TITLE
Quartz local development

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#152]
The ecommerce team already has a basic provisioned elixir machine that they're using for automation, but it's not so good for local development of quartz itself. They're using a framework called phoenix, which has the capability to do hot reloading whenever a source file gets changed. This seems to be a pretty similar need to what the monitoring team is using for their local developement.

We need to:
 1. map out what folders they need to watch
 1. figure out how to launch a phoenix server in dev_mode
 1. give them their own set of yml files and `.env` entries in monitor-ci

What this ticket isn't asking for:
 1. integration with idpe
 1. any vault work
 1. any work around provisioning state

This is a requirement for:
influxdata/idpe#8263
influxdata/quartz#3405

**Comment by hercules-influx** [comment]
Metric | Score | Level
------------ | ------------- | ------------- 
performance | 21 | :red_circle:
accessibility | 65 | :yellow_circle:
best-practices | 80 | :yellow_circle:
seo | 89 | :green_circle:
pwa | null | :question:

**Comment by subirjolly** [comment]
Seems like this is what we are asking for:
https://github.com/influxdata/quartz/blob/master/README.md

This setup is pretty easy and takes a few hours but it does work.

**Comment by Asalem1** [comment]
Gonna close this since it was resolved by the e-commerce team
