### ISSUE TITLE
Cannot create a cron task from the UI (javascript error)

### ISSUE THREAD

**Issue by christopheblin** [influxdata/ui#1521]
__Steps to reproduce:__

1. Create a bucket with the name `import` in it.
2. Attempt to create a task as described in the following:

Whenever I try to create a cron task from a working query, it fails with the error

    Failed to create new task: Cannot read property 'map' of null

This behavior happens from the "explore > save as" as seen in the following video but it also happens if I try to create a new task directly from the "tasks" menu

The cron is `0 * * * *` (which mean hourly if I am correct) and the offset is `2m` (to account for late data)

https://user-images.githubusercontent.com/11044877/118929226-87ab5780-b944-11eb-938f-bc577b040c55.mov

I try to follow (more or less) the tutorial at https://www.influxdata.com/blog/downsampling-influxdb-v2-0/

__Expected behavior:__
Have a clear error message if it is an error on my side

__Actual behavior:__
Cannot create a task

**Comment by christopheblin** [comment]
Any news on that bug ?

I cannot create a task, it seems pretty severe to me but it is only classified sev-4 ...

Is there a workaround ?

**Comment by kristinarobinson** [comment]
This is working for us in production, can you send us the query that you are using?  The video is a little blurry, so we cannot see exactly what you are sending.  Perhaps there is something in the query you are sending that is causing an issue.

**Comment by christopheblin** [comment]
any request fails

let's say I'd like to keep a single measurement 

```
from(bucket: "rt")
|> range(start: -1h)
|> filter(fn: (r) => r._measurement == "gtfs-rt-import")
|> to(bucket: "rt-downsampled")
```

there is a JS error 

```
TypeError: Cannot read property 'map' of null
    at b (insertPreambleInScript.ts:32)
    at async thunks.ts:429
```

Full stacktrace

```

  | (anonymous) | @ | thunks.ts:441
-- | -- | -- | --
  | async function (async) |   |  
  | (anonymous) | @ | thunks.ts:429
  | (anonymous) | @ | index.js:8
  | (anonymous) | @ | redux.js:477
  | handleSave | @ | TaskPage.tsx:128
  | u | @ | react-dom.production.min.js:14
  | p | @ | react-dom.production.min.js:15
  | (anonymous) | @ | react-dom.production.min.js:15
  | x | @ | react-dom.production.min.js:17
  | M | @ | react-dom.production.min.js:18
  | E | @ | react-dom.production.min.js:18
  | I | @ | react-dom.production.min.js:21
  | kn | @ | react-dom.production.min.js:84
  | Ss | @ | react-dom.production.min.js:250
  | Ye | @ | react-dom.production.min.js:39
  | Mn | @ | react-dom.production.min.js:86
  | (anonymous) | @ | react-dom.production.min.js:251
  | t.unstable_runWithPriority | @ | scheduler.production.min.js:18
  | Ts | @ | react-dom.production.min.js:251
  | Tn | @ | react-dom.production.min.js:85
  | A.Object.isExtensible.Object.isExtensible.e.___hb.e.___hb | @ | honeybadger.js:466

```

**Comment by hoorayimhelping** [comment]
@christopheblin it looks like having `import` in the name of the bucket is what's causing problems. I have a fix that appears to work - it creates the task with the proper query and it runs properly that I'm working on getting in now. I updated the description to include this information.

**Comment by christopheblin** [comment]
after a month, I can fainlly create a task now, thank you 🥇
