### ISSUE TITLE
Text editor slows down when editing a cell in a dashboard with a large number of cells

### ISSUE THREAD

**Issue by scbrickley** [influxdata/ui#1534]
Thank you for reporting a bug in InfluxData UI.

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

See https://github.com/influxdata/idpe/issues/10305

**Expected behavior:**
The text editor should respond to edits immediately

**Actual behavior:**
There is a noticeable delay between keypresses and the document updating

**Environment info:**

- System info: Cloud 2
- InfluxDB version: idpe

Original issue: https://github.com/influxdata/idpe/issues/10305#issuecomment-846067333

**Comment by hoorayimhelping** [comment]
Here's what I've found so far.

My local machine was used on a system dashboard. I was editing the query in the System Load cell.

[`onChange`](https://github.com/influxdata/ui/blob/master/src/shared/components/FluxMonacoEditor.tsx#L110-L118) is fired on every keyup.

`onChangeScript` is an action that sets the active query text. Sending this action and calling the reducer on it is straightforward and takes a negligble amount of time. The re-rendering of all the components in the chain takes between 200-500 milliseconds (on every keystroke, on a small dashboard).

`updateDiagnostics` is called on every keystroke regardless of the outcome of the calls.

I'm currently working on tracking down where the re-renders are happening and why they're so un-performant.

**Comment by nathanielc** [comment]
@hoorayimhelping I have also experienced this slowness in text editors that are not the Flux editor. For example adding a suffix to the Y axis labels it is really slow to type into that textbox under the customization section. Again this only happens on dashboards with lots of cells. 

![image](https://user-images.githubusercontent.com/3771906/134212511-4cac4fdf-8d2c-44f9-9497-08273c72e536.png)

**Comment by genehynson** [comment]
In case this is helpful, here's how I solved a similar issue in notebooks: https://github.com/influxdata/ui/pull/1959

**Comment by hoorayimhelping** [comment]
Created an epic to address this: https://github.com/influxdata/ui/issues/3356
