### ISSUE TITLE
Understand why monaco in TimeMachine started being all slow

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#1536]
We have a fix for https://github.com/influxdata/ui/issues/1534, but this is about finding the underlying cause. Will require  working through git history and isolating the offending change.

**Comment by genehynson** [comment]
I'm sorry what was the fix for https://github.com/influxdata/ui/issues/1534 @hoorayimhelping ?

**Comment by jzahnd** [comment]
Closing in favor of  https://github.com/influxdata/ui/issues/1534
