### ISSUE TITLE
Remove `cy.wait` after `window.influx.set(..)` from cypress tests

### ISSUE THREAD

**Issue by subirjolly** [influxdata/ui#1541]
**Current behavior:**
If we have to set feature flag using `window.influx.set`, we also have to add a `cy.wait(..)` so that the feature flag comes into effect. I dug into this a bit and here are my findings.

Inside `cy.window().then(...)`, we have to set the feature flag and the feature flag gets set on the window instantaneously. If you list the feature flags, the flag you just set appears fine in the list. Once `cy.window` is run, our application tries to access feature flags using `isFlagEnabled` method which doesn't have the flag set, immediately after. The reason being that there are 2 ways to access flags. One is using window object and the other is using `Redux`. `isFlagEnabled` uses redux and thus there's a lag between when we set the flag on the window and when it's actually available for the application. Resulting in out cypress tests to fail. This is the justification for adding `cy.wait(..)` in our cypress tests.

**Desired behavior:**
We set the flag in `cy.window.then(...)` using 1 or a reliable(availablility) way.

**Alternatives considered:**
1. I have tried using `cypress-wait-until` but didn't invest much time into it. My limited tries didn't work for our case. So, we should probably explore this option again.
2. Another option is to have a synchronous way for getting the flag. Make sure to `await` for the result until your expected response is received.
3. Use `isFlagEnabled` in tests and wait until it returns the desired result.

**Use case:**
Reduces flakiness in cypress tests!

**Comment by genehynson** [comment]
Related: https://github.com/influxdata/ui/issues/1268

**Comment by jzahnd** [comment]
Closing in favor of https://github.com/influxdata/ui/issues/1268.
