### ISSUE TITLE
I would like a way to select a token to use for a new telegraf configuration

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#1547]
GIVEN that i am on the telegraf load data source page (/orgs/:id/load-data/telegraf-plugins/activemq)
WHEN i create a new telegraf config from that page
THEN i am able to select a token to use for that configuration

**Comment by kristinarobinson** [comment]
Out of scope for this epic.

**Comment by barbaranelson** [comment]
Closing this out as this won't be supported when the tokens API is changed to not return the clear text for a token.
