### ISSUE TITLE
Simple Table fails to refresh if you were on a table page that no longer exists. 

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/ui#1548]
Thank you for reporting a bug in InfluxData UI.

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Run any query and use the raw data simple table view
2. Click though to a later page beyond 1
3. re-run the query in a way that the results are shorter (e.g. `limit(n:1)`) 

**Expected behavior:**
the table refreshes

**Actual behavior:**
the table disappears.  Anything that forces the panel to redraw (page refresh, collapsing the panel and reopening it) will make it show up.  If you are on page 1 when you re-run this bug does not occur.  

**Environment info:**
Cloud2 internal instance

**Comment by genehynson** [comment]
Discussion: https://influxdata.slack.com/archives/C01E1H8D04Q/p1622222755056600

I also noticed that if you're on the last page and re-run the query which returns fewer results (and thus fewer pages), you get left in the "ether" (meaning you're shown data that doesn't exist and the page selector shows you're on none of the pages). In this situation the table should put you on the new last page.
