### ISSUE TITLE
Telegraf Refresh: Add Bucket--From Plugin, Create Mode

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#1555]
GIVEN that a user is on the `Load Data` page,
WHEN the user selects `Add Plugin to New Config` CTA from any of the available Telegraf plug-ins,
Then the user is taken to a modal where the user can optionally name the new configuration file AND
the user can select a bucket from the user's available buckets from a dropdown list

https://www.figma.com/file/hMUcxA5RdoEhdJLvClWWB7/Agent-Configuration?node-id=263%3A337

**Comment by TCL735** [comment]
WIP is here: https://github.com/influxdata/ui/tree/feat_1555_plugin_create_config_mode

**Comment by TCL735** [comment]
The actual configuration text for each plugin has a source of truth that is located here: https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf

Give the above, the `.md` files located at **/src/writeData/components/telegrafPlugins** are not necessarily correct.

We will need a separate issue to capture the work required to parse the source of truth and import the individual configurations as text into the text editor.

**Comment by TCL735** [comment]
Work in progress. Branch is here: https://github.com/influxdata/ui/tree/feat_1555_plugin_create_config_mode
