### ISSUE TITLE
Telegraf Refresh: Create Config File

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#1556]
GIVEN a user has selected a bucket and plug-in, during the Add Plugin to New Config (Create a Telegraf Configuration) flow OR the Create a Configuration from the Telegraf Page flow,
WHEN the user selects the clicks the CTA to continue,
THEN the user is taken to the Create a Telegraf Configuration page, with a link to the selected plugin which opens the GitHub README documentation for the that plug-in AND
 opens an editor with the new input plugin config for the selected plugin and InfluxDB output config (including the selected output bucket) copied into the editor buffer, and the cursor at the top of the file.

https://www.figma.com/file/hMUcxA5RdoEhdJLvClWWB7/Agent-Configuration?node-id=263%3A0

**Comment by TCL735** [comment]
Re-opening this. The main purpose of this story, to add an input configuration to a new Telegraf configuration, has yet to be completed.

There is also a related bug report: https://github.com/influxdata/ui/issues/2663

We will keep both open until this is addressed.

**Comment by TCL735** [comment]
Closing this in favor of keeping https://github.com/influxdata/ui/issues/2663 open as the remaining issue.

Additional changes to this workflow will be in new tickets after we get feedback from users.
