### ISSUE TITLE
Telegraf Refresh: Save--Create Mode

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#1557]
Given a user has completed editing on the `Create a Telegraf Configuration` page during the Add Plugin to New Config (Create a Telegraf Configuration) flow OR the Create a Configuration from the Telegraf Page flow,
When the user clicks the `Save and Test` button ,
Then the `Telegraf Configuration` file is saved in the Cloud using the `Name` provided AND
the `Test your Configuration` modal opens.

NOTE:  Should be regression only.

https://www.figma.com/file/hMUcxA5RdoEhdJLvClWWB7/Agent-Configuration?node-id=263%3A0
https://www.figma.com/file/hMUcxA5RdoEhdJLvClWWB7/Agent-Configuration?node-id=263%3A4

**Comment by TCL735** [comment]
This was completed as part of https://github.com/influxdata/ui/pull/2582 and https://github.com/influxdata/ui/pull/2699
