### ISSUE TITLE
run e2e tests on edge browser

### ISSUE THREAD

**Issue by genehynson** [influxdata/ui#1574]
Cypress supports Edge because it's a chromium browser. We should run our e2e tests on Edge in addition to Firefox and Chrome.

https://docs.cypress.io/guides/guides/launching-browsers#Browsers

**Comment by genehynson** [comment]
We should wait to do this until after we've added the remocal k8s cluster to our CI. Reason being that adding it in right now will make our pipeline slower because Edge and Firefox are slower than Chrome and the slowest job in our CI right now is the cloud-e2e-k8s-idpe job. Adding more k8s-idpe jobs with slower browsers = slower CI. With remocal, the k8s-idpe job will actually become significantly faster (~17min faster) and then this is more plausible.

**Comment by genehynson** [comment]
This will require updating this image to include the edge browser: https://github.com/influxdata/cypress-slim

**Comment by genehynson** [comment]
Ok this might be a little more complicated than we originally thought. Cypress doesn't publish an image with Chrome, Firefox, _and_ Edge according to: https://github.com/cypress-io/cypress-docker-images/tree/master/browsers . So we would have to restructure how we're building the cypress-slim image. 

This might not be wroth our time.

**Comment by jzahnd** [comment]
@russorat do we have an opinion on the lift vs payout on this effort?

**Comment by russorat** [comment]
i don't see a huge number of bugs from edge browsers, so i don't think this is needed.

**Comment by drdelambre** [comment]
feel free to reopen when this becomes a distinct priority
