### ISSUE TITLE
Allow logarithmic scale for the axes

### ISSUE THREAD

**Issue by TCL735** [influxdata/ui#158]
Originally reported in https://github.com/influxdata/giraffe/issues/245 but Giraffe is already capable of it. Just need to consume that configuration and expose it in the UI.

- [ ] add option to choose logarithmic scale for x-axis
- [ ] add option to choose logarithmic scale for y-axis

The result should look similar to below. Notice how the y-axis scales very quickly - logarithmically.
<img width="1680" alt="Screen Shot 2020-10-08 at 3 01 27 PM" src="https://user-images.githubusercontent.com/10736577/95518252-8dd16280-0977-11eb-9130-2e5987000c58.png">

**Comment by philjb** [comment]
I'd love to have the configuration option for a logarithmic scale for the x-axis too for the case I have a non-time based x-axis.

**Comment by TCL735** [comment]
Closing this in favor of https://github.com/influxdata/influxdb/issues/20551 - which has a more detailed explanation including additional related features such as tick marks for log scale.
