### ISSUE TITLE
Secrets: Link to Secrets List Page for Flux Editing

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#1587]
We would like to link back to the secrets list page anywhere Flux can be edited from with in the application. 

**Acceptance Criteria**

* Anywhere a user can edit Flux, we provide a link back to the secrets list page. 

Design: https://www.figma.com/file/XulFKIibFgx9xtSL92rHlY/Injecting-Secrets-in-Notebooks?node-id=39%3A721

**Comment by jzahnd** [comment]
@daviddkkim I was unable to find a design for this, do we have a mock somewhere that I passed over?

**Comment by daviddkkim** [comment]
Chatted with @jzahnd - will provide design for https://app.zenhub.com/workspaces/applicationsui-unity-606b1041215d5f0017898847/issues/influxdata/ui/2213  and then this as a follow on !
