### ISSUE TITLE
View the History of a Notebook

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#1591]
## Background
I would be useful for a Notebook user to be able to view the interaction and actionable history of a Notebook. Currently, if modifications are made by any user in an organization, it is a black hole. Further, there isn't an encapsulated history of task runs generated from the Notebook.

We would like the ability to see how a Notebook has evolved and platform actions that have been initiated by the Notebook. 

## Acceptance Criteria
* User may view the history of modifications on an notebook via the main navigation or panel menu
* User may view a stream of task runs and their status for a given panel with in a Notebook

## Team
Product Lead: @russorat 
Technical Lead @drdelambre

**Comment by asalem1** [comment]
Closing this since it's been addressed with notebook versioning
