### ISSUE TITLE
Notebook Interaction Improvements

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#1608]
## Background
There are interaction enhancements that would make Notebooks more usable for our customers. These enhancements would increase the speed of interacting with a notebook, allow users to customize the view based on their preferences and working style and interact with data based on the user's preference. The idea behind the features is build a more fluid, intuitive and customizable experience. 

## Team
Product Lead: @russorat 
Technical Lead @drdelambre

**Comment by drdelambre** [comment]
nothing to do in here
