### ISSUE TITLE
i would like to import a dashboard from an influxdb template

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1612]
### Background
today, when you navigate in the UI to import a dashboard, you are presented with the option to load a json file or paste in json.

![image](https://user-images.githubusercontent.com/4805997/120688419-e51cc980-c457-11eb-885b-3ed74618e3fd.png)
![image](https://user-images.githubusercontent.com/4805997/120688441-ec43d780-c457-11eb-8bee-4a080946d6fc.png)

This format is using the old version of templates, which we have since removed from the UI in favor of the new templates found in InfluxDB Templates repo: https://github.com/influxdata/community-templates

### Goal
the goal of this issue is to allow users to import dashboards from an existing InfluxDB Template file found in the https://github.com/influxdata/community-templates repo.

### Acceptance Criteria
- as a user, i would like the ability to import a dashboard from an InfluxDB Template from the dashboards page.
- as a user, i would like the ability to load a .yml file from my computer from the dashboards page
- as a user, i would like the ability to paste a yml formatted string into the UI and load the contents

### Notes
- I expect the UI for this would look very similar to the install templates UI found in the settings page.
- It would be awesome if we loaded the template yml and displayed a dialog box containing all the elements of the template, with only the dashboards selected by default. Then the user could choose to add additional resources from the template if they wanted.
- The template should also show up on the templates page, along with all the other ones.

![image](https://user-images.githubusercontent.com/4805997/120688727-362cbd80-c458-11eb-8d7d-9a5d1fed1dea.png)
![image](https://user-images.githubusercontent.com/4805997/120688772-46449d00-c458-11eb-988b-d75d8214c980.png)

### Resourcing
- Technical Lead: 
- Product: @russorat 
- Design: @daviddkkim

**Comment by kristinarobinson** [comment]
Fixed.  Import templates now supports Dashboards in Template v2 format.
