### ISSUE TITLE
Improve asLink functionality

### ISSUE THREAD

**Issue by joelfried** [influxdata/ui#1619]
The asLink() function in ui/src/visualization/types/Table/TableCell.tsx currently is suited to handle strings and only strings and due to how it's constructed if you pass in an array of strings which have URLs in them it gets very confused.

This function used to be scoped to that component but was added elsewhere (specifically to display links within text rendered inside of tables).  We should decide if this function ever needs to handle arrays being passed in and if not explicitly kick them out.  If we do want to handle arrays, the function will need to be modified (recursion might be simplest?) for these cases.

**Comment by jzahnd** [comment]
Closing due to age
