### ISSUE TITLE
Notebooks: Add an input panel for loading data from a url

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1635]
the `csv.from` function can be used to load annotated csv data from a url. This issue is to create a Notebooks panel that allows the user to specify the url and generates the following flux code, where the url is what the user entered.

```
import "experimental/csv"

csv.from(url: "https://raw.githubusercontent.com/russorat/influxdb-data-examples/master/gov/usgs/earthquake/all_week-annotated.csv")
```

**Comment by drdelambre** [comment]
is there a way we can educate the user on what should be on the other side of that url? that it's not just any url, but that it needs an annotated csv over there?

**Comment by drdelambre** [comment]
the panel type shall be called "Remote CSV"

**Comment by russorat** [comment]
Sample Air Sensor Data -> "https://raw.githubusercontent.com/influxdata/influxdb2-sample-data/master/air-sensor-data/air-sensor-data-annotated.csv"

**Comment by drdelambre** [comment]
NOAA weather data:-> https://influx-testdata.s3.amazonaws.com/noaa.csv

**Comment by russorat** [comment]
More live updating data files:
USGS Earthquake Data (All Week) -> https://raw.githubusercontent.com/influxdata/influxdb2-sample-data/master/usgs-earthquake-data/all_week-annotated.csv
NOAA National Buoy Data Center (NDBC) -> https://raw.githubusercontent.com/influxdata/influxdb2-sample-data/master/noaa-ndbc-data/latest-observations-annotated.csv
