### ISSUE TITLE
Epic: Account List

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#1657]
Goal
View List of Multiple Accounts
Assumptions:  Framework by Quartz to support multiple accounts is complete.

Accept Criteria
As a user, I want to be able to view list of multiple accounts by clicking on the Account item from the Account Nav Bar menu.

As a user, when I click on the Account item, I want to be able to view my account list.  

As a user, I want to be able to see the names of my accounts in the account list.

Design Considerations
-- Need an UI wireframe for this.

Large Epic for UI Multi-User/Multi-Account UI:
https://app.zenhub.com/workspaces/applicationdumplings-60a80d872533670017a6b107/issues/influxdata/ui/1626

Team
Dev Lead: Jill Pelavin
Design: John Corrigan/David Kim
Product: Russ Savage

**Comment by kristinarobinson** [comment]
Closing this epic.  This work will be completed in the Operator UI, not the normal user UI.

**Comment by corriganjohn** [comment]
The only 'Account List' is the navigation element (for the user UI), so this Epic looks to be redundant with https://app.zenhub.com/workspaces/applicationdumplings-60a80d872533670017a6b107/issues/influxdata/ui/1287

**Comment by kristinarobinson** [comment]
Changed design, not needed.
