### ISSUE TITLE
Epic: Rename Account

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#1658]
Goal
Rename Account 
Assumptions: Account exists

Accept Criteria
As a user, I want to be able to rename my account from within the Account Details page.
Q:  Any validation?  

Design Considerations
-- Need an UI wireframe for this.

Large Epic for UI Multi-User/Multi-Account UI:
https://app.zenhub.com/workspaces/applicationdumplings-60a80d872533670017a6b107/issues/influxdata/ui/1626

Team
Dev Lead: Jill Pelavin
Design: John Corrigan/David Kim
Product: Russ Savage

**Comment by corriganjohn** [comment]
Clarification on the way this is phrased: as a user, this is not 'my' account. This is not management of a 'user account'. The 'account' here is the billing account that will contain Organizations. The user is associated to this 'account' (which we need a better name for)

IF the user has permission to see the `/billing` page (currently the only place with 'account' information)
AND IF we are using the 'Company Name' field to provide the 'account name' ('Workspace'?)
THEN This data field is used to change the 'account name'

This becomes a matter of coming up with proper naming conventions to be consistent throughout the application for how we refer to this high level 'object'
