### ISSUE TITLE
Epic: Remove Self from Account (Workspace)

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#1659]
Goal
Delete self from Account/Workspace (which in turn deletes self from Organization).

Accept Criteria
As a user, I want to remove myself from the selected Account from the Users page.
As a user, when I am the last user in the Account, I am not able to remove myself from the Account.  The feature will be visible but disabled with guidance on what the user has to do.
Q:  What URL?

Design Considerations
-- Need an UI wireframe for this.

Large Epic for UI Multi-User/Multi-Account UI:
https://app.zenhub.com/workspaces/applicationdumplings-60a80d872533670017a6b107/issues/influxdata/ui/1626

Team
Dev Lead: Jill Pelavin
Design: John Corrigan/David Kim
Product: Russ Savage

**Comment by corriganjohn** [comment]
When we enable multi-org, when the user removes themselves from an Org they would NOT be automatically removed from an ACCOUNT. They could belong to multiple Organizations within that Account/Workspace [just making sure we keep that in mind]
