### ISSUE TITLE
Epic: Change User Email Address 

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#1662]
Goal
Update Email Address for User
Assumptions: Framework by Quartz to support user ID that is not email address is completed.

Accept Criteria
As a user, I want to be able to change my email address on my Users / Organization detail page.
Q: Inline editing via pencil icon?

As a user, if I enter an existing address, I will get an error back, and disallow the email address.

Design Considerations
-- Need an UI wireframe for this.

Large Epic for UI Multi-User/Multi-Account UI:
https://app.zenhub.com/workspaces/applicationdumplings-60a80d872533670017a6b107/issues/influxdata/ui/1626

Team
Dev Lead: Jill Pelavin
Design: John Corrigan/David Kim
Product: Russ Savage

**Comment by corriganjohn** [comment]
This is part of the /About page update https://app.zenhub.com/workspaces/applicationui-5e3b05772922e316b3a210a4/issues/influxdata/ui/992

**Comment by gunnaraasen** [comment]
We've decided to delay the change email work until after the upcoming login flow changes. We will reopen this epic in a new issue.
