### ISSUE TITLE
Epic: Account Consolidation

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#1663]
Goal
Allow users to consolidate accounts  For example: email1 => account1 & email2 => account2 consolidated to email1 => [account1, account2] with email2 => account2 deleted.

Accept Criteria
As a user, I want to be able to add an existing account owned by me with a different email address.
- How do we ensure that the user has access to both accounts being consolidated?
- Maybe: Send an invite to other email address/Pass token between the UI?

As a user, I want to delete the old account, once it's consolidated.

Design Considerations
-- Need an UI wireframe for this.

Large Epic for UI Multi-User/Multi-Account UI:
https://app.zenhub.com/workspaces/applicationdumplings-60a80d872533670017a6b107/issues/influxdata/ui/1626

Team
Dev Lead: Jill Pelavin
Design: John Corrigan/David Kim
Product: Russ Savage

**Comment by corriganjohn** [comment]
Wouldn't this be accomplished by allowing users to change their own email address (https://app.zenhub.com/workspaces/applicationdumplings-60a80d872533670017a6b107/issues/influxdata/ui/1662)?

If the user has 2 email addresses (email1 & email2), used for 2 orgs/accounts, if they change email2 to match email1, then email 1 will now be associated with both orgs/accounts (and email2 will NOT).
This still requires the user to do this for EACH email address they are using (they can't do this as a 'batch' or 'group' function).

There is (currently) no UI/viewpoint for 'My Information' for the user 'object'. No way to see this sort of meta-data across organizations/accounts.

**Comment by gunnaraasen** [comment]
We are not tackling account consolidation at this time.
