### ISSUE TITLE
Epic: Create Account

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#1665]
Goal
Create Additional Account for User
Assumptions: Framework by Quartz to support multiple accounts per user is complete.

Accept Criteria
As a user, I want to be able to create an Account from the Account List page by clicking a CTA.
Q:  If Account list is only displayed when more than one account is on file, where is the CTA displayed?

As a user, when I create a new account, I can specify a name, and the region/cloud provider.
Q: Do we use APIs to create the account or redirect to Quartz URL?
Q:  Validation for Account Name?

Design Considerations
-- Need an UI wireframe for this.

Large Epic for UI Multi-User/Multi-Account UI:
https://app.zenhub.com/workspaces/applicationdumplings-60a80d872533670017a6b107/issues/influxdata/ui/1626

Team
Dev Lead: Jill Pelavin
Design: John Corrigan/David Kim
Product: Russ Savage

**Comment by corriganjohn** [comment]
There is no 'account list' page, and there are no additional UI features for creating an account. Account creation will continue to follow the current paths (whether it's through normal sign-up flow or through marketplace)

**Comment by kristinarobinson** [comment]
Is not allowed.
