### ISSUE TITLE
telegraf config could not be changed -> missing button

### ISSUE THREAD

**Issue by milestone-shredder** [influxdata/ui#1667]
If I try to edit my telegraf script under Data -> Telegraf -> any_config_title, I am missing the _save changes_ button. I tried Firefox, Chrome and Edge.
I am using cloud2.influxdata.com.

https://community.influxdata.com/t/unable-to-safe-changes-on-cloud2-influxdata-com-to-telegraf-script/20265/2

**Steps to reproduce:**

1. Got to Data
2. Telegraf
3. Headline of any config
4. There is no button to save changes

**Expected behavior:**
Klickable _save changes_ button.

**Actual behavior:**
Button not available or visible.

**Environment info:**
cloud2.influxdata.com

**Config:**
cloud2.influxdata.com

![Screenshot Telegraf InfluxDB Cloud](https://user-images.githubusercontent.com/85607101/121308399-4eda1f00-c901-11eb-8dd3-f45906f2c8d9.png)

**Comment by Anaisdg** [comment]
Thanks @milestone-shredder

**Comment by milestone-shredder** [comment]
Seems to be fixed.
