### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1673]
Seeing lots of these warnings on cloud:
`Failed to decode downloaded font: https://us-west-2-1.aws.cloud2.influxdata.com/a735637c98.woff2`

![image](https://user-images.githubusercontent.com/4805997/121396174-f6f2e680-c907-11eb-924b-f72762c6b8f7.png)

**Comment by TCL735** [comment]
Possibly a `clockface` issue.

The icomoon font can be generated here: https://icomoon.io/app
- select the desired icons
- generate font
- replace the generated font files with what is in `clockface`
