### ISSUE TITLE
Cypress Test Coverage Report

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#1688]
We would like to generate a Cypress test coverage report for the UI. This report will be used to in conjunction with a manual review of our user flows to determine areas that are in need of additional test coverage in the near term. 

It seems like the Cypress documentation covers a standard approach for generating a HTML based coverage report here: https://docs.cypress.io/guides/tooling/code-coverage#E2E-code-coverage.

**Comment by ivankudibal** [comment]
out of scope
