### ISSUE TITLE
unicode character rendered notebook unreadable

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/ui#1699]
OK, this was mostly a result of a dumb mistake due to a key mapping.  I went to toggle comments in a block of code on a notebook.  I accidentally hit the wrong modifier and typed a ÷  symbol, and now the notebook won't load ☹️

**Comment by aanthony1243** [comment]
this is the notebook.  it's not operationally critical, so please use it for debugging:  https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/notebooks/07a9fcd22d346000

**Comment by scbrickley** [comment]
Stack trace for the crash: 
![image](https://user-images.githubusercontent.com/18431450/124625863-2edc4380-de4c-11eb-9a50-c862c4e39ce2.png)

**Comment by scbrickley** [comment]
@aanthony1243 Do you have the query that generated the crash?

**Comment by asalem1** [comment]
Closing this since the problem seems to have been fixed
