### ISSUE TITLE
Hovering legend has horizontal and vertical options swapped around

### ISSUE THREAD

**Issue by 8none1** [influxdata/ui#1712]
![Kapture 2021-06-15 at 15 06 49](https://user-images.githubusercontent.com/6552931/122067387-73dffd80-cdeb-11eb-9721-c3c97ed1966d.gif)

When viewing a chart on the Tools cluster the hover legend has two options Vertical and Horizontal. 

When I choose Horizontal I get a vertical legend, when I choose Vertical I get a horizontal legend.

**Comment by TCL735** [comment]
Stale. This is fixed.
