### ISSUE TITLE
SimpleTable: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1714]
![image](https://user-images.githubusercontent.com/4805997/122088751-e684b500-cdba-11eb-9031-8bd7e13cd369.png)

```
from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_user")
  //|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```

Data i was trying to render:
[2021-06-15-09-21_influxdb_data.csv.zip](https://github.com/influxdata/ui/files/6657162/2021-06-15-09-21_influxdb_data.csv.zip)

**Comment by Asalem1** [comment]
@russorat I'm having a hard time reproducing this locally with the query listed in the screenshot and the query you wrote on the issue with the data you uploaded. Can you still reproduce this?

**Comment by russorat** [comment]
are you using the `influx.set("simpleTable", true)` feature flag? 

i've been able to repro it with the following query:

```
import "experimental/csv"

csv.from(url: "https://gist.githubusercontent.com/russorat/861fc2aafe0ddc70d8a89b5a983cd8b4/raw/04f5376a87e571ce0bc9730a9cada7495a871141/results.csv")
  //|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_user")
  //|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```

**Comment by Asalem1** [comment]
I

**Comment by genehynson** [comment]
I was able to reproduce this in tools yesterday. Going to take another look today to see if I can isolate it and fix it
