### ISSUE TITLE
Find out why e2e/buckets.test.ts is failing

### ISSUE THREAD

**Issue by 121watts** [influxdata/ui#172]
Bucket e2e tests fail in the middle of execution because the app routes the user back to login.  Only happens when testing buckets.

**Comment by drdelambre** [comment]
i think we derisked this during triage, but just a heads up for whoever takes this: the /api/v2/buckets endpoint is stubbed out in the debug service, and it's not stubbed well. if weird stuff is happening on the api layer, there's a place to look
