### ISSUE TITLE
Add ability to test notification endpoint

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#1737]
Thank you for suggesting an idea to improve InfluxData UI.

**Proposal:**
When you create a new notification endpoint, there is no way to confirm that the endpoint settings without creating a check, and a rule, and sending data that will cause the check to fire. It would be great if you could test the notification endpoint from the UI, by sending a test message.

**Current behavior:**
You need to trigger a check that causes a notification, just to check the validity of the notification endpoint configuration.

**Desired behavior:**
Easy way to test notification endpoint in isolation.

**Comment by kristinarobinson** [comment]
Superseded by https://github.com/influxdata/ui/issues/3627.
