### ISSUE TITLE
In notebooks, no way to specify custom relative time range for metric selector or query builder

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#1738]
**Proposal:**
Add a way for user to enter custom relative time range (e.g -10m) in the notebook time selector.

**Current behavior:**
You can either select one of the available relative time ranges (past 5 min, past 15 min, etc.) or you can select custom time range and select an absolute start and end time. 

**Desired behavior:**
The ability to set a custom relative time range (e.g. last 10 min).

**Alternatives considered:**
In the data explorer, there is the same UI limitation, but you can work around it by editing the raw flux in the script editor.  In notebooks there is no such workaround if you are using the metric selector or query builder.

**Use case:**
I wanted to use a notebook to define a downsampling task that ran every 10 minutes, and downsampled 10 minutes of data. I was able to schedule the task to run every 10 minutes, but I couldn't change the time range for the data being selected.

**Comment by asalem1** [comment]
Closing this since there is a feature for this currently in place
