### ISSUE TITLE
annotations: event prefixes/names/tags

### ISSUE THREAD

**Issue by jrenee42** [influxdata/ui#1752]
* in a number of cases, what should be an xy event is emitted as a singlestat event (this was fixed in an earlier PR)
* adjust prefixes for edit vs create (especially with delete)
*  edit overlay cancel fires a create_annotation.cancel event (should be edit_annotation.cancel)

changes:

note:  prefixes are either:
<ul>
<li>xyplot
<li>band
<li>singleStatWline
</ul>

<table>
<tr><th> original </th><th> changed</th></tr>
<tr><td>annotations.edit_annotation.success </td><td>${eventPrefix}.annotations.edit_annotation.success</td></tr>
<tr><td>annotations.edit_annotation.failure</td><td>${eventPrefix}.annotations.edit_annotation.failure</td></tr>
<tr><td>annotations.delete_annotation.success </td><td>${eventPrefix}.annotations.delete_annotation.success</td></tr>
<tr><td>annotations.delete_annotation.failure </td><td>${eventPrefix}.annotations.delete_annotation.failure</td></tr>
</table>

<div>special case for: dashboards.annotations.create_annotation.cancel</div>
<table><tr><th>creation</th><th>editing</th></tr>
<tr><td>${eventPrefix}.dashboards.annotations.create_annotation.cancel</td>
<td>${eventPrefix}.dashboards.annotations.edit_annotation.cancel</td></tr>
</table>

**Comment by daviddkkim** [comment]
@jrenee42 Let me know what the changed event names will be before this goes to production. 
This could potentially break the tags we have in Google Tag Manager. We have a regex set for it so should be mostly ok as long as the same pattern holds.

**Comment by jrenee42** [comment]
@daviddkkim  added a table to the description here (and to the PR) showing the changes.
