### ISSUE TITLE
typing in notebooks flux editor is slow

### ISSUE THREAD

**Issue by genehynson** [influxdata/ui#1754]
Typing in the notebooks flux editor is slow. This causes weird behavior when you have multiple tabs open with different notebooks.

I've noticed that if I close the functions panel, the editor is faster. But others have reported that does not solve the slowness for them.

I think some component tree is being re-rendered unnecessarily with every key stroke. 

Note: we do not want to add debounce to the editor to work around this problem. We should try and reduce the number of re-renders occurring first

Slack convo: https://influxdata.slack.com/archives/C01E1H8D04Q/p1623789945202400

**Comment by philjb** [comment]
I'm still experiencing very slow character input - primarily in dashboards (but I use dashboards more than other pages)

Two different gifs from two different sessions - I smashed the keyboard as fast as i could in each case.

![slow characters2](https://user-images.githubusercontent.com/13472206/170349664-1dd239fa-0f7a-4d83-a6e7-fe947d3d9cfc.gif)
![slow characters](https://user-images.githubusercontent.com/13472206/170349821-7490d639-dcb6-4815-8ffa-2fa0a34957af.gif)

@Luckette - do you want to reopen this ticket or shall I file a new bug report?
