### ISSUE TITLE
Annotations: wrong event fired when cancelling the edit overlay

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1763]
cancelling out of the edit overlay fires the `dashboards.annotations.create_annotation.cancel` event, but i think it should be `dashboards.annotations.edit_annotation.cancel`

**Comment by jrenee42** [comment]
not reproducible anymore; fixed by: https://app.zenhub.com/workspaces/applicationdumplings-60a80d872533670017a6b107/issues/influxdata/ui/1752
