### ISSUE TITLE
Replace Moment: Convert formatted dates to JavaScript dates

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#1769]
### Background
Depends on #1767

After we have a date formatter, we need to create functionality to do the inverse - take formatted dates we support and convert them to JavaScript dates

### Acceptance Criteria
- For any outputted DateTime format we support (it needs to be DateTime, time only won't work), take a string of the formatted date and return a JavaScript date object

**Comment by ChitlangeSahas** [comment]
Closing this, seems like we won't be needing this issue. Our validation handles this.
