### ISSUE TITLE
Notebooks: Release Flux Editing

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#1775]
## Goal
- To release the flux generating and editing experience improvements
- Drive to the 100 notebooks created per week within a month of release (between 60-70 per week)
- 10% percent of notebooks have a "convert to flux" as an event

## Timeline
Marketing launch week July 12 launch

## Background
We would like to update the Notebooks panel experience to simplify the user interaction and further interaction iterations. This suite of stories will represent our next phase of modifications to the panel menu and panel interaction.

**Comment by mnorriswalker** [comment]
@jzahnd, @drdelambre, @russorat,  @juliajames12 - We noticed when you convert the panel's flux it's just one long line (see screenshot.) I doubt we'll get much adoption if the generated Flux is not prettified. What do y'all think? I heard there might be an issue with the Flux team (@nathanielc) already? Can we add that into this epic? I think it's a blocker.

![image.png](https://images.zenhubusercontent.com/5d928b2631e8dd0001222f82/1e743e46-bb4b-495a-9887-90a5f66ad98c)

Friendly reminder that we also need a measurement story :)

**Comment by russorat** [comment]
Here's the issue for fixing the format capability: https://github.com/influxdata/flux/issues/3798

**Comment by drdelambre** [comment]
seems like there are no active issues here
