### ISSUE TITLE
Notebooks: Function Injection Placement

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#1778]
We would like to refine the function injection behavior for a Flux script cell. If a user does not place their cursor into the flux cell, but injects a function via the options menu, the function should be placed at the end of the flux script within the cell. 

## Acceptance Criteria

- When a user tried to inject a function in a Flux cell without placing their cursor in the cell, the function that was injected should be added to the end of the Flux script.

**Comment by juliajames12** [comment]
@jzahnd I just double checked to see if this is how the Inject Function works while using the flow-sidebar feature flag. This acceptance criteria is currently being satisfied, so as long as it stays that way after any updates are made, we should be good :)
