### ISSUE TITLE
Notebooks: Add Arrow to Indicate Selected Panel Out of User's Viewport

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#1779]
We would like to indicate when a user has selected a panel that is out of the user's viewport. This could occur if the user is scrolling or viewing a different panel. Once the selected panel leaves the viewport, an arrow should appear to indicate to the user that they have selected a panel that is no longer visible. 

## Arrow Indicating Out of Viewport Selected Panel

- TBD

## Acceptance Criteria

- TBD

**Comment by jzahnd** [comment]
@juliajames12 @russorat Can we remove this story from the Flux epic? I don't think it is mission critical to the final release?

**Comment by russorat** [comment]
I don't think this is relevant anymore.
