### ISSUE TITLE
Usage Dashboard added by default to all new accounts

### ISSUE THREAD

**Issue by corriganjohn** [influxdata/ui#1784]
GIVEN I am a new user signing up for Cloud 2
WHEN The account is created
THEN Create a Usage Dashboard by default on the Dashboards page

The Usage Dashboard template uses the experimental/usage Flux API to return usage data, and does not require adding additional buckets, tokens or variables. 

Only the dashboard will be added (the community template includes a sample Task for creating notifications, this will not be included)

[https://app.zenhub.com/files/279622976/bc96d9b4-d000-4fe1-8426-16052623f6ca/download]

**Comment by kristinarobinson** [comment]
Won't fix.  Usage is now provided in the Account Settings area.
