### ISSUE TITLE
Create Check: Window interval should match the check interval

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#179]
Given that i am creating a threshold check in the UI
When i see the data for my check graphed in the UI
Then the window period should match the check interval

This 30s
![image](https://user-images.githubusercontent.com/4805997/96194849-1e6feb80-0f00-11eb-87f4-2a5c8381f61f.png)
should actually be 15s
![image](https://user-images.githubusercontent.com/4805997/96194896-36476f80-0f00-11eb-9fd2-29efffeb1b32.png)

since that is the frequency at which the check will run. changing the frequency should also change the window period. 

If the window period is not editable, consider hiding it completely from the UI.

**Comment by kristinarobinson** [comment]
Timebox this fix to one day, attempt to fix by displaying "window period" same value as "schedule every".
