### ISSUE TITLE
Timezone selector is not linked to date picker

### ISSUE THREAD

**Issue by desa** [influxdata/ui#18]
![Screen Shot 2020-07-02 at 12 17 22 PM](https://user-images.githubusercontent.com/1477539/88116417-5d92d880-cb6d-11ea-97c5-341298e0c36b.png)

WHEN viewing a dashboard
AND the user selects a timezone and date
THEN `v.timeRangeStart` and `v.timeRangeStop` should use the timezone specified in the timezone picker

**Comment by desa** [comment]
cc @jacobmarble

**Comment by Asalem1** [comment]
@desa is this still an issue? It should've been addressed here:

https://github.com/influxdata/influxdb/pull/19146

**Comment by joelfried** [comment]
Tested this behavior locally and this problem no longer appears to be occurring.  Specifically I found a dataset with a data point that is in range when I'm on local time but out of range when I'm on UTC and changing does in fact cause the cell to report no more data available.  Thus the queries inside dashboard cells must be respecting the timezone in the drop down.
