### ISSUE TITLE
Bug: Dashboard scrolling does not reload hidden cells that come into view after a changed time range.

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#1829]
# Summary

In dashboards with multiple rows of cells (say 3x3), cells will not reload automatically if the time range is changed.

See screenshot which shows the first row displaying a different set of times (different time range) from the bottom row. I captured this after following the steps below.
<img width="409" alt="don't reload" src="https://user-images.githubusercontent.com/13472206/123678982-d7aaf300-d7fb-11eb-86f0-45bb00b61a25.png">

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Create a dashboard with at least 2 rows of cells (you may need 3). Have all the cells with working query that returns data.
2. Adjust your window size and scroll the page for the top row of cells is completely scrolled off the window (you'll see only the second and/or third row of cells).
3. Change the time range from 1hr to 2hr for example and let the visible cells start to reload.
4. Scroll up now to the first row and observe that the cell did not reload.

**Note:** this happens for both scrolling directions. If you let the dashboard load then scroll to the bottom, then the top, then change the time range then scroll down, you'll see that the hidden cells below the fold don't reload either.

**Expected behavior:**
Automatic reloading happens consistently for all cells when scrolling up or down occurs (or not at all).

**Actual behavior:**
Nonvisible cells reload inconsistently based on time range changes. It should be consistent. Either all cells reload on scrolling or none (personally, I'd prefer that scrolling does not trigger reloads and that a button is provided to reload individual cells or all currently visible cells).

**Environment info:**
influx cloud 2

**Comment by jrenee42** [comment]
according t @drdelambre ; this is working as designed.

but the user expects that as they scroll to another cell (that was previously hidden) that it will be updated to the -just-selected- time range

parts of the code I looked at:
RefreshingView 
componentDidMount in TimeSeries.tsx
src/visualization/components/View.tsx: inside the <InnerView> component

**Comment by drdelambre** [comment]
just saw my mention here. not sure how you got that impression from the conversation we had, which i believe ended by agreeing that the intersection observer should run the query if it comes back into view, which i believe is not happening here?

**Comment by hoorayimhelping** [comment]
This is occurring [here](https://github.com/influxdata/ui/blob/0a2b4a7655132e6fff2cd5e6e63ebcb01039f753/src/shared/components/TimeSeries.tsx#L146) and [here](https://github.com/influxdata/ui/blob/0a2b4a7655132e6fff2cd5e6e63ebcb01039f753/src/shared/components/TimeSeries.tsx#L164) in `TimeSeries.tsx`.

The issue appears to be when the time dropdown is changed, this component isn't aware of it and so doesn't change its state to force a reload.
