### ISSUE TITLE
i would like to apply a graph change to all graphs on a dashboard

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1859]
when we release new capabilities for graphing, it's a pain to have to click through all the cells in a dashboard to add the change. Things like number formatting or time formatting make sense to apply to all the cells in a dashboard.

as a dashboard user
given i have a dashboard full of cells
when i make a change to a graphing option in a single dashboard cell
then i am presented with a way to apply that change to all cells on a dashboard.

**Comment by kristinarobinson** [comment]
Assess whether to add to Bulk Action epic.

**Comment by Luckette** [comment]
We don't have the infrastructure to support this. Will not implement.
