### ISSUE TITLE
Scatterplot's x axis is configurable

### ISSUE THREAD

**Issue by Palakp41** [influxdata/ui#192]
When rendering the scatterplot in a dashboard, if a customized time range is selected in the ui, it will handle what properties to send to Giraffe. Giraffe will be able to control and decide what the auto domain for x axis should be.

Functionality in UI should be:
- if a user sets the domain by hand, use that.
- if they select _time for the x axis, set the default domain to the page's time window (timemachine / dashboard / whateves).
- anything else, use the auto domain. and make sure it works with the example samantha put at the bottom of that ticket (https://github.com/influxdata/influxdb/issues/18981)

Steps to fix:
1.) Update the giraffe such that the current functionality for controlling the x axis in UI is calculated in scatter plot in giraffe
2.) Update ui in a way where we we send customize properties for the x axis to giraffe's scatter plot.

**Comment by 121watts** [comment]
@Palakp41 referenced in other issue.  closing
