### ISSUE TITLE
Tokens: Buckets and Telegraf configs have expandable accordions with individual configuration options

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#1925]
Both Buckets and Telegraf config resources have expandable accordions that have individual configuration options.  
If the header level is clicked, then the individual levels are all clicked.

**Comment by daviddkkim** [comment]
https://github.com/influxdata/clockface/pull/645 

got some more clean up to do but this is how it's coming along
https://images.zenhubusercontent.com/279622976/b866e867-bd85-4b9f-a19
3-cce0c562a57b/accordion_new.mp4
