### ISSUE TITLE
Enable Sharing a Cell

### ISSUE THREAD

**Issue by asalem1** [influxdata/ui#1969]
As a user, when I select the settings toggle of a cell, I should see an option to Share a Cell Publicly within the dropdown.

The user story from hereon needs to be defined, but we might want to prompt the user to add the ability to share for either a snapshot of time (meaning, share that cell with that data at that specified time from when the share button was selected) or whether they want a visualization that should be displayed relative to whatever the current time is (so if i share a cell that's displaying data for the past hour and the receiving user doesn't see it until an hour later, they should see the new past hour of data).

**Comment by barbaranelson** [comment]
What token is used to authenticate the queries for the shared cell? Is it the user's token (and if so, how do we protect it) or a different one specific to the cell?

**Comment by jzahnd** [comment]
Closing due to share focus switching to Notebooks
