### ISSUE TITLE
Operator page: Changes to limits don't seem to take effect

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#1978]
Select a free account (e.g. bnelson+azure@influxdata.com).  Click on the account number to bring up the account details page. Click on the org id to bring up the org details popup.  Change one of the limits - e.g. change max buckets from 2 to 4 and click on 'submit changes'.  Now select the org id again, and notice that in the pop-up the max buckets limit is still 2, not 4.

**Comment by Asalem1** [comment]
Looking into this it seems like it might be an API issue. I can't reproduce it with other users:

![update-operator](https://user-images.githubusercontent.com/19984220/125349836-e07ae900-e312-11eb-9dba-06dc79eb4fde.gif)

**Comment by Asalem1** [comment]
Found the issue! So tracing the quartz logs basically indicated that the number we were trying to update for the max retention policy was getting increasingly large to the point where the API couldn't handle it. This should be resolved with:

https://github.com/influxdata/ui/pull/1981

**Comment by barbaranelson** [comment]
This is working now.  Thanks Ari.
