### ISSUE TITLE
Enable variables to return table streams 

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/ui#1980]
**Proposal:**

**Current behavior:**
<img width="896" alt="Screen Shot 2021-07-12 at 12 08 54 PM" src="https://user-images.githubusercontent.com/30506042/125328654-2e3f2380-e30a-11eb-8f65-8d8d8ef44da0.png">
<img width="726" alt="Screen Shot 2021-07-12 at 12 11 01 PM" src="https://user-images.githubusercontent.com/30506042/125328715-3f883000-e30a-11eb-8e34-701384a591a2.png">
Yields error 
` type error @2:4-2:11: expected [A] but found string (argument tables)`

**Desired behavior:**
The ability to call variables directly. 

**Alternatives considered:**
Describe other solutions or features you considered.

**Use case:**
Enables code reuse and streamlines flux development. 

Related to influxdata/flux#3872

**Comment by kristinarobinson** [comment]
@Anaisdg - This cannot be supported using the existing architecture and how variables are defined.  I talked to @nathanielc, and he said that when they build the "flux module system" then this type of functionality could be implemented.  Closing as a UI issue.  Feel free to open a similar issue in IDPE and assign to the flux team.  I don't have an ETA for this new functionality.
