### ISSUE TITLE
Maps: Add test case to notebooks e2e test

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#1983]
### Acceptance Criteria

- [This Notebooks e2e test](https://github.com/influxdata/ui/blob/master/cypress/e2e/shared/flows.test.ts#L96) is updated with some basic Maps tests.

**Comment by zoesteinkamp** [comment]
It is currently not possible to run e2e test with maps without connecting to the production maps server. 

To tests this change we need to have the maps server running, otherwise we receive a maps server error, which blocks us being able to render the options to confirm they do not crash.
