### ISSUE TITLE
Notebook: Need some way to restore if you accidentally delete your query

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#1987]
I had been working on a fairly complicated flux query on Friday and today.  I was trying to close the list of functions because they were in my way, and accidentally selected the 'x' on the right hand side of the panel. I lost the panel altogether and have no way to get it back.

It shouldn't be this easy to delete a panel.

**Comment by asalem1** [comment]
This should be resolved with notebooks versioning
