### ISSUE TITLE
Notebooks: SimpleTable pagination sometimes doesn't work

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#1988]
Unfortunately I wasn't able to make this happen consistently.

When you have a query that returns a lot of data, sometimes the pagination control at the bottom of the simpleTable view doesn't cause the table to update. You get stuck on whatever page you happened to be on (typically the first page) and advancing the page cursor or selecting another page doesn't update the display.

Sometimes it works fine, so I wasn't able to see what causes it to sometimes not update.

https://user-images.githubusercontent.com/13143006/125376009-eedefa00-e33e-11eb-98ed-d1e386ff14f4.mov

**Comment by kristinarobinson** [comment]
Beth, Merrick, this just cropped up, and might be due to the pagination fix just PR'd.

**Comment by barbaranelson** [comment]
I am ok with closing this for now. I'll reopen if I see it again. I haven't noticed this in a while.

**Comment by TCL735** [comment]
A quick test confirms this is working now in Notebooks for Simple Table.
