### ISSUE TITLE
Add UTM to data being sent to Rudderstack

### ISSUE THREAD

**Issue by mona-influx** [influxdata/ui#2003]
**Proposal:**
We currently are capturing UTM somewhere as it is being sent to GA. We would like to capture as well in the event data being sent to Rudderstack through the Rudderstack JavaScript SDK

**Current behavior:**
Events being sent but does not include UTM

**Desired behavior:**
Same events being sent, but include UTM

**Alternatives considered:**
Very open to potential solutions, as long as we can get the data 

**Use case:**
For analytics and marketing

**Comment by jzahnd** [comment]
I think everyone knows this but we are talking about Google's custom UTM parameters as documented here: https://support.google.com/analytics/answer/1033863?hl=en#zippy=%2Cin-this-article.

**Comment by alespour** [comment]
Is there a running campaign at this moment so that I can have a look at a real link decorated with UTM parameters? Thanks.

**Comment by mona-influx** [comment]
?utm_source=newsletter&utm_medium=email&utm_campaign=2021-08-04_cs_ezako_global&utm_content=nl-2021-08-04-21
?utm_source=newsletter&utm_medium=email&utm_campaign=2021-07-26_blog_collecting-data-from-chess_global&utm_content=nl-2021-08-04-21
?utm_source=newsletter&utm_medium=email&utm_campaign=2021-07-27_webinar_loft-orbital_global
<https://www.influxdata.com/resources/spacecrafts-made-simple/?utm_source=newsletter&utm_medium=email&utm_campaign=2021-07-27_webinar_loft-orbital_global>
&utm_content=nl-2021-08-04-21

are some examples
