### ISSUE TITLE
Annotations Tests: Get them working reliably again

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#2012]
[This PR](https://github.com/influxdata/ui/pull/2005) turned off annotations e2e tests due to their flakiness. Undo those changes and start getting tests to pass.

Currently skipped tests
- 'can add and then delete a range annotation for the band plot' (should be fixed when [this](https://github.com/influxdata/giraffe/pull/641) gets in)
   - annotations.band.test.ts
   - annotations.range.test.ts
   - annotations.singlestat.test.ts
   - annotations.xy.test.ts
- ~annotations.range.test.ts: 'can create an annotation that is scoped to a dashboard cell'~ this can be removed

**Comment by jrenee42** [comment]
btw:  found a bug in the tests:

 ```
it('can add and then delete a range annotation for the single stat + line graph', () => {
    addRangeAnnotation(cy)
    testDeleteAnnotation(cy)
  })

```
the  testDeleteAnnotation method creates a normal, point annotation and then deletes it.
instead we want  the second line to be `deleteAnnotation(cy)`
