### ISSUE TITLE
Notebooks: Predefined Notebooks

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#2032]
## Description

As part of our update to Notebooks for facilitating a better Task authoring experience, we would like to enable the creation of predefined notebooks. A predefined notebook would have set panels that will allow users to jump right into their preferred authoring journey. Instead of several clicks to preconfigure a notebook for tasks or alerts, a user can simply choose a predefined notebook that already has panels defined to facilitate editing based on the type of predefined notebook that the user has selected.

## Measurement Criteria

1. How many users create a template notebook?
2. How many resources are connected to a template notebook?

## Team

Design: @juliajames12
Engineering: @drdelambre
Product: @russorat

## Acceptance Criteria

- As a user, I am able to create a notebook from a template that has predefined panels based on the notebook template type.

**Comment by mnorriswalker** [comment]
@jzahnd just to confirm, this is NOT about adding Notebooks to the Templates system, allowing users to bundle Notebooks in a Template? We're talking about preconfigured notebooks with certain panels? I would change the name to "presets" to disambiguate with our Templates system? Just a thought.

**Comment by drdelambre** [comment]
i think this has been done for a bit.
