### ISSUE TITLE
SimpleTable: ellipsis looks like it's clickable but does nothing

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2036]
clicking on these ellipsis don't do anything, but they are highlighted and the mouse cursor changes to indicate they are clickable. Could we remove that behavior to reduce confusion for the user?

![image](https://user-images.githubusercontent.com/4805997/125981162-1cde7fc1-73f4-405f-a6d1-bc9c28e2dfb8.png)

**Comment by kristinarobinson** [comment]
David, we think that this is a simple styling issue, can you confirm?

**Comment by daviddkkim** [comment]
> David, we think that this is a simple styling issue, can you confirm?

@kristinarobinson worked with Sahas to arrive at a solution! 
The original intention was that I would build more feature in to allow you to click the ellipses to get a dropdown list of all the pages but I never got around to it and left it as a clickable looking button. 

Sahas is going to make it not look clickable in the PR
