### ISSUE TITLE
Open Influx failes

### ISSUE THREAD

**Issue by h3tz** [influxdata/ui#2039]
Thank you for reporting a bug in InfluxData UI.

-its just failing;
https://europe-west1-1.gcp.cloud2.influxdata.com/orgs/3785aa2278f6cd87

**Comment by visued** [comment]
+1

**Comment by visued** [comment]
https://eastus-1.azure.cloud2.influxdata.com/orgs/550f8371838382e8

**Comment by h3tz** [comment]
page available again
