### ISSUE TITLE
Replace Moment: Measure bundle size reduction

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#2066]
### Background
The whole purpose of replacing moment is to lower our bundle size. To know how well we did, we'll want to measure the bundle size with moment and then again without it.

### Acceptance Criteria
- We take two measurements of the bundle size
  1. with moment
  1. without moment

**Comment by ChitlangeSahas** [comment]
These are the findings: in summary we reduced our bundle size by `429kB`

* `moment js` size: 672kB
* `luxon js` size: 243kB

reduction: **429kB.**

Screenshots of the results: (mouse is hovered to show the package sizes.) 
**Report of Moment:**
<img width="2560" alt="Screen Shot 2021-08-16 at 4 10 06 PM" src="https://user-images.githubusercontent.com/18511823/129640146-dc730523-c016-4afb-9d9e-b96941e12146.png">

_Zoomed in_
<img width="1169" alt="Screen Shot 2021-08-16 at 4 11 08 PM" src="https://user-images.githubusercontent.com/18511823/129640224-37d9eb26-4203-4a35-88d0-ed1a3e63de0a.png">

**Report of Luxon:**
<img width="2560" alt="Screen Shot 2021-08-16 at 4 07 10 PM" src="https://user-images.githubusercontent.com/18511823/129639982-0549ae5a-81c0-474a-a28d-3ee3aad938a7.png">

_Zoomed in_
<img width="1054" alt="Screen Shot 2021-08-16 at 4 11 59 PM" src="https://user-images.githubusercontent.com/18511823/129640291-11b666ae-0a98-49cf-a0d8-b795fb84827a.png">

**Webpack report files:** 

with moment: [report_moment.html](https://ufile.io/frx2d8kz)
with luxon: [report_luxon.html](https://ufile.io/itjol283)

(cc: @hoorayimhelping , @kristinarobinson)
