### ISSUE TITLE
Bug: SimpleTable - Remove `useGiraffeGraphs` flag

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#2068]
It's been on in Prod with no complaints. We should remove it.

### Steps
1. Remove all branching code referencing the flag
1. Remove flag from flags.yml in OSS and Cloud
1. Remove flag from configcat

**Comment by TCL735** [comment]
This is pending the resolution of SimpleTable's implementation being re-ported back to Giraffe.

**Comment by TCL735** [comment]
First step is to upgrade Giraffe to the version that has the latest SimpleTable. The PR is here: https://github.com/influxdata/ui/pull/5249

**Comment by TCL735** [comment]
More updates have been made and Giraffe has been updated accordingly. Flag is currently ON in production. We will continue to monitor for issues.

Flag is slated for removal during the week of August 15 - 19.
