### ISSUE TITLE
Notebook: Updates to Demo Data Notebook

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#2071]
We would like to make the following updates to the demo data notebook:

- Add the Schedule panel after the output panel since Export as Task is now included in that panel. 
- Add an instruction to click Preview to see the visualization in the Step 1 markdown panel
- Add a screenshot to show Run within the Preview dropdown in case the user needs more direction on where to find it
- Change input data to USGS Earthquake All Week data so users don't have to turn website monitoring on to complete the demo

**Comment by russorat** [comment]
@mavarius looking for your guidance here.

**Comment by barbaranelson** [comment]
Closing out as we have removed the demo data feature.
