### ISSUE TITLE
Notebooks: client sample code in 'copy as' is inconsistent

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#2075]
In the 'copy as' feature, we generate code that the user can cut/paste into their client.  Ideally the code should be functionally equivalent in all languages. Here's a summary of my recommended changes.  

General statements:
1. Some of the client code includes print statements and others do not. I would either leave them all out, or add them to the ones that don't have them.  (My vote is to leave them out, as it is cleaner code and a client API developer can add them if they want.)
2. Some of the client code includes code to iterate over the query results, but other code does not. It simply assigns the query results to an object and leaves it up to the developer to figure out how to iterate over the object.  I think it's useful example code (may not be that intuitive on how to iterate over the results) so I would add it in any language that it isn't included in.  

Client specific comments:
Arduino:
This one is really confusing, and seems like a different sample app for wi-fi settings. I would change it to just the code that creates the InfluxDBClient with the parameters populated from the query (URL, ORG, BUCKET, TOKEN). Then have it execute the query from the notebook and get the results, like the other languages.

Go:  I don't know Go, but there is a call to client.close that seems to come too early in the sequence (unless defer causes it to do the right thing).

Swift: There is a call to client.close that seems to come too early (before the query). I'm not a swift developer so maybe this is fine.  There is also a print statement referring to CPU usage which isn't valid. I'd delete it.

**Comment by barbaranelson** [comment]
I've asked Bonitoo to work on this one.

**Comment by ivankudibal** [comment]
@vlastahajek @bednar

**Comment by vlastahajek** [comment]
Generally, the examples code would deserve a syntax highlighting. This would emphasize relevant calls and hide comments

Comments - as examples are primarily written for beginners for libraries, the best practice is to include comments for the usage of the API.

Arduino - All language examples have complete code to get examples working. Arduino world is a bit specific because these are mostly microcontrollers, where example code needs to initialize necessary hardware to have the rest of the code working.

Go - Using `defer` is common practice to schedule any clearing code to be called at the end of the surrounding function.

**Comment by barbaranelson** [comment]
Right, but this isn't example code. This is specifically taking a query you have developed (and likely confirmed working) and turning it into client code that you can copy/paste into your client app. If someone is developing an Arduino client, I would assume they have figured out how to initialize the hardware etc. I have no problem having a full Arduino client example somewhere else (probably where you select the Arduino client to download it), just not in the copy/paste feature within a notebook.

**Comment by bednar** [comment]
@barbaranelson, Swift - you are right, the `close()` should be call at the end of the script. May be a new section **Dispose the Client** will be useful.

**Comment by bednar** [comment]
@barbaranelson, the https://github.com/influxdata/ui/pull/2300 is ready to review

**Comment by barbaranelson** [comment]
@jzahnd can you have someone review and approve Jakub's PR? Thanks.

**Comment by genehynson** [comment]
@bednar looks like the PR still needs to be rebase with master to get CI to pass
