### ISSUE TITLE
Notebook: I can convert to flux only from the Input and Transform panels

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#2082]
In an effort to reduce user confusion, we want to limit the convert to flux action to only the Input and Transform panels - which are more relevant in directly editing the query. 

We would like to **remove** the convert to Flux option from the following panels: 
- Column Editor
- Markdown
- Visualization
- Notification
- Output to Bucket
- Schedule

So the only panels that would have the convert to flux function would be the following Input and Transform panels:
- Metric Selector
- Query Builder
- Flux Script
- Downsample

**Comment by juliajames12** [comment]
Note from Barbara: 
> I selected 'convert to flux' in the visualization panel (mostly because I was curious as to what it did). It changed the display to show me the flux, but I had lost the visualization and had no way to go back. I had to delete the panel and add a new visualization panel to get back to where I started.
> 
> Would it make sense to only have the convert to flux option in the input and transform panels, and not in the other ones? In the other panels, as soon as you convert to flux, you've lost whatever those panels used to do (notify, visualize, schedule etc.)
