### ISSUE TITLE
Replace Moment: Spike: Explore time usage in the App. (UTC/Local)

### ISSUE THREAD

**Issue by ChitlangeSahas** [influxdata/ui#2100]
Upon working on these issues: (#2054) and (#2013) we have come across multiple situations where it isn't clear what the standard way of processing time in our app is.

To avoid putting up band-aid solution, we would like to investigate if there is a standard way, if not, whether its feasible to standardize it, or what the direction from here on should be.

Example:

https://github.com/influxdata/ui/blob/45a44a4c2a355236ae06d1b36203fc72088f24da/src/visualization/utils/useVisDomainSettings.ts#L30-L31

what should be the standard way of passing around time, before we display it to the user? 

cc: @hoorayimhelping

**Comment by hoorayimhelping** [comment]
I explored around - it looks like one of the last places we need to make timezone aware is the date dropdown. Sahas is already working on that. https://github.com/influxdata/ui/pull/2013/files
