### ISSUE TITLE
Tokens: Display an alert banner on tokens page

### ISSUE THREAD

**Issue by Palakp41** [influxdata/ui#2108]
According to our conversation, nearing the end of this epic, we would display an alert banner to the user displaying when the tokens new UI is going live. So that the new users who have signed up but not received an email with the update are updated on this change.

I was told that we could us the rate-limit banner as the template for this.
This should go live on **Dec 9th, 2021.**
This should be taken down on **Jan 10th, 2022.**
Dates forthcoming...

Here is some provisional text to use from Nick:
Our Tokens UI is changing on Jan 10th, 2022. After that day you only be able to view and safely store token details at the point of creation. If you lose access to token credentials you can generate a new token.  Please copy any existing token credentials in your chosen safe location.

**Comment by nanderson6** [comment]
I updated the dates for this banner.
