### ISSUE TITLE
Turn on the OSS version of testing for PRs

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#211]
We want to support OSS in some way: https://github.com/influxdata/idpe/issues/8963

to do this, we have to make sure we're not constantly breaking it while we focus on cloud. lets have the robots remember how.
This task is to drop a new job into the circle-ci PR workflows that runs the monitor-ci cluster in oss mode (DEV_MODE_CLOUD=0), and run some tests.

There are some tests that only make sense to run on cloud, some that only make sense on OSS, and a majority that run on both. We need a mechanism to account for this as well, probably utilizing the globbing mechanism we use to parallelize tests

**Comment by Asalem1** [comment]
Closed with https://github.com/influxdata/ui/pull/305
