### ISSUE TITLE
Map: Coloring of pins

### ISSUE THREAD

**Issue by UzunerH** [influxdata/ui#2110]
**Proposal:**
The pins displayed in the map visualization should be able to indicate different datapoints/datagroups/etc. as different colored pins to distinguish between them.

**Current behavior:**
All lat/lon measures of a query are currently shown in the same color in the map visualization.

**Desired behavior:**
If the user adds specific tags to measures, the pins should be differently colored. 
For example, similar to the lat/lon definition:
Define a specific tag (e.g. "Group"), which can be provided for lat/lon datapoints. All datapoints with the same value in this tag will have the same color as a pin, while other valued datapoints will have different colored pins.
Also the "customize" tab when selecting the visualization type "Map" only directs to the documentation of the Map visualization, but does not provide any further customization methods. Maybe here some options to choose a specific tag and colors could be provided.

**Alternatives considered:**
As an alternative we are currently using multiple cells in the dashboard to display the differently tagged GPS data to be able to distinguish between two different "paths".
An alternative to display differently grouped datapoints inside one map could be different forms of pins (although that would be unpractical I guess).

**Use case:**
We have a project in which we will start a weather balloon and track it with GPS signals. Further, we have a prediction software running which also return GPS data. All of those are written into the DB. An optimal solution would be to show the actual GPS data and the prediction in one map with different colors to compare them. Currently we are showing them as two cells in a dashboard, which works fine for itself, but takes up more space on the dashboard and is not as effective and convenient in terms of comparing the two paths.
https://community.influxdata.com/t/coloring-pins-in-the-map-visualization/20570/5

**Comment by russorat** [comment]
@UzunerH we are releasing color thresholds based on value this week. that will allow you to have different colors based on the value column, which might work for this use case.

**Comment by kristinarobinson** [comment]
Fixed with thresholds for maps.
