### ISSUE TITLE
Bug: Visual of multiple data tables is cutoff and not grouped when viewing a SimpleTable visualization in Notebooks

### ISSUE THREAD

**Issue by mtian725** [influxdata/ui#2112]
#### Steps to reproduce:

1.  install the noaa sample dataset to a bucket (https://docs.influxdata.com/influxdb/cloud/reference/sample-data/#noaa-water-sample-data)  
2. Open a notebook instance
3. Change time range to `Past 30d` (30 days)
4. Query average temperature 
```
from(bucket: "noaa")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "average_temperature")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```
5. Visualize as a SimpleTable

## Behavior
There are 2 data tables that result from this query: one associated with `coyote_creek` and the other associated with `santa_monica`

The rows of data switch from table 0 to table 1 and vice versa multiple times. The switch from table 1 to table 0 also causes a break in which some rows are cutoff.

![image.png](https://images.zenhubusercontent.com/60be52f95b600c6c0157735b/5ee7de58-65d9-46a6-af45-b665c728617a)
![image.png](https://images.zenhubusercontent.com/60be52f95b600c6c0157735b/ae773c5f-d369-4b21-b6a2-8796c9e45963)
![image.png](https://images.zenhubusercontent.com/60be52f95b600c6c0157735b/971a9ec6-be90-4795-a280-67e1f42e5944)

**Comment by kristinarobinson** [comment]
Verify that this is still an issue.

**Comment by blegesse-git** [comment]
closing this issue as there is no break between the tables anymore. issue is no longer a problem.
