### ISSUE TITLE
Notebooks: can't see result of flux query without adding a visualization panel

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#2113]
If you add a flux script panel, and run preview, there is no way to see the results of the script without adding a visualization panel.  We used to have a preview area within the panel so you could see the results without needing to add another panel.  If we need another panel to see the results, maybe we should add both of them when you add a flux panel??? Not sure, but the current solution seems unintuitive.

**Comment by russorat** [comment]
let's explore elevating the preview out of the notebook flow itself and to a collapsable panel in the UI.

**Comment by drdelambre** [comment]
@barbaranelson did removing the friction of creating a `simpletable` visualization by adding a `table` panel address some of this, or should we keep this open for exploration?

**Comment by barbaranelson** [comment]
I think we can close this one.  For the basic case (creating a new notebook starting with a flux panel), it has been addressed. For the more power-user case, where you are adding a flux panel, it's not as you do need to add another panel, but I think those users would figure out to also add a validation or visualization panel.

**Comment by barbaranelson** [comment]
Closing out as the current experience is ok for now.
