### ISSUE TITLE
Vendor the UI in OSS

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#212]
We dont want OSS to have to install yarn and build the frontend to install a db. Keeping the source in two places also hurts our strategy to keep operational overhead low for OSS support: https://github.com/influxdata/idpe/issues/8963. Lets vendor the frontend assets in the OSS repo.

The workflow is basically that whenever someone pushes into a special branch (lets call it the `oss` branch), circle should build the frontend in OSS mode, capture the assets, and make a PR against `influxdata/influxdb`.

The location of the folder it dumps the assets into doesn't matter that much, as we're also going to have to update the makefiles and readmes in `influxdata/influxdb` to reference whatever folder you chose instead of what they currently link the `--assets` flag to.

And once we have compiled assets being checked into influxdb, we should remove the `ui` folder to ensure that `influxdata/ui` is the only place where we can update the source code

**Comment by danxmoran** [comment]
Something to consider while implementing this: #334

**Comment by drdelambre** [comment]
yus. i think whatever comes out of this ticket will choose the timing and implementation details of that ticket, so i moved it to blocked. don't wanna be prescriptive, but migrating that page to use /health should be a fast follow to closing this one

**Comment by drdelambre** [comment]
it has been requested that ui create releases, scoped to an OSS branch, and have tar'd assets be attached to the tags of those releases, so that we can keep assets outside of the repo, and instead modify the makefile to pull in and unwrap those assets.

**Comment by jzahnd** [comment]
Lets talk with the edge team

**Comment by appletreeisyellow** [comment]
This is done in https://github.com/influxdata/influxdb/pull/21090
