### ISSUE TITLE
Flows React Memory Leak: Can't perform a React State Update on an Unmounted Component

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#2124]
### Steps to Reproduce
1. Refresh the app to clear out any pre-loaded state.
1. Click Books
1. Immediately hit the back button on your mouse (or two/three finger swipe on your trackpad)
1. If the error doesn't fire, keep going back and forth like in the video below

![Screen Shot 2021-07-22 at 5 01 53 PM](https://user-images.githubusercontent.com/146112/126723702-a6b1dd61-0250-4ac8-84cd-d282c465fec8.png)

`flows.list.tsx` line 200 in the sourcemap maps to [this line](https://github.com/influxdata/ui/blob/master/src/flows/context/flow.list.tsx#L291).

https://user-images.githubusercontent.com/146112/127076210-7f0afa69-9dbd-440c-80b9-f4c4e872184b.mov

**Comment by asalem1** [comment]
Closing this as it seems to have been addressed
