### ISSUE TITLE
Maps: No way to pan map when in a notebook

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2162]
when i use the map type in a notebook, i cannot click and drag the map to show more points. see the gif below:

![Kapture 2021-07-28 at 11 08 52](https://user-images.githubusercontent.com/4805997/127347247-0877c0ed-a6c3-4ff1-8d98-f45882d26192.gif)

**Comment by zoesteinkamp** [comment]
this now works with https://github.com/influxdata/ui/pull/2166
