### ISSUE TITLE
SimpleTable pagination is limited to only certain pages if the table is resized

### ISSUE THREAD

**Issue by TCL735** [influxdata/ui#2170]
SimpleTable pagination is limited to only certain pages if the table is resized.

- build a query and submit
- switch to raw data view
- resize the table
- click on the last page in the pagination
- use an arrow button to paginate
- observe that the pagination recycles without going through all of the pages (many pages are no longer accessible through pagination)

https://user-images.githubusercontent.com/10736577/127400422-48aa0279-8478-43d6-8396-87c1ac4f2076.mp4

**Comment by drdelambre** [comment]
seems to be an issue with how it computes the number of pages (seems like pages 4 and 5 dont exist in this example), but the one that perplexes me is what is happen when page 3 selects itself, but only while i'm progressing down the pages, and not up

![Peek 2021-07-28 15-16](https://user-images.githubusercontent.com/1434802/127403406-d8bad9f2-6cd1-4384-b604-13a0ed42af6f.gif)
