### ISSUE TITLE
Notebooks: i don't want to have to delete a bunch of notebooks i never intended to keep

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2173]
user:  I just spent a bit of time rummaging around in the cluster, and I’ve created a ton of random notebooks that I now need to delete. I didn’t intend to keep any of these notebooks long term - I was just exploring the data.

- as a notebooks user, i would like a way to indicate that i intend to keep this notebook around long term, otherwise, the notebook is removed when i navigate away.

When a user opens a new notebook (either by editing a resource, creating a new notebook, or linking to a new notebook from another part of the application), the user is made aware that the notebook will not be saved until they perform an explicit action to save the notebook. This explicit action could be a button, or it could be something like giving the notebook a non-default name. Let's explore these options and see which one flows better.

the notebook will still auto-save as it does today. the notebook can autosave before the user explicitly indicates they intend to keep this notebook around long term. Once they tell us to keep the notebook, auto-save continues as usual. If they never indicate they want to keep the notebook, it should not show up in the notebooks page.

if a user attempts to navigate away from a notebook before explicitly saving it, they should be presented with a warning that their progress will be lost and an option so save it.

fyi @barbaranelson

**Comment by drdelambre** [comment]
we attempted this with ephemeral notebooks, which has shipped. all future work around this area should be encapsulated through the evolution of that solution
