### ISSUE TITLE
Notebooks: Switch to last doesn't seem to work

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#2184]
I will love this feature (when it's working)!

I had a default visualization type of graph, and the data I selected was a string, so 'mean' the default aggregator wouldn't work. I got the very helpful message:
mean cannot be applied to strings, try selecting last
and a button 'Switch to last'.

I pushed the button, and the text changed to:
last cannot be applied to strings, try selecting last.
![Screen Shot 2021-07-29 at 3 20 14 PM](https://user-images.githubusercontent.com/13143006/127573381-391961d1-ba5f-4082-9de2-bb05fd351c0c.png)

**Comment by drdelambre** [comment]
@Asalem1 fixed this with #2301, should be g2g in prod
