### ISSUE TITLE
Notebooks: Adding an empty flux cell between metrics selector and viz leads to an error

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2191]
To repro:
1. create a new notebook
2. select a metric
3. add a flux script editor between the metric selector and the viz
4. preview the notebook

![image](https://user-images.githubusercontent.com/4805997/127675208-1cc72d0c-0c36-4c7c-9bf8-5c153db6b2d3.png)

**Comment by drdelambre** [comment]
this is expected behavior, as you created a flux source, but didn't send any query. there might be better ways of letting a user know that this is the case, but as it stands this isn't a bug. please repeat in the form of a product ask
