### ISSUE TITLE
Tasks Error Messages: Format flux in task run log

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#2207]
### Background
Tasks show their flux as raw text (with `\n` characters). We should make this more human readable.

![Screen Shot 2021-08-02 at 13 03 10](https://user-images.githubusercontent.com/146112/127898356-f4e1af28-2795-49c3-adf0-da32d3a292b2.png)

### Other information
Denise provided [this example](https://github.com/influxdata/ui/blob/master/src/flows/pipes/RawFluxEditor/readOnly.tsx#L39-L46) of a `FluxMonacoEditor` being used in readonly mode.

Note: `variables` can be passed in as an empty array if no variables are present

### Acceptance Criteria
- Properly display the flux

**Comment by russorat** [comment]
For this, i'd love to add a read only monaco editor to the top of the run log modal where the flux from the first log message is displayed in a formatted and highlighted way.

**Comment by daviddkkim** [comment]
@hoorayimhelping  

How feasible is it to parse that string into a syntax highlighted view like this ? 

![image (9)](https://user-images.githubusercontent.com/12561526/128553879-a2536d68-76c9-4cd4-9e14-bbe614a835a7.png)

**Comment by hoorayimhelping** [comment]
See also: https://github.com/influxdata/ui/issues/2798

**Comment by hoorayimhelping** [comment]
this is blocked by https://github.com/influxdata/idpe/issues/12019/ but i can't add it to the blocked by control for some reason

**Comment by glinton** [comment]
This is now unblocked

**Comment by Luckette** [comment]
talk to Denise about using a read only monaco editor for syntax highlighting
