### ISSUE TITLE
Investigate adding additional endpoints for alerts

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2208]
As part of the alerting story, we would like to expose all the alerting endpoints available in Flux. They are:

https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/contrib/discord/endpoint/
https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/contrib/opsgenie/endpoint/
https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/pushbullet/endpoint/
https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/contrib/sensu/endpoint/
https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/contrib/teams/endpoint/
https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/contrib/telegram/endpoint/
https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/contrib/victorops/endpoint/
https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/contrib/zenoss/endpoint/
https://docs.influxdata.com/influxdb/cloud/monitor-alert/send-email/#examples

Also including the original ones of Slack, Pagerduty, and HTTP.

This is the current API for adding a new alerting endpoint:
https://docs.influxdata.com/influxdb/cloud/api/#operation/CreateNotificationEndpoint

This issue is to investigate what changes would need to happen to be able to support adding these additional endpoints into that API, and/or other options for supporting stored values for these notification endpoints in the UI.

This issue is closed when we have issues created for the changes needed to support all those endpoints in the API.

**Comment by drdelambre** [comment]
and this is for notebooks or the other checks interface?

**Comment by russorat** [comment]
yes, this is for notebooks.

**Comment by juliajames12** [comment]
@russorat @jzahnd Here is an initial list of the [additional endpoint details](https://docs.google.com/document/d/1Tuo_HJNUrbbJCQ92qBa01UxFtytUzofLHYVNtGLPsaM/edit?usp=sharing) to be reviewed before I start designing these endpoint form details.
