### ISSUE TITLE
Secrets: Add the ability to inject secrets into a Flux script in notebooks

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2213]
Goal
The goal of this issue is to connect the new secrets page with other parts of the UI where it would be useful to have that information. One area is when editing a Flux query. Since we have a way to 

Acceptance Crit
- as a notebooks user, i would like an easy way to inject secrets into my flux code
- as a notebooks user, i would like to view the list of secrets keys where i am editing flux code
- as a notebooks user, i should be able to hide or show secrets when editing flux code
- as a notebooks user, when i inject a secret into my flux code, it should be formatted correctly
- as a notebooks user, there should be a way to quickly jump to the secrets page to add a new secret (bonus points if you can add a new secret without leaving this page)

Design
https://www.figma.com/file/XulFKIibFgx9xtSL92rHlY/Injecting-Secrets-in-Notebooks?node-id=43%3A1060

Notes:
 - secrets are fetched from flux using the secrets lib: `my_secret = secrets.get(key: "<the key>")`
 - when using secrets, the user will also need to import the `import "influxdata/influxdb/secrets"` package

**Comment by jzahnd** [comment]
Closing for other issues representing this task
