### ISSUE TITLE
Errors charting after setting _field on a column created by a sum()

### ISSUE THREAD

**Issue by midzelis** [influxdata/ui#2223]
Context/original issue reported in forums here: https://community.influxdata.com/t/synthesize-column-after-sum-field-lost-after-sum/20924/5

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

Load the attached .csv export of my data, then perform this query

```
interval=from(bucket: "ups")
 |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
 |> filter(fn: (r) => r["_measurement"] == "nutgraf_ups_data")
 |> filter(fn: (r) => r["_field"] == "nutgraf.ups.realpower")
 |> aggregateWindow(every: 1d, fn: integral, createEmpty: false)
 |> map(fn: (r) => ({r with _value: r._value / 3600000.0 }))
 |> keep(columns: ["_value", "_time", "_field", "nutgraf.ups.name"]) 

summed = interval
|> group(columns: ["_time"])
|> sum()
|> group()
|> map( fn: (r) => ({r with "nutgraf.ups.name": "TOTAL"}))

union(tables: [interval,summed])
```
Notice that summed table doesn't contain _field, so preserve it... 
```
interval=from(bucket: "ups")
 |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
 |> filter(fn: (r) => r["_measurement"] == "nutgraf_ups_data")
 |> filter(fn: (r) => r["_field"] == "nutgraf.ups.realpower")
 |> aggregateWindow(every: 1d, fn: integral, createEmpty: false)
 |> map(fn: (r) => ({r with _value: r._value / 3600000.0 }))
 |> keep(columns: ["_value", "_time", "_field", "nutgraf.ups.name"]) 

summed = interval
|> group(columns: ["_time", "_field"])
|> sum()
|> group()
|> map( fn: (r) => ({r with "nutgraf.ups.name": "TOTAL"}))

union(tables: [interval,summed])
```
the chart UI in influxdb goes crazy... 

**Environment info:**

- System info: Run `uname -srm` and copy the output here
```
root@influxdb:/# uname -srm
Linux 5.11.17-1-pve x86_64
```
- InfluxDB version: Run `influxd version` and copy the output here
```
root@influxdb:/# influxd version
InfluxDB 2.0.7 (git: 2a45f0c037) build_date: 2021-06-04T19:17:40Z
```
- Other relevant environment details: Container runtime, disk info, etc

**Comment by midzelis** [comment]
[2021-08-02-19-38_influxdb_data.csv](https://github.com/influxdata/ui/files/6920138/2021-08-02-19-38_influxdb_data.csv)

**Comment by kristinarobinson** [comment]
@midzelis -- Can you tell me whether you are using the Cloud Native version of the UI or the Open Source version ?  Thanks.

**Comment by zoesteinkamp** [comment]
This issue has been resolved by anais and we have determined this is not a ui team bug, but possibly a flux bug.
