### ISSUE TITLE
Epic: I would like to view and manage explicit bucket schemas in the UI

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2231]
### Target Customer / Background data / Context / Market Size
The target customer for this feature is someone who is familiar with InfluxDB and is using the product at scale. They are looking for ways to lock down the data being written to particular buckets in their instance. The ability to create a bucket, view and update the explicit measurement schema's in that bucket, allow them to protect the schema in that bucket from users attempting to write data with different tags or fields.

### Goals
The goal of this epic would be to enable the viewing of measurement schemas in the UI. This would not include the ability to edit or change the schema.

### Acceptance Crit
 - DONE ~as a user, i would like to view bucket type (implicit/explicit) when viewing buckets (buckets list page)~
 - DONE ~as a user, i would like the ability to quickly view the explicit schema of a bucket~
 - DONE ~as a user, i would like the ability to quickly copy the explicit schema to the clipboard~
 - DONE ~as a user, i would like to create a bucket with a schema type: explicit~
 - DONE ~as a user, i would like to add a new measurement schema on an explicit bucket by uploading a file~
 - DONE ~as a user, i would like to extend an existing measurement schema by re-uploading the file with additions~
 - DONE  for csv and json: ~as a user, i would like to download a file containing a measurement schema in a format compatible with the ui and cli~
 - DONE ~as an analytics user, i would like to see the number of times the explicit schema is viewed on a bucket (ui only)~
 - DONE ~as an analytics user, i would like to see the number of explicit schema buckets created (ui only)~
 - DONE ~as an analytics user, i would like to see the number of times a measurement schema is downloaded (ui only)~
 - DONE ~as an analytics user, i would like to see the number of times a measurement schema is created (ui only)~
 - DONE ~as an analytics user, i would like to see the number of times a measurement schema is re-uploaded (updated) (ui only)~
 - DONE ~write up a short document with all the events that have been added~ (included in the description in this epic)

### Release Plan
TBD

### Notes
 - The ability to work with explicit schema is behind a feature flag for now. you will need to request access to it before working on this feature.
 - Here are the docs for managing bucket schemas from the command line: https://docs.influxdata.com/influxdb/cloud/organizations/buckets/bucket-schema/
 - These are the apis for getting the bucket schema: https://docs.influxdata.com/influxdb/cloud/api/#operation/getMeasurementSchemas
 - A list of errors can be found here: https://docs.influxdata.com/influxdb/cloud/organizations/buckets/bucket-schema/#errors

### Events added as part of this epic:
'bucket.view.schema.explicit'    view schemas
'bucket.creation'                create a new bucket
'bucket.schema.explicit.creation.uploadSchema'   called during creation, for each new schema being uploaded to the newly created bucket
'bucket.download.schema.explicit'  each time an existing schema is downloaded
'bucket.schema.explicit.editing.uploadSchema' uploading a new schema to an explicit bucket that already exists
'bucket.schema.explicit.editing.updateSchema' updating a schema to an explicit bucket that already exists

### Team
 - Anchor / Dev Champion - @jrenee42 
 - Product Manager - @nanderson6 
 - Design- @daviddkkim 

For the design, let's start with opening a modal when the user clicks on the explicit schema type in the buckets list. The modal should have the title `Bucket Schema` and should display the formatted JSON response from the getMeasurementSchemas API. We should be able to use the same code widget we use for displaying code samples in the app, which also includes the ability to copy the code (for use in the CLI).

figma here: https://www.figma.com/proto/nMxVr5g4Tp1vXVteztFmNL/Untitled?node-id=106%3A816&scaling=min-zoom&page-id=52%3A61&starting-point-node-id=106%3A816

![image](https://user-images.githubusercontent.com/4805997/128746995-6ab35e48-0632-4998-8961-df2d5c84645e.png)

**Comment by jrenee42** [comment]
@daviddkkim  do we want a popover(tooltip) or an old style tooltip (/title) on the file uploader component, to tell them to click to select or drop a json file?  I put a popover in and it looked bad, so I removed it.
