### ISSUE TITLE
Notebooks: I would like help building an alert status message

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2236]
### Target Customer / Background data / Context / Market Size
One of the trickiest parts of building your alert is customizing the status message. For new users that are not familiar with flux and the interpolation syntax, this can be a barrier. Also, if you format your message incorrectly, it has the potential to stop your alert from firing altogether. 

### Goals
The goal of this issue is to make it easier to build a custom alert status message that is valid.

### Acceptance Crit
- as a user, i would like the ability to inject columns and fields from my data into my status message
- as a user, i would like to preview my status message to understand that it makes sense

### Notes
- when a user injects a variable into their status message, the format should be `${ r.<variable> }`.
- flux has been updated to automatically convert floats to strings, so you don't need any helper functions

### Release Plan
TBD

### Team
 - Anchor / Dev Champion
 - Product Manager - @russorat 
 - Design - @juliajames12

**Comment by drdelambre** [comment]
does #2285 satisfy the same thing here?

**Comment by drdelambre** [comment]
imma say it does
