### ISSUE TITLE
Notebooks: Clicking cancel on a long running query has no effect

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2237]
when working with this in tools, clicking cancel doesn't cancel the query.

here's an example for 1h:
```
from(bucket: "apps")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> last()
```

![Kapture 2021-08-04 at 10 18 00](https://user-images.githubusercontent.com/4805997/128197426-75c70ee6-a03a-4dfa-922f-1f04dc77f5a7.gif)

**Comment by drdelambre** [comment]
it scares me that a sev-2 wasn't surfaced sooner, thankfully it's not that bad

**Comment by subirjolly** [comment]
@russorat Please validate this fix whenever you get a chance.

**Comment by russorat** [comment]
works great! thanks!
