### ISSUE TITLE
Notebooks: single stat config options have many issues

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2238]
Here are a list of issues i found with single stat config options in notebooks:

- prefix and postfix only allow a single char, and do not update when typing
- toggle between auto and custom for decimal places doesn't update the UI
- changing the decimal places using up and down have no effect on the ui
- you cannot update the text in the decimals option
- adding a threshold, there's no way to see what value i am using in the threshold
- clicking the colorization toggle has no effect in the UI

![Kapture 2021-08-04 at 10 41 01](https://user-images.githubusercontent.com/4805997/128201221-9d8cabea-9c03-42ab-af5a-db5c9361cfb0.gif)

**Comment by drdelambre** [comment]
triaging: this has nothing to do with single stat. there's something wrong with updating view options when they're in the sidebar. same thing happens when setting the axis label in line graphs
