### ISSUE TITLE
Notebooks: Lots of flickering in the query builder panel

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2239]
noticed the following issues with the query builder panel:

- if you select a bucket, then select a measurement, then go back and select a new bucket, the measurements aren't updated
- lots of flickering when selecting multiple tags for filtering.

![Kapture 2021-08-04 at 10 47 52](https://user-images.githubusercontent.com/4805997/128202606-dd73dfb1-791a-4b91-9795-09e3f9d55ac1.gif)

**Comment by drdelambre** [comment]
I fixed this forever ago
