### ISSUE TITLE
Notebooks: Only functions that accept a pipe argument should be injected with a pipe forward

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2241]
today, no matter what function you inject into your script, it is always added with a newline and a `|>` in front of it.

The expectation is that only functions that operate on tables would have the pipe forward operator. an example of this is the `schema.fieldsAsCols()` function: https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb-schema/fieldsascols/#function-definition

notice the function definition includes a `(tables=<-)` indicating that it operates on a set of incoming tables.

an example of a function that does not accept a tablesa argument is `schema.fieldKeys()`: https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb-schema/fieldkeys/#function-definition

When i inject a function that does not operate on a set of tables, then the function should be added directly where the cursor is, without a newline or a `|>` operator.

**Comment by wiedld** [comment]
Already fixed.
