### ISSUE TITLE
Notebooks: Idea: Add the ability to run a single panel and update panels "below" it

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2242]
use case:
i was using a notebook to collect an bunch of individual stats from a measurement. Once I had one stat, i added a new source underneath it and continued working. as the list of individual stats started to grow, previewing my notebook took longer and longer, even though i wasn't interested in the pervious panels.

proposal:
add a way to preview just a single panel, and update the panels after it (or dependant on it, not sure what the right wording is). Ideally, i'd like to run the panel and update any visualizations related to that panel without executing all the queries in the notebook.

**Comment by drdelambre** [comment]
@russorat the technical limitation on this task has been lifted with #2196, lets talk about it again!

**Comment by russorat** [comment]
Reopening this with the following request:
 - add a feature flag to enable and disable this
 - disable the feature flag until we have a better idea on how this interacts with with other preview capability in notebooks.
