### ISSUE TITLE
Pagination widget seems broken

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2248]
Clicking the next or previous in the pagination widget seems broken.

the page i am on should always be displayed. 

![Kapture 2021-08-04 at 15 53 47](https://user-images.githubusercontent.com/4805997/128246110-bc29ee46-88a7-46c1-b270-df24f6d778ac.gif)

**Comment by drdelambre** [comment]
the ui part of this was fixed in #2252, the rest of this is a clockface bug

**Comment by hoorayimhelping** [comment]
This isn't a clockface bug. This happens when the pagination nav doesn't have its width set. The component rendering the pagination nav has to explicitly set the pagination nav's width.

**Comment by ChitlangeSahas** [comment]
This issue seems to be fixed by Merrick's PR https://github.com/influxdata/ui/pull/2252 . Will be closing this.
