### ISSUE TITLE
Notebooks: Unable to select error message in the UI

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2262]
as a user, i need to copy and paste the error message from a notebook but i cannot select it in the UI.

Let's make the text selectable and add a copy button when an error is displayed.

**Comment by drdelambre** [comment]
where are you seeing this error message?

**Comment by genehynson** [comment]
I need a screenshot of this error message - I have no idea how to work this ticket otherwise

**Comment by russorat** [comment]
sure.

to repro, open a "Write a Flux script notebook"
enter the following flux:
```
import "influxdata/influxdb/sample"

sample.data(set: "usgs") |> sum()
```
preview
try to copy the error message in red from the viz panel

![image](https://user-images.githubusercontent.com/4805997/133111002-fbc500f6-f59a-4184-bb48-ddeacb360a60.png)

**Comment by genehynson** [comment]
Got it - thanks!
