### ISSUE TITLE
Notebooks: I can choose from a list of expressions to add to my alert message

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#2285]
We would like to make it easier and more intuitive for users to edit an alert message within a notebook by providing a list of expressions that they can inject. 

![Screen Shot 2021-08-09 at 11.42.16 AM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/12ccfb5e-b34f-4fe0-b555-78a3177739ed)

### Acceptance Criteria

- When a user clicks on the expressions button it opens up a side panel on the right (we can use the same side panel format as the functions side panel)
- The expressions list includes a list of expressions available for that dataset
- A user can inject an expression and it will appear where their cursor is in the alert message box
- A user can close the expressions panel either by clicking the "x" button or clicking the expressions button again

Design: @juliajames12 

Design file: https://www.figma.com/file/a7qLfWdlUDrhab9aWIxE65/Create-an-Alert-from-Notebook?node-id=664%3A9052

**Comment by drdelambre** [comment]
part of this task is also to find out a way to get the system variables available for the message (prefer an api defintion and not a const array)

**Comment by genehynson** [comment]
"system variables" meaning this: https://docs.influxdata.com/influxdb/cloud/monitor-alert/checks/create/#flux-only-interpolates-string-values
