### ISSUE TITLE
Notebooks: I can test an alert from the alert panel

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#2287]
We would like for users to be able to test an alert from the alert panel to ensure the alert endpoint is set up properly, message shows up as intended, and alert conditions are accurately set.

![Screen Shot 2021-08-23 at 12.46.00 PM (1).png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/60abf0d9-2545-4560-a083-c99f2afce97f)

![Screen Shot 2021-08-09 at 12.05.48 PM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/cde5fc90-5326-45dc-b0d5-34cdaefe0666)

### Acceptance Criteria

- When a user clicks on the test endpoint button a message is sent to the chosen endpoint
- When the test alert is sent, a notification at the top of the notebook shows that a test alert has been sent to the chosen endpoint

Design: @juliajames12 

Design file: https://www.figma.com/file/a7qLfWdlUDrhab9aWIxE65/Create-an-Alert-from-Notebook?node-id=684%3A4957

**Comment by juliajames12** [comment]
@russorat @drdelambre We still need to determine what would be included in this test alert. We talked about a couple of options, but I don't believe we landed on anything. 

When testing the alert we want users to feel confident that what they've set up in the notebook will run as intended - correct message, endpoint, and conditions. How close to the real alert can we get with this test alert?

**Comment by drdelambre** [comment]
everything but conditions iirc, that would be handled elsewhere per tim's question in #design last week

**Comment by drdelambre** [comment]
some concerns that were raised by this moved to limiting it's scope. the first phase (and probably the scope of this ticket) is to move the `test` button over to the panel where you enter the endpoint details, and when you click on it... it should run a query, that runs the notification endpoint, with the credentials and a test message of "your credentials worked" (until someone comes up with something better). if i add a slack endpoint... add the credentials and url in there... then click "test", i should see the message "your credentials worked" show up in my slack channel.

the second phase is to use the actual message attached to the alert, with full string interpolation support. we want to ensure that clicking `test` only sends one alert.

**Comment by juliajames12** [comment]
Updated design with test endpoint option.
