### ISSUE TITLE
Notebooks: I can select a notebook preset from the notebook list page

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#2308]
We would like help users discover different ways to use notebooks by adding a section at the top of the notebooks list page with links to predefined notebooks.

![Notebooks List Page (3).png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/8081e814-2243-48f6-9d4f-ddda6dc6f696)

Predefined Notebooks to link to: 
- **New Notebook** - Metric selector + simple table + graph (what we currently use for Create Notebook)
- **Set an Alert** - Metric selector + simple table + alert panel
- **Schedule a Task** - Metric selector + simple table + schedule panel
- **Write a Flux Script** - Flux panel + simple table
- **Blank Notebook** - no panels

Prototype: https://www.figma.com/proto/a7qLfWdlUDrhab9aWIxE65/Create-an-Alert-from-Notebook?node-id=772%3A8442&scaling=min-zoom&page-id=662%3A5686&starting-point-node-id=772%3A8225&show-proto-sidebar=1

Images to include:

Set an Alert Image
![Set an Alert Image.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/51378e5c-9d3c-42a9-9d49-ccd2d9d7733b)

Schedule a Task Image
![Schedule a Task Image.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/23ddf308-9187-4d67-8a7b-c7fde615ffc1)

Write a Flux Script Image
![Write a Flux Script Image.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/f7a6df2c-cc82-45b9-a8d0-ccd2e9c512ed)

Blank Notebook Image
![Blank Notebook Image.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/832b79a7-fb71-4bb5-8903-02650ae740f3)

Design: @juliajames12 

Design file: https://www.figma.com/file/a7qLfWdlUDrhab9aWIxE65/Create-an-Alert-from-Notebook?node-id=668%3A5337

**Comment by russorat** [comment]
@ShmuelLotman what's still to be worked on here?
