### ISSUE TITLE
Metric Selector Schema doesn't persist across panels

### ISSUE THREAD

**Issue by Asalem1** [influxdata/ui#231]
### Steps to Reproduce:

1. Select a bucket in a metric selector in flows
2. See Results for that bucket
3. Add a new Metric Selector
4. Select a different bucket for the second metric selector
5. See results for the first bucket disappear

### Background

What's happening here is that we aren't storing the schema results onto the pipe, but are actually storing it outside in the reducer. This is causing the UI to apply results directly to the pipe without storing a reference to the original results

**Comment by 121watts** [comment]
@Asalem1 please make this a real story.
