### ISSUE TITLE
Notebooks: Flux Predefined Notebook

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#2323]
We want to add a predefined notebook for users who want to start with flux. This notebook will include a flux panel and a simple table. 

![Screen Shot 2021-08-11 at 5.38.28 PM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/471df6c6-7256-44ba-a422-0e756d4a3a28)

**Comment by drdelambre** [comment]
this was done here: https://github.com/influxdata/ui/pull/2171
