### ISSUE TITLE
Notebooks: Blank Predefined Notebook

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#2324]
We want to add a predefined notebook for users who want to start from scratch with a blank notebook. This notebook wouldn't include any panels. 

![Screen Shot 2021-08-11 at 5.51.58 PM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/849fe79e-e2e8-461d-9b7e-9b256213d636)

**Comment by drdelambre** [comment]
this was taken care of here: https://github.com/influxdata/ui/pull/2330
