### ISSUE TITLE
Tasks: stop shedding users

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#2335]
when analyzing how users generate tasks within our system, i found that of the ~330 people where trying to create a task through the task page, 30 had tried to import a task; an interface to the depreciated v1 templating system. none of them succeeded. Instead of dropping 10% of our traffic into a deadend when they try to create a task, lets just remove that workflow completely and have the "create task" button on that page... create a task

![Screenshot from 2021-08-12 11-25-19](https://user-images.githubusercontent.com/1434802/129249134-73b9b48e-703c-441f-9138-6cd30986152c.png)

data from last week

success is defined as clicking submit with a valid json object in one of the template import forms, tracked with event `Valid JSON Task Import Submitted`

**Comment by barbaranelson** [comment]
@russorat can you weigh in on this one? Thanks.

**Comment by russorat** [comment]
we also need to remove the export option from the UI as well, as it generates templates using the old format. The other option is to update both of these to be the same as the existing InfluxDB Templates format.
