### ISSUE TITLE
Design for Cancel Flow Inside App

### ISSUE THREAD

**Issue by nanderson6** [influxdata/ui#2346]
We would like for users to be able to provide feedback prior to deleting their account. 

Currently, we only collect user feedback on the landing page after account deletion, but by requiring it earlier in the account cancellation flow, we will gain a better understanding of reasons why users are deleting their accounts and eventually be able to provide them with potential solutions.

[Design file](https://www.figma.com/file/0gNEHedxD1J0bb1mkie6Aw/Free-Users-Account-Deletion?node-id=504%3A538) 

[Prototype] (https://www.figma.com/proto/0gNEHedxD1J0bb1mkie6Aw/Free-Users-Account-Deletion?node-id=523%3A1150&scaling=min-zoom&page-id=504%3A538&starting-point-node-id=523%3A1150)

More details [here] (https://docs.google.com/document/d/1DM54OmPaDZskfLpqwn1J412ngDuhhTERgybHdO1xTXo/edit)

**Comment by juliajames12** [comment]
@nanderson6 @subirjolly I've added the updated design. Let me know what you think! If you select "Other reason" in the protoype it will take you through the full flow.

**Comment by nanderson6** [comment]
Hey @juliajames12 , this is looking great.
I'm going to be working on some of the dropdown options later this week.
One thought I had when looking at the mock-up's, is that from a customer's perspective we should probably put the disclaimer text and liability radio button on top, and the survey questions below that.
I'm imagining that some users may be inclined to cancel the operation once they read that they need to back up their data first, and/or will lose all their data.
If they spent time writing out an answer an then read the fine print and cancel the operation after that would have been a waste of time.

What are your thoughts on that change?
