### ISSUE TITLE
Flakes in Annotations Tests In Firefox for Range, Band, Plot

### ISSUE THREAD

**Issue by ShmuelLotman** [influxdata/ui#2359]
Getting failures in annotations E2E tests quite frequently in firefox, see here for example: 
https://app.circleci.com/pipelines/github/influxdata/monitor-ci/3962/workflows/da86c053-e545-4eac-9e8d-c0ce74e6ab30

**Comment by genehynson** [comment]
related: 
- https://github.com/influxdata/ui/issues/2344
- https://github.com/influxdata/ui/issues/2334
