### ISSUE TITLE
Notebooks: I can select from a list of existing endpoints in the alert panel

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#2377]
We'd like to keep the existing endpoints we currently have in the alert panel, but in a new format that will accommodate a larger list in the near future. 

Unselected
![Screen Shot 2021-08-16 at 12.19.15 PM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/45775114-2a64-466b-968f-4f15d465d66a)

Slack
![Screen Shot 2021-08-16 at 12.19.23 PM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/9e5947b4-7200-4bc7-b8ef-339cab4386a1)

HTTP Post
![Screen Shot 2021-08-16 at 12.19.38 PM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/e077b43c-1a4d-491e-8826-6982a0c89e14)

PagerDuty
![Screen Shot 2021-08-16 at 12.19.47 PM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/8ff4c83e-3ae9-483e-892c-425acc2620a8)

**Comment by ShmuelLotman** [comment]
This is done

**Comment by juliajames12** [comment]
@jzahnd Reopening this issue. The UI in the alert panel hasn't been updated to reflect these mocks.
