### ISSUE TITLE
Notebooks: I can test the endpoint of an alert

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#2378]
We would like users to be able to test the endpoint they selected for their alert so they can catch and correct any issues before creating the alert task.

![Screen Shot 2021-08-16 at 12.51.33 PM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/d7b1eb46-18ce-4b1a-babf-0df1aa183a06)

Design Lead: @juliajames12

**Comment by drdelambre** [comment]
@juliajames12 can you update the design on #2287 and close this ticket? this one is missing context on what is required from the engineer
