### ISSUE TITLE
Add Form to Free Tier `Delete Organization` Popup

### ISSUE THREAD

**Issue by subirjolly** [influxdata/ui#2419]
Add Form to Free Tier Delete Organization Popup

Something like this mock

![image](https://user-images.githubusercontent.com/1637395/130116411-aa12e64f-97f6-49a9-9444-02b7bedcc782.png)

Question dropdown options here:
https://docs.google.com/document/d/1reVivSO7eV_DAv9L12iJrkuDsFGM4IyMamITjV0x2Hs/edit

**Comment by subirjolly** [comment]
Also send relevant data(tbd) to Snowflake using rudderstack.

**Comment by subirjolly** [comment]
@genehynson did you work on this? I created another story thinking I don't have this one.

**Comment by genehynson** [comment]
I don't think I did. The only delete org related thing I worked on was this: https://github.com/influxdata/ui/issues/2427

**Comment by subirjolly** [comment]
It's unrelated. Closing this story and working on the duplicate story I created this morning.
