### ISSUE TITLE
Annotations: As a user I can modify an existing annotation 

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/ui#242]
See #241 [creating]
See #222 [deleting]

I may have placed an annotation at an incorrect time or I want to change the text content of the annotation

GIVEN I have at least 1 annotation stream visible (and in existence)
AND there are annotations visible in my current time range
THEN I can interact with and modify them from any visualization they are overlaid on to

WHEN I hover over an annotation
THEN I see a tooltip containing time, summary, (optionally) message, and an edit button

WHEN I mouse into the tooltip and click the edit button
THEN I see an overlay (similar to the add annotation overlay) with fields to modify the summary, timeStart, timeStop, and message

WHEN I click the green `Save Changes` button
AND there are no form errors
THEN the overlay closes and my annotation is updated
AND I see the changes reflected in the position of the annotation and the text in the hover tooltip

### Error state

WHEN I click the green `Save Changes` button
AND there are form errors (empty summary, timeStart, timeStop)
THEN I see error text below each offending input
AND the form does not submit

**Comment by hoorayimhelping** [comment]
closed with #990
