### ISSUE TITLE
Alerts display on home screen says checks don't exist when they do

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#2422]
In tools, I was looking at the list of alerts on the home screen, and noticed that some of them were clickable and some were not. When I hovered over the ones that were not links, I see the message "The check that created this no longer exists".  But, if I go to the alerts screen, I can see that check. Also, if a check is running, I don't know how it doesn't exist.  See screenshots for details.

![Screen Shot 2021-08-19 at 10 17 41 AM](https://user-images.githubusercontent.com/13143006/130114714-3ae46555-70ce-4e1a-b319-64234669935d.png)
![Screen Shot 2021-08-19 at 10 18 02 AM](https://user-images.githubusercontent.com/13143006/130114748-914dc809-0a5c-4963-901f-1d5d297bfd6d.png)

**Comment by subirjolly** [comment]
found another issue, most likely unrelated but adding the number here. just in case.

#2439

**Comment by russorat** [comment]
A few things here:

We should update the hover text to say something like "This status was generated from a custom alert Task"

The second part about being unable to link is a known issue, but one we need to find a solution for. The check you see on the alert screen isn't what generated this status, it was generated by a custom alert task with the same name.

Long story short, there's no way for us to link to custom alert tasks from the `_monitoring` bucket. This is something we need to solve for in engineering, especially as we see more and more custom alert tasks being created.

**Comment by barbaranelson** [comment]
Oh, that is confusing.  How do we distinguish 'custom alert tasks' from regular tasks, or from alerts with the same name? I guess I don't understand how these components relate to each other.  Is it something we would need to solve at the platform level? Just need to know who to ask, and what to ask for.

**Comment by subirjolly** [comment]
Currently, it's not possible to distinguish as there's no way back from a check back to its task. You can create a custom task and make it pump to `_monitoring` bucket with a custom check id.
In the following image, the Alert named `Query Request Rate` is pushing this generated check id to _monitoring.
![image.png](https://images.zenhubusercontent.com/5fa9843597598f467dccb2b9/1b3247b9-10af-42a3-ba87-91b95f20ab1c)

Whereas in this following image, this is pushing a custom check id to _monitoring.
![image.png](https://images.zenhubusercontent.com/5fa9843597598f467dccb2b9/e3d18ccf-7ee9-439d-a5dd-13c9fa53ee24)

I had a discussion with Russ and seems like that we would have to create a Research task to figure out how to fix this issue. I will create an issue and will brainstorm/work on this with my team or others.

**Comment by subirjolly** [comment]
I am also looking at how we distinguish between the Alert Tasks and Custom Tasks in the codebase to get a better sense.
