### ISSUE TITLE
Send Data to Snowflake When Clicking `Delete` For Deleting Organization

### ISSUE THREAD

**Issue by subirjolly** [influxdata/ui#2424]
Send relevant data(tbd) to Snowflake using rudderstack when clicking `Delete` button for deleting the organization.

![Screen Shot 2021-08-19 at 2.55.43 PM.png](https://images.zenhubusercontent.com/5fa9843597598f467dccb2b9/3e95d825-64ae-46fc-910e-f5eb97a82724)

Do this for the Free and PAYG forms.

**Comment by jzahnd** [comment]
Lets confirm what needs to be sent, right now we are thinking:

- Tier
- UserId
- Org
