### ISSUE TITLE
Notebooks: Add a loading state to the alert panel

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#2433]
We would like to add a loading state to the alert panel when it's loading. Please keep this consistent with the loading state from the visualization and column mapping panels, which shows the text "Loading".

https://images.zenhubusercontent.com/279622976/17166b28-fec7-46ee-a939-3b0fed2bc226/screen_recording_2021_08_23_at_10_12_07_am.mov

**Comment by jzahnd** [comment]
Let's consider if we want to abstract this loading behavior to a higher level in another issue.
