### ISSUE TITLE
Notebooks: I understand that I have to click Preview in order to see the results of the alert, visualization, and column mapping panels

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#2434]
We would like to make it easier for users to understand that they need to click "Preview" in order to see the results of the alert, visualization, and column mapping panels. Right now, those panels only show "This cell will display results from the previous panel" prior to the user selecting preview. To make it easier to understand, we'd like to add the Preview button to the panel itself and example the phrase to say "This cell will display results from the previous cell after selecting Preview."

Current Design:
![Screen Shot 2021-08-23 at 10.25.21 AM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/c8be159f-a1ec-4a32-8e75-f95f80b6ac1e)

New Design:
![Notebook - input selected (7).png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/83ce272f-2697-4b22-af60-1188bb83ca33)

**Comment by drdelambre** [comment]
is this invalidated with #2242?

**Comment by juliajames12** [comment]
@jzahnd @drdelambre @russorat I've updated this issue with the new design.
