### ISSUE TITLE
Epic: Dynamically create Flux Help Panels from source files

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#2489]
### Target Customer / Background data / Context / Market Size
The user in the UI who wants to get up-to-date, in depth flux documentation help while building queries in the data explorer.

### Goals
Update the help display panel for all flux functions so that the panel information is derived from flux source files, and not hard coded.  

### Acceptance Crit
- as a user, I want the Data Explorer Script Editor Function box to list all Flux functions alphabetically by Flux package first, and then alphabetically within that package.  (e.g.  date.second, date.week, geo.filterRows)

- as a user, I would like the ability to select/search for any current Flux function from the Script Editor Function box

- as a user, when I select a flux function in the Script Editor function box, the following item's will populate from the latest flux source documents:
1.  the flyover panel's description
2. the flux function name
3. the list of arguments, their signatures, and the headline for each argument
4. the function type signature
5. the link to the document website 

- as a user, I do not want to see an example in the flyover panel for any Flux function. (currently available today for some flux functions)

![image.png](https://images.zenhubusercontent.com/5f496c1520d76ccd20391de7/874c2b83-3b97-4abb-b83b-e757a9787855)

- as a user, I want this capability in Data Explorer and Notebooks.

### Technical Notes/Requirements

- Flux team will create a flat file that has all docs in JSON format.

- A Service will be created to read and store the flux help from the file.

- The UI application will call the service via API in real-time to get (a) list of all flux functions and/or (b) detailed help object of any selected function.

Please refer to existing javascript library to parse flux files into JSON object:
This is the code that exposes the wasm, and I will work to make it return the entire json documentation for the stdlib. https://github.com/influxdata/flux/blob/master/libflux/flux/src/wasm/mod.rs

And to return all flux functions:
function in flux wasm/mod.rs to get all json documentation https://github.com/influxdata/flux/blob/master/libflux/flux/src/wasm/mod.rs

And sample js demo calling wasm:
https://github.com/BarWeiner1/Wasm-Docs/blob/master/www/index.js
https://github.com/BarWeiner1/Wasm-Docs/blob/master/www/index.html

### Release Plan
This code will be put behind a feature flag so that it can be enabled on a specific date.

Team
Anchor / Dev Champion - @TCL735 
Product Manager -- Nicholas Anderson
Design -- @daviddkkim

**Comment by TCL735** [comment]
The top 30 most used Flux functions courtesy of Nathaniel
```
Count   Name
---------------
1410683 filter
1404168 range
1401475 from
1208959 sort
1200610 keep
1123877 yield
1071422 map
1052950 pivot
1034614 last
1012339 fill
1010948 time
1007651 union
1006347 int
996008 events.duration
198993 group
159630 aggregateWindow
149131 limit
131289 now
129858 distinct
70317 sum
61562 difference
53429 keys
47556 set
43532 max
41203 timeShift
36530 join
35419 drop
31687 count
24345 first
21423 experimental.addDuration
```
