### ISSUE TITLE
Epic: UI Color Mapping

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#2492]
### Target Customer / Background data / Context / Market Size
The user in the UI who wants to refresh line graphs and get the same color mapping of data series for each refresh.

### Goals
Create permanent color assignments for data series in line graphs. 

### Acceptance Crit
- as a user, when i refresh a line graph, i would like the lines to stay the same color.

- as a user, when a line graph that has more than one data series is rendered, I would like the ability to see the same colors set to data series when the graph is redrawn.

- as a user, when I change color families and I have more than one data series, the visualizations correctly reflect color choices in the new family and data series do not change colors when refreshed.
 
- as a user, I would like the ability to see the same colors in dashboard cells, Data Explorer, and Notebooks, after the query has been saved.  (no requirement for color saving **during** initial query development)

- as a user, if I have more data series than the color family selected, then the data series will continue to be assigned within the color family, reusing colors as needed.

- as a user, the assignment of colors to data series is stored per cell, per data explorer window or notebook panel.

### Open Questions:
- What happens when the user changes the query and/or the group key?  When the user changes an existing group key, the new key will be assigned a new color.

Release Plan
This code will be put behind a feature flag so that it can be enabled on a specific date.
Team
Anchor / Dev Champion -
Product Manager -- @russorat
Design -- @daviddkkim. (no UI facing feature at the moment)

Technical Notes
- Data Series color assignment will be saved via graph option, as a numerical color family index.  This will NOT be viewable to the user at the present time.  Future capability:  Allow user to assign color index within color family.
- the "line" in a graph is determined by the group key. 

Additional graphs that will need support (in the future, out of scope for this epic):
- stacked line
- line + single stat
- histogram (probably)
- heatmap (probably)

**Comment by russorat** [comment]
do we have any analytics on how often users change color schemes on a graph?
