### ISSUE TITLE
Notebooks: Ephemeral Notebooks Support

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2495]
### Target Customer / Background data / Context / Market Size
When we try to enable more links to notebooks in the application (from the buckets page for example), we see that users end up with a large number of notebooks that they did not intend to keep. This wouldn't be an issue, but it makes finding the notebooks they did intend to keep tough and in shared environments, can create a large list of "Untitled" notebooks, which make it hard to find the notebooks users did intend to keep.

This is similar to the "explore" use case, where the user explores data without actually creating anything. This is useful, and it is something you can't do today in notebooks.

### Goals
The goal of this epic is to create a mechanism such that a user can explore their data without creating a notebook that others in the org can see. Users should be able to use all the features of the notebook, but the data is not persisted unless a user takes a specific action, such clicking save (although we can explore other options). 

Once the user have indicated they would like to keep the notebook, we can continue to autosave as we do today.

### Acceptance Crit
- as a user, i would like to have the notebook editing experience without keeping the notebook around for others to see.
- as a user, i would like to explicitly "save this notebook" and come back to it later.
- as a user, i would like to understand that my notebook is being auto saved or not
- ~as a user, i would like some indication that i will lose my progress when i navigate away from an unsaved notebook.~ This will be tested in the next round of user research.
- as an analytics user, i would like to know how many people do not save their notebooks.

### Team
 - Anchor / Dev Champion
 - Product Manager - @russorat 
 - Design - @juliajames12 

### Design
[Figma File](https://www.figma.com/file/4CJBzm1vNNXYxVg8hLHeEl/Ephemeral-Notebook?node-id=64%3A105
)
### Notes
- for this the user clicks a link in the app (the buckets page for example) and is taken to a notebook url that doesn't have an id (the current notebook) and is able to work in this notebook until they hit an explicit save button
- once the user hits the save button, the text of the save button updates to "Autosaving" and is disabled
- clicking save updates the url with an id for the notebook and begins autoupdating.
- users can export resources from ephemeral notebooks without saving.

**Comment by drdelambre** [comment]
capturing loose conversations around this:
now that notebook creation comes through the templating system, we might be able to use those endpoints as a place to hold an ephemeral notebook until it is saved (not saved means no ID for the route)

**Comment by drdelambre** [comment]
saw this was marked as ready to go. are there things to do in this epic? if not, i have completed everything in this epic and am taking full credit

**Comment by juliajames12** [comment]
Added the Figma file to the description.
