### ISSUE TITLE
Views: X Domain limits as variables / Auto-refining views

### ISSUE THREAD

**Issue by msarehn** [influxdata/ui#2517]
Thank you for suggesting an idea to improve InfluxData UI.

**Proposal:**
The visible X domain limits should be available as a variable for a query. In effect, this would allow the query to react to zoom-ins in order to refine the displayed data.

**Current behavior:**
Zooming in does not have any effect on the executed query.

**Desired behavior:**
There should be an option so that zooming refines the displayed data, i.e. modifies the query's start and stop time points as well as the averaging duration.

**Alternatives considered:**
Instead of a separate set of variables, zooming in could directly modify `v.timeRangeStart` and `v.timeRangeStop`. In Dashboards, this would nicely sync up all views to the same time range. A separate set of variables allows for more flexibility, however.

**Use case:**
When viewing large time spans of data where you want to quickly investigate peculiarities in the data in a very narrow time interval, fiddling with the time range controls of a dashboard is very cumbersome. Simply being able to "zoom in" while the query automatically becomes more finely grained would be a huge plus in usability.

**Comment by kristinarobinson** [comment]
Won't fix.  This is counter to the use of the existing dashboard logic.
