### ISSUE TITLE
Notebooks: Export as alert task should be consistent in the modal

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2522]
For the alert panel, the button on the panel is Export as Alert Task. The modal should also have a title "Export Alert Task" and the button should be "Export Alert Task" in the modal.

![image](https://user-images.githubusercontent.com/4805997/131572147-ab4cead5-04e9-477f-96a9-650b4fcb45eb.png)

**Comment by Asalem1** [comment]
Removing the bug label since there was no mention of this when the feature was fleshed out
