### ISSUE TITLE
Notebooks: Add a default Flux script when you select "Schedule a Task"

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2523]
When a user opens the "Schedule a Task" option, they see a blank box. The feedback was to provide an example script in the flux panel.

Here's a basic flux task we could start with, but I'm open to other suggestions.
```
from(bucket: "bucket")
  |> range(start: -1h, stop: now())
  |> filter(fn: (r) => r["_measurement"] == "measurement" and r["_field"] == "fieldname")
  |> mean(column: "_value")
```

![image](https://user-images.githubusercontent.com/4805997/131571680-6fa7622e-f46c-40eb-8b44-99f9beed1f18.png)

**Comment by drdelambre** [comment]
i dont understand. what is wrong with a blank box, and who gave the feedback for an example script that will fail when they try to run it (beginner user, external builder persona, etc). i can't make suggestions if there's no context on what the problem is that this solution is trying to address

**Comment by bpalani** [comment]
The feedback is to replace:
```
// Uncomment the following line to continue building from the previous cell
// __PREVIOUS_RESULT__
```
with an example downsampling task code again commented out (so they should not fail when user tries to run it). Example:
```
// Sample flux task that downsamples a measurement "mem" and field "used" from bucket "telegraf" to bucket "downsampled"
//
//  from(bucket: "telegraf")
//    |> range(start: -1h, stop: now())
//    |> filter(fn: (r) => r["_measurement"] == "mem" and r["_field"] == "used")
//    |> mean(column: "_value")
//    |> to(bucket: "downsampled")
```
Goal is to encourage users to build more tasks. We are just providing a sample script to get started rather than keep it blank.

**Comment by jzahnd** [comment]
After reviewing with the team, we would like to simply remove all text in the box for now. This will simplify the experience
