### ISSUE TITLE
Add a clock widget to the dashboard

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#2551]
> How can I add a clock which shows the current time to an InfluxDB2.0 Dashboard? I'd prefer a clock that constantly updates to have it accurate to the second.

This issue would add a new panel to a dashboard that would display the current date time in a user specified format. It can be a digital format similar to single stat:

![image](https://user-images.githubusercontent.com/4805997/132526247-911f8b6b-0747-4779-b23f-8298a479a98e.png)

**Comment by jzahnd** [comment]
Closing due to age
