### ISSUE TITLE
Fix / address lsp issues after lsp upgrade

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#2553]
There has been a rewrite of the lsp, bringing it to version ~v0.6.2~ (now 7.0). There was an attempt to upgrade the UI to the latest version but we are seeing several test failures. We would like to address these failures so that we can get the latest rewrite integrated into the UI so that we do not fall behind. 

This effort will be coordinated by @genehynson from the UI team and @rockstar on the Flux team.

Existing PR with failures: https://github.com/influxdata/ui/pull/2444

**Comment by jzahnd** [comment]
@rockstar Do you happen to have a list of breaking changes on this?

**Comment by jzahnd** [comment]
We have a meeting to review what is needed for next steps on this issue on 9/24

**Comment by jzahnd** [comment]
After our meeting, we have agreed to pair on this task between the Flux and UI teams. Going forward, we expect this process to much smoother as we will have only incremental lsp changes being merged in.

**Comment by genehynson** [comment]
Blocked on bugs in the wasm library

**Comment by barbaranelson** [comment]
After we upgrade the LSP, it would be good to retest https://github.com/influxdata/ui/issues/3135 to see if the issue persists.
