### ISSUE TITLE
Notebooks: When I select a remote csv file the time range should auto-populate

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#2557]
We would like for the time range to autopopulate when a user selects a remote csv file, otherwise they would have to guess the time range of the sample datasets.

![Screen Shot 2021-09-08 at 11.26.20 AM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/c3fd7087-bb5f-470f-be27-d58667075134)

Is it possible to do this for Remote CSVs that the user uploads as well?

**Comment by drdelambre** [comment]
is this a dupe of #2556?
