### ISSUE TITLE
__PREVIOUS_RESULT__ substitution needs an upgrade

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#2609]
we still have a regexp mutating a query string floating around in the code base. CRAZY.
this is breaking whenever we have imports in the previous result
one place where this is becoming a problem is the use case of
```
panel one:
import "influxdata/influxdb/sample" 
sample.data(set: "noaa")

panel two:
sorted = __PREVIOUS_RESULT__
    |> keep(columns: ["_time"])
    |> group()
    |> sort(columns: ["_time"])

sorted
    |> first(column: "_time")
    |> yield(name: "first")
```

this seems like it would also be a problem if multiple instances were used like:
```
panel one:
import "influxdata/influxdb/sample" 
sample.data(set: "noaa")
    |> keep(columns: ["_time"])
    |> group()
    |> sort(columns: ["_time"])

panel two:
__PREVIOUS_RESULT__
    |> first(column: "_time")
    |> yield(name: "first")

__PREVIOUS_RESULT__
    |> last(column: "_time")
    |> yield(name: "last")
```

we want to make sure that we pull out the imports from the incoming query and join them with the outgoing query and use AST substitution instead of regexp every time we are dealing with __PREVIOUS_RESULT__

**Comment by asalem1** [comment]
@drdelambre how do we handle the case where `__PREVIOUS_RESULT__` is used by a user twice within the same panel? Not sure what the solution would be other than to try and add some docs to link to the user about the `__PREVIOUS_RESULT__` and its usage right? Like, how do engineer for user intent in that case?
