### ISSUE TITLE
Downloadable font: rejected by sanitizer

### ISSUE THREAD

**Issue by TCL735** [influxdata/ui#2629]
The console is spitting out errors regarding the "icomoon" font. Previously this was reported as https://github.com/influxdata/ui/issues/1673 - but the issue remains unresolved.

![Screen Shot 2021-09-15 at 4 37 00 PM](https://user-images.githubusercontent.com/10736577/133527532-0bdc26ac-d472-4592-8c99-e41da9f305cd.png)

**Comment by TCL735** [comment]
One possible lead to explore is the pathing for font assets, as explained here: https://www.seanmcp.com/articles/fix-downloadable-font-rejected-by-sanitizer-error-in-firefox/

**Comment by hoorayimhelping** [comment]
I saw this error in chrome:

```
OTS parsing error: invalid version tag
```

maybe doing a couple of searches and cross referencing the results is the way to go?

**Comment by ChitlangeSahas** [comment]
We tried removing `.eot` and `.ttf` files, that does not seem to fix it. To see this error, hard refresh the browser, go to the network tab and find any `.woff` or `.woff2` files. And then click on them to see the response, you'll notice more 404-s thrown in the console.

**Comment by TCL735** [comment]
Crazy idea: what if we deleted all references to 'icomoon' in the UI repository? Since 'icomoon' is already (and should be) handled by Clockface, why is it necessary to reference 'icomoon' directly in the UI repository stylesheets? Perhaps this error is from the 3 stray references to 'icomoon'? Which appear to do nothing or add very little to styling for components that will no longer be used.

**Comment by TCL735** [comment]
Didn't work. Still getting the sanitizer error in Tools after deployment.

**Comment by TCL735** [comment]
We are back to this being a clockface problem

**Comment by TCL735** [comment]
Attempts to use only one of the file formats and deleting the rest from `icon.scss` were not successful.

In Chrome:
- removing any of the formats will cause a console error
- keeping all formats will show no discernible error, however, this issue was originally reported on Firefox. See below regarding Firefox.

In Firefox:
- removing any of the formats will cause a console error
- keeping all formats will cause a 404 when you look at the Network responses for `Fonts`

**Comment by TCL735** [comment]
Update: the previous test locally was not done correctly. Any unused font files should be deleted, which they were not for the test, because Clockface's rollup with attempt to build all font files regardless of being used or not.


Will attempt another test and report back.

**Comment by TCL735** [comment]
Still does not work.

It appears that **icomoon.eot** and **icomoon.svg** either links or refers (imports) to the other three files that end with **.woff**, **.woff2**, and **.ttf**

**Comment by TCL735** [comment]
One way to solve this issue is to ask Giraffe to bundle all of its CSS into a single file, similar to what Clockface already does. This will allow the static assets in the CSS to be put into the correct folder during build time.

Closing this issue in favor of https://github.com/influxdata/giraffe/issues/686
