### ISSUE TITLE
Alerts: I can create an Alert in a notebook

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#263]
As a user, I can create a simple threshold Alert in a notebook so that I can create an alert quickly.

### Alert Cell Type 

GIVEN: I am in a notebook
WHEN: I hit the + plus button and select an Alert
THEN: An Alert cell with a condition, metric input, boolean statement,  appears in the notebook

### Conditions

Given I have an Alert Cell in a notebook
When I click + plus button _within_ the Alert Cell
Then I see a dropdown with Boolean operators  "AND", "OR" and "NOT"
And a new line with condition builder: [metric] [greater than][value input]

**Comment by jzahnd** [comment]
This is done
