### ISSUE TITLE
Add stepBefore and stepAfter interpolation for line graphs

### ISSUE THREAD

**Issue by kpelckmans** [influxdata/ui#2651]
**Proposal:**
It would be great to select stepBefore and stepAfter interpolation for line graphs as demonstrated [in the giraffe storybook](https://influxdata.github.io/giraffe/?path=/story/line-graph--y-domain-controlled-mode)

**Current behavior:**
![current behavior](https://user-images.githubusercontent.com/638955/57954251-3ffe1b00-78a7-11e9-9dd2-4f0c41d309f4.gif)

**Use case:**
When was the signal 1 and when was it 0?
![line interpolation is harder to interprete](https://user-images.githubusercontent.com/19192256/133890845-1aeb7b29-895d-4cb6-aad4-919630c75748.jpg)

**Comment by kristinarobinson** [comment]
Please see https://github.com/influxdata/EAR/issues/3058
