### ISSUE TITLE
File Upload Experience - unify/clean up file uploader widget

### ISSUE THREAD

**Issue by jrenee42** [influxdata/ui#2660]
we have *three* file upload widgets that are almost but not quite exactly the same.

./src/buckets/components/csvUploader/DragAndDrop.tsx
./src/buckets/components/lineProtocol/configure/DragAndDrop.tsx
./src/shared/components/DragAndDrop.tsx

they all listen for drag and drop on the window, not on the component, so only one can be on the page at the time.

goals:

1) unify them into *one* class
2) unify their css with the new mini dnd uploader here:  https://github.com/influxdata/ui/issues/2659
3) eventually, only have one component and switch the existing pages, one by one into using the new unified component.

**Benefits:** 
- Consistent user experience anywhere that .CSVs are uploaded 
- Consistency will better accommodate component reuse
- Supports maintainability

**Comment by ALuckette** [comment]
@hoorayimhelping to create smaller tickets for this.

**Comment by wdoconnell** [comment]
Closed due to priority and supersession by other tickets.
