### ISSUE TITLE
I can see an existing Alert's status on a details dashboard

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#267]
Status: 
Inactive, Active (Pause & Play)

Data Table:
Run Log Status:
Completed (Success)
Completed (Fail)
Incomplete (System Error)

Run Log Message:
Why it failed/succeeded

Alert status/check if any:
user determined input like Crit/Warn/Fault

**Comment by jzahnd** [comment]
Closing due to dupe and age
