### ISSUE TITLE
Telegraf Refresh: update plugins to match Telegraf release 1.20.0

### ISSUE THREAD

**Issue by TCL735** [influxdata/ui#2678]
Telegraf has released version 1.20.0 which includes new plugins.

- [ ] Update the .conf files with the new plugins and any changes to existing plugins
- [ ] Add logos for the new plugins

**Comment by sjwang90** [comment]
A lot of them I think can be reused. Here you go:


**1) Elasticsearch Query Input Plugin (elasticsearch_query)**
 - Same as inputs.elasticsearch

**2) Internet Speed Monitor Input Plugin (internet_speed)** 
- Same as Wireless


**3) mdstat Input Plugin (mdstat)**
- Same as inputs.linux_sysctl_fs (Linux logo)

**4) ROCm System Management Interface (SMI) Input Plugin (amd_rocm_smi)**
- (make sure image is blue like the other icons)
- ![image](https://user-images.githubusercontent.com/32681364/134237100-462344bc-240c-4b22-a03b-84b60370a563.png)

**Comment by TCL735** [comment]
Here's the list of the "new" plugins as detected by the script:
```
  'amd_rocm_smi',
  'elasticsearch_query',
  'internet_speed',
  'jolokia2_agent',
  'jolokia2_proxy',
  'mdstat',
  'net',
  'netstat',
  'trig',
  'twemproxy',
  'http_listener'
```

**Comment by sjwang90** [comment]
'amd_rocm_smi', - new
  'elasticsearch_query', - new
  'internet_speed', - new
  'jolokia2_agent', - info in inputs.jolokia2 https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf
  'jolokia2_proxy', - info in inputs.jolokia2 https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf
  'mdstat', - new
  'net', - net and netstat are under two different readmes: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/net/NET_README.md
  'netstat', - net and netstat are under two different readmes: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/net/NETSTAT_README.md
  'trig', - doesn't have a readme; i will add one
  'twemproxy', - doesn't have a readme; i will add one
  'http_listener' - can ignore, has been rename influxdb_listener (i'll double check with the team, i don't think we can remove for backwards compatibility)

**Comment by sjwang90** [comment]
Seems like we need to do something with jolokia2 because of the `jolokia2_agent` and `jolokia2_proxy` breakouts?

![image](https://user-images.githubusercontent.com/32681364/134400907-c0df3d88-0e8f-4bcb-8fc8-7cd4af04a80f.png)
