### ISSUE TITLE
I can't capture data I am capturing at 1Hz

### ISSUE THREAD

**Issue by BecsLutton** [influxdata/ui#2700]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Submit query to populate a table with Time, Value and Field at a rate of 1s over a time range of 24 hours

**Expected behavior:**
Get a 3 column table with values of every second for a 24 hour period

**Actual behavior:**
"An InfluxDB error has occurred. Please report the issue here"

**Visual Proof:**
![image](https://user-images.githubusercontent.com/60777350/134659795-67332e18-b5b1-4735-94bf-5f7e20a7e143.png)

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by kristinarobinson** [comment]
@BecsLutton - are you still having this issue?

**Comment by kristinarobinson** [comment]
closing due to lack of response.
