### ISSUE TITLE
Dashboards: Variables can no longer be re-arranged by clicking and dragging

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#275]
![Kapture 2020-11-05 at 08 51 43](https://user-images.githubusercontent.com/4805997/98270865-2a216180-1f44-11eb-88ae-41e2fa0314e3.gif)

you used to be able to rearrange these variables on the dashboard, but now you can't

**Comment by BondAnthony** [comment]
I don't believe this issue is resolved, could someone please confirm? I've seeing the following behavior as of today.

![variables](https://user-images.githubusercontent.com/7663097/105117897-52c4ec00-5a9b-11eb-942b-9d25fc3847a6.gif)

**Comment by russorat** [comment]
i can confirm this is still an issue in cloud.
