### ISSUE TITLE
Telegraf Refresh: Test your configuration should not have "Previous" button

### ISSUE THREAD

**Issue by TCL735** [influxdata/ui#2751]
When a user creates a Telegraf configuration, either through "+ Create Configuration" or from a Plugin, there is a step before "Test your configuration" that will ask the user to "Save and Test". By clicking "Save and Test" a user completes the act of creating a new configuration.

On the next step, "Test your configuration", it does not make sense to allow the user to click on a "Previous" button. It is confusing to allow the user to go back to the "Save and Test" step, because does this mean that the configuration is now unsaved (aka deleted)? Or does this mean the user is now using the creation process to do an edit? As there is a separate flow for editing configurations, users should be nudged to use that instead of "Previous" to attempt any edits.

The "Previous" button should be removed under this feature.
- create a new component similar to the `VerifyCollectorsStep` component to remove the "Previous" button
- keep the existing `VerifiyCollectosStep` component to allow for feature flag deactivation and until this feature flag is removed
- Move the "Listen for Data" and "Finish" buttons next to each other, with "Listen for Data" on the left (subject to design change)

<img width="1680" alt="Screen Shot 2021-09-30 at 10 01 35 AM" src="https://user-images.githubusercontent.com/10736577/135500618-ed327523-9fbf-4b89-bcc9-d45ce527bb00.png">
<img width="1680" alt="Screen Shot 2021-09-30 at 10 02 11 AM" src="https://user-images.githubusercontent.com/10736577/135500632-ffcce912-70c3-4cf4-b215-4742aacb4bd3.png">

**Comment by ChitlangeSahas** [comment]
We'll just remove the previous button from the current UI as well, it seems like a good idea since the same idea applies. We don't need the previous button here.
