### ISSUE TITLE
better error handling for bucket creation

### ISSUE THREAD

**Issue by jrenee42** [influxdata/ui#2799]
while working on explicit buckets, a pattern was copied that is not optimal.

essentially, some errors get handled by the component, and others get delegated up.  they should all be handled in one place.

from @hoorayimhelping : https://github.com/influxdata/ui/pull/2766/files/f15fb859f09f2fbfe91de8ab4a5c4d7c9812eb19#r721570446

"this method is a bit inconsistent in its error handling: if the response isn't a 201, the caller of this method has to handle it. If it's a generic failure, this method handles it.

I personally think we shouldn't handle the error at this level but at the component layer. It makes more sense to me to have the section of the app that's calling this method handle the error since how it's handled is often specific to that part of the app."

He is referring to the pattern here:

https://github.com/influxdata/ui/blob/master/src/buckets/actions/thunks.ts
in the  method: createBucket 
and the method that is being added in the PR referenced above: addSchemaToBucket

**Comment by wdoconnell** [comment]
Closing this PR based on priority.
