### ISSUE TITLE
Cloud 2 should provide custom user-selectable retention periods

### ISSUE THREAD

**Issue by 8none1** [influxdata/ui#2815]
**Proposal:**
I think we're missing a trick in Cloud 2:  we should provide a bucket retention policy of greater than 1 year and less than "never".
Today I was trying to draw a graph of $THING and compare it to what $THING looked like last year.  I expect that this is a fairly common use case.  Weather patterns, server traffic, global warming, crypto values....
Except the RP on my bucket is 1 year.
So I can compare $THING today to $THING tomorrow minus 1 year, but I can't compare $THING to the last 30 days, but 1 year ago.
Additionally, I don't want to use "never".  I want to compare my things to a year ago, give or take a few months.  18 months RP would suit me, but perhaps 2 years would suit other people.  I don't want to use never, because I don't want to keep the data forever. So either I have to suck the costs up, or I have to delete data.  (We should discourage people from deleting if we can, it's computationally expensive.)
Not sure I explained that very well.  Here's another try:
I want to compare a measurement from the last 30 days to the same 30 day period last year.  They only way we can do that today is by using a RP which never deletes data.  This is suboptimal.

**Current behavior:**
When creating or editing a bucket you are given a drop down of pre-configured RPs as the screenshot shows.

**Desired behavior:**
The ability to also enter my own custom RP.  The backend API does allow it.

**Alternatives considered:**
None

**Use case:**
See proposal above for an example use case.
As a user I want to select an RP which is longer than one year but shorter than infinity so that I can compare data from this month a year ago to now.

![image](https://user-images.githubusercontent.com/6552931/136151472-f385052d-acd6-4746-b36f-582b1ec2398a.png)

Slack conversation here: https://influxdata.slack.com/archives/CDBJ35NBV/p1633423716122000

**Comment by kristinarobinson** [comment]
Need design to create an experience for this.

**Comment by Luckette** [comment]
@mavarius This is a small amount of effort with a high impact. Can you propose a designer to help w/ this?
