### ISSUE TITLE
Allow for more configurability of bucket retention policy via UI

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/ui#2817]
Currently when defining a bucket, way in which the user defines the retention policy is via this modal:  ![image (3).png](https://images.zenhubusercontent.com/597ad6dbf8b79f8376e11888/7557bf14-fb20-47f5-af34-5a6c57a2ec0e)

However, via the CLI/API -- it is possible for the user to set the retention policy for a bucket to be of any duration, including those not available within the drop list shown.

The pre-fixed durations provided in the drop list is good for many users and enables them to quickly select one of these.  However, there are certainly users who wish to have longer durations (beyond 1 year, but less than "never" i.e. keep the data forever).  This enhancement request is to offer more flexibility for the end user to define their bucket retention duration.

There are a number of potential options to consider/perform user testing including:

**combo box** -- allow user to type in value, this requires more validation because this is not just a number -- it is a number with a supported time unit (day, month, years, etc.).
**custom** -- with a subsequent modal which can separate the numerical portion from the supported time unit (such that we reduce the complexity of the validation by encoding it into the modal).  This is somewhat similar to the way that Data Explorer works when the user need/wants a custom time range for queries.
**other** -- perhaps an alternative approach needs to be considered on the original modal?  eliminating the never/older than selection and just offer a single modal (where the relevant defaults/controls can be placed)?  Important to remember the free tier needs to be "fixed" to 30 days max.

From a testing perspective, I would like to understand what happens if we set the RP to a value not supported by the drop list (given the current design/implementation) and you attempt to edit?

Acceptance criteria:
1) user is able to quickly set a retention policy based on a time duration quantity and a time unit through the UI
2) user is able to quickly set a retention policy based on a time duration quantity and a time unit through the CLI
3) regardless of where this was originally set (UI, API, CLI), the UI should support modifying this to any time duration and supported unit

Proposed units: hours, days, weeks, years 

Related:
 https://github.com/influxdata/ui/issues/2815

**Comment by appletreeisyellow** [comment]
Work is done in https://github.com/influxdata/ui/pull/5959
