### ISSUE TITLE
Notebooks: When I output to a bucket, I receive a message indicating that the data has successfully written to a bucket

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#2826]
As a user, I want to receive a notification after selecting an output bucket and running the notebook, so that I know the data has successfully been written to a bucket.

Currently, we have a notification that says "Notebook run successful" which doesn't necessarily indicate the data has been written to a bucket. We would like to update the message and include the actual name of the bucket the data has been written to.

Current Message:
![Screen Shot 2021-10-18 at 11.06.58 AM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/ffbe4b67-1ca5-4219-9784-01bdd52150bd)

New Message: 
![Output to Bucket message.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/0f3d16d4-b047-418f-a698-97903ff880cf)

**Comment by jzahnd** [comment]
We do not always know if we wrote successfully to the bucket, we probably should not message given that knowledge, or lack thereof.

**Comment by barbaranelson** [comment]
@juliajames12 Can we close this out as we don't have the output-to-bucket panel any more.

**Comment by barbaranelson** [comment]
Closing this issue as we have removed the to-bucket panel.
