### ISSUE TITLE
Notebooks error when I click on my data bucket name to filter data

### ISSUE THREAD

**Issue by eye-c** [influxdata/ui#2828]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. ...click on notebooks
2. ...click on Data bucket to filter data
3. ...error message appears suggesting I issue a bug report

**Expected behavior:**
I expected to be able to explore how my data was structured inside influxdb

**Actual behavior:**
black screen with error message upon selecting my data bucket

**Visual Proof:**
https://user-images.githubusercontent.com/55814315/136447462-f7354be7-b22d-4a22-ae17-336074d5b2af.mp4

## About your environment
Influxdb Cloud

**Config:**
```
[[outputs.influxdb_v2]]
  urls = ["https://us-central1-1.gcp.cloud2.influxdata.com"]
  token = "token here"
  organization = "myorg"
  bucket = "MQTT_data"

[[inputs.mqtt_consumer]]
  servers = ["ssl://xxxxxxxxxxxxxxxxxxxxx.s1.eu.hivemq.cloud:8883"]
  topics = [
    "my/test/topic"
  ]
  topic_tag = "topic"
  qos = 2
  max_undelivered_messages = 100
  persistent_session = true
  client_id = "username"
  username = "username"
  password = "password"
  data_format = "influx"
  tag_keys = [
    "value",
    "temp"
  ]
  [[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
```

**Comment by drdelambre** [comment]
thanks for the bug report! there seems to be a conflict with one of feature flags that we turned on. if you log out and in again, it'll reset that flag, and selecting the bucket will work again.
