### ISSUE TITLE
Notebooks: To Bucket panel requires a Visualization panel to work

### ISSUE THREAD

**Issue by genehynson** [influxdata/ui#2830]
Currently the To Bucket panel only works if you follow it up with a Visualization panel. This is because we intentionally [only execute `.visual` queries. ](https://github.com/influxdata/ui/blob/master/src/flows/context/flow.query.tsx#L379). 

We could also execute `.output` queries but this could have weird side effects. Say someone does put a visualization panel after a To Bucket panel. Then we would execute the `|> to(...)` query twice. The same effect could happen if someone adds a flux panel after a To Bucket and uses `__PREVIOUS_RESULT__`. That would run the `|> to(...)` twice. And I don't think we want to write the data multiple times. 

We need to investigate a way to isolate the queries that contain side effects (e.g. output queries like `|> to(...)`) and make sure we only run those once.

**Comment by drdelambre** [comment]
i like the `output` idea for getting it to run when the notebook is switched out of preview mode, but there's also a ticket from barbara to remove the distinction between run and preview, which just highlights that we need to have a product talk about how these side effects are used by users. they're being added at twice the rate as the downsample and markdown panels, but you have to change the run mode to get them to work, and they only run on the notebook if you have a visualization panel. i think their saving grace is that the version with side effects is really only generated / exposed when we generate a task, but no a lot of people are generating tasks, so i dont know if there's enough people using it like that or what the expectation is.

**Comment by genehynson** [comment]
Another simple thing we could do is just move the "Run" button to the To Bucket panel itself. So if you want to execute that panel, you have to run it specifically

**Comment by jzahnd** [comment]
Closing this given we are removing output to bucket (#3157)
