### ISSUE TITLE
Secrets: Add the ability to inject secrets into the alert panel endpoint details

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#2862]
We would like to add he ability to inject secrets into the alert panel in order to safely inject endpoint details. 

Design: https://www.figma.com/file/XulFKIibFgx9xtSL92rHlY/Injecting-Secrets-in-Notebooks?node-id=106%3A687

**Comment by wiedld** [comment]
Gene already did this one.

note that design now prefers the "add new secret" to be in the sidebar (not an overlay modal). so no changes to be done. closing.
