### ISSUE TITLE
query builder should always show selected options

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#2866]
i was poking around the frontendservices bucket with the querybuilder in notebooks, searched for one measurement, selected it, explored it.... then thought "lemme check this other thing" so i typed in the filter to find the other measurement, selected it, and then i got a bunch of weird tables come back, because.... i had not unselected the original measurement. but i had no idea it was still selected because it was being filtered.

if an option in one of the query builder cards is selected, it should always be visible

**Comment by jzahnd** [comment]
Let's make it consistent with Data Explorer for now
