### ISSUE TITLE
RawFluxDataTable should come from Giraffe

### ISSUE THREAD

**Issue by TCL735** [influxdata/ui#2868]
In **src/timeMachine/components/Vis.tsx** the `TimeMachineVis` component is still using a component implemented by the UI. This component and visualization is known as the `RawFluxDataTable`. It should come from Giraffe.

- [ ] Replace the `RawFluxDataTable` with the one available in Giraffe
- [ ] Ensure that the Giraffe visualization still meets the intended purpose of `RawFluxDataTable`
- [ ] Feature flag, if desired or necessary

**Comment by kristinarobinson** [comment]
Fixed.
