### ISSUE TITLE
notebooks: If start with selected bucket, should bring that bucket into view in query builder 

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#2879]
I selected a bucket (in tools) and was taken to the notebook with the query panel, but the selected bucket was offscreen so it didn't look as if it had been selected. When I scrolled down, I could see it was in fact selected.

Would be better to have the selected bucket in view in the query builder panel.

**Comment by subirjolly** [comment]
Balaji is working on this and #2866 tickets with Daniel(Design). Once I get an update, I will work on this.

**Comment by barbaranelson** [comment]
@subirjolly is this supposed to be working now? I tested today and it doesn't work with a large list of buckets. See attached video - if I select a bucket that's far down the list, it looks like it very briefly shows that bucket on the screen and then it jumps out of view.

https://user-images.githubusercontent.com/13143006/149435258-4964437b-40ff-42eb-9886-ab135bb749b8.mov

**Comment by subirjolly** [comment]
> @subirjolly is this supposed to be working now? I tested today and it doesn't work with a large list of buckets. See attached video - if I select a bucket that's far down the list, it looks like it very briefly shows that bucket on the screen and then it jumps out of view.
> 
>  Screen.Recording.2022-01-13.at.5.20.55.PM.mov

It's supposed to be fixed and it does work in most cases. Scroll to the selected item is provided by clockface component but it does the scroll into view, roughly. And it is buggy as well.

I am able to reproduce it locally. Let me try to figure out a solution, either locally or in clockface.

**Comment by subirjolly** [comment]
Added a new fix and is validated now.
