### ISSUE TITLE
Bug: Flaky Test - unable to create a task, unknown error

### ISSUE THREAD

**Issue by genehynson** [influxdata/ui#2887]
A bunch of tests and pipelines are failing when trying to create tasks. 

![image](https://user-images.githubusercontent.com/6411855/137398510-d92198de-497a-47d2-8a41-9d7b8366fe86.png)

```
AssertionError: Timed out retrying after 10000ms: Expected to find element: `[data-testid="notification-success--dismiss"]`, but never found it.
```

Examples:
- https://app.circleci.com/pipelines/github/influxdata/monitor-ci/6152/workflows/7a57efe2-4e05-4605-a881-055b828e53b2/jobs/216891
- https://app.circleci.com/pipelines/github/influxdata/monitor-ci/6152/workflows/9397e27e-9d8a-4cc0-9124-a58f39567ebf/jobs/217026

**Comment by kristinarobinson** [comment]
flakiness resolved.  closing.

**Comment by kristinarobinson** [comment]
Checked CircleCI insights link, `can create a task` is still the number one flaky test.  
https://app.circleci.com/insights/github/influxdata/monitor-ci/workflows/build/tests?branch=master&reporting-window=last-7-days
