### ISSUE TITLE
the website is showing some error and not showing whole data

### ISSUE THREAD

**Issue by Awais744** [influxdata/ui#2894]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. I was just using explore to run queries but it stucked.
2. When  I changed graph into table.
3. ...

**Expected behavior:**

**Actual behavior:**

**Visual Proof:**

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by kristinarobinson** [comment]
Closing due to no further information

**Comment by Awais744** [comment]
Ok, thanks.
