### ISSUE TITLE
Notebooks: Support cron tasks

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#2903]
we need to support cron type tasks in the schedule panel before we can turn on this functionality
https://github.com/influxdata/ui/pull/2901

Design: https://www.figma.com/file/a7qLfWdlUDrhab9aWIxE65/Notebook-Alerts-and-Tasks?node-id=1134%3A12762

![Every Option 1 (2).png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/ebfcf244-d84b-4683-94f2-e8b18a03f370)

![Cron Option 1 (2).png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/bf3c4969-bf07-42e2-80e5-2c5a2a48d327)

**Comment by jzahnd** [comment]
How many tasks are created with every vs cron in our general task pool? What is the most common usecase?
