### ISSUE TITLE
Most UI events are not showing up in Tools

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#2923]
We are seeing a huge drop in UI events in Tools. It seems unlikely that we have taken such a large drop in events. We should investigate this outage as soon as possible given that we are trying to measure features and iterate based on testing and KPI metrics for decision moving forward.

**Comment by drdelambre** [comment]
did we ever get a story on this one?

**Comment by jzahnd** [comment]
Closing this for now. Hopefully our updated tooling will help with this.
