### ISSUE TITLE
Remove Export Task Popup from Schedule Panel

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#2926]
Users seem to be finding the button just fine, but only 30% of the users that click on the button actually create a task. instead of having a popup that scares them away with a giant wall of flux and options, lets just have the button create a task. the user needs some way to know that they created that task and the ability to navigate to it, but also note that task export is a one way, atomic, interaction, so we shouldn't be giving them the expectation that changing something in their notebook will then change something in their task.

**Comment by drdelambre** [comment]
this is live already
