### ISSUE TITLE
notebooks: Band graph crashed and then couldn't recover the panel

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#2935]
I created a notebook and selected the Band visualization, and the panel crashed with an error: 
react-dom.production.min.js:198 TypeError: Cannot read properties of undefined (reading 'xs')
    at band.ts:57
    at Array.forEach (<anonymous>)
    at ys (band.ts:56)
    at ws (band.ts:455)
    at memoize-one.esm.js:34
    at e.getSpec (PlotEnv.ts:303)
    at uy (PlotResizer.tsx:41)
    at Wo (react-dom.production.min.js:150)
    at ki (react-dom.production.min.js:178)
    at ja (react-dom.production.min.js:232)

I then changed from the Band visualization to a Graph visualization, but I still get the internal error in the panel. I had to delete the panel and add a new panel with a Graph visualization for it to recover.  It would be good if changing the visualization would cause the panel to recover.

**Comment by subirjolly** [comment]
@barbaranelson I fixed this yesterday and merged it some time back. Please feel free to test it in tools or any other environment once it gets deployed today.

**Comment by asalem1** [comment]
This has since been fixed by @TCL735
