### ISSUE TITLE
X axis incorrectly assumes time, when plotting x_not_time against y_not_time

### ISSUE THREAD

**Issue by gefaila** [influxdata/ui#2990]
I’m using pivot to form a table so I can chart two values against each other.
![image](https://user-images.githubusercontent.com/69196723/138411790-5669ad63-fd1f-43a9-abad-9da0ac68a835.png)

The chart renders with the assumption that x is time.
![image](https://user-images.githubusercontent.com/69196723/138411845-f6b91aca-45d2-47d0-b537-c14ae6922583.png)

However, if you zoom in a million times you can get the chart to display properly.
![image](https://user-images.githubusercontent.com/69196723/138411988-c48c2e57-0a6b-426c-91df-ed46953a06d6.png)
However, whenever you double click, or refresh, the x axis returns to the faulty scale.

The bug comes from the incorrect assumption somewhere that the x axis should be scaled according to the min and max of *_time* for the data involved. This is fine for all cases when x *happens to  be _time*.

Since the feature exists to select **any** column as the x-axis, the range of the x-axis should logically be either:
a) auto-scaled according to the min() and max() of **x_not_time**
b) scaled explicitly by the user

The bug has been fixed for “scatter” plots.  It's strange that no-one thought to apply the same fix to line plots

Q: Why don’t I use scatter plots?
A: Because I want lines and not just points. And that is not an option on scatter plots. It assumes you want only points.  That is another issue which I'll log separately.

**Comment by gefaila** [comment]
@kristinarobinson thanks for joining!
Can you update any readers of this issue on proposed fix timetable?
Thanks again.

**Comment by kristinarobinson** [comment]
Won't fix.  We only graph against time and do not support graphing using non-time series data.
