### ISSUE TITLE
Add hover info to icons on left hand side of window

### ISSUE THREAD

**Issue by rogpeppe** [influxdata/ui#2992]
**Proposal:**

The new UI looks like this, which is certainly a bit sleeker, but the icons on the left (to me at least) are quite cryptic.

![image](https://user-images.githubusercontent.com/66491/138417536-3bb533ec-5755-47c8-b4a8-e0b7953e20a6.png)

Hovering over some them does produce some URLs giving a clue to what the icons mean, but ISTM
that it would be better to have some explicit text (e.g. "Data Explorer" rather than `https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/data-explorer`) and it would be good to show some info consistently for all of them, because clicking can often be a destructive operation that takes a while and potentially loses the current window's state.

**Comment by kristinarobinson** [comment]
great suggestion.  Taking it to the design team.
