### ISSUE TITLE
notebooks: Turning on auto-save wipes out your preview

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3005]
When you hit the 'save' button, your previewed data goes away, and you have to hit preview again to continue your work. Seems an odd effect, if it is by design.

**Comment by jzahnd** [comment]
Leaving open as a reference to the behavior we are seeing, should be addressed by publish lifecycle work

**Comment by barbaranelson** [comment]
Closing, as it seems to work now.
