### ISSUE TITLE
Flows: UX Clean Up

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#302]
@mnorriswalker commented on [Tue Nov 10 2020](https://github.com/influxdata/influxdb/issues/19977)

### Misc
- [x] On the List Page, empty state label should say "`Create Flow` to get started" & Create Flow is a button to create flow.
- [x] Insert Cell: Change labels to Input, Pass-through, Output
- [x] Change results icon from `zap` to `play`
- [x] Don't expand error state results panel

### All Cells
Given: I see a cell that hasn't been previewed/ran
When: I see "Run Flow to See Results"
Then: It says "Run" or "Preview to see results" depending on what button is selected at the top-level of the notebook (also note text change)
And: the icon is a Play caret not a lightening bolt to visually connect to the button above
- [x] Run vs Preview wording

### Metric Selector
- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6
- [ ] 7
- [x] 8
- [ ] 9

1. Check to see why the Parser is so slow to load 

2. On the Metric selector decapitalize the nouns in the search field to: field, measurement, tag

3. Metric Selector always shows schema for loading state even after a metric is selected.
GIVEN: I have selected _n_ metrics
WHEN: I click back into the Search field
THEN: I see all available metrics in the dropdown

~4. Metric Select schema loading takes a long time, perhaps infinite scroll in the metric selector. What can be done to improve load time?~

~5. Strings in Metric Selector
Given: I have selected a string
And:  any aggregate is selected by default
When: I hit run/preview
Then: First is selected by default~

6. Change error message when a string doesn't work with selected aggregate {"code":"invalid","message":"unsupported input type for mean aggregate: string"}
change to "String is unsupported input type for mean aggregate: change to first or last." <-- something a bit more helpful

7. In the Metric Selector schema, Label the value not the tag, otherwise everything is a string because tags are strings

8. Show window period of the aggregation even though it's not changeable

9. Show fetching schema text in loading state after a moment

### Visualization Cell
- [x] Visualization cell update text to: "This cell will display results from the previous cell"

### Flux Script
- [x]  Flux Script Cell: Switch Line 1 & Line 2 defaults so that  "Use __Previous_Result__ to continue building from previous cell" is line 1 and
"Enter Flux Script here" is line 2

### Export As Task
- [x] In the overlay panel, `Export Task` button should be enabled by default & the input fields have required asterisk
Given: I do not have `Name` or `Run Every`
When: I click `Export Task`
Then: `Name` & `Run Every` are highlighted as an error state

- [x] "Export to Task" generates a notification with the name of the Task you just created, and I stay on the Notebook 

### Run
When: I click Run
Then: The data tables reload with spinner
And: I get confirmation a notification that the data written "Run successful. {BucketName} updated."

- [x] Results spinner
- [x] Notification

### Export as Dashboard Cell

- [x] Size the code preview to exactly the number of lines
- [x] No text wrap
- [x] Don't fire a million queries when typing
- [ ] Don't show tooltip on visualization
- [x] Attempt to reduce vertical height in other ways

---

@mnorriswalker commented on [Tue Nov 10 2020](https://github.com/influxdata/influxdb/issues/19977#issuecomment-724993240)

CC @noramullen1 add your text changes to this Issue, please. 

@barbaranelson _see "All Cells" section above._ 
The label `Preview` or `Run `will change depending on the button selection (`Preview` is default.) We could also link the text `Preview` and `Run` to complete the action but the concern was that it runs/previews the entire notebook not just the cell and the placement doesn't make that clear. So we're going to stick to the top-level control and research further before making it clickable.

CC @alexpaxton @drdelambre 

---

@barbaranelson commented on [Tue Nov 10 2020](https://github.com/influxdata/influxdb/issues/19977#issuecomment-725001419)

Could we default to Run instead of Preview? Preview feels like a fairly advanced concept and is only applicable if I have defined an output bucket.  Staying with the top-level control but defaulting to Run would address my concern for the first-time user.

**Comment by drdelambre** [comment]
regarding that last one.. run vs preview. it used to be just run, then we added that differentiation after breaking some things and came to this viewpoint:

To aid in providing the user a place that they feel free to explore within, we want them to have to either opt in to or confirm any experience that will have lasting consequences. They shouldn't build up a fear that a frivolous button press will make their data unavailable.

we might want to rethink how we present that environment to a user, but I don't agree that defaulting to a condition that creates unclear side effects within the system for the first time user is a beneficial product choice. maybe this is a signal that we should explore a few ways of giving the user more feedback about potential side effects, however design might frame that.

**Comment by barbaranelson** [comment]
I guess I don't follow the comment about unclear side effects. Is the area of concern that it will write the wrong data to an output bucket? If I don't have an output bucket in my flow, are preview and run identical, or are there some other side-effects I'm not understanding? If the concern is around output buckets, then maybe we could control the behavior in that cell, rather than differentiating the entire flow.

**Comment by drdelambre** [comment]
in an interaction where we're running queries to provide a window into your data, what is "wrong data" and what is "right data" is an explicit intent of the user that is generated specific stages in their exploration; as i'm crafting the right data for for a runbook for my team, one step of which is to write a transformed results set into my bucket, i'm running a bunch of "wrong data" against an outline of a runbook until i have massaged the results to the shape i need. I can then run it with side effects, verify that the data works and is showing up in the bucket, then continue with the next stage.

output bucket is currently the first panel that creates side effects, but high on the hitlist for the future would be webhooks or notifications. the later two may generate state outside of our system, but should be treated with the same reverence.

totally agree that we might want to revisit how we present this to the user. the current evolution came from introducing a "publish / commit" functionality to encompass future iterations of "flows as an executable resource" that got phased out on scope, but could be equally addressed at this point in time with a checkbox on any cell that produces side effects that says "run me for true true". not being prescriptive to design for that one, but i will campaign for at least the adoption of that copy if prompted.

**Comment by alexpaxton** [comment]
Created this issue for removing the legend in the export to dashboard overlay: https://github.com/influxdata/giraffe/issues/386
