### ISSUE TITLE
Clockface 3.0 - Nav Hover Menu stays present after navigating 

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#3027]
https://user-images.githubusercontent.com/146112/138916364-5ca96721-67a8-4ab9-9484-fdcc5efea40e.mov

**Comment by ChitlangeSahas** [comment]
https://github.com/influxdata/ui/pull/3067 needs to be merged in and this can be closed.

**Comment by ChitlangeSahas** [comment]
This was fixed in https://github.com/influxdata/ui/pull/3096
