### ISSUE TITLE
Figure out strategy for when the buttons and search input get squished in

### ISSUE THREAD

**Issue by daviddkkim** [influxdata/ui#3031]
![Screen Shot 2021-10-26 at 12.06.34 PM.png](https://images.zenhubusercontent.com/604f76d7b2c0ce7a06471654/8d2b9f25-5f82-494a-991f-1614c13febb3)

**Comment by ChitlangeSahas** [comment]
https://github.com/influxdata/ui/pull/3285, Demo data button was removed, we can close this issue.
