### ISSUE TITLE
cloud data explorer->script editor throws error

### ISSUE THREAD

**Issue by letrout** [influxdata/ui#3050]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Set up a query in the data explorer (InfluxDB CLoud)
2. Run the query, works
3. Click on "Script Editor"
4. Says error, with a link to this issue submission

**Expected behavior:**
Get some Flux code that I can edit to refine my query

**Actual behavior:**
Error msg

**Visual Proof:**

![influx_error](https://user-images.githubusercontent.com/33353303/139147206-8825baf2-c856-4b2c-9f7d-c22ccd75777e.PNG)

## About your environment

**Environment info:**

https://eastus-1.azure.cloud2.influxdata.com/orgs/ea217d2a13db2282/data-explorer

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```
I don't know how to run any of these CLI commands on the cloud instance

**Comment by kristinarobinson** [comment]
@letrout -- thanks for filing this issue.  Can you give an example of a flux query that created the error for you.  
Once that occurs, please go to the console.log and copy an errors you see.
Also from the Network tab, find the POST to the /query api call, and copy the response from that call, which gives us the data to reproduce the graph, before the error is displayed.

**Comment by letrout** [comment]
I can't seem to repro this. I was able to hit it more than once at the time, but now I can't seem to recall the query necessary to trip it (or perhaps it was a transient problem).

Probably should just close this. If I manage to hit it again I'll make sure to include the query.

**Comment by kristinarobinson** [comment]
Closing until it can be reproduced.
