### ISSUE TITLE
Remove or reduce  /usage API call from unneeded areas of the UI

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#3054]
An incident occurred where a customer experienced Cloud UI slowness and breakage when the /usage API returned too much date due to cardinality rate limit events.  

 /usage api should not be called in areas of the UI where usage data is not relevant (e.g. dashboard list, task list, etc).  Remove /usage API calls where unnecessary (may be embedded in /getAllResources?)

The full URL
`https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/orgs/4930a3d6870ceb57/usage?start=-30d`

![CleanShot 2021-10-28 at 12.26.14@2x.png](https://images.zenhubusercontent.com/5f496c1520d76ccd20391de7/17d6bbd8-d529-4614-b1b3-0f962d910a6d)![CleanShot 2021-10-28 at 12.29.46@2x.png](https://images.zenhubusercontent.com/5f496c1520d76ccd20391de7/20d41f0e-0f8a-4e13-a41a-6dbbb5e4523b)
![Screen Shot 2021-10-27 at 5.43.50 PM.png](https://images.zenhubusercontent.com/5f496c1520d76ccd20391de7/5d127b09-6ee1-4d6c-ac70-f07f4f7f55a7)

**Comment by genehynson** [comment]
We can disable this by turning off flag `newUsageAPI`. Here's where it's happening in the source: https://github.com/influxdata/ui/blob/master/src/cloud/components/onboarding/EngagementLink.tsx#L22

Should I turn this growth flag off?

**Comment by genehynson** [comment]
Talked to Barbara and Daniel Campbell. We decided to turn the flag off for now since it was only be using to track user engagement. 

I've opened a [new issue](https://github.com/influxdata/ui/issues/3152) to revisit a better way to track engagement that doesn't cause performance issues.
