### ISSUE TITLE
Make all notification endpoints available to free and PAYG customers

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3076]
We currently limit notification endpoints so that free users only get the Slack option, and PAYG customers get all notification endpoints.  This isn't a useful distinction, and has misled our customers - e.g. Luxxfolio evaluated our product on the free tier, then moved to PAYG and were not aware that PagerDuty was an option, so they built their own equivalent.

After discussion with Balaji, we want to make all notification endpoint options available to all cloud2 users, whether free, annual or PAYG.

**Comment by drdelambre** [comment]
this has always been the case for notebooks, are we talking about updating the old alerts interface?

**Comment by barbaranelson** [comment]
Yes. I wasn't aware that notebooks doesn't make the same distinction  (even better reason to get rid of the restriction).
