### ISSUE TITLE
standardize alphabetical order in dropdown lists within the UI

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3080]
When we show a drop-down list of buckets, we are inconsistent in how we display them across the UI, e.g.:
The buckets page shows the two system buckets, followed by user buckets (in case-insensitive alphabetical order).
The notebooks page shows user buckets, followed by system. Within the user buckets it is case-insensitive alphabetical order.
The data explorer page shows upper case user buckets, followed by system buckets, followed by lower case user buckets.

Can we agree on one format and apply it consistently across the UI?  My vote would be user buckets (case-insensitive alphabetical order) followed by system buckets.

**Comment by jrenee42** [comment]
summary:  we need to have consistent ordering.  do we want to group them by type, or just have them be case-insensitive alphabetical order? @daviddkkim  please advise.

the data explorer and notebooks group them, but differently. the main buckets page lists them alphabetically


<hr>

after speaking to @barbaranelson ; this is a problem with the bucket selectors; not in dropdowns.  specifically; here: 

the buckets page, in case-insensitive alphabetical order:

![Screen Shot 2021-11-11 at 4.10.07 PM.png](https://images.zenhubusercontent.com/5fbbf7579d1f2e09ec8ff6e2/2ea55443-44c7-4ee9-907a-c531731aca3b)

the data explorer:
![Screen Shot 2021-11-11 at 4.08.14 PM.png](https://images.zenhubusercontent.com/5fbbf7579d1f2e09ec8ff6e2/9ea4f659-710f-4838-933f-0688074eb6ca)

notebooks:
![Screen Shot 2021-11-11 at 4.07.57 PM.png](https://images.zenhubusercontent.com/5fbbf7579d1f2e09ec8ff6e2/22fa16b5-d22d-4eb3-8446-d9e3aa3e80e0)

and the bottom of the sort in the notebooks:
![Screen Shot 2021-11-11 at 4.12.03 PM.png](https://images.zenhubusercontent.com/5fbbf7579d1f2e09ec8ff6e2/74bea06f-a878-4369-8e9b-35a7d7abce4f)
