### ISSUE TITLE
Clockface 3.0: Show column headers and meta data in normal case rather than UPPER CASE in raw data view 

### ISSUE THREAD

**Issue by bpalani** [influxdata/ui#3087]
Issue:
As a user who doesn't always remember the exact case of my tag names, and use the Raw Data view to see the column headers, I feel that the new Clockface 3.0 upgrade has made it more difficult to iteratively create my flux queries with appropriate filters because all the column headers seems to be in UPPER CASE in the Raw Data view mode.

As an example in the screenshot below the column ORGID is shown in the raw data view:
![image](https://user-images.githubusercontent.com/10112209/139512958-6ed1b09c-c90d-4f46-8280-4f29857b8968.png)
But if I try to filter by ORGID, then it will not produce me the result, because the actual tag name is OrgID and not ORGID. However it is hard to figure this out in raw data view.

Kindly fix this bug to show column headers in normal case as was done before the Clockface 3.0 upgrade

**Comment by daviddkkim** [comment]
closed by #3065 
great work @ChitlangeSahas !

**Comment by daviddkkim** [comment]
closed by #3065
