### ISSUE TITLE
notebook: Shared link says 'no data returned' even though original notebook has data

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3100]
I have a notebook in tools (barbara 99) - see first screenshot. I created a shareable link, but when I click on the link I can see some of the notebook, but I get 'no data returned' for the table view, even though it shows data in the original notebook and the visualization which comes below the table view looks fine in the shared view.

![Screen Shot 2021-11-01 at 1 48 28 PM](https://user-images.githubusercontent.com/13143006/139740203-3023c777-a1c2-47cb-92de-4cf98dd5587c.png)
![Screen Shot 2021-11-01 at 1 48 07 PM](https://user-images.githubusercontent.com/13143006/139740232-a1ec288d-7060-4aaf-9550-3356a4b63712.png)

**Comment by jzahnd** [comment]
Let's verify this one and see if it's fixed.

**Comment by genehynson** [comment]
Verified that it's been fixed in tools. Here's the share link: https://influxdb.aws.influxdata.io/share/XNIMvV3LcZxgmKmi10E48
![image.png](https://images.zenhubusercontent.com/5fceb17341f743ce2116433f/b3d16053-6ea6-4547-9817-c6ec71a58b7a)

**Comment by barbaranelson** [comment]
Yes, it's working now. Thanks.
