### ISSUE TITLE
Notebooks: I want to create a task with a Notebook

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#3103]
Once we fix the dependencies linked to this issue, we'll be able to offer the same features users have in the current task UI, but within a Notebook. This will help us transition other parts of the app to have Notebooks as the main way for interacting with queries. 

The feature has already been created under the `'createWithFlows'` feature flag. [Here](https://github.com/influxdata/ui/pull/2901) is the ticket for that feature flag.

Outstanding Questions:
- Do we want to A/B test this Task Notebook vs. the current Task UI? [Test Brief](https://docs.google.com/document/d/1svQBEWOK_Nyd3Yd7e7gjtYrTU8kZIqvjAmFJEo9Vsuo/edit#heading=h.1ewszmvjy0cv)
- Do we want to A/B test using the Flux panel vs. Query Builder panel within the Task Notebook?
- Do we want to A/B test a version of Notebooks that doesn't allow you to add additional panels other than what's necessary for creating a task (query builder/flux panel, simple table, schedule panel)?

Notes: 
- Run the test with new users where there is no existing behavior that can get disrupted with this new experience.
- Remove Export as Task from Data Explorer for those users.

**Comment by jzahnd** [comment]
This is already done.
