### ISSUE TITLE
Notebooks: In the Task panel, fix the bug that allows users to open the Export as Task modal without an input in the Every field

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#3104]
Right now, users are able to proceed to Export as Task without an Every input. We shouldn't allow users to move forward in the process to export a task since the Every input is required. 

Once this is fixed, we should only show an error state on the Every field if they've tried to Export as Task without an Every input. 

https://images.zenhubusercontent.com/279622976/4e99fc9a-3263-417f-8736-63f9670b5f24/screen_recording_2021_11_01_at_7_21_28_pm.mov

**Comment by genehynson** [comment]
Looks like @drdelambre fixed this in https://github.com/influxdata/ui/pull/3138 so I'm closing it
