### ISSUE TITLE
Research: Determine a better name for Notebooks

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#3110]
Based on feedback we received from the latest round of research, we have reason to believe "Notebook" isn't the best name for that feature. The word carries connotations of note-taking and storing notes and queries. Although that is one benefit of a Notebook, there's much more you can do with it.

Let's survey users to help us determine what the right name is.

**Comment by jzahnd** [comment]
Closing until this comes up in another venue or proposal.
