### ISSUE TITLE
Notebooks: When I select data, I can see the time range of that data

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#3111]
We'd like to show users the time range of the data they've selected, instead of having them guess that time range. This will provide more visibility into their datasets and help users build queries without having to guess the time range.

I imagine we'd place this information on the query builder since that's where they are selecting the data. A notebook can have multiple input panels, so we wouldn't want to show this for the whole Notebook, we'd want it specific to each data set.

Design: TBD

Questions:
- Is it possible to show users the time range of the data from the selected bucket and/or metric? 
- If a specific metric was recorded at a later date than the entire dataset, can we base the time range on that information?

**Comment by jzahnd** [comment]
This is no longer relevant, closing
