### ISSUE TITLE
Notebooks: Make panel types more visible within the Notebook experience 

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#3118]
We'd like to explore and test a version of Notebooks in which the Notebook panel types are more visible and easily accessible to users. Currently users can only see the Notebook panel types after clicking on the add button.

![Screen Shot 2021-11-02 at 11.02.32 AM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/c71313d4-06aa-4e5c-a4ed-5de515982a9f)

Design: TBD

**Comment by jzahnd** [comment]
Thought process currently is to put this at the bottom to be more visible but not in the way.

**Comment by jzahnd** [comment]
Closing due to being a duplicate
