### ISSUE TITLE
Alerts: I can export a new Alert

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#312]
### Export to New Alert
GIVEN I have a notebook with valid entries and an output bucket selected
WHEN I click the green `Export` button in the cell header
THEN I see an overlay with a name input, a preview of the generated flux, a submit button, and a cancel button
AND the "Create New" tab is selected by default

[Design Mockup (Overlay)](https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=1360%3A3)

#### Error State

GIVEN `Name` input is empty
WHEN I click the green `Export` button
THEN I see [error messages](https://influxdata.github.io/clockface/?path=/story/components-forms-standard--formelement) under each invalid input with text "This field is required"
AND nothing is submitted

[Design Mockup (Error State)](https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=1360%3A1304)

#### Success

GIVEN inputs are filled
WHEN I click the green `Export` button
THEN a new alert is created

WHEN the new alert is successfully created
THEN the overlay closes
AND I see a [notification](https://influxdata.github.io/clockface/?path=/story/atomic-notification--notificationdialog) appear for 5s with text "[Alert name] successfully exported!" and a button labeled 'Go to Alert'

WHEN I click the button in the [notification](https://influxdata.github.io/clockface/?path=/story/atomic-notification--notificationdialog)
THEN I am taken to the alert I just created

---

Clockface Components
[Alert](https://influxdata.github.io/clockface/?path=/story/atomic-alert--example)
[Overlay](https://influxdata.github.io/clockface/?path=/story/components-overlays-family--overlay)
[Tabs](https://influxdata.github.io/clockface/?path=/story/components-navigation-tabs-family--tabs)
[Notification](https://influxdata.github.io/clockface/?path=/story/atomic-notification--notificationdialog)
[Form](https://influxdata.github.io/clockface/?path=/story/components-forms-standard--formelement)
[Button](https://influxdata.github.io/clockface/?path=/story/components-buttons-composed--standardbutton)

**Comment by jzahnd** [comment]
Closing due to age and being done for v1
