### ISSUE TITLE
notebook: Shared link gets internal error

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3127]
I am testing in tools. I created a notebook (Barbara - hourly successful notebook runs). I created a read-only token to the frontendservices bucket, and then generated a share link for the notebook using this token.  https://influxdb.aws.influxdata.io/share/5f386367d8dd2000

When I click on the share link, I get an internal error and the console shows the following:
![Screen Shot 2021-11-02 at 9 51 01 AM](https://user-images.githubusercontent.com/13143006/139910080-a411968b-5519-4cdd-8dab-01584ad9aeaa.png)

**Comment by genehynson** [comment]
Verified this is fixed in tools. Here's the new share link: https://influxdb.aws.influxdata.io/share/IvOc8NZIqM5xkVpMpGD5S
![image.png](https://images.zenhubusercontent.com/5fceb17341f743ce2116433f/9c958fbb-8b7d-40b3-94bd-f5fe0c5fb160)

**Comment by barbaranelson** [comment]
Yes, it is working now. Thanks.
