### ISSUE TITLE
Maps: I see Maps styled to part of the InfluxDB Cloud UI

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#313]
### Style for brand palette
When: I'm viewing the map visualization in InfluxDB Cloud
Then: I can see the map styled to look like part of the custom UI

### Light Mode / Dark Mode
Given: I've selected the Map visualization
When: I switch to light or dark
Then: The map tiles also switch to appropriate palette

### Technical Notes
Use Mapbox Studio to create:
https://www.mapbox.com/mapbox-studio

Login to InfluxData's Mapbox account is in Engineering Vault

**Comment by kristinarobinson** [comment]
As a user I want to be able to see the map in both Light and Dark mode.

Note: MapBox provides a studio to style the map which generates css  and/or properties to control the light/dark mode.  https://www.mapbox.com/mapbox-studio

Style the map using Influx Data brand palette.

**Comment by mnorriswalker** [comment]
@Palakp41 - This was actually pretty easy... lowered estimate to 1

Changed the typography to `Rubik` with an `Arial` fallback

Dark:
https://api.mapbox.com/styles/v1/influxdata/cklspghhd1opp17mmz0yk7rcy.html?fresh=true&title=view&access_token=pk.eyJ1IjoiaW5mbHV4ZGF0YSIsImEiOiJja2hndnM0eWQwNTVtMzRwZnd5cmQxNHhoIn0.IEAjIguiM67ql4mhiD88rw

Light:
https://api.mapbox.com/styles/v1/influxdata/cklsr0en41qam18p7exyykg2x.html?fresh=true&title=view&access_token=pk.eyJ1IjoiaW5mbHV4ZGF0YSIsImEiOiJja2hndnM0eWQwNTVtMzRwZnd5cmQxNHhoIn0.IEAjIguiM67ql4mhiD88rw

We should use a different theme depending on if the dashboard is in Light or Dark Mode like this random Mapbox screenshot demonstrates :)
![image.png](https://images.zenhubusercontent.com/5d928b2631e8dd0001222f82/affeded4-51b9-4678-8d0e-6adb72a73fd3)
