### ISSUE TITLE
notebooks: Tab is 4 space, which is inconsistent with our docs and rest of UI

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3135]
Came from Verkada (ref: https://github.com/influxdata/EAR/issues/2756)

All your examples have 2 spaces tabulation, but when you hit tab in the notebook editor it does 4 spaces which is kinda annoying 🙂 because I'm ending up having a mix of both. Just checked, Script Editor in Data Explorer does 2 spaces.

Examples of documentation with 2 spaces:
https://docs.influxdata.com/influxdb/v2.0/query-data/flux/join/
https://docs.influxdata.com/flux/v0.x/stdlib/universe/pivot/

**Comment by drdelambre** [comment]
confirmed that both script editor and flux panel in notebooks both share the 4 space convention

**Comment by barbaranelson** [comment]
That's not what I see. I see the script editor (in data explorer) doing 2 space tabs, and the flux editor in notebooks doing 4 space tabs (at least in tools where I tested today).

**Comment by genehynson** [comment]
I'm also seeing 4 space tabs in both data explorer and notebooks hmm

**Comment by genehynson** [comment]
Here's how I'm trying to reproduce it. Am I doing it wrong? Tried the same thing in tools and got the same result.

Data Explorer:
https://user-images.githubusercontent.com/6411855/140173204-bdd76ca5-4b94-4aa9-986e-48b89de12dc6.mov

Notebooks:
https://user-images.githubusercontent.com/6411855/140173121-aac38412-73e5-4929-bd63-1a26ba9f3ee2.mov

**Comment by barbaranelson** [comment]
Here are the videos for what I am doing.  I'm creating a new flux script, and each tab indents 2 spaces in the data explorer, but 4 spaces in notebooks.

https://user-images.githubusercontent.com/13143006/140177704-40b8a592-f5c2-442a-ae7a-72df886ed454.mov


https://user-images.githubusercontent.com/13143006/140177828-806a48f7-68c1-412e-ae30-24a49a8500cf.mov

**Comment by genehynson** [comment]
Weird! Data explorer uses 4 spaces as a tab for me when I craft the query. Maybe an LSP issue?

https://images.zenhubusercontent.com/279622976/bcdf7056-9dac-4cac-b2f0-48c3cee50812/screen_recording_2021_11_03_at_1_43_56_pm.mov

**Comment by genehynson** [comment]
@rockstar @nathanielc do y'all have any ideas why we might be seeing inconsistent tab behavior from the LSP?

**Comment by genehynson** [comment]
@barbaranelson now that the new LSP is in tools & prod, can you try to replicate this issue?

**Comment by barbaranelson** [comment]
Well, it's consistent now. I get 4 space tabs in notebooks and in data explorer script editor.  Though the docs use 2 space tabs, so it would be great if we could change the default from 4 to 2.

**Comment by nathanielc** [comment]
Flux's official formatter uses 4 spaces. Additionally we are running the examples for the Flux reference docs through the formatter so they will also have 4 spaces. (That is ongoing work part of the migration to fluxlang.dev) 

There will still likely be other docs still with 2 spaces and we should figure out a convenient way to format them with the Flux formatter so all Flux code is consistent beyond just number of spaces.

**Comment by barbaranelson** [comment]
Thanks for clarifying, Nathaniel.  I'll close out this issue, as we are consistent within the UI, and then open an issue for the docs team to update their flux examples by somehow running them through the flux formatter.

**Comment by barbaranelson** [comment]
Closing out this issue as the spacing now appears to be consistent within the UI.
