### ISSUE TITLE
Update 404 Page(s) in the UI

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#3156]
We would like to make our 404 pages more informative and useful to users and perhaps promote signing up to Influx. We should investigate all 404 locations and then update them to include signup details and a more useful messages.

We will need to investigate where all of our 404 pages live and apply them accordingly.

Design: 
![404 Page (1).png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/a8c9d0f4-e8e5-4135-8b03-352bf1c74282)

Figma: https://www.figma.com/file/tjf40318y3Q59sCPSOu7aL/404-Page?node-id=7%3A381

**Comment by jzahnd** [comment]
We need to follow up with the e-commerce team to update the design on the Quartz side.

**Comment by subirjolly** [comment]
@jzahnd I am guessing we need to replace this page?

![image.png](https://images.zenhubusercontent.com/5fa9843597598f467dccb2b9/03450a1b-49af-4302-8ade-1beaef2494c2)
