### ISSUE TITLE
embed instructions for installing the CLI into the UI

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/ui#3170]
**Proposal:**
Move the interactive instructions for installing the CLI to the UI. See https://portal.influxdata.com/downloads/

**Current behavior:**
In order to figure out how to install the CLI, users must find the documentation, and then find the interactivity configurator for installing the CLI.
![Screen Shot 2021-11-08 at 9 42 52 AM](https://user-images.githubusercontent.com/13948193/140762266-e471cd88-1f6f-4ee1-a322-d40cc8fcfc8c.png)

**Desired behavior:**
These instructions are available in the UI, and potentially prominent as a "next step" on new account creation. Especially when paired with: https://github.com/influxdata/ui/issues/3161

**Use case:**
This is a path for getting users into a development loop asap.

**Comment by kristinarobinson** [comment]
Moving to Onboarding initiative.

**Comment by wdoconnell** [comment]
This was added by https://github.com/influxdata/ui/pull/5896 and preceding tickets, so this ticket can be closed.

Note that this is currently not visible due to the IOx onboarding flag. https://github.com/influxdata/ui/issues/6640
