### ISSUE TITLE
Color Map: Spike - figure out how all of these pieces fit together and come up with a more concrete architecture

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#3171]
While starting work on this epic, I realized I needed to get a deeper understanding of how all the pieces of the UI, IDPE and giraffe fit together.

### Acceptance Criteria
- The outcome of this spike should be a document and drawing that illustrate what I've learned on this spike

**Comment by ChitlangeSahas** [comment]
We've explored bunch of ideas, we have a way forward.
