### ISSUE TITLE
firstMile: Telegraf Setup instructions more step-by-step

### ISSUE THREAD

**Issue by sjwang90** [influxdata/ui#3183]
**Proposal:**
This came up in our user research for the Telegraf UI Refresh work. One of the users didn't notice there was a third step because the scroll bar wasn't that prominent (even less prominent in safari). Didn't know how to get Telegraf fully up and running.

![image](https://user-images.githubusercontent.com/32681364/140835705-924d2c29-5a13-4296-9c2d-511360e8f74a.png)

**Current behavior:**
Telegraf configuration set up are 1-3 steps that users need to go through to get their Telegraf up and running. If the window isn't viewed correctly users may not see the later steps.

**Desired behavior:**
Minimally make the scroll bar more prominent. @daviddkkim had other ideas a more click through method that users had to go through. 

**Alternatives considered:**
Describe other solutions or features you considered.

**Use case:**
Why is this important (helps with prioritizing requests)?
Don't want users to skip out on later steps and not understand why their Telegraf isn't running anymore.

**Comment by kristinarobinson** [comment]
Changing numbering to 1 of 3, 2 of 3 and 3 of 3.
And
Disable Finish button until visible.
@sjwang90 -- is this ok?

**Comment by sjwang90** [comment]
@kristinarobinson Yup! That sounds great!

**Comment by wdoconnell** [comment]
Telegraf UI refresh (https://github.com/influxdata/ui/pull/4078) was completed in this PR; styling is acceptable.
