### ISSUE TITLE
Telegraf Redesign: Add new flow from bucket list Add Data button

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#3188]
When in the `Buckets` list, and the `Add Data` button is clicked and the `Configure Telegraf Agent` option is selected, then the latest flow should be used.

Current flow shows:
![image.png](https://images.zenhubusercontent.com/5f496c1520d76ccd20391de7/671ddfd3-6822-4ff8-8cb0-36db5aad63a3)
![image.png](https://images.zenhubusercontent.com/5f496c1520d76ccd20391de7/ba686197-2e03-4eb8-a473-dddf13f1d0dd)

Should go to:
![image.png](https://images.zenhubusercontent.com/5f496c1520d76ccd20391de7/6dd6c51b-417e-4bb2-ba2c-cd92ef05a48b)

**Comment by ChitlangeSahas** [comment]
Converted it into a story and removed the bug label.
