### ISSUE TITLE
Lazy load monaco

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#320]
Monaco takes a huge chunk of our bundle, for an interaction that is pretty buried in the application's UX. To help speed up the site and reduce the amount of time spent parsing JS on the initial load, lets lazy load it to get it out of that initial request!

**Comment by 121watts** [comment]
we should also reduce the size of the bundle by eliminating unused monaco editor features: 
https://github.com/microsoft/monaco-editor-webpack-plugin/issues/97
