### ISSUE TITLE
Epic: Persistent Help Bar

### ISSUE THREAD

**Issue by nanderson6** [influxdata/ui#3208]
Product Brief with background information here: https://docs.google.com/document/d/11Z5eCEqbm_zlnMJOwenyKJrB63i5LCj53S9zgAPlykY/edit#

### Target Customer / Problem Statement
Target User: Existing cloud users at any engagement stage who need help

User Stories:
AS a user in the UI
WHEN I want to find help with a topic
THEN I am able to find all the help resources in 1 place

AS a user in the UI
WHEN I want to get the support Addon
THEN I am able to easily find that option on the help/support page

AS a user in the UI
WHEN I need to reach out to support
THEN I am easily able to do so through the UI

### Goals
* Provide an ever-present help experience for cloud users, so they can answer their questions and find in-person help and relevant content faster

### Technical Notes
* TBD

### Acceptance Criteria
Given that a user in the UI needs help, 
the NavBar will have a new icon that shows `Help and Support` as a main navigation item.

Given that a user has the NavBar in collapsed mode, 
a new icon will show `Help and Support` as a main navigation item

Given that the `Help and Support` main nav item is clicked, 
the following popover menu items are visible with Headings:  
Under `Support`:
- Documentation
- FAQs
- Contact Support
Under `Community`:
- Official Forum
- Influx Slack
Under `Feedback`:
- Feedback and Questions

For the Contact Support, when clicked, 
- if PAYG, then,
Display a modal for the customer to fill out.
- if not PAYG, display modal to upgrade (see [link](https://www.figma.com/file/zn1PRkjE6CvBy52q0K2vAr/Support-in-the-UI?node-id=353%3A3938)), which will include a link to the status.influxdata.com at the top, and the following links for users to click on:
 - Forums
 - InfluxDB Slack 
 - Feedback & Questions Form

For PAYG customers, the Contact Support modal should have the following fields:
- A status page link is displayed at the top of the modal with verbiage (see figma)
- Severity dropdown, with description values in dropdown (with integers assigned behind those values)
- A Tooltip is displayed next to severity dropdown to provide a link to the support policy website for definitions of severity.
- Description, a text field with a limit of 2500 characters (verify against Salesforce API for other limits)
- Media file, which can be attached via a button

When the modal is submitted, call the SalesForce API to create a new ticket, with the input values from the modal, and the following additional information:
- `InfluxCloud` as the Deployment Version 
- Customer Email for Email CC

When Ticket is created, call SalesForce API to attach the follow notes to the ticket:
Browser type and version (if available), console.log errors (if any), most recently visited area (from context), org id, org name; account name, user id (different from user name which is an email address), account id, region

Display a spinner while the API is being called.

Display a confirmation page to the user, see design figma).
 - If severity 1 is selected, than an additional component will displayed to the user, which provides direct phone numbers for Support. (see figma)

For documentation, go to docs.influxdata.com

For FAQs, go to docs.influxdata.com/influxdb/latest/troubleshooting/frequently-asked-questions/
(make sure we have cloud FAQ, not OSS, check with docs team)

For Forums, go to community.influxdata.com

For Influx Slack, go to https://influxcommunity.slack.com/join/shared_invite/zt-mcmhhwae-dUsWR0xUzrqQ3k1Puo52Lw#/shared-invite/email

Feedback Form, create a simple form has a freeform text field for description, with a limit of 2500 characters and the ability to attach a media file.
- When submitted  this form will be sent via SalesForce API, in queue for the product team.

Metrics to capture:
What page is the user currently on before clicking on the Help & Support
(At what point is user needing the most help?)
How many times did users use the help panel before completing a task or creating a notebook
(How helpful is the help & support panel for completion of user journeys?)
How many users opened feedback form AND submitted a feedback
(How likely are users to use the feedback form?)
How many free users clicked on “upgrade” button after contact
(How many users are persuaded by the contact support feature to upgrade?)
Captured through Rudderstack/Snowflake/Domo stack

### Technical Requirements
The SalesForce API will require a Node microservice to be written as a relay service.  This node service will handle the following:
- Authentication requirements between to SalesForce API
- Integration directly with SalesForce API
- Provide a Rest API interface to the UI Web App to send all requests
- Return generated ticket Id to UI
- If SalesForce API returns an error for Feedback and Question, then display error and retry logic
- if SalesForce API returns an error for Contact Support, display link to retry which loads the original Contact Support modal with entered information pre-loaded, AND  a link to redirect to the link for support.influxdata.com. (see figma design)

### Release Plan
* Use a Feature Flag.
* Deployments team will be responsible for setting up the microservice on its server in all environments
* Marketing will include announcement of new feature in its monthly roundup newsletter
* Release to Tools env for shakeout
* Release to all production environments by turning on Feature Flag
* Docs team will be included in the rollout plan (https://github.com/influxdata/docs-v2/issues/new?assignees=&labels=&template=new-feature.md&title=)

### Links to Background Docs / Designs
* Designs - https://www.figma.com/file/zn1PRkjE6CvBy52q0K2vAr/Support-in-the-UI?node-id=0%3A1
* Growth team epic - https://github.com/influxdata/cloud-growth/issues/77

### Team
Designer - Andy Moon
PM - Nick Anderson
Eng - Dumplings UI team, Palak Bhojani Lead
Informed - Support team (Veeresh, Joe)

**Comment by nanderson6** [comment]
Just added in a link to the product brief that Andy and I created.

**Comment by kristinarobinson** [comment]
removed requirement for phone number on the tech support modal, as support cannot handle additional volume.  per veeresh email
