### ISSUE TITLE
Recent dashboards container should remove word wrapping

### ISSUE THREAD

**Issue by TCL735** [influxdata/ui#3219]
Recent dashboards has word wrapping which causes long dashboard names to get cutoff and wrapped into the next line. This make certain names look strange.

Here is an example
<img width="358" alt="Screen Shot 2021-11-11 at 1 53 56 PM" src="https://user-images.githubusercontent.com/10736577/141376994-e975eec0-f174-424b-9434-ebf7a2074933.png">

Word wrapping should be removed.

**Comment by genehynson** [comment]
It looks like this feature is being removed by the flag `docSearchWidget`. When `docSearchWidget` is on, this "Recent Dashboards" component is replaced with the Documentation search widget. ![image.png](https://images.zenhubusercontent.com/5fceb17341f743ce2116433f/7b3d5bf2-3e3f-4ad3-8b0b-df0e8a9253e7)
