### ISSUE TITLE
Multi Org - Typeahead dropdown: new implementation with limits for display

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#3220]
Adam mentioned a dropdown for variables taking a long time to load and looking like the UI has stalled after clicking.

this is for the use case when there is an initial value set for the dropdown, ~if there is no value then it already shows 'loading'~ (variables always have a default value)

https://user-images.githubusercontent.com/146112/141379859-d681ef6d-7e25-4ff0-b571-9917714bc8cd.mp4

**Comment by Luckette** [comment]
This is a dependency for multi-org. 

@juliajames12 is checking w/ the design team to find out if design work has already been done. If so, we just need the link to the figma. If not, she will take this on.

**Comment by juliajames12** [comment]
@Luckette Andy didn't have anything to hand off, so I'll be starting a new design for this. 

This isn't really stated in the ticket, but based on the conversation a while back with @kristinarobinson, I remember the implementation to solve for this is to only show a set number of items in the list and then having a message like "Search  to view more". If this is off from what you guys were thinking, let me know.

**Comment by Luckette** [comment]
@juliajames12 That is exactly correct. @kristinarobinson will send you a hand-drawing of what she had in mind.

**Comment by wdoconnell** [comment]
Recommend closing this issue after discussion with @brandenTenbrink. This duplicates [#761](https://github.com/influxdata/clockface/issues/761) in clockface, which design is releasing shortly.
