### ISSUE TITLE
Local Development Links are Broken

### ISSUE THREAD

**Issue by adamkasztenny** [influxdata/ui#3227]
## About the bug

All 3 of the links under [Starting Dev Server](https://github.com/influxdata/ui#starting-dev-server) in the README are broken. I'm trying to figure out how to run the UI locally.

Also, I think explanations about how to run and test the app should be the first thing mentioned in the README.

Here's what I did to get this running locally (I have no idea if this is right, but it seemed to work):
1. Start InfluxDB 2.0 in a Docker container, exposing the port on 8086.
2. Run `yarn start`
3. I went to localhost:8080 and was able to load and visualize demo data and changes I made in the source code were reflected in the UI.

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Click all of the links under Starting Dev Server in the README.
2. Observe that they are broken.

**Expected behavior:**
Some sort of documentation about how to run the app locally should exist in the README.

**Actual behavior:**
No documentation about how to run the app locally exists in the README.

**Visual Proof:**
![image](https://user-images.githubusercontent.com/12041666/141599957-cf52e433-0c35-4331-a69e-2399e535c3c2.png)
![image](https://user-images.githubusercontent.com/12041666/141599965-f6e206ac-c8a9-4b95-8ff3-d562d8e792be.png)

## About your environment

**Environment info:**
Fresh clone of this repo.

**Config:**
Node v14.18

**Comment by kristinarobinson** [comment]
@ adamkasztenny -- Unfortunately, you CANNOT run our cloud UI locally.  You can only run our OSS version locally.   That's why this links are failing for you, they are intended for our own developers.

To run the OSS version of our code, please download the OSS version of our code from our website.
