### ISSUE TITLE
Log scale for Y Axis

### ISSUE THREAD

**Issue by pbdeuchler** [influxdata/ui#3228]
**Proposal:**
I would like to be able to display data in cloud dashboard graphs in a log scale without changing my query/data.

**Current behavior:**
I have to use `math.log` on the data points, which can in some cases results in different calculations, and also prevents re-use of the queries.

**Desired behavior:**
I would like to change the y-axis behavior to logarithmic in order to better visualize the data

**Comment by timhallinflux** [comment]
https://github.com/influxdata/influxdb/issues/20551

Same issue in the core InfluxDB repo.

**Comment by kristinarobinson** [comment]
Won't fix.  Outside of approved scope of work.  Check out the Grafana product for more graph types

**Comment by pbdeuchler** [comment]
Just for context, this was a feature request for InfluxCloud and I was directed here. Spinning up my own grafana instance just to perform common visualization tasks from influx cloud data reduces the value of influx cloud quite a bit, since my whole goal is to not manage extraneous infra. 

Also fwiw, log scales are a pretty common need. Would it make more sense to move this ticket to the chronograf or giraffe repos?
