### ISSUE TITLE
allow lazy loading in type-ahead variable dropdown

### ISSUE THREAD

**Issue by jrenee42** [influxdata/ui#3234]
when there are more than 100 items in the dropdown, it can take a *long* time to render the items, and the component seems clunky and non-responsive.

as discussed here: https://influxdata.slack.com/archives/C01EENA6F9N/p1636669689233000

will use the react infinite scroll component from the react-window library to enable lazy loading
from this library: https://github.com/bvaughn/react-window

in particular, this codepen is a good starting off point:
https://codesandbox.io/s/5wqo7z2np4?file=/src/App.js:303-316

so; will  enable lazy-rendering when there are more than 100 items, with a ‘page size’ of 30;
will start with those numbers first and make them easy to change/adjust as the code is tested.

**Comment by kristinarobinson** [comment]
Refactoring design.  No longer appropriate.
