### ISSUE TITLE
notebook sharing: link breaks if you flip from presentation to non-presentation mode

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3244]
Steps to reproduce:
1. Build a notebook.
2. Put into presentation mode.
3. Generate a share link.
4. Click on link - will display fine
5. Put notebook in non-presentation mode.
6. Click on share link - will get InfluxDB error:
```
react-dom.production.min.js:198 TypeError: Cannot read properties of undefined (reading 'name')
    at button (/static/27.78a3fc3d4b.js:2)
    at /static/24.832b4d5d33.js:2
    at Wo (/static/24.832b4d5d33.js:2)
    at yi (/static/24.832b4d5d33.js:2)
    at ki (/static/24.832b4d5d33.js:2)
    at Na (/static/24.832b4d5d33.js:2)
    at ja (/static/24.832b4d5d33.js:2)
    at As (/static/24.832b4d5d33.js:2)
    at Cs (/static/24.832b4d5d33.js:2)
    at vs (/static/24.832b4d5d33.js:2)
ra @ react-dom.production.min.js:198
```

**Comment by genehynson** [comment]
I think the actual issue here is that no buckets are selected in the query builder

**Comment by barbaranelson** [comment]
Hmm, interesting. Happy to retest when the fix is out. Why would the lack of a bucket reference behave differently in presentation/non-presentation mode? If I share the notebook in presentation mode, I can break the link by flipping the notebook to non-presentation mode, then fix it again by flipping back to presentation mode.

**Comment by genehynson** [comment]
it is different because we use different UI components for the "read only" view. And the bug only existed in the read only version of query builder 😄
