### ISSUE TITLE
Notebooks: Redirect Bucket Exploration to Notebooks

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#3249]
We would like to redirect all traffic from bucket exploration to Data Explorer to Notebooks (Load Data -> Buckets -> Data Explorer to Load Data -> Buckets -> Notebooks). Technically, we have this ability already but would need to be rolled out to production

However, as part of this effort, we would like to offer a notice at the top of the notebook that would offer the user a direction back to Data Explorer if that is the user's preferred interface. 

In addition, we would like to know how many folks navigate to Notebooks from exploring their bucket and then return to Data Explorer. We can event the message that we create but may also need to dig into GA to trace the flow of users. 

## Acceptance Criteria

- All users who explore their bucket are redirected to a Notebooks experience
- Users are presented with copy that will guide them back to Data Explorer if they desire the old editing experience 
- We can measure users moving from Notebooks back to Data Explorer via CTA AND via the Navigation.

**Comment by drdelambre** [comment]
so the work here is to add a cta on notebooks, that only shows up for the bucket template, that when clicked stores a setting on the user, that will then selectively redirect them to either the data explorer or notebooks based on that setting whenever they click that buckets list item?
seems like that would be counter productive to notebooks adoption? what's the intent here?

**Comment by jzahnd** [comment]
@bpalani see comment above, we are concerned about moving folks off of notebooks. Could we remove the CTA requirement and measure via GA for general loss of users back to data explorer?

**Comment by barbaranelson** [comment]
Closing this out as we decided to go live without the message redirecting back to data explorer.
