### ISSUE TITLE
add cloning and deleting to the notebook page

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#3251]
currently in notebooks, there is a heavy cost to cloning and deleting of a notebook. since the user must check to see the contents of a notebook before deleting, to ensure they're not deleting the wrong one, the user flow follows:
- navigate a list by name, find a potential match and click on it
- if it's not the correct notebook, take note of the name of the notebook, return to the list, find where you left off by matching a list item to that name, and continue the search
- if it is the correct notebook, take note of the name of the notebook, return to the list, find where you left off by matching a list item to that name, then select the delete button, and confirm

we can save a lot of that cognitive overhead and back and forth if we remove one of the validation cycles and allow the user to delete right from the notebook they're currently in. By reducing the overhead of deleting one off explorations, where the user hasn't even been introduced to list navigation, we should also be able to remove the need for ephemeral notebooks (dont wanna keep it? just delete it)

Design: 
![Delete and Clone in Notebook.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/86630a4d-6ca5-4f1d-9fac-62b10c411ed8)![Delete Confirmation.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/b6307a08-e7e4-4a2e-a2c9-f0748717d93d)
![Clone.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/b68e69bf-0b7d-41aa-83bf-6bb3abe1b7b3)

**Comment by jzahnd** [comment]
When we pull this in for Notebooks, we need to create tickets for the other list views for updating them accordingly.
