### ISSUE TITLE
add "+ notebook" button to the bucket page

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#3254]
in the bucket exploration list page, when a user clicks on a list item, it opens directly into data explorer. this non-standard interaction mechanism represents nearly 25% of all data explorer traffic, and we dont know if it's completely by accident, caused by the nonstandard interaction, or if it's intentional and helps people explore their data faster.

the idea here is to remove that ambiguity by encapsulating that interaction into a button that, when clicked, creates a new notebook for the user

**Comment by jzahnd** [comment]
The idea here is to complete this before we remove ephemeral notebooks so that we don't start creating a giant list of notebooks.

**Comment by jzahnd** [comment]
Let's shelve this for just clicking on the button and opening in a notebook
