### ISSUE TITLE
notebooks: Revisit presentation mode with notebook sharing

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3272]
Today if you share a notebook in presentation mode, and then flip the notebook to non-presentation mode, the shared notebook flips too. This seems like the wrong coupling.  I should be able to share in presentation mode, and then change my own display to non-presentation without impacting the shared experience.  

It might make more sense to have presentation mode be a local display setting, rather than a property of the notebook, or maybe just make it a property of the shared notebook.

Capturing this for future discussion, after we've seen some usage of shared notebooks.

**Comment by drdelambre** [comment]
we might want to connect this change with the publish cycle work, so that local changes arent reflected in your public share until you publish the notebook, which also updates your tasks and the like

**Comment by asalem1** [comment]
This should be closed since it's been addressed by the publish lifecycle work
