### ISSUE TITLE
Show correct pages for `contract` account type

### ISSUE THREAD

**Issue by randycoulman** [influxdata/ui#3276]
## About the bug

(Cloud only)

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Set up an account with an `accountType` of `contract` (or fake a response that indicates this) and marketplace `billingProvider` (anything but Zuora).
2. Attempt to access the `/checkout` route
3. Note that it is accessible
4. Attempt to access the `/billing` route
5. Note that you see the free account billing page

**Expected behavior:**
1. The `/checkout` route should be inaccessible
2. The `/billing` route should show the marketplace billing page

**Actual behavior:**
1. The `/checkout` route is accessible
2. The free account version of the billing page is shown

**NOTE:** For non-marketplace `contract` users, we'll still want to show the Free billing page for now, but @gunnaraasen will be writing a new story for a different variant of this page for that case.

**Visual Proof:**

Checkout Page:
![image](https://user-images.githubusercontent.com/1406203/142261043-14d24b1d-708f-4c06-b61e-741bc48ccb25.png)

Billing Page:
![image](https://user-images.githubusercontent.com/1406203/142260842-737568fe-074a-454e-950f-86d212235920.png)

**Comment by subirjolly** [comment]
@juliajames12 @jzahnd If `/checkout` page isn't accessible, should I just redirect the user to home page or should I show 404 page?
