### ISSUE TITLE
Notebook sharing: generate a new read-only token when click on the share link

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3283]
When https://github.com/influxdata/idpe/issues/12378 is implemented, it will break the current notebook sharing implementation, as we will no longer be able to get the value of the token from the API.  We need to have moved away from the current solution (to getting a JWT to use for the shared notebook queries) before this IDPE issue can be completed.

**Comment by barbaranelson** [comment]
As there is an urgency to removing the API to get a clear-text token, we are going to change this feature to generate a new read-only token whenever the user requests to share a notebook.  The rest of the functionality remains as it is today, but the user will no longer be able to use an existing token to share a notebook.

**Comment by jzahnd** [comment]
@juliajames12 we need a naming convention for the naming of the token here.

**Comment by juliajames12** [comment]
@barbaranelson Based on this description, a new autogenerated token is created each time the user shares a notebook, right? If so, I think we should include the Notebook name and a timestamp in the autogenerated name. For example if I were to share the Notebook Usage Stats Notebook at 3:00pm it would be Notebook Usage Stats Share 2022-01-25T15:00:00.000Z and again at 4:00pm Notebook Usage Stats Share 2022-01-25T16:00:00.000Z

Or is one token created per notebook the first time they share it and then referenced each time the user shares that Notebook. So if I shared the Notebook Usage Stats Notebook at 3:00pm and 4:00pm only one token would appear in the API token list, and the “last used” field would be based on the 4:00pm time.

**Comment by barbaranelson** [comment]
It looks like you need a new token whenever you leave the notebook and come back again (there doesn't seem to be a way to get the share URL again after you leave the notebook).  So, can we go with generating a token with the current time (e.g. Notebook Usage Stats Share 2022-01-25T15:00:00.000Z) whenever we are generating the share URL.

**Comment by subirjolly** [comment]
@juliajames12 So, should i just hide the dropdown? Let me know if the above mentioned nomenclature is the final one. I will start working on it once you give me a go.

Also, As a next step did you want to flesh out "autoGenerated" boolean as well if you'd like to filter out the auto-generated tokens? That's going to require api update.

**Comment by barbaranelson** [comment]
There is an urgency to this so I don't want to tie it to API changes. We can do that as a separate effort.  Yes, let's just get rid of the drop-down as the user doesn't have the option to select a token any more.

**Comment by subirjolly** [comment]
> 

Absolutely! This is why I mentioned it to be the next step, if we want to add this feat. I will start working on it and @juliajames12 can let me know the nomenclature. Thanks!

**Comment by barbaranelson** [comment]
Just realized my comment about not tying this to an API change was misleading. I meant not tying it to an API change in another team (the ability to distinguish between auto-generated tokens and user-generated tokens).
