### ISSUE TITLE
Notebooks: Remove Bird Migration Demo Data from Query Builder

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#3286]
The Bird Migration demo data doesn't load when selected since it's historical data and the default time range is for the past 3 hours. There is no indicator that the user would have to change the time range or what to change it to in order to see the data, so it looks like broken demo data set or bug.

To avoid overcomplicating the conditions to solve for a historical demo data set, we want to remove this from the Query Builder. 

We'll need to inform the docs team that we're removing this so they can update the demo data docs.

**Comment by juliajames12** [comment]
@barbaranelson @bpalani @jzahnd Discussed this with Gene and Boatie as well, but wanted to give you all a heads up on why we want to remove this demo data set.

**Comment by barbaranelson** [comment]
Fine by me.
