### ISSUE TITLE
Notebooks: Task editing for non-notebook Tasks

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#3298]
When opening a task in a Notebook that was not created via a Notebook, we would like to present the user with a Flux panel and a schedule panel. The Flux panel should contain the task itself and the schedule panel should be populated with the original schedule details.

**Comment by drdelambre** [comment]
we need to be able to tell if a task was generated by a notebook or not, so this is blocked by https://github.com/influxdata/idpe/issues/9811
