### ISSUE TITLE
Move Usage Page javascript from Quartz to influxdata/ui

### ISSUE THREAD

**Issue by 121watts** [influxdata/ui#331]
Once the Usage Page contract is defined (#325).  Bring over Quartz's Usage Page javascript to `influxdata/ui` and stub out the API based on the contract defined in #325

**Comment by subirjolly** [comment]
There's still some work and testing left once we connect this page to the API which e-Commerce team gives us.
The discussion was around changing what's going to be in the response and whether they are going to return only the data which needs to be rendered or the entire dataset. Regardless, we'd have to make all those changes. Along with that, there are also some changes which were discussed.

![image.png](https://images.zenhubusercontent.com/5fa9843597598f467dccb2b9/ac7d80af-0ca6-4e06-87b5-ea85c56bba9c)

Initially, we will be retaining the existing dropdown options and not what we have in the new UI(which is a lot granular).
