### ISSUE TITLE
Move Billing Page javascript from Quartz to influxdata/ui

### ISSUE THREAD

**Issue by 121watts** [influxdata/ui#332]
Once the Billing Page contract is defined (#325).  Bring over Quartz's Billing Page javascript to `influxdata/ui` and stub out the API based on the contract defined in #325

**Comment by subirjolly** [comment]
Connecting the new UI(we have partially done) we have with the new API.

**Comment by corriganjohn** [comment]
Do we need separate issues for the two different `/Billing` pages (free and PAYG)?
