### ISSUE TITLE
Debug Rudderstack Reporting Issue

### ISSUE THREAD

**Issue by subirjolly** [influxdata/ui#3322]
It seems that snowflake has been receiving data for a long while now. Rudderstack flag (`rudderstackReporting`) has been turned off and still the data has been reaching snowflake. We need to investigate, what's sending(leaking) data to rudderstack in order to get some clarity on the functionality which wasn't intended to be turned on yet.

**Comment by jzahnd** [comment]
We will investigate if this happens again.
