### ISSUE TITLE
OSS needs a way to update the version displayed on the sign-in page without modifying UI sources

### ISSUE THREAD

**Issue by danxmoran** [influxdata/ui#334]
Original issue: influxdata/influxdb#20007. We have a work-around for now, so this is more a future-looking request.

The `VersionInfo` component rendered as part of the OSS sign-in page uses [hard-coded constants](https://github.com/influxdata/ui/blob/master/src/shared/components/VersionInfo.tsx#L16) to set the version / git hash that's displayed to users. These constants are [set at build time based on the environment](https://github.com/influxdata/ui/blob/master/src/shared/constants/index.ts#L62-L63).

Since OSS still contains a copy of the UI code, the git hash of the UI at build time == the git hash of the server at build time, so the UI stays accurate as long as we remember to update `version` inside of `package.json` (see influxdata/influxdb#20077). When we refactor OSS to pull artifacts from / vendor this repository, matching up the git hashes / versions will get even trickier.

IMO it'd be nice if the UI displayed two separate versions:
1. The version of the UI codebase, hard-coded at build time
2. The version of the server as reported by `/health`

**Comment by drdelambre** [comment]
that suggested path sounds like a great implementation
