### ISSUE TITLE
Bug: Dashboards - Table settings

### ISSUE THREAD

**Issue by datsistrain** [influxdata/ui#3343]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Go to Dashboards
2. Add a Cell
3. Choose Table then go to Customize
4. In Column Settings, click to adjust Scroll with table or Fixed
5. The error occurs 

**Expected behavior:**
Something changes in Table display

**Actual behavior:**
Error occurs

**Visual Proof:**

https://user-images.githubusercontent.com/90777339/144178267-cf6cfda1-d437-4cc9-b8a2-59cef0655bcd.mp4

## About your environment

**Environment info:**
InfluxDB 2.0.7 runs as a docker container

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by ChitlangeSahas** [comment]
I can not seem to reproduce this.

**Comment by kristinarobinson** [comment]
Infinite render occurring?

**Comment by kristinarobinson** [comment]
NOTE: please test https://github.com/influxdata/ui/issues/3864 once a PR is complete for this.  See if the same fix works.
