### ISSUE TITLE
Monaco: autocomplete injection mechanism tied to LSP delay

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#3347]
when running our tests, the LSP adds a bunch of autocomplete help for the user. if we type too fast for this mechanism to resolve, then seemingly random characters start getting injected into the flux code and our tests start failing. right now we have all of our tests hardcoded to 10ms delays between key presses, mostly implicitly through cypress' defaults. this means that if the LSP ever decides to take.. 11ms to resolve it's autocomplete request, our tests will start failing.

we should look into how we might decouple these

**Comment by wiedld** [comment]
No longer occurring.
