### ISSUE TITLE
Tokens: I am not able to pick the buckets for my token - due to user error

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3353]
I am trying to create a token with access to a few buckets, but when I try to generate the token, my only choices are All buckets or I see the string "Individual Bucket Names" but no actual bucket names, and nothing to click on.  See screen shot (from tools).

![Screen Shot 2021-12-01 at 2 49 25 PM](https://user-images.githubusercontent.com/13143006/144327053-881ac888-6046-4b28-bd0e-dded395928b3.png)

**Comment by barbaranelson** [comment]
I just realized my problem. It's user error but we may still want to rethink this.  Instead of putting the name in the description field, I accidentally put it in the search field, so no bucket names are appearing in the list of available buckets (because none match my description).

**Comment by Palakp41** [comment]
@barbaranelson I think that doesn't seem very user friendly. Would it be better to display something like `No resources match your query`(below the search bar) when the string in the search field doesn't match anything else?

**Comment by barbaranelson** [comment]
Yes, I think that would help, as it draws my attention to the fact that I was searching.

**Comment by Palakp41** [comment]
I communicated the design requirement for this issue with @mavarius who came up with the attached design to display `No buckets/telegrafs/resources match your query`. Also, the `Individual X` has been updated to look like a heading to reduce the confusion.

![image (2).png](https://images.zenhubusercontent.com/5cfe72d856132d6a798735d8/7379df8d-ee8a-4298-8fbb-b0da28f5fecf)
