### ISSUE TITLE
Notebooks: Wasn't able to export as task from notebook

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3367]
I created a notebook with a simple query and tried to export it as a task, but I kept on getting an error:

![Screen Shot 2021-12-02 at 6 09 41 PM](https://user-images.githubusercontent.com/13143006/144532998-3ad3be7e-501e-4586-bdbb-dbed2db5c4e2.png)

I then tried saving the notebook, and then exported it as a task and that worked.  It looks as if you can't export to task from an unsaved notebook.

**Comment by barbaranelson** [comment]
Actually, I don't think that worked. Once or twice I would not get the error message and just get the success one, but I have no way of confirming if the task was created as I don't know what it was named.  I also get success and fail messages, so not sure if the success ones are accurate.
![Screen Shot 2021-12-02 at 6 16 17 PM](https://user-images.githubusercontent.com/13143006/144533709-d99afb25-da4c-4113-97dd-1786a81dbb89.png)

**Comment by drdelambre** [comment]
fix incoming, but it seems like the tasks _were_ being generated in the background. of course, the error message signifies that the only mechanism that would show you _which_ tasks those were, has failed. but we do have some means available for exposing the panel ids in the console, so lemme know if you need help cleaning them up

**Comment by barbaranelson** [comment]
Yeah, no rush, but I probably should figure out how to clean them up, as I have probably created at least a dozen tasks - fortunately they are running at pretty low frequency.

**Comment by drdelambre** [comment]
if you run this in the console:
`influx.set('flow-debug-queries', true)`

then a new button should show up on the top of each of the panels. when you click that new button on the schedule panel you were exporting from, a bunch of stuff should print in the console. there's a `Panel: xxx` header for each panel, and the one that is the darkerish grey is the id of the panel you clicked on. if you go to the tasks page and enter that id into the search input, you should see all of the tasks generated by that panel.

to ensure the notebook interface doesn't get artificially busy as time goes on, make sure to turn off the flag when you're done with:
`influx.set('flow-debug-queries', false)`
