### ISSUE TITLE
Tokens: Switching organisations keeps tokens of previous org on the Tokens page

### ISSUE THREAD

**Issue by shirish87** [influxdata/ui#337]
Version: OSS influxdb:v2.0.1 (Docker)

Steps:

1. Create an organisation "org2" so that there are two orgs: "default" and "org2"
2. Generate some tokens in "default" org
3. Switch organisations by clicking the user avatar in the side panel, then "Switch Organisations"
4. In "org2", navigate to Data > Tokens

Result:
* Server returns empty list for tokens in the response for the `/api/v2/authorizations?orgID=<orgId>` request
* List of tokens of "default" organisation are still displayed. You can even deactivate tokens (for the default org) from "org2"
* Refreshing the page produces an empty token list

**Comment by jzahnd** [comment]
This should be fixed now, closing.
