### ISSUE TITLE
Tech Debt: cypress explorer tests take significantly longer than all other shared e2e tests

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/ui#3385]
I have been spending time optimizing a CI pipeline, and I have found that `cypress/e2e/shared/explorer.test.ts` is a consistent outlier in taking noticeably longer than the other shared e2e tests.

The shared e2e tests are run concurrently, starting at approximately the same time, and the CI pipeline blocks until all the e2e tests finish.

Out of 4 arbitrarily chosen CI runs from the past 24 hours:

- explorer took 4m50s, next longest run was checks at 3m46s
- explorer took 5m3s, next longest run was dashboardsRefresh at 4m27s
- explorer took 5m15s, next longest run was at dashboardsRefresh at 4m1s
- explorer took 5m17s, next longest run was dashboardsRefresh at 4m7s

Not 100% of the time is spent in the test in each of those cases -- each job spends time pulling a Docker container and starting an environment, for instance -- but the timings show that our CI pipeline will complete faster if we reduce the time spent in explorer tests.

**Comment by hoorayimhelping** [comment]
I took a crack at this under branch `bucky_split_explorer_tests`. I split the explorer test suite into two test suites, and I had problems from the start running the explorer tests that write queries in the script editor view, either in master or on a branch.

**Comment by Luckette** [comment]
no longer needed after fixing flaky tests
