### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by arihan-butlr** [influxdata/ui#3390]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Login
2. ...
3. ...

**Expected behavior:**

I am supposed to log in
**Actual behavior:**

It took me to a black page with a link here
**Visual Proof:**

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by asalem1** [comment]
@arihan-butlr where were you trying to log in from? Do you have an existing account? You can try accessing the login page here:

https://cloud2.influxdata.com/signup
