### ISSUE TITLE
Check Threshold definitions, cannot enter numerical value beginning with minus or plus signs

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/ui#3399]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Generate a test data set to a bucket
2. In Alerts create a threshold check based on the data set
3. In Thresholds click on a threshold level to bring up the definition fields
4. In a value field type a negative value.  e.g. -2.5

**Expected behavior:**

Expected to be able to enter negative values with the keyboard

**Actual behavior:**

When the minus (-) or plus (+) signs lead the value, they do not appear when typed in the value field. 

**Visual Proof:**

Screencast
![EnterNegThreshValue01](https://user-images.githubusercontent.com/25881301/145222561-338818d3-f6e5-4623-8be6-45cf7450b1ec.gif)

**Work Around**
Use the value arrows.  Or type the value and then return to the head of the field and then type the minus or plus character. 

## About your environment

**Environment info:**

Testing against latest remocal on Ubuntu 20.04. 

Last commit 
```
commit e551c111dc941bbb7fe1554cf5b9d387ea771325 (HEAD -> master, upstream/master, origin/master, origin/HEAD, cypress/check-config)
Author: karel-rehor <karel-rehor@users.noreply.github.com>
Date:   Tue Dec 7 09:41:44 2021 +0100
```

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by kristinarobinson** [comment]
@karel-rehor - at present, negative values for threshold have not been implemented and will NOT work.  This would have to be a feature request.

**Comment by karel-rehor** [comment]
@kristinarobinson 
I'm not sure what you mean when you say that "negative values for threshold have not been implemented". 
I've created a test data set with negative values, and defined a threshold alert using them.  The alerts seem to be triggered correctly. 

LP Data Set:
```
zed,foo=bar mag=50,dur=60 1641822054085
zed,foo=bar mag=19.8,dur=45 1641822114085
zed,foo=bar mag=7.9,dur=30 1641822174085
zed,foo=bar mag=3.15,dur=18 1641822234085
zed,foo=bar mag=1.26,dur=12 1641822294085
zed,foo=bar mag=0.5,dur=9 1641822354085
zed,foo=bar mag=0.398,dur=6 1641822414085
zed,foo=bar mag=0.158,dur=4 1641822474085
zed,foo=bar mag=0.0631,dur=3 1641822534085
zed,foo=bar mag=-0.61,dur=2 1641822594085
zed,foo=bar mag=-1.72,dur=3 1641822654085
zed,foo=bar mag=-2.28,dur=5 1641822714085
zed,foo=bar mag=-3.25,dur=8 1641822774085
zed,foo=bar mag=-3.6,dur=13 1641822834085
zed,foo=bar mag=-4.34,dur=21 1641822894085
zed,foo=bar mag=-2.76,dur=34 1641822954085
zed,foo=bar mag=-0.88,dur=55 1641823014085
zed,foo=bar mag=-0.094,dur=89 1641823074085
zed,foo=bar mag=1.25,dur=59 1641823134085
zed,foo=bar mag=6.06,dur=39 1641823194085
```
Alert: 
```json
{
  "id":"08bd0d5d28b05000",
  "name":"Negative vals",
  "ownerID":"08bd039a6ff66000",
  "orgID":"c827c1f591a3a4d7",
  "query":{
    "text":"from(bucket: \"devbucket\")\n  |\u003e range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |\u003e filter(fn: (r) =\u003e r[\"_measurement\"] == \"zed\")\n  |\u003e filter(fn: (r) =\u003e r[\"_field\"] == \"mag\")\n  |\u003e aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |\u003e yield(name: \"mean\")",
    "editMode":"builder",
    "name":"",
    "builderConfig":{
      "buckets":["devbucket"],
      "tags":[
        {"key":"_measurement","values":["zed"],"aggregateFunctionType":"filter"},
        {"key":"_field","values":["mag"],"aggregateFunctionType":"filter"},
        {"key":"foo","values":[],"aggregateFunctionType":"filter"}
      ],
      "functions":[
        {"name":"mean"}
      ],
      "aggregateWindow":{
        "period":"1m",
        "fillValues":false
      }
    }
  },
  "taskID":"08bd0d5d2c428000",
  "statusMessageTemplate":"Check: ${ r._check_name } is: ${ r._level }",
  "every":"1m",
  "offset":"0s",
  "tags":[],
  "createdAt":"2022-01-10T13:40:32.034661037Z",
  "updatedAt":"2022-01-10T13:40:32.034661037Z",
  "thresholds":[
    {"allValues":false,"level":"CRIT","value":-2.17,"type":"lesser"},
    {"allValues":false,"level":"WARN","value":-0.1,"type":"lesser"},
    {"allValues":false,"level":"INFO","value":1,"type":"lesser"},
    {"allValues":false,"level":"OK","value":1,"type":"greater"}
  ],
  "type":"threshold",
  "labels":[],
  "links":{
    "self":"/api/v2/checks/08bd0d5d28b05000",
    "labels":"/api/v2/checks/08bd0d5d28b05000/labels",
    "members":"/api/v2/checks/08bd0d5d28b05000/members",
    "owners":"/api/v2/checks/08bd0d5d28b05000/owners",
    "query":"/api/v2/checks/08bd0d5d28b05000/query"
  },
  "status":"active",
  "latestCompleted":"2022-01-10T13:43:00Z",
  "latestScheduled":"2022-01-10T13:43:00Z",
  "lastRunStatus":"success",
  "taskID":"08bd0d5d2c428000"
}
```

Alert History: 
![StatusesFromThresholdWithNeg01](https://user-images.githubusercontent.com/25881301/148780177-35a1717b-18ae-4f95-9d07-9f74ad69e006.png)

I can set negative values using the arrow buttons in the control.  

The issue is that I cannot enter a value in the control manually, when it is signed, e.g. -1.01, -2.72.  That is when the minus sign is typed first.  I can however enter the magnitude, move the cursor to the head of the control and then add the minus sign.  The keystroke sequence would then be e.g. {'2','.','7','2',[HOME],'-'}.  However it should naturally be e.g. {'-','2','.','7','2'}
