### ISSUE TITLE
Check Threshold Definitions - threshold value of '0' disappears when opening threshold for edit 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/ui#3407]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Generate some test data
2. Create a Threshold Check
3. In the thresholds group select the logic "Is inside range" and set values to 0.0 and 99.99
4. Save the check
5. Open the check again for editing

**Expected behavior:**

Expected values defined in step 3 to be loaded by default into the value fields

**Actual behavior:**

The zero value "0.0" is not loaded.

Note that other values e.g. "3.14" or "-2.72" load correctly. 

**Visual Proof:**

![ZeroValueThreshold01](https://user-images.githubusercontent.com/25881301/145398525-35f156e3-5e12-4e26-b2e6-75e90687d0ea.gif)

## About your environment

**Environment info:**

Testing against latest remocal.  

Last commit in UI project. 

```
commit e551c111dc941bbb7fe1554cf5b9d387ea771325 (HEAD -> cypress/check-config, upstream/master, origin/master, origin/HEAD, master)
Author: karel-rehor <karel-rehor@users.noreply.github.com>
Date:   Tue Dec 7 09:41:44 2021 +0100

```

**Config:**

**Logs:**

**Comment by karel-rehor** [comment]
I noticed when inspecting the response body of the PUT call to `/api/v2/checks` that the 'range' threshold contains no `min` value after it was set to '0' 
```
   "thresholds":
       [
           {"allValues":false,"level":"CRIT","value":15.03155,"type":"greater"},
           {"allValues":false,"level":"INFO","max":7.28,"within":true,"type":"range"},
           {"allValues":false,"level":"WARN","value":7.28,"type":"greater"}
       ],
```
Compare this to when a positive value was used 
```
"thresholds":
   [
      {"allValues":false,"level":"CRIT","min":0.5,"max":100.1,"within":true,"type":"range"}
   ]
```

**Comment by jzahnd** [comment]
It is possible that this is an API issue vs a UI issue, we should investigate.
