### ISSUE TITLE
Remove errant capitalization in API token creation message

### ISSUE THREAD

**Issue by nanderson6** [influxdata/ui#3417]
The "s" in "Successfully" should not be capitalized here.
Caught by Tim Hall when reviewing an upcoming blog post.
See attached screenshot in comment.

**Comment by nanderson6** [comment]
![Screen Shot 2021-12-07 at 4.14.03 PM.png](https://images.zenhubusercontent.com/60e78f93b32c481855a0db36/89d74aaf-d236-44f9-be0f-cf878968ad35)

**Comment by barbaranelson** [comment]
Also, the text shouldn't say cloned.  I see this text even if I don't clone a token, and just create a new token.  Please change it to "You've successfully created an API token"

**Comment by blegesse-git** [comment]
@barbaranelson what if we set the text to read "You've successfully created an API token" when user creates a token, and have the text read "You've successfully cloned an API token" when token is cloned? I think having it say "...successfully created a token" when user is only cloning it can be a bit confusing.

**Comment by barbaranelson** [comment]
Yes, I'm fine with that if we can distinguish cloning a token. from creating a new one. I filed the issue because when I created a new token, it said I had successfully cloned a token (which I hadn't).  What you have in the video looks great. Thanks.
