### ISSUE TITLE
Demo Data / Sample Data Removal Followup

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#3421]
1. Remove dead code in UI
2. Remove from docs
3. Remove from IDPE
4. Follow up with teams on last cleanup

**Comment by jzahnd** [comment]
Jessica to check if Tyson in deployments is working on this

**Comment by gaughen** [comment]
Just fyi @tysonkamp has been working on this issue - https://github.com/influxdata/k8s-idpe/issues/5509. He merged the changes today.

**Comment by jzahnd** [comment]
Follow up work will need to be done again logic around bucket list in Flux queries and determining the org. @jzahnd to create a follow up issue.

**Comment by jzahnd** [comment]
This issue has been completed
