### ISSUE TITLE
Query builder (in notebook and data explorer) limits measurements to the first 200

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3432]
In the query builder in data explorer and in notebooks, we limit the number of measurements to the first 200. This is a usability problem for buckets that have more than 200 measurements (e.g. the apps bucket in tools).

We need to enable users to see all the measurement names in the time range they have selected.

For reference: 
https://github.com/influxdata/ui/blob/master/src/flows/pipes/QueryBuilder/context.tsx#L25
https://github.com/influxdata/ui/blob/master/src/timeMachine/apis/queryBuilder.ts#L19

**Comment by jrenee42** [comment]
two issues:
1) how many items to get from the server?
2) use lazy-loading for the ui itself?

```
  const query = `import "regexp"
  
  from(bucket: "${bucket}")
  |> range(${timeRangeArguments})
  |> filter(fn: ${tagFilters})
  |> keep(columns: ["${key}"])
  |> group()
  |> distinct(column: "${key}")${searchFilter}
  |> limit(n: ${limit})
  |> sort()`
```

**Comment by barbaranelson** [comment]
This also came in as an EAR: https://github.com/influxdata/EAR/issues/2933

**Comment by kristinarobinson** [comment]
please increase to 500
