### ISSUE TITLE
notebooks: Query builder is missing some of the buckets

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3441]
In tools, there is a bucket called resource_log. If I create a new notebook, starting with the query builder, resource_log isn't listed as an available bucket. It's not in the list of buckets and if I search for it, it's not found.

It looks like notebooks is only fetching 100 buckets.  There are 139 buckets in tools.

resource_log does show up as an available bucket in the data explorer, and in the buckets list page.

**Comment by jzahnd** [comment]
This id done, closing
