### ISSUE TITLE
Help Bar (Phase 2): Update the SFDC Ticket with more user information

### ISSUE THREAD

**Issue by Palakp41** [influxdata/ui#3455]
- Display a spinner while SFDC api is being called after Contact Support form is submitted.
- Update SFDC Ticket with the following information:
       - Browser type and version (if available),
       - console.log errors (if any),
       - most recently visited area (from context),
       - org id / IDPE ID (mona's team working on adding this as a field in sfdc, however, IDPE ID will be deprecated by engineering soon)
       - org name;
       - account name,
       - user id (different from user name which is an email address),
       - account id,
       - region (mona's team working on adding this as a field in sfdc)

#### Fields that should be hardcoded server-side
  - [x] Case Origin - value: `Cloud App`
  - [x] Group - value: `Support Tier 1`
  - Case Owner - Queues - value: `Support Tier 1 Queue`
  - [x] Status - value: `New`
  - [x] Priority - value: `Priority 3`
  - [x] Deployment Type - value: `InfluxCloud2.0`

#### Fields that the user fills in
  - [x] Subject
  - [x] Description
  - [x] Severity

**Comment by Luckette** [comment]
Help needed getting case number returned

**Comment by hoorayimhelping** [comment]
See: https://github.com/influxdata/EAR/issues/3322
