### ISSUE TITLE
limit Lead to collapse

### ISSUE THREAD

**Issue by shijiaxun** [influxdata/ui#3484]
1.execute flux 

from(bucket: "test")
  .....
  |> limit(n:15, offset: 1)

  If I set limit.offset to be less than.
  For example:  limit(n:15, offset: -1)
this system will collapse

**Comment by barbaranelson** [comment]
@shijiaxun can you tell us more about where you are running this, and what you mean by "the system will collapse". Is this the open source version or our cloud version? I tried to reproduce the issue in our cloud version, and we return an error message "unexpected EOF" if the offset is negative.

**Comment by kristinarobinson** [comment]
Closing due to lack of response.
