### ISSUE TITLE
Error returning schema.measurementTagValues()

### ISSUE THREAD

**Issue by samhld** [influxdata/ui#3485]
Version: 2.1.1 
More specifically:
```InfluxDB dev (git: f78c189211) build_date: 2021-12-21T03:39:33Z```

Logs:
There were no logs from the instance for any of the queries, successful or not.  Separate issue perhaps?

____________

[Update] Same with `schema.tagValues()`

Running the query yields this error:

![Screen Shot 2021-12-20 at 7 35 07 PM](https://user-images.githubusercontent.com/4852912/146866673-01fc36e9-ceaa-404f-baa2-d0137cc5bc74.png)

I verified data existed in that time window immediately afterward:

![Screen Shot 2021-12-20 at 7 30 38 PM](https://user-images.githubusercontent.com/4852912/146866548-7d279301-f74b-487c-9f14-4e21209876d1.png)

`tag1` is also an existing Tag:

![Screen Shot 2021-12-20 at 7 36 30 PM](https://user-images.githubusercontent.com/4852912/146866817-4786c7fd-3d37-47b7-a981-0059d36cc2c7.png)

**Comment by appletreeisyellow** [comment]
This should be fixed in Cloud 2 and InfluxDB v2.6.0+

Here is a Cloud 2 visual proof:

https://user-images.githubusercontent.com/14298407/222839212-755304fd-53eb-4687-8412-61dc579f4665.mov
