### ISSUE TITLE
feat: add ability to activate/deactivate a task from the task view (runs) page

### ISSUE THREAD

**Issue by glinton** [influxdata/ui#3488]
**Proposal:**
Add the ability to activate/deactivate a task from the task view (runs (`/orgs/orgID/tasks/taskID/runs`)) page.

**Current behavior:**
There is no way to activate/deactivate a task from the view page:
![image](https://user-images.githubusercontent.com/2653109/146991401-6ca72c32-eb9f-43d9-b83f-2631ea7b790c.png)

Only from the list page:
![image](https://user-images.githubusercontent.com/2653109/146990636-c3a61915-487f-49ed-bfb1-c1f8fd8b5994.png)
![image](https://user-images.githubusercontent.com/2653109/146991446-37dbad65-32f9-4e1e-97ff-4084cda84120.png)

**Desired behavior:**
The ability to activate/deactivate a task from the task view (runs) page.

**Use case:**
When viewing a task, it'd be great to not need to go back to the task list, search for my task, then activate/deactivate it before returning to the task view.

**Comment by kristinarobinson** [comment]
Moving to Bulk Actions epic.

**Comment by kristinarobinson** [comment]
Fixed.
