### ISSUE TITLE
Tech Debt: Swap out internal Clockface components with @influxdata/clockface

### ISSUE THREAD

**Issue by asalem1** [influxdata/ui#3492]
In order to reduce some drift in styling and within our codebase, we should consolidate and replace any lingering clockface components that exist within the UI repo to `@influxdata/clockface`. 

### Why is the current structure a problem?

As it stands, we are using internal clockface components for part of the UI when we could potentially swap that out to our own internal library that's currently maintained. The issues that surround the current setup is potential code drift, styling differences, and a bloated codebase where we maintain similar code in two different places

### How to remediate the issue

We should audit the `src/clockface` components to see what needs to be ported over to the `@influxdata/clockface` library, then slowly deprecate / delete the existing components within `src/clockface` and replace their usages with ones in the `@influxdata/clockface` library.

### Definition of Done

Being able to delete the `src/clockface` components without having any issues in the UI

**Comment by Luckette** [comment]
@brandenTenbrink and @wdoconnell - This is a good opportunity to clean up where components should be in clockface.

**Comment by TCL735** [comment]
Not really a "good first issue" as newcomers were hesitant to move files around. 😀
