### ISSUE TITLE
not able to login all of a sudden

### ISSUE THREAD

**Issue by HimanshuRupeek** [influxdata/ui#3498]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. ...
2. ...
3. ...

**Expected behavior:**

**Actual behavior:**

**Visual Proof:**

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by kristinarobinson** [comment]
@HimanshuRupeek -- are you still unable to login?  can you tell me which region and service provider (AWS, GCP, or Azure)?

**Comment by nikswyftx** [comment]
hello, i am having a simmilar issue, i deleted a user who had not accepted an invite and then invited them again, they now get a 500 error when they login

**Comment by asalem1** [comment]
Thanks for reporting this @nikswyftx! The fix should be deployed. Please let us know if this is still an issue and we can open up a support case for you to get this all sorted
