### ISSUE TITLE
InfluxDB Cloud: number format

### ISSUE THREAD

**Issue by sauvant** [influxdata/ui#3519]
The number format in the UI is broken in my instance of InfluxDB Cloud. A "Single Stat"cell for instance shows the following value:

111.474.245.00

The thousands separator is german style. Fine with me. But the decimal separator should be a "," instead of the ".".
Am I missing something?

Best,
Keith

**Comment by kristinarobinson** [comment]
@sauvant- I'm sorry you're having this issue.  I cannot reproduce this issue.  What browser are you using?

**Comment by sauvant** [comment]
Happens in Chrome (v97.0.4692.71):
![grafik](https://user-images.githubusercontent.com/41591972/149126754-09b75c1f-1c29-4731-8044-a8dff863e4dd.png)
as well as Firefox (91.5.0esr):
![grafik](https://user-images.githubusercontent.com/41591972/149127029-7ad1ed11-6dfc-4e9e-9e31-a89547013722.png)

**Comment by TCL735** [comment]
@sauvant this is now fixed and you should see the correct number format for your locale.
