### ISSUE TITLE
Python Generator Write Options Don't Work on Paste because they lack tabs

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/ui#3523]
In the Python code generator, the first batch of code uses a ```with``` construct to scope the resources for a write operation. 

However, the following code blocks are not indented so do not actually work when pasted.

By default you get:
```python
from datetime import datetime

from influxdb_client import InfluxDBClient, Point, WritePrecision
from influxdb_client.client.write_api import SYNCHRONOUS

# You can generate an API token from the "API Tokens Tab" in the UI
token = "zDfcaZVAp3xMwI0hqlHwrEO4wfZzW8q5oHmX-qV9T3gsjVlEyPCHMTwMJTxlom5T9pvJ9wDmaQyMZi9xdSFnVg=="
org = "rick+book@influxdata.com"
bucket = "rick+book's Bucket"

with InfluxDBClient(url="https://eastus-1.azure.cloud2.influxdata.com", token=token, org=org) as client:
write_api = client.write_api(write_options=SYNCHRONOUS)

data = "mem,host=host1 used_percent=23.43234543"
write_api.write(bucket, org, data)

```
which obviously won't work because the last 3 lines are not indented. If you are using a python shell, you have to copy each line individually.

**Comment by wiedld** [comment]
I believe you mean the code samples page, where you are asking for all the sections following the initialization, to be pre-indented for python.

meaning this:
<img width="1330" alt="Screen Shot 2022-02-02 at 10 58 24 AM" src="https://user-images.githubusercontent.com/10232835/152219834-05786959-3ab3-42ec-a253-6889e07f8fc9.png">

Specifically, the following sections indented:
- Write Data. all options (1-3)
- Execute a flux query
- Dispose the client.

Is this correct?

**Comment by wiedld** [comment]
updated. tested with python shell. straight copy/paste works.
<img width="794" alt="Screen Shot 2022-02-02 at 12 14 40 PM" src="https://user-images.githubusercontent.com/10232835/152230186-3af32cc1-a880-4334-ad73-f853151c3314.png">
