### ISSUE TITLE
Python Code generator, Query Code Not indented properly, incomplete

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/ui#3524]
It appears that the query code is meant to be scoped with a ```with``` construct, but the ```with``` is not included, and also the ensuing code is not indented. This is the code that works:

```python
with InfluxDBClient(url="https://eastus-1.azure.cloud2.influxdata.com", token=token, org=org) as client:
...     query = 'from(bucket: "rick+book\'s Bucket") |> range(start: -1h)'
...     tables = client.query_api().query(query, org=org)
...     for table in tables:
...             for record in table.records:
...                     print(record)
```

but this is the code that is provided:

```python
query = 'from(bucket: "rick+book's Bucket") |> range(start: -1h)'
tables = client.query_api().query(query, org=org)
for table in tables:
    for record in table.records:
        print(record)
```

(note also the lack of escaping mentioned in #3522 )

**Comment by wiedld** [comment]
@rickspencer3  I could not reproduce this issue.

- I assume this is the "export to client" from the notebooks.
- The only way this could (hypothetically) happen would be if we were missing templates for both the `def.initialize` and `def.executeFull`. (Meaning, the bundled code sent to the UI frontend was incomplete.)
- could you tell me exactly how it happened?
