### ISSUE TITLE
notebooks: Message "notebook run successful" can be misleading

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3525]
Let's remove the notification "Notebook Run Successful"

## Context

I have a notebook with a basic query builder, and visualization panel. Every time that I change the time selection in the upper right hand side of the notebook (e.g. from 12 hours to 7 days) I get a pop up in the corner saying "notebook run successful" but the notebook has not re-run with the changed time. I need to explicitly hit 'run' to make it run with the new time.

(As a solution, I would be fine if we just got rid of this message altogether, because it can be confusing - e.g. it says the notebook run was successful, even if there is a problem in your flux).

**Comment by barbaranelson** [comment]
Figured out it was actually a different problem : https://github.com/influxdata/ui/issues/3526 but keeping this one open because I have found the message to be misleading.

**Comment by jzahnd** [comment]
I agree with removing the notification. The interaction with the button is enough to indicate the notebook has run. Unless there is an easy way (I don't think there is) to only show the notification if there aren't any errors, it's pretty confusing.
