### ISSUE TITLE
notebooks: When change time range, query runs with old time range not new one.

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3526]
With a basic notebook with a query builder and a visualization, every time I change the time range, the notebook refreshes with the time previously selected - e..g used to be 24 hours, change it to 3 hours, will run with 24 hours.  Then change to 7 days, will run with 3 hours. 

(I actually thought it didn't rerun the query, and filed another issue to capture that, but the problem is that it runs it with the wrong time range.)

**Comment by jzahnd** [comment]
I was able to reproduce this in production as of this morning, 1/10.
