### ISSUE TITLE
Add Autorefresh for Notebooks

### ISSUE THREAD

**Issue by asalem1** [influxdata/ui#3532]
As notebooks starts to gain traction as the main part of our application, we want to expand the existing functionality so that transitioning from other parts of the app won't mean sacrificing out on features. In addition, with the current work that's being done for error threshold triggering on the UI, we're going to need a way to run queries in the background (without a task) for individuals who want to present live data in presentation mode over large screens. We should use the existing design and infrastructure to expand the existing auto refresh capabilities into notebooks.

Current Autorefresh Design:
<img width="1919" alt="Screen Shot 2021-12-02 at 12 16 1" src="https://user-images.githubusercontent.com/81173353/148816025-6a00e1af-14fb-412d-9998-b35bbeb17889.png">
<img width="603" alt="Screen Shot 2021-12-02 at 12 17 1 (2)" src="https://user-images.githubusercontent.com/81173353/148816027-56c4e88e-dbd1-4a77-b59f-044a3b17f9d4.png">

New Autorefresh Design:
[Figma](https://www.figma.com/file/qP1atZtFp9axPu8BRYuvQk/Dashboards-Enable-Autorefresh?node-id=0%3A1)
<img width="1920" alt="Autorefresh _ Indefinite" src="https://user-images.githubusercontent.com/81173353/148815921-eb76ed9d-d9f3-462e-9662-e0077ae37e14.png">
![Autorefresh _ Custom (1)](https://user-images.githubusercontent.com/81173353/148815928-7df1a3da-fcf2-44b8-8814-769567d76ad4.png)

**Comment by jzahnd** [comment]
We need to decide where we would like to have the autorefresh button/functionality triggered. Current suggestions are via the updated dropdown or as a button outside of the dropdown. @bpalani any thoughts?
