### ISSUE TITLE
firstMile: Client library - Add instructions for python3

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3573]
When you select Load Data/Client Libraries/Python, the instructions are only for python 2. We should update the text to cover python 3.

**Comment by kristinarobinson** [comment]
@willpiers - Can you doublecheck that your onboarding verbiage includes instructions for loading py3, in addition to the existing py v2?

**Comment by Luckette** [comment]
This has been implemented in the firstMile Python Wizard
