### ISSUE TITLE
Flux Dynamic Help Panels: add property to the FluxDocs schema  

### ISSUE THREAD

**Issue by blegesse-git** [influxdata/ui#3584]
In order to keep the UI's script editor functionality of injecting flux functions, in fluxdocs, we need a property with the flux function's example value.
Below is a response we would expect from fluxdocs api call. Currently, the 'example' property doesn't exist. Therefore, it needs to be added to the api
<img width="544" alt="Screen Shot 2022-01-13 at 2 13 55 PM" src="https://user-images.githubusercontent.com/66275100/149402472-29862ada-5230-479d-bef7-efa0b8ca6ff8.png">

**Comment by TCL735** [comment]
Closing this in favor of https://github.com/influxdata/ui/issues/3638
