### ISSUE TITLE
Simple table cell view error

### ISSUE THREAD

**Issue by Dfldr** [influxdata/ui#3606]
## About the bug

**Steps to reproduce:**

1. Create a dashboard with a cell
2. Select data
3. After rendering the view of the data in a cell, change the view to "simple table"

**Expected behavior:**
I expected the data to be listed in a simple table. Same behavior as the normal table cell view

**Actual behavior:**
The cell fails to update (failed to update cell notification appears). The only thing appearing is an empty cell.

**Visual Proof:**
![cellView1](https://user-images.githubusercontent.com/88332140/149738909-a98b6200-141f-46ce-80e0-382d25ba18a2.png)
![cellView2](https://user-images.githubusercontent.com/88332140/149738917-f9083c46-70ab-40c2-b63d-da5725b20693.png)
![cellView3](https://user-images.githubusercontent.com/88332140/149738919-cda2924f-07ca-4078-88cb-bb6e076cdce8.png)
![cellView4](https://user-images.githubusercontent.com/88332140/149738923-3b6f8652-dd76-42d4-bca6-78b204c61578.png)
![consoleError](https://user-images.githubusercontent.com/88332140/149738925-d190ba43-3118-482c-b645-73fc663ab8de.png)
![networkError1](https://user-images.githubusercontent.com/88332140/149738926-44aec333-7348-4691-b10e-43e9b85b2771.png)
![networkError2](https://user-images.githubusercontent.com/88332140/149738928-a5f24a35-2e35-47b9-9134-85c126157ee4.png)

## About your environment
**Environment info:**
- System info: Linux 5.11.0-46-generic x86_64
- InfluxDB version: influxdb:2.1.1

**Comment by kristinarobinson** [comment]
@Dfldr - can you confirm that you are using the Open Source version of our product, and not the Cloud version?  thanks!

**Comment by Dfldr** [comment]
I am wokring with remocal/K8s-IDPE on UI project, sorry for leaving that out in enviroment info. I will add git log information about last K8s repo commit.
commit 08e9ee1cfad9f9eaee5543e62becc7e8e57c1b58 (HEAD -> master, origin/master, origin/HEAD)
Author: Wojciech Kocjan <wkocjan@influxdata.com>
Date:   Thu Jan 20 11:55:56 2022 +0100

**Comment by hoorayimhelping** [comment]
Related: #3625
