### ISSUE TITLE
Investigate e2e flakiness

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#361]
Sean and Timmy have noted flakiness in e2e tests recently.

### Tests to investigate:
- `shared/explorer.test.ts`
- `shared/checks.test.ts`
- `shared/labels.test.ts`
- `shared/tokens.test.ts`

Failures from Sean's runs:
- https://app.circleci.com/pipelines/github/influxdata/ui/1210/workflows/cf676dfa-1417-43b8-bd76-7edf7b9bcc6f/jobs/5877/parallel-runs/4/steps/4-107?invite=true
- https://app.circleci.com/pipelines/github/influxdata/ui/1203/workflows/0c52152d-af8d-41f0-906b-f946a0ecf329/jobs/5802/parallel-runs/1/steps/1-108?invite=true

Failures from Timmy's runs:
- https://app.circleci.com/pipelines/github/influxdata/ui/1205/workflows/4fc8e7aa-8c59-49d7-93a3-a7990f053f2d/jobs/5819/parallel-runs/6/steps/6-108?invite=true

**Comment by TCL735** [comment]
Mine failed on labels and tokens. Re-run cleared them up.

https://app.circleci.com/pipelines/github/influxdata/ui/1205/workflows/4fc8e7aa-8c59-49d7-93a3-a7990f053f2d/jobs/5819
