### ISSUE TITLE
Add host name and URL to the about page

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3619]
We are about to introduce a second US-West region, and we need a way for a user to get the URL to their cloud instance. In the past, we expected people to figure it out from the documentation, but with two US-west regions with very similar names that is going to be harder. It would be useful if the about page would show the name and the URL to your region (in addition to the user id and org id that it currently shows).

**Comment by tkyocum** [comment]
xref: https://github.com/influxdata/idpe/issues/12450

**Comment by rbetts** [comment]
It would be ideal to provide this along with the other information needed to create a CLI configuration in a single place in the UI (and perhaps provide a download cli-config option).  This might be a nice thing to link to token creation, as well, since the token needs to be available and added to the configuration. Please see:

https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/config/create/#create-a-connection-configuration-and-set-it-active

This request was raised as feedback in a recent early-user usability review.

**Comment by barbaranelson** [comment]
For context, here's what the docs will look like: https://github.com/influxdata/docs-v2/pull/3693. You can also look at the status page (status.influxdata.com). The user needs to know if they are on us-west-2-1 or us-west-2-2.

**Comment by jzahnd** [comment]
The endpoint work is complete:

- Openapi spec: https://github.com/influxdata/openapi/pull/260
- Issue with updates and response shape: https://github.com/influxdata/openapi/pull/260

**Comment by juliajames12** [comment]
Here is an updated About page design with the new fields. Please let me know if there need to be any updates! 
https://www.figma.com/file/xNp4pU1J6vXXjAV7ZuUKig/Provider-Info-in-About-Page?node-id=2%3A
<img width="1440" alt="About Page" src="https://user-images.githubusercontent.com/81173353/150229307-e16b47e7-f949-43da-9862-a981cf58c929.png">
4

**Comment by tkyocum** [comment]
I feel like the organization url should include just the url to send data
to or log in, not the org or anything else since that data is already on
the same page.

This looks really clean and will be super helpful!
-- 

- Tim

**Comment by barbaranelson** [comment]
That works for me. Let's change the URL so it is only https://us-west-2-1.aws.cloud2.influxdata.com and not include the /org piece.

**Comment by juliajames12** [comment]
Great! Just updated the design to match [here](https://www.figma.com/file/xNp4pU1J6vXXjAV7ZuUKig/Provider-Info-in-About-Page?node-id=2%3A4). That change makes it possible to use the same width for all of the copy boxes.

<img width="1440" alt="About Page (1)" src="https://user-images.githubusercontent.com/81173353/150243281-3d079988-65fe-458d-9f6d-2cc96281f889.png">

**Comment by bpalani** [comment]
@juliajames12 we should change that `Organization URL` to `Cluster URL` or `Host` (since we use host in CLI commands)? Organization url seems indicate the one with their orgid.

**Comment by barbaranelson** [comment]
Cluster URL is consistent with the docs. I would prefer that to Host.

**Comment by juliajames12** [comment]
Just updated the design to show "Cluster URL" instead of "Organization URL" :) 

https://www.figma.com/file/xNp4pU1J6vXXjAV7ZuUKig/Provider-Info-in-About-Page?node-id=2%3A4
