### ISSUE TITLE
TypeError in console after pressing a button

### ISSUE THREAD

**Issue by k3yi0** [influxdata/ui#3626]
## About the bug

**Steps to reproduce:**

1. Create a dashboard with cell
2. Create a new bucket
3. Select Advanced Configuration, then "explicit" bucket schema option. Press "add new measurement schema" button

**Expected behavior:**
To create new input field for schema name and drag&drop area to upload explicit schema.

**Actual behavior:**
It behaves as it is supposed to. The issue is uncaught type error that happens after pressing the button.
The same error happens after pressing dismiss button for new explicit schema.

**Visual Proof:**
![BeforeTypeError](https://user-images.githubusercontent.com/97002262/150128455-e6cd1ff2-8deb-4dea-a835-5bfcde03704f.png)

![AfterTypeError](https://user-images.githubusercontent.com/97002262/150128468-514dee8c-02c2-4910-9d1f-1b0b5713a6bd.png)

## About your environment

**Environment info:**

Linux 5.11.0-44-generic x86_64
Influx CLI 2.2.1 (git: 31ac783) build_date: 2021-11-09T21:24:22Z

**Comment by kristinarobinson** [comment]
Dumplings team, lets take a look to see if this is also happening in Cloud version.  If it's not, please reassign to team/edge.

**Comment by hoorayimhelping** [comment]
Confirmed this happened in my local setup and on our tools setup. It's indeed a cloud bug.
