### ISSUE TITLE
Alerts: HTTP Notification endpoint still sending notifications after deactivation 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/ui#3630]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. In AWS setup a simple express HTTP listener (example below)

In Influxdb UI

1. Add some test datapoints to a bucket with some timestamps going into the future for at least several minutes
2. Create a Threshold check that will trigger a Crit status based on the datapoints
3. Create an HTTP Notification Endpoint directed to the listener in AWS 
4. Create a notification rule, that binds together the check and the endpoint
5. Wait to verify 
   5.1. in AWS console that notifications are received by the listener 
   5.2 and in the UI that they are part of the notification history
6. In Influxdb UI deactivate the Notification Endpoint 
7. Add some more test datapoints with timestamps in the future that will trigger a Critical status notification 
8. Wait for ten minutes or for the next scheduled run of the Notification Rule

**Expected behavior:**

Expected the deactivated endpoint to stop sending notifications.  

**Actual behavior:**

After roughly ten minutes (default scheduler) notifications are appearing in the console of the AWS listener.
When then checking the notification history, these post-deactivation notifications are listed. 

**Visual Proof:**

## About your environment

**Environment info:**

Testing against K8S-IDPE remocal with up to date copy of UI project 

Latest commit in UI 
```
commit 019ec01d3ca48826c02777043ddd76cb47ac7416 
Author: karel-rehor <karel-rehor@users.noreply.github.com>
Date:   Wed Jan 19 10:13:01 2022 +0100
```

Latest commit in K8S-IDPE
```
commit ead1db508e2afa1c713e3872b6419b3e8c771be7 
Author: Hercules Mango Churchill <alchemy@influxdata.com>
Date:   Wed Jan 19 09:08:24 2022 +0000

```

**Config:**

**Logs:**

### Additional artifacts

*Simple Express listener*
Deployed on AWS EC2 Micro
```javascript
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.post('/', (req,res) => {
        console.log('POST')

        let body = ''

        req.on('data', (data) => {

                console.log(`DATA: ${data}`)
                body += data
        })

        req.on('end', () => {
                res.writeHead(200, {'Content-Type': 'text'})
                res.end(`received: \n ${body} \n`)
        })

//      res.send('POST received\n')
})

app.listen(port, '0.0.0.0', () => {
  console.log(`Example app listening at http://0.0.0.0:${port}`)
})

```
*Simple project for listener*
```json 
{
  "name": "app",
  "version": "0.0.1",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "anon",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.1"
  }
}

```

**Comment by jzahnd** [comment]
Let's validate this and kick over to idpe if we can reproduce.

**Comment by wiedld** [comment]
Reproduced.
1. AlertCheck made 12:20 pacific.

2. alert notifications received 12:32 to 13:32 pacific.

3. Notification Endpoint set to “inactive” at 13:34 pacific.
<img width="1516" alt="Screen Shot 2022-02-08 at 2 43 24 PM" src="https://user-images.githubusercontent.com/10232835/153088050-a7752943-9b93-4709-8ea5-b25d3c3e7237.png">

4. Alerts continued to be received at endpoint:
<img width="671" alt="Screen Shot 2022-02-08 at 2 41 08 PM" src="https://user-images.githubusercontent.com/10232835/153088172-7d17e3fc-0e7d-4abc-b4fb-df9e019e968a.png">

**Comment by wiedld** [comment]
Closing ticket in UI, but creating this bug report in idpe.
