### ISSUE TITLE
Flux Dynamic Help Panels: transform function signature to example for injection

### ISSUE THREAD

**Issue by TCL735** [influxdata/ui#3638]
Currently, there is a feature that allows the user to select "inject" on a Flux function and have an example of that function inserted into the Script Editor. The example code is static and only exists for the limited set of functions found in the static documentation.

We want to have an example for any function found through the Fluxdocs service. The example function should rely on the `fluxType` property which is the function signature, to create an example function. Possibly, make use of the `name` property also.  Build this functionality to allow the inject feature to continue to work with the new Fluxdocs service.

We may need to change interfaces in the UI. This should only be done in the UI because changes to this feature are easier to maintain in the UI, as this is a UI feature.

- use existing properties in the interface such as `fluxType` and `name` to create the example code
- should not require storage
- may update or create UI specific interfaces

**Comment by Luckette** [comment]
@TCL735 reaching out to the flux team to request type gets added as a parameter. 

Until we get this 'type' parameter, this issue is blocked.
