### ISSUE TITLE
Remove the AutoRefreshDropdown Component

### ISSUE THREAD

**Issue by asalem1** [influxdata/ui#3647]
This is fairly straightforward housekeeping. It looks like we're still referencing the AutoRefreshDown component in certain parts of the app, but it's currently disabled in every context, instead being toggled by the new overlay for setting the auto refresh context. We should remove the component, in addition to all references to it from the codebase.

Files / lines to remove:

- [x] https://github.com/influxdata/ui/blob/master/src/shared/components/dropdown_auto_refresh/AutoRefreshDropdown.tsx
- [x] https://github.com/influxdata/ui/blob/master/src/shared/components/dropdown_auto_refresh/AutoRefreshDropdown.scss
- [x] https://github.com/influxdata/ui/blob/master/src/style/chronograf.scss#L42
- [x] https://github.com/influxdata/ui/blob/master/src/timeMachine/components/RefreshDropdown.tsx
- [x] https://github.com/influxdata/ui/blob/master/src/timeMachine/components/Queries.tsx#L70
- [x] https://github.com/influxdata/ui/blob/master/src/timeMachine/components/Queries.tsx#L10
- [x] https://github.com/influxdata/ui/blob/master/src/dashboards/components/DashboardHeader.tsx#L251-L256
- [x] https://github.com/influxdata/ui/blob/master/src/dashboards/components/DashboardHeader.tsx#L7

As part of this removal, we should see if there's any other code associated with the old dropdown that can be removed.

**Comment by AyushPathak3011** [comment]
Hello, is this issue open?

**Comment by asalem1** [comment]
@AyushPathak3011 yes it is
