### ISSUE TITLE
Unable to select text in data table in Safari

### ISSUE THREAD

**Issue by brettbuddin** [influxdata/ui#3650]
When I toggle "View Raw Data" in Explore and get the data table view, I'm unable to select any of the content in the table in Safari. After digging a bit more I discovered that this style is prohibiting me from doing so: https://github.com/influxdata/ui/blob/57744d0fc09c88cd9ae9c0a27135cc1e25d5d0bb/src/timeMachine/components/TimeMachine.scss#L6-L10

Here's the realized style as it's seen in my browser:

<img width="303" alt="Screen Shot 2022-01-20 at 11 23 08 AM" src="https://user-images.githubusercontent.com/6059/150379344-27240eeb-da80-4d50-9154-7c4341b71bd9.png">

When I disable this style, I'm able to select content in the table without issue.

**Comment by philjb** [comment]
previous case https://github.com/influxdata/ui/pull/450
