### ISSUE TITLE
Load Data: File upload instructions don't make sense

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3653]
For annotated CSV, there are two issues:
1. The text is so dark that it is really hard to see where you can upload the file. (see screenshot). I couldn't make out the line "Drop a file here or click to upload".
2. The instructions say to "select the bucket you want your data uploaded to and drag & drop your data into the dropzone below". I don't see where I can select the bucket, and the dropzone is above not below.
![Screen Shot 2022-01-20 at 11 33 27 AM](https://user-images.githubusercontent.com/13143006/150409960-b9e23286-58a7-47c3-b2de-c50b77746ff8.png)

For line protocol, the screen is easier to read but there is the same issue that I'm being told to select a bucket but not clear how I would do that (and the dropzone is above, not below).

**Comment by kristinarobinson** [comment]
I think this is a dupe?  I will look for the issue that I think we were going to fix this Sprint.
