### ISSUE TITLE
LoadData: CSV Data (CLI) should include link to download the CLI

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3654]
We provide lots of details on how you would pass data to the CLI, but no reference as to where to get the CLI.  We should point to the downloads page so that people know where to download influx.

**Comment by barbaranelson** [comment]
Can copy something similar to the Telegraf page.
![Screen Shot 2022-01-20 at 1 27 04 PM](https://user-images.githubusercontent.com/13143006/150424808-a6d3c9c9-59b5-4607-a4d4-85063335aabd.png)

**Comment by kristinarobinson** [comment]
Moving to Onboarding epic.
