### ISSUE TITLE
Epic: Eliminate clear-text tokens from UI

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3661]
For improved security, we don't want to show the clear-text of a token in the UI, once the user has generated the token and has had an opportunity to copy it to wherever they want to store it.

This epic summarizes areas in the UI where tokens are currently visible.

**Comment by barbaranelson** [comment]
https://github.com/influxdata/ui/issues/3656

**Comment by barbaranelson** [comment]
https://github.com/influxdata/ui/issues/3655

**Comment by barbaranelson** [comment]
CLI config - https://github.com/influxdata/ui/issues/3636

**Comment by barbaranelson** [comment]
Notebook sharing - https://github.com/influxdata/ui/issues/3283

**Comment by barbaranelson** [comment]
Some discussion here: https://github.com/influxdata/idpe/issues/12854

**Comment by kristinarobinson** [comment]
Epic completed.
