### ISSUE TITLE
Bug: Error while viewing token permissions

### ISSUE THREAD

**Issue by desarrolloEusk** [influxdata/ui#3666]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. ...
2. ...
3. ...

**Expected behavior:**

**Actual behavior:**

**Visual Proof:**

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by kristinarobinson** [comment]
@desarrolloEusk - 
Thank you for filing an issue.  In order to help, we need a few more things.

Can you tell us:
What happened when the error occurred?
How to reproduce it?
Are you using our Cloud or OSS product?  
What version?
What browser are you using?

Thanks for using InfluxDB.

**Comment by desarrolloEusk** [comment]
I was trying to set a Token that could have read permissions for all bucket and write permisions for only one bucket. It was apparently created, but when I tried to see the token description, the platform crashed. By the way, that token didn't worked, so I have to use an all read/write token.

**Comment by Palakp41** [comment]
I will fix this such that it will not break the UI terribly when viewing such tokens. Also, currently you can either create `all read, all write` to buckets token or `specific bucket read, specific bucket write` token. We will discuss more on how to implement the case when user wants to select `all bucket read, specific bucket write` token.

**Comment by kristinarobinson** [comment]
[Bug: Tokens: Accordion should not be collapsible](https://github.com/influxdata/ui/issues/3974) -- fixed with this bug fix.
