### ISSUE TITLE
Evaluate Amplitude for Measuring UI Features and Activity

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#3668]
## Background
We have been searching for a tool that will help us measure the effectiveness of our UI features and to gain further insights into user behavior in the UI. In addition, we would like session-level tracking that will allow us to follow specific users and organizations. 

The tooling that we have currently either doesn't offer session-level tracking or is hard to aggregate and analyze data from a visual perspective. After evaluating several providers, Amplitude floated up the top as offering both a great UI and robust measurement capabilities. 

## Goals
- Integrate Amplitude into the UI
- See data flowing into Amplitude
- Setup an initial list of graphs/dashboards that we will use for measuring activity in Notebooks
- Define a list of questions we would like to answer both in notebooks and the general UI
- Take a pass at answering the questions we define and offer our thoughts on how Amplitude faired as a tool in seeking those answers

Proposed Questions to Answer Via Amplitude: #3941

### Future UI Questions to Answer
- Could this be used to measure our new onboarding process?
  - Yes
- How often users are hitting the page that links to open a Git Issue? We would like to have information about the activity being performed at the time (this would likely be a stretch goal). 
  - We think we might be able to answer this already as what we want is the page that the error occurred on via Honeybadger. 
  - Do we want to know how many people clicked the button? It seems like that won't tell us much currently. We may want to look at this from where other flows may fall off after a release to identify issues.
- We would like to know how often a user aborts the switch back from script editor to visual builder after they have made flux modifications vs. how often they continue and go back to the Visual builder so that we have data to help decide if it is important to do any further work to reserve build the Visual builder to match flux changes.
  - Need to reword. 
  - Also would like more context on the goal of this measurement. 
  - Likely we can add this into the existing questions we will answer

### Future Notebooks Questions to Answer
 - We would like to know how often an alert is set up in notebooks, but not exported so that we know if this is causing confusion for them and needs to be refined.
   - What level of measurement should we focus on here...do they look at the alert, interact with it etc. 
 - We would like to know how often a user clicks on the notebooks navigation but then doesn’t create a new notebook or click on another notebook (they navigate back off of it) and be able to compare that with other navigation menu items (so we would need to do them all) to help determine if they know what to do after clicking on that navigation.
   - We need to break this into different items in the UI for this. 
-  We would like to know how often a user “exports to client library” and does a “copy to clipboard” vs. closes the window (are they observing or actually using this).

**Comment by barbaranelson** [comment]
A few more questions to answer:
Dumplings team (Bucky) would also like to use this as they develop the new onboarding screens, to see if they do in fact achieve the goal of making it easy to be write/query data in the first 5 minutes.

In Data explorer and in the notebook query builder panel, how many folks get away with the query builder, and how many need to use the script editor (this will help us understand how useful the query builder is, and how soon do people go beyond what it can do).

**Comment by wiedld** [comment]
done
