### ISSUE TITLE
Notebooks: Turn on Preview From Here in Production

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#3677]
We would like to turn on Preview From Here in Notebooks in Production. This functionality allows the user to preview a Notebook from a certain point, rather than running the entire notebook.

## Acceptance Criteria
- The Preview From Here flag is on for production
- We are able to run the Preview From Here functionality in Production
- Create a task for removing the flag in a month

**Comment by jzahnd** [comment]
This is already done, closing for now.

**Comment by asalem1** [comment]
Wait, @jzahnd  did we want to remove the feature flag?

**Comment by jzahnd** [comment]
Good catch @asalem1, we do indeed. I am creating a ticket for that now.
