### ISSUE TITLE
Disable auto-refresh for shared notebook anonymous users

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#3679]
**Story**

As an account holder, I want to prevent anonymous users that I have shared a notebook with from turning on auto-refresh so that I can prevent unexpected charges on my account from one of those users leaving auto-refresh turned on for extended periods of time.

**Acceptance Criteria**

*Given* that
  a notebook has been shared with me
*When* I
  I try to turn on auto-refresh
*Then*
   that auto-refresh option will not be available to me

**Notes and Background**

During Stand-up on 2022-01-20, Barbara Nelson expressed some concern over auto-refresh on shared notebooks because the person that the notebook is being shared with will not be the person paying the charges for the queries associated with that notebook, but the person sharing will be.

Balaji expressed a desire for this setting to be set by each individual, versus it getting set by the creator of the notebook and being inherited by the person it is shared with as a way to help mitigate this.

During the subsequent stand-up on 2022-01-21, there was still some concern expressed that even though it was being modified to be allowed to be changed by the user (vs. inherited from the creator), that the user could still turn on auto-refresh and then leave their computer running for several days, racking up cost.

Balaji and myself discussed this on 20-22-01-21 and decided that for now, the best thing to do would be to disable auto-refresh in these instances until we have more data to know how often this situation might occur and we know whether this auto-refresh capability will be a necessary capability for anonymous users.

@juliajames12 to help make call on whether to gray out the option or remove altogether (or alternative) for disabling this feature.

**Comment by asalem1** [comment]
I may be misunderstanding this, but sharing a notebook that has auto refresh enabled on it doesn't get saved onto the notebook, so sharing the notebook won't auto refresh the notebook that's shared. If that's the concern here then we should close this out. If it's not, what's the crux of the issue?

**Comment by garylfowler** [comment]
@asalem1 - Will the user that the notebook is shared with see the auto-refresh option and can they turn it on?

**Comment by asalem1** [comment]
> @asalem1 - Will the user that the notebook is shared with see the auto-refresh option and can they turn it on?

They currently can’t see it, it’s not a part of the UI.

**Comment by garylfowler** [comment]
The yes, agree, we can close this.
