### ISSUE TITLE
Clockface: Update the type ahead dropdown component to allow for custom color selection

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#3680]
We would like to update the [Type Ahead Dropdown](https://influxdata.github.io/clockface/?path=/story/components-dropdowns-composed--typeaheaddropdown) component so it can handle custom color selection. We'll be using it for selecting colors for Slack alerts and potentially elsewhere in the app. 

This updated component should do the following:
- A user should be able to select from the list of prepopulated colors. List items should show HEX code, not color name, along with the corresponding color swatch.
- When a user starts typing in a hex code of their choice, the prepopulated hex codes should be displayed until the hex code doesn't match.
- When a user types in their own custom HEX code, the field should accept that hex code.
- When a user leaves a notebook and then comes back to it, the selected HEX code should persist unless the user selects another color from the dropdown or types in a new hex code.

Prepopulated colors:
- #DC4E58
- #FFB94A
- #2FA74D
- #0098F0
- #8E1FC3

**Design**
[Figma](https://www.figma.com/file/yGX7J9hSW1fEtNTdEidqaX/Dropdown-Menus?node-id=101%3A956)

<img width="948" alt="Color Selector Dropdown (3)" src="https://user-images.githubusercontent.com/81173353/150826091-b3d38283-7216-4f8e-899a-f3fdd7a72629.png">

**Comment by jzahnd** [comment]
@appletreeisyellow is going to reach out to Dumplings for some help getting up to speed on this.

**Comment by appletreeisyellow** [comment]
Seems like we are using [Color Picker](https://influxdata.github.io/clockface/?path=/story/components-color-picker-family--colorpicker) instead of [Type Ahead Dropdown](https://influxdata.github.io/clockface/?path=/story/components-dropdowns-composed--typeaheaddropdown) for color selector specifically in issue #2572. Are we planning to modify the clockface component Color Picker or Type Ahead Dropdown to support custom color selection?

**Comment by juliajames12** [comment]
@appletreeisyellow I believe we'd need to modify the Type Ahead Dropdown component to support custom color selection.

**Comment by appletreeisyellow** [comment]
After a review with @hoorayimhelping last week on the current "Type Ahead Dropdown" component, we think it will introduce complex usage to this component if we modify on it, so I created a new component in clockface called "Creatable Type Dropdown" in the above PR
