### ISSUE TITLE
Auto Refresh: User's refresh settings should persist in modal

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#3682]
Currently, when a user inputs their auto refresh settings, confirms, and then goes back to click on the auto refresh to button to cancel or update the their auto refresh settings, the inputs from the previous selections don't persist and are reset to the default.

We'd like to update the experience so users can see their previous auto refresh settings so they can easily set those again in the future. 

[Prototype](https://www.figma.com/proto/qP1atZtFp9axPu8BRYuvQk/Dashboards-Enable-Autorefresh?node-id=199%3A767&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=199%3A767&show-proto-sidebar=1)

**Comment by asalem1** [comment]
Closing in favor of https://github.com/influxdata/ui/issues/4163
