### ISSUE TITLE
Remove feature flag for PAYG Credit Test

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#3686]
We have been running the PAYG Credit Test for a decent amount of time in Production. In keeping with our general processes, we should remove the feature flag after a month or so. 

We would like to remove the `paygCheckoutCredit` flag and fall back to Google Experiments if we would like to turn it off in production. There is a dependency on the Quarts side for this feature flag, however. ~~We will need to coordinate with @influxdata/ecommerce before removing this flag.~~ This is not actually the case, we can move forward with removing the feature flag.

**Comment by randycoulman** [comment]
@jzahnd It turns out that Quartz doesn't actually use this feature flag like I thought it did. We rely only on the Google Experiment to turn the feature on and off. So, I was wrong when we discussed this issue today and no coordination with our team is actually needed after all. Thanks!

**Comment by jzahnd** [comment]
Thanks for the update Randy!
