### ISSUE TITLE
Performance issue in dashboards

### ISSUE THREAD

**Issue by Dfldr** [influxdata/ui#3692]
## About the bug
A performance issue appeared during Cypress testing of time range feature in dashboards.
I input a higher amount of data into defbucket to fill every minute of a month in a graph for testing purposes (around 87000 points).
I created a cell with a graph to display the data.
While the query loaded after changing the time range, rendering of the graph took longer, which caused the test to frequently fail, because Cypress could find the element it was searching for.
I then reduced the data input to eliminate this performance issue and complete the test.
First amount of points that reliably worked for testing purposes was around 3000 (for Cypress).
Rendering that many points might not be entirely necessary, since the user is not able to see them.

The issue can be reproduced by creating a graph with a large amount of points in it and changing the time range after saving the cell configuration. 

- System info: Linux 5.13.0-27-generic x86_64
- Enviroment: working with remocal/K8sIDPE on a project UI
- last k8sidpe repository commit: commit 42e9d495ca5471b83dc879186f4b018d1906bad2 (HEAD -> master, origin/master, origin/HEAD)
Author: Will Cooke <will@whizzy.org>
Date:   Mon Jan 24 10:51:53 2022 +0000

    chore: unpin storage (#5812)

**Comment by kristinarobinson** [comment]
Thanks for the finding this.  However, we do not have the bandwidth to fix.  We've changed markdown libraries a few times for various reasons.
