### ISSUE TITLE
Notebooks(Alert): HTTP Test Alert not being received 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/ui#3706]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. In AWS EC2 setup a micro instance with a simple express HTTP listener that echos received messages to the console
2. Go to Influxdbv2 UI (note that during this test the feature flag 'notebooksNewEndpoints' was set)
3. Add test data to a bucket
4. Create an Alert Notebook
5. Use the test data to define the query
6. In the alert section choose the HTTP endpoint
7. Provide the URL to the listener in AWS 
8. Click the button 'Test Alert'

**Expected behavior:**

Expected to see the alert message echoed to the AWS EC2 instance console

**Actual behavior:**

No alert message was received. 

Note, that this same endpoint was used in an earlier test of an tradition Alert > Notification Endpoint, and the message was received. 

Note as well, that the Test Alert message was received at a Slack endpoint. 'This is a test notification'.  So this is what I'm expecting to see in the console. 

**Visual Proof:**

![NotebookTestAlert01](https://user-images.githubusercontent.com/25881301/151164352-174ed563-cbb0-4545-bfd3-ebbce5facd4c.gif)

Note in the above screencast that a notification message had been echoed to the console from an earlier test.  This message was from an endpoint configured in Alerts, and bound to a Threshold check via a Notification Rule.  

## About your environment

**Environment info:**

Tested in K8S-IDPE Remocal. 
Latest UI commit
```
commit a918e664f19a21d33b21fe2c19c7cac8aa01c573 (upstream/master, origin/master, origin/HEAD, master)
Author: Palakp41 <palak@influxdata.com>
Date:   Tue Jan 25 17:16:27 2022 -0800
```
Lates K8S-IDPE commit
```
commit 84c1d4fd7f71ca41759a5f31e3c245c59f3bd4da (HEAD -> master, origin/master, origin/HEAD)
Author: Hercules Mango Churchill <alchemy@influxdata.com>
Date:   Wed Jan 26 02:00:44 2022 +0000
```

**Config:**

**Logs:**

**Comment by jzahnd** [comment]
@karel-rehor Is this working outside of the Notebooks UI that you know of?

**Comment by karel-rehor** [comment]
@jzahnd 

I caught the backend flux query call and tried it in Explorer, 

```javascript
import "strings"
import "regexp"
import "influxdata/influxdb/schema"
import "influxdata/influxdb/secrets"
import "experimental"
import "array"
import "http"
import "json"

http["endpoint"](url: "http://ec2-13-52-255-26.us-west-1.compute.amazonaws.com:3000")(
    mapFn: (r) => {
        return {headers: {"Content-Type": "application/json"}, data: json["encode"](v: "This is a test notification")}
    },
)

array.from(rows: [{value: 0}])
    |> yield(name: "ignore")
```
It also fails to send a message.  BTW are all of the library imports necessary? 

However modifying it based on flux documentation to `http.post` works. 

```javascript
import "array"
import "http"

http.post(
   url: "http://ec2-13-52-255-26.us-west-1.compute.amazonaws.com:3000", 
   data: bytes(v: "This is test notification number 9"),
   headers: {"Content-Type": "application/json"}
)

array.from(rows: [{value: 0}])
    |> yield(name: "ignore")
```
From my EC2 console after using `http.post`

```
$ sudo node app.js 
Example app listening for HTTPS
Example app listening at http://0.0.0.0:3000
POST
HEADERS: {"host":"ec2-13-52-255-26.us-west-1.compute.amazonaws.com:3000","user-agent":"curl/7.68.0","accept":"*/*","content-length":"46","content-type":"application/x-www-form-urlencoded"}
DATA: { key: 'salutation', value: 'How do you do?' }
POST
HEADERS: {"host":"ec2-13-52-255-26.us-west-1.compute.amazonaws.com","user-agent":"curl/7.68.0","accept":"*/*","content-length":"39","content-type":"application/x-www-form-urlencoded"}
DATA: { key: 'greeting', value: 'Dobry den' }
POST
HEADERS: {"host":"ec2-13-52-255-26.us-west-1.compute.amazonaws.com:3000","user-agent":"Go-http-client/1.1","content-length":"27","content-type":"application/json","accept-encoding":"gzip"}
DATA: This is a test notification
POST
HEADERS: {"host":"ec2-13-52-255-26.us-west-1.compute.amazonaws.com:3000","user-agent":"Go-http-client/1.1","content-length":"27","content-type":"application/json","accept-encoding":"gzip"}
DATA: This is a test notification

```

**Comment by karel-rehor** [comment]
BTW it appears that the `http.endpoint` function is intended to post data from a pipeline. The return value is a function which needs to be called.

```javascript
import "http"
import "json"

endpoint = http.endpoint(
    url: "http://ec2-13-52-255-26.us-west-1.compute.amazonaws.com:3000"
)

from(bucket: "devbucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "jsoucno")
  |> filter(fn: (r) => r["_field"] == "mag")
  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)
  |> yield(name: "last")
  |> endpoint(mapFn: (r) => ({headers: {}, data: json.encode(v: r)}))()
```
Rewriting the Test Alert call using `http.endpoint`

```javascript
import "array"
import "http"
import "json"

endp = http["endpoint"](url: "http://ec2-13-52-255-26.us-west-1.compute.amazonaws.com:3000")(
    mapFn: (r) => {
        return {headers: {"Content-Type": "application/json"}, data: json["encode"](v: "Ceci est un avertissement 2")}
    },
)

array.from(rows: [{value: 0}])
    |> yield(name: "ignore")
    |> endp()
```
And then in the EC2 console. 
```
HEADERS: {"host":"ec2-13-52-255-26.us-west-1.compute.amazonaws.com:3000","user-agent":"Go-http-client/1.1","content-length":"27","content-type":"application/json","accept-encoding":"gzip"}
DATA: "Ceci est un avertissement"
...
```
However IMHO I think `http.post` is cleaner

**Comment by wiedld** [comment]
Confirmed behavior. Confirmed solution.

Doing update now (confirming lifecycle of notebook tasks is still good), then will push-up PR.
