### ISSUE TITLE
Is Influxdata cloud 2 down?

### ISSUE THREAD

**Issue by amirft1374** [influxdata/ui#3709]
I tried to insert data to Influxdata cloud2 using the python script. However, the database is not receiving or showing data.
I even tried to query and it gave me an error. 
I changed the URL and token to a locally hosted influxdb and everything was running fine.
I am even getting nothing by running this simple code.

```
from influxdb_client import InfluxDBClient
from influxdb_client.client.write_api import SYNCHRONOUS


token = "MY_TOKEN"
org = "MY_ORG"
bucket = "MY_BUCKET"
url = "https://us-east-1-1.aws.cloud2.influxdata.com"

with InfluxDBClient(url=url , token=token, org=org) as client:
    write_api = client.write_api(write_options=SYNCHRONOUS)

data = "mem,host=host1 used_percent=23.43234543"
write_api.write(bucket, org, data)
```

Is anybody else experiencing the same issue?

**Comment by aalvarez737** [comment]
I also see my buckets empty, also errors querying usage and billing

**Comment by karel-rehor** [comment]
For future reference the influxdb cloud status can be monitored at the following link. 
https://status.influxdata.com/
