### ISSUE TITLE
Notebooks(Alerts): Notification history contains unclear mix of alert and task instance information 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/ui#3710]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. In AWS EC2 set up a micro instance with a simple HTTP listener that echos messages back to the console
2. Open Influxdbv2 (note that during this test the feature flag 'notebooksNewEndpoints') was set
3. Add test data to a bucket with data points that will trigger a critical threshold alert
4. Create an Alert set in Alerts based on the test data (Threshold Check - Endpoint - Rule)
5. Create a new Alert Notebook
6. Create a query based on the test data
7. In the alerts section define a threshold designed to trigger an alert notification 
8. In the endpoints section select HTTP and set the URL to the EC2 instance.  In this case plain HTTP with no tokens or authentication. 
9. Generate more test data with timestamps in the future and values to trigger the notification
10. Export the Notebook as a task 
11. Monitor the EC2 instance console for messages
12. Open Alerts > Alert History > Notifications 

**Expected behavior:**

Expected notification information to be consistent.  That notifications from tasks generated from notebooks, would not mix information with Alert instances such as Check, Endpoint and Rule.   

**Actual behavior:**

There are entries in the Notification History with 'Notebook Generated Check' listed as the check, but then with the Alert Endpoint and the Alert Rule listed in those columns.  However, it is understood that the Notebook Generated Task, is not bound to the Endpoint and Rule instances in Alerts.  It's a bit confusing. 

**Visual Proof:**

![NotificationHistory03](https://user-images.githubusercontent.com/25881301/151201622-09f29f10-3833-4ef8-afb2-8d8a4c9dd945.png)

## About your environment

**Environment info:**

Testing in K8S-IDPE remocal. 

last UI commit
```
commit a918e664f19a21d33b21fe2c19c7cac8aa01c573 (upstream/master, origin/master, origin/HEAD, master)
Author: Palakp41 <palak@influxdata.com>
Date:   Tue Jan 25 17:16:27 2022 -0800
```
last K8S-IDPE commit
```
commit 84c1d4fd7f71ca41759a5f31e3c245c59f3bd4da (HEAD -> master, origin/master, origin/HEAD)
Author: Hercules Mango Churchill <alchemy@influxdata.com>
Date:   Wed Jan 26 02:00:44 2022 +0000
```

**Config:**

**Logs:**

**Comment by jzahnd** [comment]
@jzahnd To review with Bonitoo team on why we do not want to do this

**Comment by wiedld** [comment]
@jzahnd @garylfowler and @wiedld have a consensus:
We do not want notebook alerts listed under the status checks, nor to be setting status checks.
But we do want notebook alert notifications, to be listed under the notifications.

**Comment by wiedld** [comment]
reason why is here:
https://github.com/influxdata/ui/issues/4081

Fixing as I remove our use of `monitor.check()`

**Comment by wiedld** [comment]
we decided not to remove monitor.check(). for now.
see more reasons here:
https://github.com/influxdata/ui/issues/4081#issuecomment-1074584517
