### ISSUE TITLE
Templates: bucket and data should not be empty before the template can be imported

### ISSUE THREAD

**Issue by ivankudibal** [influxdata/ui#3714]
## About the bug

1. When I want to apply the community template in my cloud2 account, and the bucket referenced from template with my invaluable data (still being collected) already exist, then the UI fails to load the template.

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Remove all the template history (previous versions of templates with same name), remove bucket or start with empty cloud account 
1. Run iot center against cloud (https://github.com/bonitoo-io/iot-center-v2), cd app, yarn init and run, then generate data from ui (http://localhost:3000/devices/virtual_device (Click on pencil icon)
1. Import the template, https://github.com/influxdata/community-templates/blob/master/iot_center/iot_center.yml

Or simpler procedure can be to reproduce with all `telegraf` based templates:

1. Remove all the template history (previous versions of templates with same name), remove bucket or start with empty cloud account 
2. Run telegraf and start collecting data eg about localhost, make sure you have `telegraf` bucket with data.
3. In UI add Dashboard by importing new community template -- https://github.com/influxdata/community-templates/blob/master/linux_system/linux_system.yml

**Expected behavior:**

The template should be imported successfully..

**Actual behavior:**

UI shows the error.

**Visual Proof:**

![image](https://user-images.githubusercontent.com/8028110/151375827-defb7d1a-7be7-4548-8550-fedbaddcf429.png)

## About your environment

**Environment info:**

Cloud2, no more than week old version..

**Comment by ivankudibal** [comment]
Just reproduced  during IoT Workshop by one of the visitors, today..

**Comment by kristinarobinson** [comment]
This is a known issue with pkgr - @aanthony1243 @dgnorton.

**Comment by stuartcarnie** [comment]
@SimonRichardson this is because we had to support importing templates where the value is missing (pre schema support), allowing us to round-trip the data and omit the value when it was written again whilst the feature was disabled. We could probably just default to implicit now, as the feature is no longer optional.
