### ISSUE TITLE
Put back bucket selector to Load data file uploader. 

### ISSUE THREAD

**Issue by ChitlangeSahas** [influxdata/ui#3721]
We removed the bucket selector in https://github.com/influxdata/ui/pull/3557/files

We need to put it back. We'll work with design to come up with the better solution to address: #2867

**Comment by barbaranelson** [comment]
To clarify - we need to put the bucket back in all the screens where we give users a drag/drop interface to upload their file, because they need a way to tell us into which bucket to write the contents of the file.  This applies to both the flux annotated CSV file and the line protocol file.
