### ISSUE TITLE
Manual refresh is missing from dashboards

### ISSUE THREAD

**Issue by TCL735** [influxdata/ui#3725]
<img width="1680" alt="Screen Shot 2022-01-27 at 5 31 35 PM" src="https://user-images.githubusercontent.com/10736577/151471515-d4a66d71-e22e-42d7-ade3-1130eadcc45d.png">

Manual refresh was accidentally removed. There has been no discussion or announcement that manual refresh should be removed. Manual refresh should be put back.

Here are the PRs that removed it:
https://github.com/influxdata/ui/pull/3699  
https://github.com/influxdata/ui/pull/3717

**Comment by TCL735** [comment]
Manual refreshing with a button is very useful. It is a lot faster than refreshing the whole page. And for debugging purposes, a developer may not want to refresh the whole page. This button serves a very useful purpose.

**Comment by appletreeisyellow** [comment]
Manual refresh button is back!

PR #3737 and #3728 revert the code that removed the manual refresh button.
