### ISSUE TITLE
Dashboards - markdown editor - table

### ISSUE THREAD

**Issue by Dfldr** [influxdata/ui#3729]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Create a dashboard
2. Add note
3. Use Markdown editor
4. Try to create a table using hyphens (---)

**Expected behavior:**
A table is displayed in the render output

**Actual behavior:**
Horizontal rule is displayed instead of column's header. Pipes don't separate columns.

**Visual Proof:**
![markdownEditor1](https://user-images.githubusercontent.com/88332140/151562827-c9e8c074-a519-4db9-baab-9934af334ef5.png)

## About your environment

**Environment info:**
Testing with remocal on a UI project (Ubuntu 20.04)

**Comment by kristinarobinson** [comment]
May not be able to handle.  Will investigate what Monaco editor can handle.

**Comment by ivankudibal** [comment]
adding link to demo https://markdown-it.github.io/

**Comment by kristinarobinson** [comment]
Won't fix.
