### ISSUE TITLE
Dashboards - markdown editor - Fenced code block

### ISSUE THREAD

**Issue by Dfldr** [influxdata/ui#3730]
About the bug

Steps to reproduce:
List the minimal actions needed to reproduce the behavior.

    Create a dashboard
    Add note
    Use Markdown editor
    Use ``` to create Fenced code block

Expected behavior:
Fenced code block is displayed.

Actual behavior:
The block appears as a part of the code.

Visual Proof:
![Fenced_code_block](https://user-images.githubusercontent.com/88332140/151566035-0e7790fc-5ea4-4ff0-a6cb-40d74a05e4a4.png)

About your environment

Environment info:
Testing with remocal on a UI project (Ubuntu 20.04)

**Comment by kristinarobinson** [comment]
Investigate Monaco editor capabilities.

**Comment by kristinarobinson** [comment]
Thanks for the finding this.  However, we do not have the bandwidth to fix.
