### ISSUE TITLE
Dashboards - markdown editor - Footnote

### ISSUE THREAD

**Issue by Dfldr** [influxdata/ui#3732]
## About the bug
**Steps to reproduce:**

1. Create a dashboard
2. Add note
3. Use Markdown editor
4. Add footnote

**Expected behavior:**
![image](https://user-images.githubusercontent.com/88332140/151575449-c63f4c1a-76b8-4ebd-baa0-61888b0159a3.png)

**Actual behavior:**
Part of the text is shown as code and footnotes don't work
![image](https://user-images.githubusercontent.com/88332140/151575638-12ca06e9-d1f5-4242-a277-0f0c055b8e28.png)

## About your environment
Testing with remocal on a UI project (Ubuntu 20.04)

**Comment by kristinarobinson** [comment]
Thanks for the finding this.  However, we do not have the bandwidth to fix.
