### ISSUE TITLE
Dashboards - markdown editor - definition

### ISSUE THREAD

**Issue by Dfldr** [influxdata/ui#3733]
## About the bug

**Steps to reproduce:**
1. Create a dashboard
2. Add a note
3. Use markdown editor
4. Create a definition using ":"

**Expected behavior:**
![image](https://user-images.githubusercontent.com/88332140/151576356-e503e945-59ab-4c7d-abda-f2412497b51c.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/88332140/151576420-d0ffb9b5-adc1-4e60-a9c2-c4aad8693e10.png)

## About your environment

**Environment info:**
Testing with remocal on a UI project (Ubuntu 20.04)

**Comment by kristinarobinson** [comment]
Thanks for the finding this.  However, we do not have the bandwidth to fix.
