### ISSUE TITLE
Dashboards - markdown editor - Task list

### ISSUE THREAD

**Issue by Dfldr** [influxdata/ui#3734]
## About the bug

**Steps to reproduce:**
1. Create a dashboard
2. Add a note
3. Use markdown editor
4. Create a task list using brackets [x]

**Expected behavior:**
![image](https://user-images.githubusercontent.com/88332140/151577267-95f8c22e-b543-4989-98f2-b60265692a2f.png)

**Actual behavior:**
The task list looks the same as unordered list.
![image](https://user-images.githubusercontent.com/88332140/151577783-87c65431-c2da-4368-8a4f-2e2bbc43a9ac.png)

## About your environment

**Environment info:**
Testing with remocal on a UI project (Ubuntu 20.04)

**Comment by kristinarobinson** [comment]
Won't fix.
