### ISSUE TITLE
Dashboards - markdown editor - subscript and superscript

### ISSUE THREAD

**Issue by Dfldr** [influxdata/ui#3735]
## About the bug

**Steps to reproduce:**
1. Create a dashboard
2. Add a note
3. Use markdown editor
4. Use X^2^ to add superscript and H~2~O (~~) to add subcript

**Expected behavior:**
![image](https://user-images.githubusercontent.com/88332140/151578468-f63fb7e0-c2a1-4f6e-8a5d-f125d05dee08.png)
![image](https://user-images.githubusercontent.com/88332140/151578518-4be46387-e510-4a5a-9ecd-7710cccfad93.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/88332140/151578705-61b58201-5c7a-41d5-b4fa-697db63e496e.png)

## About your environment

**Environment info:**
Testing with remocal on a UI project (Ubuntu 20.04)

**Comment by kristinarobinson** [comment]
Thanks for the finding this.  However, we do not have the bandwidth to fix.

**Comment by ivankudibal** [comment]
@kristinarobinson we can give you capacity, this could be a nice task for junior developers..

**Comment by kristinarobinson** [comment]
We have tried fixing this using various libraries.  At this point we are no longer changing around libraries.  The current library does not support this.
