### ISSUE TITLE
Dashboards - markdown editor - Emoji, strikethrough

### ISSUE THREAD

**Issue by Dfldr** [influxdata/ui#3736]
## About the bug

**Steps to reproduce:**
1. Create a dashboard
2. Add a note
3. Use markdown editor
4. Type any :emoji:
5. Use tilde symbols to add strikethrough

**Expected behavior:**
![image](https://user-images.githubusercontent.com/88332140/151579644-1203546a-427c-4b64-8857-43163f636a6d.png)
![image](https://user-images.githubusercontent.com/88332140/151579558-d2ebb16e-1c0f-4660-9490-0dceb88e1895.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/88332140/151579855-5854ee04-5815-4446-8bb2-079c6c7f4b99.png)

## About your environment

**Environment info:**
Testing with remocal on a UI project (Ubuntu 20.04)

**Comment by kristinarobinson** [comment]
Thanks for the finding this.  However, we do not have the bandwidth to fix.
