### ISSUE TITLE
Notebook: Download as CSV doesn't work for individual pipes 

### ISSUE THREAD

**Issue by appletreeisyellow** [influxdata/ui#3738]
## About the bug

**Steps to reproduce:**

1. Open a notebook
2. Click on three dot button on any graphs or tables
3. Click "Download as CSV"

**Expected behavior:**

Download a CSV file

**Actual behavior:**

Nothing is downloaded.

**Visual Proof:**

<img width="1437" alt="Screen Shot 2022-01-28 at 11 45 14 AM" src="https://user-images.githubusercontent.com/14298407/151599222-e0b7ab77-8c7b-451a-8f7a-66a07cb5c813.png">

**Comment by drdelambre** [comment]
this was resolved in https://github.com/influxdata/ui/pull/3762
