### ISSUE TITLE
Turn on downloadNotebookPDF in Production

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#3739]
We would like to turn on `downloadNotebookPDF` in Production. This functionality allows the user to download an entire Notebook in PDF or PNG.

## Acceptance Criteria
- The `downloadNotebookPDF` is on for production
- We are able to export an entire Notebook in both presentation mode and and regular interaction mode as PDF and PNG.
- Create a task for removing the flag in a month

**Comment by appletreeisyellow** [comment]
A task is created to remove this flag in #3800
