### ISSUE TITLE
Implement billing settings deactivation UI

### ISSUE THREAD

**Issue by OfTheDelmer** [influxdata/ui#3756]
### Description
Figma:
https://www.figma.com/file/BkocQXFhElANIPHt8ypxJL/Multi-Account-Redesign?node-id=219%3A1227

As a `FREE` or `DIRECT PAYG` USER
I want to see a `DEACTIVATE ACCOUNT` button in the Billing Settings tab
So that **I CAN VIEW AN OVERLAY** describing cancellation terms
AND provide optional **USER DEACTIVATION**  feedback
AND agree to cancellation 
AND deactivate my account.

### Acceptance Criteria

Given a `free` or `payg` user goes to the billing settings tab
When they view account settings
Then they can see a `DEACTIVATE ACCOUNT` button with a brief explanation.

---

Given a `free` or `payg` user goes to the billing settings tab
When they click `DEACTIVATE ACCOUNT` 
Then they can see a deactivation overlay with the following:
   - terms for deactivation
   - agreement checkbox  to deactivation,
   - provide optional user feedback
   - an active deactivation button (if agreed)

---

Given a `free` or `payg` user goes to the billing settings tab
When they click `DEACTIVATE ACCOUNT` in their deactivation overlay 
Then they are logged out of their account and all terms of deactivation are effective on their account.

**Comment by OfTheDelmer** [comment]
Todos:

- [x] add deactivation section, brief and button
- [x] add overlay with terms, checkbox, feedback, and deactivation button
- [ ] fix formating, element spacing and address design issues within overlay
- [ ] check in with design on final look and copy of text

**Comment by abshierjoel** [comment]
In `feat/deactivation-ui` I copied the `handleCancelAccount` callback from the `BillingContext` over to the `UserAccountContext`. It was being imported, but the account deactivation button does not exist within the `BillingContext`. UI team is going to make a decision on where this behavior should live.
