### ISSUE TITLE
Annotations MVP: As a user I can write an annotation

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#377]
GIVEN I am a user and I want to annotate a visualization I am looking at in a Dashboard Cell:

WHEN I click the Annotations button
THEN I see a toolbar with controls for annotations

WHEN I click the blue Annotate button
THEN I see instructions on how to annotate a visualization, including a start time with date/time picker, title and summary for the event.

WHEN I click the blue Add Annotation button
AND there are no form errors
THEN my annotation is written to the bucket selected 
AND I see a notification appear (success, 5s, "Annotation written successfully! Please wait a moment for it to appear")

WHEN I click the blue Add Annotation button
AND there are form errors
THEN I see error text below each invalid input

Design Mockup
AddAnnotationOverlay.tsx

This UI is partially built out:
Access the overlay by clicking Annotate
Access the overlay with route orgs/orgID/dashboard/dashboardID/add-annotation (from dashboard) or orgs/orgID/data-explorer/add-annotation (from DE)

**Comment by kristinarobinson** [comment]
Moving this issue out to placeholder epic for post-MVP work.  MVP issue https://github.com/influxdata/ui/issues/550 replaces this issue.

**Comment by jzahnd** [comment]
@kristinarobinson is this still relevant?

**Comment by kristinarobinson** [comment]
Closing, not an relevant feature.
