### ISSUE TITLE
Notebook: Some panels don't work correctly when added as a first panel

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3777]
If you add an alert panel as the first panel, it does not display correctly and instead shows a confusing error that "This cell will display results from the previous cell after selecting Run."  We need some way to correctly handle panels that need previous results to run correctly, either by not allowing them to be an option when adding a panel at the top of the notebook, or by giving a more specific error message that explains the problem.

**Comment by barbaranelson** [comment]
I'd be fine with that (greying them out).

**Comment by juliajames12** [comment]
This is what it would look like if we disabled the buttons and had the cursor show they can't click on those panels. 
<img width="709" alt="Screen Shot 2022-03-09 at 11 29 59 AM" src="https://user-images.githubusercontent.com/81173353/157489538-64bf907d-c635-47c7-b246-907c6b4a78de.png">

If the user is only allowed to add those panels, I think they would infer that they need a data source first before adding those other actions, but if it's confusing we can add an error message on hover. Let me know what you think.

**Comment by garylfowler** [comment]
"This panel is only available after you have added a data source panel" ?

**Comment by juliajames12** [comment]
Here is an updated mock with that tooltip. This should be ready to go :) 

<img width="709" alt="Insert panel if there is no data source (2)" src="https://user-images.githubusercontent.com/81173353/157511477-0465aabe-5728-4a14-a348-e3bc7624dffa.png">

**Comment by garylfowler** [comment]
Thanks @juliajames12.  @jzahnd - this one is ready for consideration in next Iteration.

**Comment by drdelambre** [comment]
if you add 3 markdown panels, then we still wouldn't want them to add an alert right?
