### ISSUE TITLE
Alerts: Alert Check is internally inconsistent, when manually updating flux versus the UI.

### ISSUE THREAD

**Issue by wiedld** [influxdata/ui#3781]
Made an Alert Check to test alerts.
Made edits through the flux editor. Not reflected in UI.
Made edits through the UI. Not reflected in the flux editor.
Upon save in Alerts flux editor --> redirect to Tasks page.

## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

#### To create inconsistency:
1. go to Alerts
2. create an Alert Check.
   * 2 minute resolution
   * pick "Original name"
3. also made an Alert Endpoint and Alert Notification, but do not think this is required.
4. Edit the Alert Check, via the flux editor.
    * select your AlertCheck > settings icon (upper right). See the screenshot in step #5.
    * Update flux range to be 10 minutes (so always include a data point, with update frequency).
5. Edit the Alert Check, via the list view.
    * without selecting AlertCheck --> in the list view, click on the edit for the name. (pencil icon)
    * update the name. Below is my new name chosen.
<img width="1279" alt="Screen Shot 2022-02-04 at 7 02 19 PM" src="https://user-images.githubusercontent.com/10232835/152627808-37716a5e-9ced-4753-bde9-76b0f5c3bb5d.png">

6. re-open the flux editor view. Everything now mismatches.
    * select your AlertCheck > settings icon (upper right).
    * flux has `|> range(start: -10m)`
    * flux has a task with an old name, and old frequency: `option task = {name: "Original name", every: 2m, offset: 0s}`
    * List view (of all alert checks) shows the updated name.
    * But the view within the flux editor (see left panel below in step #7) still shows the original name.

#### Testing if flux is the source of truth.
7. Unclear on when AlertCheck frequency should be. Try updating in flux.
    * in flux editor, find `option task = {name: "", every: 2m, offset: 0s}`
    * update to every 10 minutes in flux `every: 10m`.
    * do NOT overwrite the UI part (left panel)
<img width="1371" alt="Screen Shot 2022-02-04 at 7 43 02 PM" src="https://user-images.githubusercontent.com/10232835/152627559-f19cd488-3e34-4b57-9ecc-6e2ee8553d20.png">

8. Save and close.
9. Redirects to the Tasks page. (not the alert page.) Another bug.
10. Go to Alerts > view the Alert Check again.
11. see that the UI part is the source of truth.
    * Has overwritten the flux query.
    * Is back to `option task = {name: "Original name", every: 2m, offset: 0s}`

#### Observations:
* the AlertCheck > settings icon (upper right), provides a fluxEditor which appears to be based on the task (not the AlertCheck).
       * I think this is how the AlertCheck list view can have a different set of names, which is not consistent with the fluxeditor view (which is based on the task name).
       * Plus a redirect back to the tasks page, upon save.

.

**Expected behavior:**
That there is internal consistency.
Redirect on save, should to back to the original page.

.

**Actual behavior:**
Flux and UI keeps not matching.
I'm building a state model in my head to figure out how to edit these AlertChecks properly.

.

**Visual Proof:**
Screenshots are provided above.

**Comment by wiedld** [comment]
Made the issue description be problem based. Here is one proposed solution. All parts together is the solution:
* keep using the task overlay, but have the redirect on save use the proper overlay controller behavior. (which returns to last page.)
* the task overlay itself, for the flux editor, should have only 1 way to edit things: via the flux script. 
    * Otherwise if you have 2 sources, (the flux script and the UI form inputs on the right) you have to decide winners programmatically.
    * the flux script should be your src of truth, when using a flux editor.
* once flux is your src of truth, the resultant changes to the task state object (e.g. “name” and “every”) needs to occur. 
    * this could be an API roundtrip, with the backend parsing the new task attributes out of the flux script and we taking the new attributes on the next GET. (caveat: I don't know what the backend services can do)
    * or we can use the flux parser we have on the frontend, and extract ourselves from the ast.
* still need a resolution on the concept of AlertCheck name, versus task name
    * maybe keep them separate?
    * is less confusing once the task overlay (for flux editor) no longer has those form inputs for name. That way the only "name" seen in the flux editor is clearly labeled as the task name, not the AlertCheck name.


May be better solutions. This is just one option.

**Comment by drdelambre** [comment]
the solution here would be to move the alerts interface to be more inline with our plan with the other task generating panel
https://github.com/influxdata/ui/pull/3537
