### ISSUE TITLE
Bug: Variables(in Settings): exporting variable shows an overlay background but not an overlay container

### ISSUE THREAD

**Issue by k3yi0** [influxdata/ui#3784]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. go to the settings
2. create a variable
3. export the variable

**Expected behavior:**
The expected behavior is for an overlay to show up with a container with a variable value.

**Actual behavior:**
The overlay shows up without a container.

**Visual Proof:**

![export_var](https://user-images.githubusercontent.com/97002262/152775296-cb11971e-4c10-484f-8b7e-fe81dae97902.png)

![export_var_overlay](https://user-images.githubusercontent.com/97002262/152775308-2f31052b-fde1-45bf-98f5-013b95a79b1e.png)

## About your environment

**Environment info:**
Testing in K8S-IDPE Remocal

The latest commit in project UI
```
commit 65592aad01b9ddd369107e63c22227b075b9dd23 (HEAD -> master, origin/master, origin/HEAD)
Author: Chitlange Sahas <chitlangesahas@gmail.com>
Date:   Fri Feb 4 10:58:12 2022 -0700
```

**Comment by kristinarobinson** [comment]
@hoorayimhelping -- is this related to the export v2 template work you did last sprint?

**Comment by ChitlangeSahas** [comment]
Looks like the functionality was removed here: 

https://github.com/influxdata/ui/pull/3545/files#diff-51a0339ce3729db2c04fce205ffc356c7a82d16cdab1aaa1626d24fbf684c2e2L130-L132
