### ISSUE TITLE
Notebook: hide 'Set Auto Refresh' button before a notebook is saved

### ISSUE THREAD

**Issue by appletreeisyellow** [influxdata/ui#3787]
## About the bug

A notebook should not be able to refresh before it is saved, so we want to hide the 'Set Auto Refresh' button.

<img width="1496" alt="notebook-auto-refresh" src="https://user-images.githubusercontent.com/14298407/152812203-9ddda45d-a2f3-448c-8017-242ae85d7b96.png">

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Create a new notebook

**Expected behavior:**
- Hide 'Set Auto Refresh' button when creating a new Notebook
- Show 'Set Auto Refresh' button when a Notebook is saved, i.e. when the 'Save Notebook' button is clicked

**Comment by asalem1** [comment]
@appletreeisyellow why don't we want this appearing for ephemeral notebooks? A user should be able to set auto refresh on for a notebook if it hasn't been saved. Not sure why this is an issue / bug

**Comment by appletreeisyellow** [comment]
@juliajames12 noticed this at an UI demo time and I looked into the code and thought that a notebook cannot be auto refreshed unless it has an id, which means a notebook is saved. Correct me if I'm wrong @asalem1

**Comment by jzahnd** [comment]
Closing for now due to publish life cycle work
