### ISSUE TITLE
Unlimited characters in some fields

### ISSUE THREAD

**Issue by k3yi0** [influxdata/ui#3789]
## About the bug

Some fields don't have the maxlength attribute at some places, while they have it at others. For example, if you try to rename a newly created cell through a dashboard, the maxlength attribute is set to 68 characters. However, if you create a new cell over the Data Explorer > Save As > Dashboard Cell, the cell can have unlimited characters. The same thing goes for tasks. You can create a new task with unlimited characters; however, at the Tasks tab, you can rename it with a maximum of 90 characters. If you edit the said task instead of just editing its name at the Tasks tab, you can once again rename it with a total length of unlimited characters. 

The layout breaks with long enough names/descriptions, and the user has to scroll to the sides. 

- [ ] Load Data > Bucket > name field
- [ ] Load Data > Telegraf > name and description fields
- [ ] Load Data > API Token > description field
- [ ] Data Explorer > Save As > Dashboard Cell > cell name field
- [ ] Data Explorer > Save As > Variable > name field
- [ ] Data Explorer > Save As > Tasks > name field
- [ ] Tasks > Create Task  > name field
- [ ] Settings  > Variables > Create Variable > name field

I found one more in the Dashboards > dashboard description, but this one doesn't break the layout; the user just can't see the full description.

**Visual Proof:**

Dashboards > Cell > Rename the cell; max. length is 68 characters

![limited_char](https://user-images.githubusercontent.com/97002262/152822092-02251412-8c0c-4068-b47c-6dd60134722c.jpg)

Data Explorer > Save As > Dashboard Cell

![unlimited_char](https://user-images.githubusercontent.com/97002262/152823336-7d096d56-4121-44b7-a1ac-7241ea21a2e7.jpg)

This is what it looks like on the dashboard. The settings button for the cell is shifted; it's always at the end of the name.

![unlimited_char_dashboards](https://user-images.githubusercontent.com/97002262/152823367-5405caa6-c2aa-4148-b452-5e673ac98b77.jpg)

The entire issue is just a mild inconvenience. I just find it weird that some fields are limited and others are not.

**Comment by kristinarobinson** [comment]
Duplicate against https://github.com/influxdata/idpe/issues/8389
