### ISSUE TITLE
Color Mapping: Potential React memory leak

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#3790]
### Steps to reproduce
1. ensure `graphColorMapping` is on
1. Create a new line graph or edit one.
1. In query builder, select a measurement - either add a new one, or remove an existing one
1. Click Submit
1. Observe the react error in the console

```
Warning: Cannot update a component (`GetFlags`) while rendering a different component (`TimeMachineVis`). To locate the bad setState() call inside `TimeMachineVis`
```

https://reactjs.org/link/setstate-in-render

https://user-images.githubusercontent.com/146112/152839193-4a12f3b7-6242-4a15-9652-4f83d30d49c2.mov

**Comment by TCL735** [comment]
I noticed that putting this block: https://github.com/influxdata/ui/blob/master/src/visualization/types/Graph/view.tsx#L198-L217 and this block: https://github.com/influxdata/ui/blob/master/src/timeMachine/components/Vis.tsx#L98-L117 into `useEffect` hooks seems to get rid of the console error. However, I was unable to verify that color mapping still worked as intended when those blocks are inside `useEffect` hooks.
