### ISSUE TITLE
Alerts: alert check task not running consistently.

### ISSUE THREAD

**Issue by wiedld** [influxdata/ui#3803]
Was trying to debug an issue about alert notifications (from the Alerts section) not being halted and triggering too many alerts.

Instead, I have the opposite issue. Alert checks are not being triggered as they should. Got activation delays, and an unexplained 50minute halting of the task.

## About the bug

**Steps to reproduce:**
1. Set sample data to be fetched into bucket, every 5 min.
2. Set AlertCheck to be checked every 10 min.
    * Created 14:00 pacific time (22:00 UTC)
3. Set Notification to check Alert status, every 2 min.
4. Result:
     * AlertCheck was triggered at 14:10, 14:30, 14:40, **HALTED**, 15:30, 15:40
     * POST notification was received at the server at 14:12, 14:32, 14:42, **HALTED**, 15:32, 15:42
     * no AlertChecks, nor notifications, occurred for about 50 minutes (the "halted" noted above)...then started again...then halted again.

.

**Expected behavior:**
Alert Checks to be triggered on a rather persistent basis. At the outside limit of every 10min, (matching the AlertCheck frequency).

.

**Actual behavior:**
Alert checks were:
* delayed until first trigger
* were not consistently triggered afterwards
* halted and stopped for >50 minutes. Then started again.

.

**Visual Proof:**
SampleData refresh rate into buckets:
<img width="1432" alt="Screen Shot 2022-02-07 at 3 51 34 PM" src="https://user-images.githubusercontent.com/10232835/152891569-aebe46ce-fd4b-45cf-9d92-66ece49a25b0.png">

AlertCheck:
<img width="1013" alt="Screen Shot 2022-02-07 at 2 15 41 PM" src="https://user-images.githubusercontent.com/10232835/152889323-196ec2a9-3459-4d5e-8e50-58f32eed3d28.png">
<img width="1268" alt="Screen Shot 2022-02-07 at 3 27 22 PM" src="https://user-images.githubusercontent.com/10232835/152889404-3e2104a7-9728-42de-8417-ee97e8485f67.png">

AlertCheck history, and notifications received:
<img width="2056" alt="Screen Shot 2022-02-07 at 3 44 59 PM" src="https://user-images.githubusercontent.com/10232835/152891009-83a21443-3f21-456f-9b28-925d676c4c43.png">

## About your environment
k8s-idpe version:
```
commit 32eca80f7aa59becd5e7efdc39a919cbd067b0d5 (HEAD -> master, origin/master, origin/HEAD)
Author: Hercules Mango Churchill <alchemy@influxdata.com>
Date:   Mon Feb 7 17:15:48 2022 +0000
```
ui version:
```
commit 65592aad01b9ddd369107e63c22227b075b9dd23 (origin/master, origin/HEAD, master)
Author: Chitlange Sahas <chitlangesahas@gmail.com>
Date:   Fri Feb 4 10:58:12 2022 -0700
```

**Comment by wiedld** [comment]
Think this may be caused by the sample data.
Apparently the s3 bucket of data has a time resolution of every 10 seconds, 
but the update rate (for a single co sensor) was in chunks.

One example had a 15minute chunks updated, of 10 second data.

Closing this ticket.

**Comment by timdonovanuk** [comment]
I don't know how but this should be indicated somewhere in the UI. I've been tearing my hair out wondering why my alerts don't trigger (I set them to 5 seconds because I want to test) and just happened across this post. My influxdb records data at 1m intervals and after changing the alert to check every minute I'm finally getting alerts. 

It doesn't make sense to me why data resolution has an impact on alerts that run with a frequency higher than the data resolution. The question "is x == y" should be true/false, and trigger an alert; why does how often I ask that question have any relevance?
