### ISSUE TITLE
invalid line protocol 

### ISSUE THREAD

**Issue by okvittem** [influxdata/ui#3810]
![image](https://user-images.githubusercontent.com/3093300/153210485-b5f6b244-29e0-4a61-a689-aeb6e7879a36.png)

I try to upload a line protocol file and get the error message above : invalid line protocol
This looks like a bug because the web-page should know the protocol..

I also try to upload this data via the curl write api, which returns nothing - implicit acceptance ?
No data to be seen in  'data explore'
 
Here is the line protocol file content :+1: 
`htp,sensor_id=rk01 seq=0,box_temp=23.27,water_temp=22.66,height=2.00,voltage=3.26,battery=0.05,solar=7.57,signal=28,pressure=987.4,bmp_temp=20.48,probe_time=1644346926 1644346926000000
htp,sensor_id=rk01 seq=1,box_temp=23.52,water_temp=22.83,height=2.00,voltage=3.24,battery=0.05,solar=7.71,signal=28,pressure=987.4,bmp_temp=20.48,probe_time=1644348417 1644348417000000`

**Comment by sanderson** [comment]
@okvittem From the LP you provided, it doesn't look there are any new lines separating each line. Try this:

```
htp,sensor_id=rk01 seq=0,box_temp=23.27,water_temp=22.66,height=2.00,voltage=3.26,battery=0.05,solar=7.57,signal=28,pressure=987.4,bmp_temp=20.48,probe_time=1644346926 1644346926000000
htp,sensor_id=rk01 seq=1,box_temp=23.52,water_temp=22.83,height=2.00,voltage=3.24,battery=0.05,solar=7.71,signal=28,pressure=987.4,bmp_temp=20.48,probe_time=1644348417 1644348417000000
```

**Comment by okvittem** [comment]
Thanks for the feedback, but I guess the line feed was removed by the wiki.

I have  have multiple parameters per sensor-box which has a  sensor_id, 
that produces a set of values presented on the lines given.

There is a concept of a bucket that I guess could be a group of sensor-boxes.
I don't understand how the measurement id would relate to this - could that be the problem ?

Or it is a problem by it self that the API silently ignores input.
There is also a concern that I can not copy/paste text error messages.

Here is the curl command that sends the two lines above: 
`curl --request POST \
"$server/api/v2/write?org=$org&bucket=$bucket&precision=ns" \
  --header "Authorization: Token $token" \
  --header "Content-Type: text/plain; charset=utf-8" \
  --header "Accept: application/json" \
  --data-binary '`

 I also tried to upload sample-sensor-info.csv, but I get error message enclosed from the url : 
https://europe-west1-1.gcp.cloud2.influxdata.com/orgs/<org-id>/load-data/file-upload/annotated_csv

![image](https://user-images.githubusercontent.com/3093300/153480973-35b90712-fb5a-46be-a9d7-796964f34a40.png)

**Comment by kristinarobinson** [comment]
The UI currently can only handle Annotated CSV, not just plain CSV.  Our CLI has the expanded capability to interpret CSV without the header annotations.  There is a feature request to add this capability, which has not yet prioritized.
