### ISSUE TITLE
Bug: Helper error message mentions string being used even though int is used

### ISSUE THREAD

**Issue by abalone23** [influxdata/ui#3824]
The following query with `quantile()` requires a float be used rather than int, but the popup error message indicates a string is being used:
```js
import "array"

data = array.from(rows: [
  {_time: 2020-01-01T00:00:00Z, _field: "exampleField", _value: 3, foo: "bar"}
])

data
  |> quantile(column: "_value", q: 0.99, method: "estimate_tdigest", compression: 1000.0)
```
>It looks like you're trying to apply a number-based aggregate function to a string, which cannot be processed. You can fix this by selecting the Aggregate Function "Last"

It also mentions using `last()` which doesn't make sense. It should say to convert to float before using `quantile()` with the `estimate_tdigest` method. Note that the `exact_selector` method does work with an int.

<img width="1804" alt="Screen Shot 2022-02-10 at 12 09 24 PM" src="https://user-images.githubusercontent.com/330044/153488444-c3072082-e185-4173-9935-0f076008733f.png">

**Comment by Luckette** [comment]
@AyeAndy - Do you have design recommendations on how to word/present this error message?

**Comment by ChitlangeSahas** [comment]
@AyeAndy : Yes! So we decided that we will just show the flux error. And if we wanted a better error message, we'll reach out to the flux team and have them change the wording, in the future. We don't want to hard code error messages in the front end.

About the button margins, I agree, except the whole notification is gone so we are fine 👍
