### ISSUE TITLE
Pinned Item Card Titles Overflow cards when more then a few characters in length

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#3860]
**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Create a notebook and save it with a long name
2. Pin the notebook
3. Go to homepage and observe the pinned item card

**Expected behavior:**
The notebook name is confined within the pinned item card

**Actual behavior:**
The notebook name exceeds the boundaries of the card and overlaps into other areas of the UI

**Visual Proof:**

** Note **

Reported originally by Daniel
<img width="948" alt="Screen Shot 2022-02-14 at 11 22 16 AM" src="https://user-images.githubusercontent.com/97983559/153948560-267e12df-604d-48ce-b2d4-0a748c537d82.png">

**Comment by appletreeisyellow** [comment]
@garylfowler How do we want the long titles to look like? Here are three options I can think of and each has it's pros and cons:

## Current bug

<img width="751" alt="Screen Shot 2022-02-15 at 2 40 02 PM" src="https://user-images.githubusercontent.com/14298407/154150982-6a7b97f7-c334-4205-b9c4-859beaa69d71.png">


## Option 1

* Hide the long word in the title
* Drawback is that users cannot see the long word unless they clicked on the pinned item

<img width="748" alt="Screen Shot 2022-02-15 at 2 41 16 PM" src="https://user-images.githubusercontent.com/14298407/154150708-8b08d393-d7a5-4778-aaeb-fe90ce190a7e.png">

### Option 2

* Scroll horizontally
* Drawback is that some pinned items with long words will have a horizontal scroll bar underneath the box. The look for such a pinned item maybe not consistent with the pinned items without long words. See the left and right boxes in the video below.

https://user-images.githubusercontent.com/14298407/154150739-7fe53745-55b9-4fb5-b5c0-44924c6dff88.mov


### Option 3 

* Wrap the text
* Drawback is that the long word will be broken at any random place, but at least this one shows all the words without overlapping into other areas of UI 

<img width="870" alt="Screen Shot 2022-02-15 at 3 13 48 PM" src="https://user-images.githubusercontent.com/14298407/154150768-36e1a6d2-a378-4224-abb2-3ef8a18a7e29.png">

**Comment by garylfowler** [comment]
@juliajames12 and I discussed and we choose option #3.  Thanks.
