### ISSUE TITLE
Notebook(Alerts): HTTP Basic Auth Test Alert with bad credentials ends with notification that looks like success

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/ui#3880]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Setup an echo listener to receive HTTP messages including Basic Authentication verification. Headers and body should be simply echoed to the console once authentication succeeds. Authentication failure should follow the RFC and return HTTP Status 401.
2. Go to Influxdbv2 UI (note that during this test the feature flag 'notebooksNewEndpoints' was set)
3. Add test data to a bucket
4. Create an Alert Notebook
5. Use the test data to define the query
6. In the alert section choose HTTP
7. Click Authorization Basic
8. Add the URL to the listener
9. Add a bad name and/or a bad password
10. Click "Test Alert"

**Expected behavior:**

Expected to see a notification that the test failed. The notification should not leave the impression that the alert test succeeded when the server returned an HTTP Code of 400, 401, 500 etc.  

**Actual behavior:**

The notification is colored green, as if the test succeeded.  The text "A test alert has been sent to HTTP" does not indicate the final state of the entire test process.  An inattentive user might conclude that the configuration is correct and the test is a success. 

Note. Not all servers will be configured to provide clear information as to why or how the message was received or rejected, however they should return 401 when authentication fails and the user should be informed of this. 

**Visual Proof:**

![NBBasicAuthAlertBadCreds01](https://user-images.githubusercontent.com/25881301/154309022-97d904d4-09b5-4800-99dd-7723d21806bc.gif)

## About your environment

**Environment info:**

Testing in K8SIDPE Remocal

latest commit in project UI
```
commit c5a2b5d154a2a8913ee2274a86c3c232a038be70 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Author: wiedld <wiedld@users.noreply.github.com>
Date:   Mon Feb 14 14:24:46 2022 -0800
```
latest commit in K8SIDPE
```
commit d65bf8f0c3fe9a84637ea06a446d65f7051282dd (HEAD -> master, origin/master, origin/alchemy/automatic, origin/HEAD)
Author: Hercules Mango Churchill <alchemy@influxdata.com>
Date:   Wed Feb 16 04:16:35 2022 +0000
```

**Comment by karel-rehor** [comment]
Related to this would also be a test of the endpoint that fails to receive any response within a reasonable timeout.

**Comment by wiedld** [comment]
This one is because:
1. a test alert query is generated
2. query is POSTed and ran in backend
3. the backend only validates that the query run (the `http.post()`) was successfully sent.
4. backend returns the 2xx status code.

on step 3 above, the "success" is because the POST was sent...and it does not surface if the return from the `http.post()` was an error (e.g. bad creds, etc).

**Comment by drdelambre** [comment]
the ask here is that we forward the response message from within the query that is being sent, to the client somehow (showing results, parsing results and reading status codes, throwing errors, whatever). we'd want to derisk a solution that could be applied to other endpoints and not require us to write an endpoint handler for every endpoint, or  at least flag product if we can't / it gets weird

**Comment by wiedld** [comment]
Response from what we know is a valid http POST endpoint, with invalid creds:

<img width="1877" alt="Screen Shot 2022-03-02 at 3 16 05 PM" src="https://user-images.githubusercontent.com/10232835/156465849-6d870268-8476-4dce-b76a-5fc54dee258c.png">

**Comment by wiedld** [comment]
note: the `/api/v2/query` was updated to send an error message on "badURL" or invalid endpoint.
(thanks flux team)

Do we want to ask them to update it surface additional errors from the POST request?

**Comment by wiedld** [comment]
The bad creds still returns a 2xx, and response body has no error to parse.

New change from query endpoint --> it now returns an error for an invalid URL!
Made a PR to surface any errors.

**Comment by wiedld** [comment]
update on this ticket:
- the merged PR will surface any errors return from the backend, when we test the endpoint
- but the backend does not pass along auth error (the exact issue/bug documented here)

**Comment by wiedld** [comment]
Closing this ticket. Any additional changes would be backend (and auto-surfaced due to code changes already made associated with this ticket).
