### ISSUE TITLE
Write a test

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#3898]
Our e2e testing philosophy is that we should cover that sacred bond between engineering and product with an automatically verifiable contract; not that all features should at all times work in all conditions, or that every permutation and edge case is expressed in testing, but that there are paths, above all else, that should work for our users. An example would be: no matter what feature you're working on, no matter what changes you made, no matter what gets merged into master, a user should always be able to create a bucket through our ui. So we add a test for that happy path.

To keep up velocity and encourage a culture of product experimentation, we've never gotten to the point of enshrining tests as acceptance criteria for feature delivery. As a side effect, this bond needs to be a conscious point of communication as flags are sunset and new features are enshrined into the core user experience.

So lets get some practice! The task is to go find a single user path that is important from a product perspective and underserved by our tests, then to patch that up with a new e2e cypress test.

**Comment by wiedld** [comment]
Way past done by now. 😆
