### ISSUE TITLE
Click query running animated circle to cancel a query

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#3917]
**Proposal:**

The spinning circle that shows the query runtime should also be a button to cancel the running query.

<img width="195" alt="Screen Shot 2022-02-17 at 6 32 03 PM" src="https://user-images.githubusercontent.com/13472206/154606666-ac16badc-882d-4969-82d1-5b6f65291912.png">

**Current behavior:**

The "hourglass" is not a button and the "submit" button turns into the "cancel" button. 

**Desired behavior:**
I'd like to see the query elapsed time graphic to be a cancel button. The existing cancel button can stay too.

I think the hourglass is better because it is animated and after clicking submit, that is where the attention is. The customer/user wants to see the data appear and is waiting for the query timer to go away. It's the natural place to click. The cancel button for explorer and cell editor is off to the side away from the action.

This would also allow cancelling queries in dashboard cells as there is currently no way to cancel those.

**Alternatives considered:**
NA

**Use case:**
Makes me happy.

**Comment by philjb** [comment]
related to https://github.com/influxdata/influxdb/issues/18933

**Comment by kristinarobinson** [comment]
Won't fix.
