### ISSUE TITLE
Bug: Raw data view page scroll impossible to use beyond a handful of pages. 

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#3918]
## About the bug

In cloud2, the raw data view shows a table with left right click scroll to access the pages of the table. Pagination is great, but for more than a few handfuls of page results, the ui elements make it practically impossible to get to the desired page. 

Consider this screenshot:
<img width="490" alt="Screen Shot 2022-02-17 at 6 44 52 PM" src="https://user-images.githubusercontent.com/13472206/154608415-a5d50864-3502-44fc-97d0-1112cbd55885.png">

How to I get to the 10,001th page quickly? I can't. I have to click 10,000 times (from the start or the end). 

You might say, that I should just download the csv if I have that much data as the query response, which is reasonable.  But this takes me away from the single pane of glass ui. Page 10,000 is an extreme example. Something like 30 pages would be reasonable where the clicking is excessive but the data not so large the downloading the csv should be the only option.

I'm listing this as a bug because the feature is so difficult to use in this situation. But this is a minor inconvenience with a reasonable workaround (csv). 

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Create a query and data set that returns a lot of data; run it on the explorer page
2. switch to raw data view
3. try to get to a middle page

**Expected behavior:**

Ability to enter in a specific page or otherwise scroll quickly without having to click more than a handful of times.

**Actual behavior:**

Excessive mouse clicking

**Visual Proof:**
See above

## About your environment

**Environment info:**
cloud2

**Config:**

na

**Logs:**

na
**Performance:**
na

**Comment by Luckette** [comment]
I chatted with @mavarius, @brandenTenbrink is working on a design for this.

**Comment by brandenTenbrink** [comment]
This has been addressed with this PR: https://github.com/influxdata/clockface/pull/740

An optional input has been added. 

![image](https://user-images.githubusercontent.com/15152523/157768641-1dff894d-3070-4dc8-ad81-2c157c36dfb6.png)
