### ISSUE TITLE
Bug: Type error for line graphs

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#3920]
An error is shown in the UI (An InfluxDB error has errored) in the Data Explorer when the following query is used in the  Tools cluster:

```
from(bucket: "apps")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "idpetarget_calls")
  |> filter(fn: (r) => r["_field"] == "counter")
  |> last()
  |> map(fn: (r) => ({_value: r.kind + " " + r.key + " " + r.role}))
  |> distinct()
```
  
The stack track shows:
https://files.slack.com/files-pri/T02GAR81Y-F034FKXLXCG/image.png

The raw data view and table view render properly.  The line graph shows the error.

For more information, please contact Roger Peppe, who found the original incident.

**Comment by barbaranelson** [comment]
Another case of this: https://github.com/influxdata/ui/issues/3965 Can we do what Timmy suggested and add a more intuitive error message?
