### ISSUE TITLE
Notebooks(Alert): our "test alert" is intended to only test the endpoint, not the query correctness.

### ISSUE THREAD

**Issue by wiedld** [influxdata/ui#3927]
Our notebook Alert panel has two outputs:
(1) Test Alert
(2) Export Task

Test Alert button:
* tests only the endpoint itself.
* a.k.a. is the endpoint data correct
* it does not test the rest of the query input. (e.g. `field > 12`)

Export Task button:
* generates the final task to be exported.
* then tests the entire query by running it
* finally, exports the task (POST to create the task)

.

The problem with this design, is that someone may have an alert which passed the "Test Alert" button, but fails on "Export Task" (because it is a bad query -- such as missing a field). See video example:

https://user-images.githubusercontent.com/10232835/154780030-9786afcf-362f-4771-8d63-2144076deb96.mov

### Recommendation:
* change the "Test Alert" button text, into "Test Endpoint"?
* that way it's less confusing.
* and we'll not actually run the full task (which would write data)

**Comment by karel-rehor** [comment]
I might suggest testing the "connection".  Which would use the endpoint plus authentication parameters to ensure that a request returns a 2XX response. Any other response code would generate an error notification.  In this case the button text would be "Test Connection".

**Comment by drdelambre** [comment]
task is to update the button text to "test endpoint" to make it clear to the user that we are running a test of their endpoint credentials and not a test of the full alert
