### ISSUE TITLE
Notebook(Alerts): Export notebook as task triggers phantom run not recorded in task run history

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/ui#3928]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Setup an echo listener to receive HTTP messages. Headers and body should be simply echoed to the console once authentication succeeds. 
2. Go to Influxdbv2 UI (note that during this test the feature flag 'notebooksNewEndpoints' was set)
3. Add test data to a bucket
4. Create an Alert Notebook
5. Use the test data to define the query
6. In the alert section choose HTTP
7. Add the URL to the listener
8. Click 'Export Alert Task'
9. Inspect the endpoints.  A check was run and notification was sent
10. Tasks > Open newly created task 

**Expected behavior:**

If a task was run immediately upon creation, expect a record of that run to be recorded in the "Runs" list.

**Actual behavior:**

The runs list is still empty. 

**Visual Proof:**

![NBExportAlertAsTaskTriggersFantomRun01](https://user-images.githubusercontent.com/25881301/154956158-99759c07-bec6-41eb-ae1c-ce837ec7ae4c.gif)

## About your environment

**Environment info:**
Testing in K8SIDPE

latest commit project ui

```
commit 7f6a7997396b4cbae41cb300cafaac4306e73b56 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Author: wiedld <wiedld@users.noreply.github.com>
Date:   Fri Feb 18 16:40:49 2022 -0800
```

latest commit project K8SIDPE

```
commit 39c95a0c4ff722649d49c14bef5eb5f5726afebf (HEAD -> master, origin/master, origin/alchemy/automatic, origin/HEAD)
Author: Hercules Mango Churchill <alchemy@influxdata.com>
Date:   Sat Feb 19 01:41:48 2022 +0000
```

**Comment by drdelambre** [comment]
the work item here is to remove the verification that runs the query against the /api/v2/query endpoint and instead rely on the frontend validation that will be coming out of the flux team from this discussion: https://github.com/influxdata/ui/issues/3926

**Comment by wiedld** [comment]
@drdelambre should we also include a basic check that the Alert trigger options (which field, and a number value) has been set?

Otherwise we'll have lots of bad tasks being generated. Because will include this:
`trigger = (r) => r["undefined"] > 0`

**Comment by drdelambre** [comment]
@wiedld we should, but that's not part of this ticket. this is just for removing the query that happens before saving the task

**Comment by wiedld** [comment]
Already fixed.
