### ISSUE TITLE
Notebooks: flux error messages line numbers don't match input

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#394]
**Steps to reproduce:**

1. Create a new notebook
2. paste in (or create) a long multiline flux query that has an error (e.g. copy from someplace else)
3. Preview the book
4. Observer that the flux error message reports errors in flux as if it is just one long line without my formatting.

![Screen Shot 2020-12-04 at 9 59 07 AM](https://user-images.githubusercontent.com/13472206/101198215-f8b9b580-3617-11eb-8d61-e9187f659c13.png)

**Expected behavior:**

Error messages need to reflect the input formatting otherwise it's really hard to figure out where in flux the error is coming from.

**Actual behavior:**

* Error message like `compilation failed: error at @1:587-1:594: invalid expression @1:583-1:587: then` is shown.
* The error message also seems to show only the first line of the error message - it stops at "then".

**Environment info:**

internal environment

**Comment by alexpaxton** [comment]
Ah interesting. The actual query that gets run is just a giant string, so that explains why all the errors on deep in line 1. Not sure if this is a frontend or backend thing but we can tinker with how the query gets sent.

**Comment by mnorriswalker** [comment]
Closed by https://github.com/influxdata/ui/pull/398
