### ISSUE TITLE
Address flaky tests

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#3942]
Influx ci/cd has identified these tests as flaky.  I have disabled them following the ops guide.

```
cloud/billing
cloud/checkout
cloud/checkout
cloud/home
cloud/operator
cloud/operatorRO
cloud/orgs
cloud/pinned
cloud/userAccounts
shared/buckets
shared/checks
shared/dashboardsRefresh
shared/explorer
shared/explorerVisualizations
shared/flowsSidebarExportToClipboard
shared/labels
shared/nav
shared/queryBuilder
shared/simpleTable
shared/tasks.pagination
shared/tasks
shared/telegrafPlugins
shared/tokens
```

**Comment by jzahnd** [comment]
As noted in a separate conversation, we have rolled back the update that skipped these tests. The dashboard that gives visibility into these tests shows all flakes, regardless of how many times they are happening or if they are blocking a build. We need to triage based on each test and create issues for the ones that may be blocking.

**Comment by kristinarobinson** [comment]
All UI tests no longer run in IDPE repo.  Might want to close this?  @barbaranelson

**Comment by barbaranelson** [comment]
Yes, we can close this one. I still want us to focus on fixing flaky tests as we find them in the UI repo runs, but don't need to use this issue to track that.

**Comment by TCL735** [comment]
Many of theses tests have been addressed separately in various issues. Closing this.
