### ISSUE TITLE
Notebook(Alerts): MailGun exported flux script for task is not compilable

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/ui#3945]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. In MailGun setup an account and then an Email API integration using the Web API and Curl.  Copy and save the API Key and domain for later use in Influxdb UI.  
2. Go to Influxdbv2 UI (note that during this test the feature flag 'notebooksNewEndpoints' was set)
3. Add test data to a bucket
4. Create an Alert Notebook
5. Use the test data to define the query
6. In the alert section choose MailGun
7. Add the key and domain from the first step to the configuration
8. Use the MailGun account email for the _from_ field, and in the _to_ field add an email address to which you have access
9. Click  "Export Alert Task" 

**Expected behavior:**

Expected alert task to be created. 

**Actual behavior:**

A failure notification message is shown.  

In developer tools networking the response message is: 

```
{"code":"invalid","message":"error @62:13-63:41: missing return statement in block\n\nerror @42:19-64:10: missing pipe argument (argument endpoint)\n\nerror @42:19-64:10: found unexpected argument r (argument endpoint)"}
```

**Visual Proof:**

![NBAlertMailgunExport01](https://user-images.githubusercontent.com/25881301/155323970-1ab4fed7-46b7-4b16-9943-f514e0dced31.png)

Copied the payload from the tools > networking into Explorer. The flux code has compilation issues, as indicated by the response message. 

![MailGunAlertGeneratedFlux01](https://user-images.githubusercontent.com/25881301/155324117-38ab0d29-24c8-4a91-b535-efd0452468a5.png)

## About your environment

**Environment info:**
testing in K8SIDPE Remocal 

latest commit in project UI
```
ommit 7f6a7997396b4cbae41cb300cafaac4306e73b56 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Author: wiedld <wiedld@users.noreply.github.com>
Date:   Fri Feb 18 16:40:49 2022 -0800
```

latest commit in K8SIDPE
```
commit eed93bdff4fb9e3247a148837cda4cd6204c69ca (HEAD -> master, origin/master, origin/alchemy/automatic, origin/HEAD)
Author: Hercules Mango Churchill <alchemy@influxdata.com>
Date:   Wed Feb 23 08:21:44 2022 +0000
```

**Comment by wiedld** [comment]
The error message will no longer appear, because we are not doing any query validation before the CRUD call to create a query.

But the bad flux will still exist. After you export the query to a task --> try running the task.
