### ISSUE TITLE
Bug: Static Legend: has default 0 height in Notebooks

### ISSUE THREAD

**Issue by TCL735** [influxdata/ui#3962]
Reported by https://community.influxdata.com/t/static-legends-dont-actually-appear-on-my-notebooks/21943

Currently,
- Static Legend defaults to a non-zero (visible) height for the Data Explorer
- Static Legend defaults to a zero (not visible) height for Notebooks

We should offer a sane (visible) height in all places.

**Comment by kristinarobinson** [comment]
Talk to Unity team about notebooks.

**Comment by hoorayimhelping** [comment]
There is a height slider at the bottom of the configuration options that is set to 0% by default. Is this a mistake or by design?

![Screen Shot 2022-03-08 at 10 12 56 AM](https://user-images.githubusercontent.com/146112/157266903-c1bf4a66-9283-4e16-8568-2da6d02d41ef.png)
