### ISSUE TITLE
Bug: Specific query crashes UI, have to refresh page

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ui#3965]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Run this query in the data explorer:

```
import "influxdata/influxdb/sample"

sample.data(
  set: "airSensor"
)
|> distinct(column:"_field")
```

**Expected behavior:**

I expect to be able to observe the results

**Actual behavior:**

Reports that an error occurred and no results are shown. The page must be refreshed in order to run another query.

**Visual Proof:**

![image](https://user-images.githubusercontent.com/3771906/155760432-f690259e-a54c-4eda-86c3-044b3e886627.png)

## About your environment

**Environment info:**

Cloud 2 Product

**Comment by nathanielc** [comment]
FWIW I ran this same query in a notebook and get a similar error for the visualization pane.

![image](https://user-images.githubusercontent.com/3771906/155760941-f17f7011-ef76-459f-b0f9-26437bd149cb.png)

**Comment by barbaranelson** [comment]
See also https://github.com/influxdata/ui/issues/3920

**Comment by hoorayimhelping** [comment]
>Uncaught TypeError: col is undefined

https://github.com/influxdata/ui/blob/master/src/visualization/types/Graph/view.tsx#L126-L130

```ts
  const [xDomain, onSetXDomain, onResetXDomain] = useVisXDomainSettings(
    storedXDomain,
    col.type === 'number' ? col.data : null,
    timeRange
  )
```
