### ISSUE TITLE
Dashboard cell Configure panel crash

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#3969]
## About the bug

On an internal dashboard, I clicked Configure for a cell to look at the flux query. The query editor component gave me an error. It was persistent until i hard refreshed the page. I did not need to log in again. Using the dashboard refresh button did not clear the issue (just the hard refresh). I unfortunately do not know how to get into this state.

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Unknown

**Expected behavior:**
No webapp crashes or at least an information error message about what went wrong.

**Actual behavior:**
Cell configure query editor component error.

**Visual Proof:**

![Screen Shot 2022-02-25 at 2 53 38 PM](https://user-images.githubusercontent.com/13472206/155814398-5709d16e-786b-42e9-ac34-cdc7f1041be7.png)
![Screen Shot 2022-02-25 at 2 54 23 PM](https://user-images.githubusercontent.com/13472206/155814412-387a2e28-b9df-4242-8aa1-d6b62438cfe1.png)

## About your environment

**Environment info:**
cloud2

**Config:**

na

**Logs:**

na

**Comment by kristinarobinson** [comment]
Thanks @philjb.  This is a known issue for our content data loader.  We're looking at implementing a CDN to help with this issue.

**Comment by jzahnd** [comment]
Closing due to upcoming CDN work.
