### ISSUE TITLE
usage not working

### ISSUE THREAD

**Issue by robertoctf** [influxdata/ui#4011]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. ...tried to access usage
2. ...
3. ...

**Expected behavior:**

**Actual behavior:**

**Visual Proof:**

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by kristinarobinson** [comment]
@robertoctf - can you verify whether you are a free tier user on Cloud, a PAYG customer on cloud, or using our OSS product?

**Comment by jzahnd** [comment]
This was a bug that we have fixed, closing for now.
