### ISSUE TITLE
Cant view usage

### ISSUE THREAD

**Issue by hanhsien** [influxdata/ui#4014]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Click on view usage
2. ...
3. ...

**Expected behavior:**

Usage charts displayed

**Actual behavior:**

Error message

**Visual Proof:**

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by JoeEarly** [comment]
![Screenshot 2022-03-04 at 5 36 13 pm](https://user-images.githubusercontent.com/5208459/156813536-1598c3e5-955c-4695-949c-7bee7bde0def.png)
Can reproduce

**Comment by hanhsien** [comment]
Hi
I just get this screen when I click on Usage.

[image: image.png]

**Comment by kristinarobinson** [comment]
@hanhsien -- Can you tell me if you are a free tier user (in which case you would not see usage information), or a PAYG client?

**Comment by hanhsien** [comment]
Hi Kristina,

I am a free tier user, but prior to this I was able to see usage metrics
such as data upload rate, # of queries, etc.

Regards,
Han

**Comment by natalya-patrikeeva** [comment]
We have the same issue (I actually opened a [new Issue](https://github.com/influxdata/ui/issues/4031)). We are under Pay as You Go tier. We use InfluxDB Cloud and we are not able to see our organization metrics.

**Comment by JoeEarly** [comment]
Once I added my billing info and upgraded from free tier I could see data

**Comment by jzahnd** [comment]
This was a bug that we have addressed, closing for now.
