### ISSUE TITLE
Spike: Notebook(alerts): flux validation prior to exporting a task.

### ISSUE THREAD

**Issue by wiedld** [influxdata/ui#4020]
When bonito did QA on the alerts panel in notebooks, they found a series of bugs related to alerts exported to tasks with invalid flux.

The longterm fix, (agreed by all parties), is going to be a few months. We have the option of some short term fixes. However, there is some disagreement on whether and what to handle short term -- based on what is UI responsibility, and what is UI tech debt. We need more discussion.

Additional note: the invalid flux issue occurs in our current (released) prod, as well as the additional alert features awaiting release.

### Bugs caused by this underlying issue:
* https://github.com/influxdata/ui/issues/3764
* https://github.com/influxdata/ui/issues/3945
* https://github.com/influxdata/ui/issues/3847
* https://github.com/influxdata/ui/issues/3846
* https://github.com/influxdata/ui/issues/3764
* https://github.com/influxdata/ui/issues/3919
* error shown here: https://github.com/influxdata/ui/issues/3926#issuecomment-1045547348

### Long term fix (agreed long term path):
* work seen in https://github.com/influxdata/ui/issues/3926
* note that this fix will only cover a subset of our bugs 
* additionally, some of the "catching of bugs" are arguably UI bugs (imho -- feel free to disagree 😆 )

## Scope of work:
The found bugs cover a range of problems. Including:
* incorrect flux hardcoded in the UI repo
* invalid user input (in the UI form fields), which are not validated before we construct the flux query
* UI form field inputs, are not being correctly imported/used in the flux query. (a.k.a. when the UI constructs the query, the query does not match the UI input fields.)

We need to decide if we still keep playing whack-a-mole with these issues, (especially as new issues keep being found), or alternatively we decide there is a fundamental approach/improvement needed.

**Comment by wiedld** [comment]
A specific example of one "fundamental approach" to be taken -- change our testing requirements.
* have the user stories, and matching test cases
* cover the full path of generating, testing, and exporting an Alert from the Alert panel.
* this full path definition includes that a valid flux is generated, and that an invalid flux cannot be exported.
* the exported flux will run (a.k.a. a 200 on the query API endpoint).

note that this^^ is one general/approach question. There are also a bunch of other approaches...or we can continue on the whack-a-mole, as we discover new bugs.

**Comment by subirjolly** [comment]
I did think about this and it’s going to be very tricky debugging this unless we start having test credentials for each of these services. because even if the flux query works fine, in some cases, then also the test wouldn't have worked. For example, `telegram.endpoint` in test wouldn't work but for the same, `telegram.message` needed to be used. For the actual alert, endpoint needed to be used. So, there's a fundamental issue, issue being, non-conforming to consistency across even a single integration itself.
If we start conforming to the usage of endpoint or message then the integration can be tested manually and we can validate the flux query that its fundamental parts match, relating to the current integration. On top of that, if we can have test credentials then we can guarantee the end-to-end validity of the test as well as the alert.

**Comment by jzahnd** [comment]
We might have a few different areas to address here:

* How do we deal with form validation
* How do we understand data validation

**Comment by wiedld** [comment]
This spike can broken out into action items:
* form validation for any UI inputs, prior to tasks being output: https://github.com/influxdata/ui/issues/4229
* using the semantic analysis method from the new wasm binary, if/when it becomes available: https://github.com/influxdata/ui/issues/3926
* we still have incorrect flux being hardcoded into our UI code in notebooks. I believe the solution would be;
   * fix what we currently have
   * have test cover include the actual flux query syntax exported from the Alerts Panel

**Comment by wiedld** [comment]
Action items are created. Closing issue.
