### ISSUE TITLE
Notebook(Alerts): multiple variables in Alert definition generates uncompilable flux in exported task 

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/ui#4021]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Setup an echo listener to receive HTTP messages 
2. Go to Influxdbv2 UI (note that during this test the feature flag 'notebooksNewEndpoints' was set)
3. Add test data with at least two numeric fields to a bucket
4. Create an Alert Notebook
5. Using the test data define the query to use all numeric fields 
6. In the alert section define a trigger using the first numeric field AND the second numeric field. 
7. In the alert section choose basic HTTP with the endpoint from step 1
8. Click "Export Alert Task"
9. Locate the generated task in Tasks from the nav bar. e.g. Tasks > Notebook Task for local_XXXXX
10. Click Run. The task is scheduled. 
11. Return to the tasks list via the Nav Bar. And check Last Run Status 

**Expected behavior:**

Expected the task to run successfully.

**Actual behavior:**

Last Run Status is failed.  
The logs show the message. 

```
Unexpected error from query; Err: error @26:36-26:56: expected bool but found (r:{A with ixs:B}) => bool (function): error @26:36-26:56: expected bool but found (r:{A with ixs:B}) => bool (function)
```

Edit the task and the flux script shows a compilation error on line 26. 

```
trigger = (r) => r["dur"] > 20 and (r) => r["ixs"] > 28
```

**Visual Proof:**

![NBAlert2Vars01](https://user-images.githubusercontent.com/25881301/157010689-fcf2f82b-b758-46ea-9e56-59c24c5dbb66.png)

The generated flux script in the task editor
![NBAlert2VarsGenFlux01](https://user-images.githubusercontent.com/25881301/157010745-6d1a1e96-a969-4de0-ae61-c58b2a5f22d0.png)

## About your environment

**Environment info:**

Testing against K8SIDPE Remocal 

Latest commit in project UI

```
commit 22850c6b4a45fa63c8e8cf267439f90cc8e58460 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Author: Jakub Bednář <jakub.bednar@gmail.com>
Date:   Mon Mar 7 08:19:59 2022 +0100
```

Latest commit in K8SIDPE

```
commit 7f2c8fcedb1170828a73670afccd8565685fcf74 (HEAD -> master, origin/master, origin/alchemy/automatic, origin/HEAD)
Author: Hercules Mango Churchill <alchemy@influxdata.com>
Date:   Mon Mar 7 08:17:01 2022 +0000
```

**Comment by wiedld** [comment]
The error message will no longer appear, because we are not doing any query validation before the CRUD call to create a query.

But the bad flux will still exist. After you export the query to a task --> try running the task.
