### ISSUE TITLE
Bug: Missing data from page to page in Simple Table  

### ISSUE THREAD

**Issue by blegesse-git** [influxdata/ui#4025]
**Bug only exists in local env (not prod)**
## About the bug 

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. install the noaa sample dataset to a bucket (https://docs.influxdata.com/influxdb/cloud/reference/sample-data/#noaa-water-sample-data)
2. Open a notebook instance
3. Change time range to Past 30d (30 days)
4. Query average temperature
5. Visualize as a SimpleTable

**Expected behavior:**
When switching pages, the data rendered on the following page should pick up from the last row index. 
For instance: if 10 rows are shown on the first page, the next page should start at row 11 

**Actual behavior:**
on a given page, there are always 4 missing rows. For example - first page will show 6 rows, then the next page picks up at the 11th row. 

**Visual Proof:**

## About your environment

**Environment info:**

This bug only exists in local dev environment. This is because the row height of simple table varies from one environment to another. Why? that's the million dollar question. 
As shown in the screenshots below, row height in prod is much smaller than row height in dev. 
![Screen Shot 2022-03-02 at 4 18 25 PM](https://user-images.githubusercontent.com/66275100/157062412-75153fe9-a5a2-4f6a-88d2-803514bba4f6.png)
![Screen Shot 2022-03-02 at 4 18 41 PM](https://user-images.githubusercontent.com/66275100/157062681-d41b638b-f16a-4747-8e53-08e1d472c944.png)

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by kristinarobinson** [comment]
@blegesse-git Is this still happening for you?  And is it related to window size?  (If you resize the window, the issue goes away or gets worse)

**Comment by blegesse-git** [comment]
couldn't reproduce this issue. Therefore, it's safe to assume the problem is resolved.
