### ISSUE TITLE
InfluxDB Cloud organization usage metrics dashboard not showing

### ISSUE THREAD

**Issue by natalya-patrikeeva** [influxdata/ui#4031]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior. Refreshing the page. 

1. In the UI, go to Organization -> Usage to see the usage metrics dashboard

**Expected behavior:**
See the usage metrics dashboard with information like the number of queries, MB of data, etc.

**Actual behavior:**
Only see the error message - An InfluxDB error has occurred. Please report the issue here.

**Visual Proof:**
Chrome:
<img width="762" alt="screen-shot" src="https://user-images.githubusercontent.com/10470710/157105982-e04d2534-de47-471c-af89-b7e0ce30a89b.png">
Safari:
<img width="923" alt="Screen Shot 2022-03-07 at 1 48 25 PM" src="https://user-images.githubusercontent.com/10470710/157107118-5327cea3-7c00-4b15-8440-629c58b5a87c.png">

## About your environment

**Environment info:**

- System info:
```bash
uname -srm
Darwin 21.3.0 x86_64
```
- Running InfluxDB Cloud on us-west-2-2.aws.cloud2 
- Same bug in Google Chrome Version 98.0.4758.102 (Official Build) (x86_64) and Safari Version 15.3 (17612.4.9.1.8)

**Comment by jzahnd** [comment]
This was a bug that has since been fixed. Closing.
