### ISSUE TITLE
Multi Org Phase 1 - End to End Testing

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4053]

**Comment by kristinarobinson** [comment]
Testing Complete:
should have the dropdown and be able to select/switch the Account
should have the dropdown and be able to select/switch the Organization
should have the user avatar and user initials and be able to open the user option popover by clicking on the avatar

Tests still Needed:
- User Profile (ability), Ability to Select Account Org defaults

Moving back into Ready until code is complete for remaining use cases.
