### ISSUE TITLE
Token list isn't cleared when switching between orgs

### ISSUE THREAD

**Issue by danxmoran** [influxdata/ui#406]
**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Set up a fresh instance of OSS 2.x, creating `org_a`
2. Create a 2nd org, `org_b`
3. Switch to `org_a` and navigate to `Data` -> `Tokens`. You should see the name of the token created by `setup`
4. Switch to `org_b` and navigate to `Data` -> `Tokens`. You'll see the same tokens as ^^^
5. Refresh the page. The token will disappear.

**Expected behavior:**
Tokens from `org_a` never appear the view for `org_b`.

**Actual behavior:**
`org_a` tokens appear in the UI until a page refresh forces a full reload.

**Comment by drdelambre** [comment]
closing in favor of #337
