### ISSUE TITLE
firstMile: Text Changes based on Internal Run-Through

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#4100]
There are some minor text changes that need to happen. The text changes need to happen on steps 2, 5, 6, and 7. See the mockup for comments with the :recycle: emoji to indicate where the changes are.

Included in this change are a couple of code snippets that shouldn't be copyable - they are illustrative code snippets that are included in the next code block that is to be copied.

**Comment by Luckette** [comment]
Thank you @taramk @AyeAndy @will-influxdata @kristinarobinson @mavarius for discovering these improvement areas via our internal run-through.
