### ISSUE TITLE
firstMile: node.j Get Started App - Display Data Structure as part of Dynamic Get Started Experience

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4136]
## Figma

See new Figma from @AyeAndy: 
https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=714%3A2554

ACs
-

**Comment by Luckette** [comment]
FYI @kristinarobinson

**Comment by Anaisdg** [comment]
Off the top I would suggest something like:

Bucket: A named location where you store your data. The highest hierarchical level in the InfluxDB data structure
Measurement:  Where you store associated fields. The second highest hierarchical level in the in the InfluxDB data structure 
Fields: A key-value pair where you store your time series data 
Tags: A key-value pair where you store meta-data about your fields. Do not store data with unlimited number of values as a tags. 

It could be helpful to reference a sample data set in the description and provide an example, perhaps:
https://docs.influxdata.com/influxdb/v2.1/reference/sample-data/#noaa-water-sample-data

Or provide some examples outside of that sample data set like: 
Measurements: i.e. weather and industrial_monitoring
Fields: i.e. temperature, humidity and  pressure, flow rate, power. 
Tags: i.e. region and factory

**Comment by Luckette** [comment]
@AyeAndy is meeting with @Anaisdg on Tues 3/29 to work on this design/text

**Comment by Luckette** [comment]
@kristinarobinson to send @Anaisdg & @AyeAndy a table visualization of data to use in the onboarding flow
