### ISSUE TITLE
firstMile: Edit Text on Create a Token page & Auto Create Token (Python, Javascript, & GO)

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4139]
**Problem:** As of 3/16/22, the Create a Token page doesn't clarify that the user can delete and create different types of tokens in the future. The user doesn't know why they're creating an all-access token.

**ACs**
- ~Auto-create token for the user in all the set up flows (Python, GO, Javascript)~
- Change the text and design on the tokens page according to the Figma screenshots in this ticket. (Do this for Python, GO, and Javascript)
- ~Maintain the functionality that automatically inserts the token into the correct place in the code snippet. (Do this for Python, GO, and Javascript)~

**Dev Notes**
- See Figma screenshots below.

**Comment by kristinarobinson** [comment]
@AyeAndy - We need the verbiage or design to fix this.  I assume that we want to REMOVE the create token button, automatically create the token and populate the export statement with that token value.  Please confirm.

**Comment by kristinarobinson** [comment]
Tables using SampleData AirSensor and BitCoin prices:
<img width="1561" alt="AirSensorSample" src="https://user-images.githubusercontent.com/70343856/161332116-ae36df5c-16dc-425e-ab22-ae2846d240a8.png">
<img width="1620" alt="Coindesk_sample" src="https://user-images.githubusercontent.com/70343856/161332123-a3b0bc23-4491-447e-ba6c-ca0e19a5d564.png">

**Comment by AyeAndy** [comment]
![Screen Shot 2022-04-05 at 9 35 25 AM](https://user-images.githubusercontent.com/8049399/161803010-93af50eb-b5dd-444c-ace0-544974e07ebd.png)
this is what I had in mind @kristinarobinson , what do you think?

**Comment by hoorayimhelping** [comment]
Partially completed with https://github.com/influxdata/ui/pull/4396. The text about all-access tokens not being the best security practice needs to be added in.
