### ISSUE TITLE
Query Experience Toggle

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#4153]
## EPIC Description

<p></p>

The query experience team is leaning towards a flux edit focused User Interface for Query as a replacement for Data explorer.  Its focus will be on helping the user get started with flux vs. the existing visual builder as an alternative to flux editing.

<p></p>

Because this will be a big change in user experience, it will be too risky to turn it on for and have it be changed for everyone.

<p></p>

The alternative it to take an approach, similar to those done by Atlassian in the Jira product, or Microsoft with Outlook, or Google with Gmail:

<p></p>

**Give the user the chance to choose between the old view and new view.**

<p></p>

This will then give us the opportunity to get feedback and look at analytics for which view is getting used by percentage.

<p></p>

## Acceptance Criteria

<p></p>

- A visual indication will be available within Data Explorer to indicate there is a new view to try out

- When a user chooses the "new view" they will be moved to an alternate data explorer window (specs TBD after Query Experience Project)

- When in the new view, a visual indication will be available within Data Explorer to indicate they can choose to go back to the old view

- When a user chooses the "old view" they will be moved back to the old Data Explorer view

- If feasible (won't be known until after the new view is designed), any query criteria already specified should move to the new window

- An amplitude Event is generated for any toggle selection

- Feature is initially hidden behind a feature flag

<p></p>

<p></p>

## Notes

<p></p>

<p></p>

If possible, we will want to try to be able to track in amplitude how long a user stays in the new view before toggling back (and if they toggle back)

<p></p>

Would also like to be able to keep stats from time of query start to successful query with each view, but existing DE will probably need some additional instrumentation to do this.

<p></p>

<p></p>

<p></p>

<p></p>

<p></p>

<p></p>

**Comment by garylfowler** [comment]
Link to feature: https://influxdata.productboard.com/feature-board/planning/features/12533460

**Comment by juliajames12** [comment]
Here's the design for the toggle:

Toggle Description: [✨](https://emojipedia.org/sparkles/) Try new Data Explorer

Toggle Off:
<img width="1513" alt="Screen Shot 2022-04-11 at 3 30 40 PM" src="https://user-images.githubusercontent.com/81173353/162826847-8cd2141f-6a61-4b7b-80a8-6072b6475010.png">

Toggle On: 
<img width="1512" alt="Screen Shot 2022-04-11 at 3 31 09 PM" src="https://user-images.githubusercontent.com/81173353/162826893-a9d96102-70a9-4414-aa50-b6312cf96213.png">

**Comment by drdelambre** [comment]
@juliajames12  is this replacing the "upgrade now" button or are we running this to one side of it?

**Comment by juliajames12** [comment]
Here's what the design would look like along with the upgrade now button:

<img width="1512" alt="Current Data Explorer View" src="https://user-images.githubusercontent.com/81173353/163883783-18dc9fe5-78a4-4ed7-b1ca-b84ed8b59fec.png">
<img width="1512" alt="New Data Explorer View" src="https://user-images.githubusercontent.com/81173353/163883786-76293b30-286f-41ed-a745-a30ac0ad42db.png">
