### ISSUE TITLE
Notebooks: Markdown - "Type markdown here" should disappear when typing

### ISSUE THREAD

**Issue by abalone23** [influxdata/ui#416]
**Steps to reproduce:**
1. Click + sign
2. Select **Markdown**
3. Type some text

**Expected behavior:**
I expect the default **Type markdown here** to go away

**Actual behavior:**
The default **Type markdown here** remains

<img width="1284" alt="Screen Shot 2020-12-08 at 3 43 09 PM" src="https://user-images.githubusercontent.com/330044/101554843-4746b700-396c-11eb-8290-3b182cc0fea4.png">

## Technical notes
- Should be placeholder text not actual text

**Comment by 121watts** [comment]
blocked on upgrading the markdown library: #257
