### ISSUE TITLE
Post Query Statistics in Notebooks

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#4169]
## User Story

<p></p>

As a user, I would like to see some information about the query I just ran:

<p></p>

- How many tables were returned

- How may rows were returned

- How long the query took

<p></p>

So that I can better understand what happened during the query and the query results.

<p></p>

## Acceptance Criteria

<p></p>

- An additional row will be shown at the top of the validate data window within Notebooks

- The row will contain a small-font (right justified?)line  that will state, "X tables, and X  number of rows Returned, Query Time:  x ms".   **review with Julia**

- When a query is re-run, the text will go away until the re-run completes

- When a query is re-run and it completes, the information will update to reflect the latest query info

- Since we default to "last 100", the line will state "X tables, last 100 rows Returned, Query Time:  x ms" if there are 100 rows.  When less than 100, it will show the actual number as indicated previously

**Comment by garylfowler** [comment]
Link to feature: https://influxdata.productboard.com/feature-board/planning/features/12573241

**Comment by juliajames12** [comment]
Here's the [new design](https://www.figma.com/file/KMokp5JansuytkbU4e9xA8/Notebook-Table-with-Stats?node-id=0%3A1) with the stats included in the top left corner above the table: 

<img width="1440" alt="New Notebook Table - With Stats" src="https://user-images.githubusercontent.com/81173353/163881889-f720bc0a-0bb7-4ba5-b9cb-e5a444302f02.png">

**Comment by appletreeisyellow** [comment]
> Since we default to "last 100", the line will state "X tables, last 100 rows Returned, Query Time: x ms" if there are 100 rows. When less than 100, it will show the actual number as indicated previously

This criteria is different from what we have in the design. The design shows the total row number. Just to double check with @garylfowler, which is the most updated version?

**Comment by garylfowler** [comment]
Do we actually know the total number of rows in this case?  I prefer the
total number of rows, but I didn't think we had that when we limited the
results.  So if we don't have it, we'll show 100 (or less).

**Comment by appletreeisyellow** [comment]
Another question @garylfowler, do we want this design to apply to the simple table that's displayed for the data explorer?

**Comment by garylfowler** [comment]
My thought was that we would try this in Notebooks first, and if we got
positive feedback, then we would add it to data explorer; but I'll open a
separate issue for that one.  Thanks!
