### ISSUE TITLE
Notebooks:  I can preview/run a notebook

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#417]
## User Problem
As a notebooks early access user, I don't know how to preview/run the notebook and try clicking the prompt below the cell that says "Click Preview to See Results"

Example from @abalone23, "I tried clicking it multiple times before reading the text that said to click Preview located at the top of the notebook."

## Proposed solution
Given: I have a notebook with at least one cell
When: I click the Play button or the text "Click Preview/Run to See Results"
Then: The notebook is Previewed/Ran

![Screen Shot 2020-12-08 at 1.57.36 PM.png](https://images.zenhubusercontent.com/5d928b2631e8dd0001222f82/860d82c5-52b2-4553-bbfa-167da11e5a96)

**Comment by 121watts** [comment]
preview button runs everything

**Comment by drdelambre** [comment]
this might involve moving logic that is currently in the submit button, into the query context so that all panels can call a `queryAll` function to refresh the list
