### ISSUE TITLE
Notebooks - Adding an additional Metric Selector displays "Loading..." and spinning icon before bucket is selected

### ISSUE THREAD

**Issue by abalone23** [influxdata/ui#418]
**Steps to reproduce:**
1. Add measurement, fields and tags to the default Metric Selector
2. Click the Plus icon
3. Add an additional Metric Selector

**Expected behavior:**
The **Loading...** message and spinning icon should only display after choosing a bucket while retrieving the measurement, tags and fields

**Actual behavior:**
Note the spinning icon and **Loading...** message _before_ choosing a bucket.

<img width="1082" alt="Screen Shot 2020-12-08 at 4 55 43 PM" src="https://user-images.githubusercontent.com/330044/101559601-4d419580-3976-11eb-9101-c62f5f1d161f.png">

**Environment info:**
https://us-west-2-1.aws.cloud2.influxdata.com/

**Comment by drdelambre** [comment]
i think i fixed this with something else. feel free to reopen if i'm wrong
