### ISSUE TITLE
Share Notebooks

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#419]
### Acceptance Criteria:
- [x] See a list of notebooks across organization
- [x] Save a notebook so the rest of the organization

### Team 
~Docs @noramullen1~ 
Product @russorat
Design @mnorriswalker 
Engineering @drdelambre

**Comment by russorat** [comment]
@drdelambre can we close?

**Comment by drdelambre** [comment]
yeah, it's this button
