### ISSUE TITLE
complex graph seems to result in slow console interaction

### ISSUE THREAD

**Issue by rogpeppe** [influxdata/ui#4211]
## About the bug

Looking into a slow UI editing experience, I discovered what appears to be a correlation between a complex displayed graph and a very slow keyboard response time in the script editor.

When I add a `group` to the Flux script, which reduces the number of lines in the graph by a couple of orders of magnitude, the console becomes responsive again.

I've shared a couple of examples that demonstrate the issue with @hoorayimhelping (I don't want to share here as they're only valid in the private tools environment).

**Comment by Luckette** [comment]
@rogpeppe This will be addressed in a dashboard performance improvement.
