### ISSUE TITLE
upgrade cypress to 9.5.2

### ISSUE THREAD

**Issue by subirjolly** [influxdata/ui#4222]
It's that time again - let's update cypress to latest. As of creating this, we're running Cypress v8.7.0 and the latest cypress is at v9.5.2.

Places where changes are needed:

✅ cloud-2-cypress: https://github.com/influxdata/cloud-2-cypress/pull/34
✅ ui: https://github.com/influxdata/ui/pull/4307/files
✅ cypress-slim: https://github.com/influxdata/cypress-slim/pull/11

I think that's it..

**Comment by subirjolly** [comment]
Merged the following.
https://github.com/influxdata/ui/pull/4307/files
https://github.com/influxdata/cypress-slim/pull/11
https://github.com/influxdata/cloud-2-cypress/pull/34

**Comment by wiedld** [comment]
We are now on cypress 12. v9 was last published/maintained a year ago.

**Comment by appletreeisyellow** [comment]
Closing this one since 9.5.2 upgrade is done. There is a WIP PR that upgrades cypress to v10.11.0 https://github.com/influxdata/ui/issues/6273. As Denise mentioned, cypress is on v12 as of today, we may want to open another issue to keep track of the upgrading
