### ISSUE TITLE
Notebooks: I can start coding in the script cell without rewriting lines

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#424]
### Cursor placement
Given: I have added a Flux Script cell
When: I click into the Flux Script cell
Then: my cursor is below the commented code
And: I begin typing at the bottom of the code block beneath Line 1 & Line 2

Note: Match existing pattern of script blocks (related to https://github.com/influxdata/influxdb/issues/16668)

### Placeholder Text
Given: I have added a Flux Script cell
When: I click into the Flux Script cell
Then: the text should say:
```
// Uncomment the following line to continue building from the previous cell
// __PREVIOUS_RESULT__ 
```
![image.png](https://images.zenhubusercontent.com/5d928b2631e8dd0001222f82/bdb9c37d-a6a2-445a-90c3-37535e4455d8)

### Tech Notes
Related to https://app.zenhub.com/workspaces/applicationui-5e3b05772922e316b3a210a4/issues/influxdata/ui/416

**Comment by drdelambre** [comment]
we have a flag called `cursorAtEOF` defined in the system that will automatically move the cursor to the end of the code block when it is automatically focused. is part of this to enable that flag for all monaco editor instances?
