### ISSUE TITLE
Cloning naming convention

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#4241]
whenever we clone a resource, we have to pull the entire list of the resource, iterate over them, and collate the number of repeating instances to recreate the format of `resource name (clone 2)`. naturally, as the number of resources increase, so does the cloning operation and the complexity of maintaining the code just to increment the number at the end.

big waste of resources and risk of timeouts breaking operations for little product gain, we should just change the format.

**Comment by garylfowler** [comment]
We can use a timestamp instead of a serial number:  Resource name (cloned on 12-22-2022:02:22:22).

**Comment by garylfowler** [comment]
Date format, to be more International, can be YYYY-MM-DD
