### ISSUE TITLE
firstMile: Wizard Step 3: Create a Token (Javascript)

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4245]
User Story: Step 3: Create a Token

    ACs

    - When the user is on the create a Token step, highlight that portion of the wizard
    - Display the text from the Figma Prototype, the text may contain links (in accordance w/ the JAVASCRIPT flow)
    - When the user clicks a link, open a new tab
    - NEW - Automatically generate the token in alignment w/ the changes made to the python flow. 
    - NEW - Once the generate token modal generates the token, automatically place the token inside the copy code component in the appropriate spot
    -  When the user clicks the "Next" button, navigate the user to the next step in the wizard and checkmark the overview step as being completed (blue checkmark)
    - When the user clicks the "PREVIOUS" button, navigate the user to the previous step in the wizard

**Comment by hoorayimhelping** [comment]
closed with https://github.com/influxdata/ui/pull/4284
