### ISSUE TITLE
Notebooks - Force Measurement Selection

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#4253]
## **Story Description & Background**

<p></p>

The current Notebooks interface allows for users (after selecting a bucket) to select a  _measurement or a _field.   This then allows them to choose a field without also requiring them to choose a measurement which causes the metadata lookup to need to grab metadata from all measurements.  This has been reported to cause performance issues with large datasets.

<p></p>

But as a SaaS service provider, I want to force my users to choose a measurement so that I can narrow that metadata and give the user a better user experience.

<p></p>

## Suggested Implementation

<p></p>

- Remove the group/filter option from the first panel the user sees after selecting a bucket.

- Give that panel a title of "Measurement"

- Show the user only a list of measurements to choose from within that panel

- The list of measurements is the complete list for that bucket, not filtered by time range

- Still allow the user to search for a measurement, but don't include fields or tags (only measurements)

- Subsequent panels work as they do today, except there is no longer a _measurement option in them

<p></p>

Design from design team:

![](https://lh5.googleusercontent.com/3qw1d3dsZiG3tVlQuqL0TH8mTtorYkWUAEUMyZpthgSE6Hj_3OQWSi84Jnxo5YmgZwPyjPd-Fe3J83PA29VQqWuJrCMQGbw6wn42s0KQk34Dv2lKMC9kui5J7NQkPs2af3RYMLaPms4Z)

## Acceptance Criteria

<p></p>

- User will see a measurement selection panel after selecting a bucket

- User will see a list of measurements in that panel

- User will be able to search through the list of measurements in that panel, or scroll through them

- All measurements will be shown (not just the measurements in the current time range (a change of current behavior)

- User will be able to select a measurement

- Field Selection won't be available until after a measurement has been selected

- User won't be able to add more panels until after they have made a measurement selection

- Measurement panel won't be available until after bucket selection; it could be done like we currently do with bucket selection:  

![](https://pb-files.s3.amazonaws.com/production/attachments/b8c7acfbbcabe7e0cba874cf7fe7ad925b7836a4fc95794677e1087a2449c036/image.png)

(but in this case, it would say to select a measurement first)

- User will NOT be able to select more than one measurement

- Once a measurement is selected the next panel will not give an option for _measurement

- When building the flux query, the query will have only one measurement in the script

- When converting to flux the user will only have one measurement selected (if they have selected one)

- User doesn't see a filter dropdown in the measure selection panel

- For pre-existing notebooks that already have more than one measurement, the old UI will be shown for backward compatibility

## Design Notes

<p></p>

- The current design has a number showing the number of measurements selected; this needs final determination as some feel that more than 1 measurement should never be allowed

<p></p>

<p></p>

<p></p>

<p></p>

**Comment by drdelambre** [comment]
note for engineering: in notebooks, you can save a query builder, meaning there's a migration to deal with here. this solution should also handle the case where a user has an existing query builder that has selected something other than a _measurement for the first column as well as any _measurement columns that already have multiple selections. a simple first stab might be to just have those columns as read only with the ability to delete, but not mutate. propose the chosen solution to product before proceeding
