### ISSUE TITLE
Notebooks - Show all Fields and Values

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#4254]
## **Story Description & Background**

<p></p>

The current Notebooks interface shows the user a list of fields and values after making in the group/filter panel of the query builder.  Currently it only shows fields and values that appear in the data within the current time range set by the user in the interface.

<p></p>

But as a SaaS service provider, I want to let my users see all of the possible fields/values so that I don't have to filter the metadata when gathering it and so that I don't confuse the user and think they have data missing.

<p></p>

## Suggested Implementation

<p></p>

- When showing a list of fields/values - show the complete list, not filtered by date range

## Acceptance Criteria

<p></p>

- When user looks at the drop down list after selecting a bucket and measurement, they will see a complete list of field/tag/values; not filtered by their time range

<p></p>

## Notes

<p></p>

- Another user story handles changing the behavior to show complete list of measurements instead of filtering them by data

<p></p>

<p></p>

<p></p>

<p></p>

**Comment by garylfowler** [comment]
Link to feature: https://influxdata.productboard.com/feature-board/planning/features/12705190

**Comment by drdelambre** [comment]
NOTE: this is just removal of the time constraint from the queries that fetch these
