### ISSUE TITLE
Flux Centric Script Editor (New Data Explorer)

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#4287]
## EPIC Description

<p></p>

As part of the query experience project, the query experience team identified a number of design elements they want to include in the new user query experience and start to build out an MVP version for user feedback.

<p></p>

**The new interface will have four main sections:**

<p></p>

1. A schema browser area where the user is shown a tree view of their data.  They will start by seeing a list of buckets.  They can "expand" that bucket list to see a list of measurements inside.  They can expand a measurement and then see a list of fields inside.

2. A Flux Script Panel; this is intended to be the focal point of the interface and "front and center".  When starting a new query, this script window will be empty until the user starts adding to it, but will eventually hold the complete contents of the script they are building.

3. A Data View or Preview Panel.  This will be the area where results are shown after executing their script.  The requirements around this window will be made in a separate EPIC.

4. A list of searchable flux functions panel.  This will allow the user to search through flux functions to choose one they want to use in their script.  This will be much like what the script editor has today.

<p></p>

<p></p>

In addition to these 4 main areas, there will be a time range selector, similar to what is in place today. 

<p></p>

**Some general concepts:**

<p></p>

1. Users will be able to always manually type in the script panel.  If they know flux and can write a flux script, they are not required to select anything from the schema menu nor the flux function area.

2. Users will be able to select items from the schema and INJECT them into their flux script.  At the injection point, the appropriate flux query lines that go along with their selection will be inserted into the script.

3. Injection trigger will be a button offering to Inject ~~and replace or Inject and append (button wording TBD).  is still TBD; items discussed are drag and drop from schema list;~~ ~~right click on schema item and see a submenu of "inject" and "preview" or a submenu of "filter by this field" or "group by this field";  a double-click on the item; a checkbox selection for the item.~~   NOTE:  This is currently still being debated and may change in approach.

4. When the injection is triggered, the appropriate lines of flux will be added.  Injection won't be available until the user has selected a measurement or field (it will not be available after only a bucket selection).  The injection will include the from, date, range, and filter selection the user has made.

5. Like with schema items, users will be able to inject flux functions into their script; with the injection trigger still TBD.  It may be an inject button like it is today, but may be drag and drop.

6. There is no expectation to automatically remove items that were previously injected from the schema if the user chooses a different item from the schema, the user will simply be starting a new query and replacing the existing flux.  If the user doesn't want what was previously injected, they can also just manually remove those lines.  This will likely change after user testing.

7. The result view, for now, will be a 10 line table preview as shown today in Notebooks from the result of a query.  This will be temporary, and the work to enhance this view into a streaming preview will be tracked in a different EPIC.

8. The user will be able to re-size the four windows to meet their desired real-estate ratio

9. Once there is at least a bucket and a measurement in the flux script window, the user will than have a run button available to them

10. Load/Save options will be added on in a separate EPIC

11. LSP will be added on in a separate EPIC (unless existing work can be re-used).

12. The schema view will show all buckets, measurements, and fields (all metadata) without regards to the current time range set.

13. When injecting a schema item into the script, the timerange variables will be automatically put into the from statement.

14. No visualization options beyond the data preview is expected for this EPIC, that will be added on later.

15. Errors can be shown to the user in the data preview section for this first iteration

16. Users will have an option to undo any injection made

<p></p>

## General Acceptance Criteria

<p></p>

- Users will be able to browse their schema to see list of buckets available to them

- Users will be able to browse their schema to see lists of measurements within each bucket

- Users will be able to browse their schema to see lists of fields within each bucket

- Users will be able to select fields to inject into their script; when doing so, the script will build the appropriate from, range, and filter lines

- Users will be able to "search" for buckets, measurements, fields as well as seeing them in a tree view

- Users will be able to inject functions from a function list into their script

- Users will be able to use keywords to search for the function they are looking for

- ~~Items will inject to the point of the cursor in their script (both schema items and flux functions)~~

- When the script has a bucket and measurement selection, a Run option/button will be made available; it will be grayed out or otherwise unavailable until then

- Users will be able to write and run scripts regardless of whether or not that have injected items from the schema or the function list

- ~~A 25 point preview will be shown to the user upon a successful flux script run~~

- While a script is running (for now), the user will only have a visual indication as such, and the run button/option won't be available (this will hopefully change in a later revision)

- When a flux script is re-ran, the data preview from the previous run will go away until the new run completes

- When injecting from the schema or from the flux functions, the user will have an option to "undo" their changes

- It is not expected at this time to be able to "undo" more than 1 injection (go back further)

<p></p>

## Notes

<p></p>

The objective of the MVP is to have functional prototype for user testing.  It is expected that there will be significant changes after user testing.

## Schema Browser Design:

![](https://pb-files.s3.amazonaws.com/production/attachments/c357fd2d77e02bdf6087e7bf1229f06706dbdda666f56ad9c1aaf870ca299b01/image.png)

## Success Criteria

<p></p>

Some criteria for measuring the success of this project:

<p></p>

- Greater than 50% of the users that try the "New Data Explorer" stay with this option  and don't go back to the old

- A larger percentage of queries do not timeout than with the old implementation

- The overall time it takes from the launch of data explorer to the time of first query result has been reduced from previous numbers (averages)

- The overall number of queries performed grows at least a slightly higher rate than it grew previously

- General (subjective as it may be) feedback is more positive than with previous data explorer

- Larger percentage of users are making manual flux edits than before

<p></p>

**Comment by garylfowler** [comment]
Link to feature: https://influxdata.productboard.com/feature-board/planning/features/12699535

**Comment by jzahnd** [comment]
First step is to schedule a kickoff

**Comment by wiedld** [comment]
Core of this work is done. Closing.
