### ISSUE TITLE
InfluxDB Beta is changing the default port from 9999 to 8086

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#43]
the pr for this change is here: https://github.com/influxdata/influxdb/pull/19494

**Comment by drdelambre** [comment]
note: i think this is isolated to OSS GA, but if i'm wrong and this resurfaces for cloud local dev, we just need to update the ingress controller's nginx conf in monitor-ci:
https://github.com/influxdata/monitor-ci/blob/master/conf/ingress/nginx.cloud.conf#L80

**Comment by russorat** [comment]
fixed in https://github.com/influxdata/ui/pull/825
