### ISSUE TITLE
Unable to access UI

### ISSUE THREAD

**Issue by kevin192291** [influxdata/ui#4328]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

Simply try to access the UI via https://cloud2.influxdata.com/ and click any menu item.

**Expected behavior:**

**Actual behavior:**

**Visual Proof:**

## About your environment

**Environment info:**

**Config:**
Not sure, I am using the Cloud Instance

**Logs:**
N/A

I am getting an error in my dev-tools console as such:

```
Uncaught SyntaxError: Unexpected token '<' (at 73.7416b0fc16.js:1:1)
27.8601cc9885.js:2 ChunkLoadError: Loading chunk 73 failed.
(missing: https://ap-southeast-2-1.aws.cloud2.influxdata.com/static/73.7416b0fc16.js)
    at Function.n.e (f7c5d48c31.js:1:15722)
    at 28.007d586a2d.js:1:669241
    at O (27.8601cc9885.js:2:2496049)
    at Zs (27.8601cc9885.js:2:2610221)
    at Tu (27.8601cc9885.js:2:2596917)
    at Du (27.8601cc9885.js:2:2596845)
    at Su (27.8601cc9885.js:2:2596708)
    at bu (27.8601cc9885.js:2:2593695)
    at 27.8601cc9885.js:2:2543482
    at t.unstable_runWithPriority (27.8601cc9885.js:2:2620340)
```

**Comment by kristinarobinson** [comment]
@kevin192291 - Thanks for filing this defect.  This is a known issue that occurs when the UI application has gone through a recent deployment, and some assets do not load completely.  @jzahnd , what is the workaround for this when it occurs?

**Comment by kristinarobinson** [comment]
@kevin192291 - I checked with our team, and a hard refresh of your cache will fix this issue.  (for Chrome, open Dev Tools, then hold shift-click on the refresh icon and then select `Hard Refresh`). On Mac the shortcut is CMD-SHIFT-R.  Let us know if this does not resolve your issue.  Thanks.
