### ISSUE TITLE
"An InfluxDB error has occurred. Please report the issue here."

### ISSUE THREAD

**Issue by ono760** [influxdata/ui#434]
On my personal Cloud 2 account https://us-west-2-1.aws.cloud2.influxdata.com/, I click on “Data” to select  Telegraf plugins but I get a message: “An InfluxDB error has occurred. Please report the issue here.” 

<img width="1792" alt="Screen Shot 2020-12-14 at 7 44 32 PM" src="https://user-images.githubusercontent.com/14097441/102168282-d78d6c00-3e44-11eb-9756-9ed662838699.png">

<img width="1611" alt="Screen Shot 2020-12-14 at 7 44 18 PM" src="https://user-images.githubusercontent.com/14097441/102168281-d65c3f00-3e44-11eb-96a8-9027ed126d10.png">

**Comment by mnorriswalker** [comment]
@ono760 this error generally isn't to do with any particular part of the app but because internal users tend to log into a bunch of different accounts and have session issues piled up. Please clear cache, hard refresh, and if need empty local storage.
