### ISSUE TITLE
Flux Dynamic Help Panels: tooltip should indicate required or optional for parameters

### ISSUE THREAD

**Issue by TCL735** [influxdata/ui#4342]
In this feature, when the user hovers over a function, the tooltip shows the parameters with their names and descriptions, but there is no indication on whether a parameter is required or optional. This can be especially confusing when the user injects the function and does not see any placeholder text between the parentheses. To help the user understand why a parameter will not be injected, the tooltip will indicate if a parameter is required or optional.

BEFORE:
<img width="432" alt="Screen Shot 2022-04-07 at 10 04 18 AM" src="https://user-images.githubusercontent.com/10736577/162258392-40b3014c-bec5-498d-a44e-09ba57a946b7.png">

AFTER:
<img width="422" alt="Screen Shot 2022-04-07 at 10 04 41 AM" src="https://user-images.githubusercontent.com/10736577/162258428-38de1f12-07b0-449a-854f-85f962131f8a.png">

<img width="420" alt="Screen Shot 2022-04-07 at 10 05 38 AM" src="https://user-images.githubusercontent.com/10736577/162258462-b9f960b0-38f1-4b53-b039-b75ac7d69495.png">

<img width="421" alt="Screen Shot 2022-04-07 at 10 05 11 AM" src="https://user-images.githubusercontent.com/10736577/162258493-13255bbf-0938-405c-ae77-c8978ee113ac.png">

**Comment by brandenTenbrink** [comment]
Seems good to me. Only thing I would add is to change the color of required so it stands out from the parameter name and optional. Perhaps making it a red/red variant to match the standard we use with required input fields?

**Comment by TCL735** [comment]
@brandenTenbrink sounds good! Yes, we will change the color of required.

**Comment by blegesse-git** [comment]
i'm on it! @TCL735
