### ISSUE TITLE
'Shift + Click'  Pan Graph Window tip does not work in Chrome

### ISSUE THREAD

**Issue by ivankudibal** [influxdata/ui#435]
Thank you for reporting a bug in InfluxData UI.

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Open Dashboard in UI, click on ? 
2. There is the tip 'Shift + Click'  Pan Graph Window
3. Use the tip on the chart..

![image](https://user-images.githubusercontent.com/8028110/102244223-509bca80-3efc-11eb-99c7-d37fc425d695.png)

**Expected behavior:**
Describe what you expected to happen.

Pan

**Actual behavior:**
Describe What actually happened.

Zoom action instead of Pan

**Environment info:**

Cloud2

**Comment by hoorayimhelping** [comment]
see https://github.com/influxdata/giraffe/issues/426
