### ISSUE TITLE
Create template with no flux

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#4375]
I want to be able to save a cell without a query so that we can educate users on dashboards and cells without them needing data written yet or any data queried. 

The flux trainers have asked for a "blank" template that has no flux in it, as a way to teach their flux classes.  Can we instigate whether this is possible?

Today's behavior:  If you try to create a template with an empty flux entry, the export / import statements are successful, but the cell doesn't show up.

From Emily Kurtz:
`They can’t import a dashboard with an empty query, it says that it was imported successfully but it doesn’t seem to work. Is there any way we can create a placeholder dashboard that would then let students fill in the query?`

**Comment by hoorayimhelping** [comment]
Can we get some more information about the empty query they're using? What's the query look like, what does the data they're querying look like?

**Comment by Luckette** [comment]
Met with @emilykurze on 7/19/22. Shes going to get back to me with more information. However, we still need the ability to save a cell even if it's not returning any data so that users can learn about dashboards and cells.

**Comment by ALuckette** [comment]
confirmed with @emilykurze that this ticket can be closed.
