### ISSUE TITLE
Large notebooks appear to save but don't

### ISSUE THREAD

**Issue by onelson** [influxdata/ui#4383]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. create a new notebook
2. idk, make it large (I pasted raw csv at ~156k as a string literal)
3. save the notebook to the version history (for good measure)

**Expected behavior:**

I expected my notebook to save, or to indicate saving had failed.

**Actual behavior:**

Saving appeared to be working, but changes were not persisted.

In the network tab, I can see 413 status responses coming back to the client.

**Visual Proof:**

https://user-images.githubusercontent.com/301388/163008767-9bdd7729-bb36-49e3-9e5f-1265dc7b4d05.mp4

## About your environment

**Environment info:**

cloud2

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by appletreeisyellow** [comment]
This bug is fixed and you can save large notebooks now! @onelson
