### ISSUE TITLE
Test Font Updates in Pending Clockface Update

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#4394]
Per influxdata/clockface#758, we would like to update the fonts in Clockface to match the recent marketing brand changes. We have a request to have a member of the Unity team test locally with a designer to catch any large spacing or other obvious issues that we could correct before moving to a live environment.

**Comment by appletreeisyellow** [comment]
Tested locally, aside from some minor changes in ui, no major issues. I talked to Branden, and he said that he and Bucky would pull the clockface version 4.0.0 on ui into staging on Monday (Apr. 25) for testing.
