### ISSUE TITLE
InfluxDB issue

### ISSUE THREAD

**Issue by alvynabranches** [influxdata/ui#4412]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Getting an issue page after having around 1M records

**Expected behavior:**

**Actual behavior:**

**Visual Proof:**

## About your environment

**Environment info:**

 Darwin 21.4.0 arm64
--> Using influxdb:latest image (pulled on 17th Apr)

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by jzahnd** [comment]
Thank you for filing an issue. In order to help, we need a few more things.

Can you tell us:
What happened when the error occurred?
How to reproduce it?
What browser are you using?

Thanks for using InfluxDB.

**Comment by alvynabranches** [comment]
I found that InfluxDB doesn't not allow the load I produce on a free tier even on local installation hence I moved to TimeScaleDB.
