### ISSUE TITLE
hangup when editing script

### ISSUE THREAD

**Issue by rogpeppe** [influxdata/ui#443]
**Steps to reproduce:**

In a script editor in Data Explorer, paste this text:
```union(tables: [a```
then start typing this text after the final `[a`:
```, ini```
This hangs up forever for me

**Environment info:**

Cloud2.
Chrome 87.0.4280.66

**Comment by drdelambre** [comment]
cannot repro. @scbrickley did you fix this some other way?

**Comment by scbrickley** [comment]
I'm not 100% sure, but it's possible this was caused by https://github.com/influxdata/idpe/issues/9592, which was resolved in https://github.com/influxdata/flux/pull/3487

**Comment by drdelambre** [comment]
awesome. imma close this. as always, anyone should feel free to reopen it if the behavior is still floating around
