### ISSUE TITLE
firstMile: nodejs - Write Data Bugs

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4468]
## nodejs Write Data

_Bugs discovered on 4/25 during validation of the nodejs onboarding wizard_

ACs
   - The write failed, Add flush to the write data code snippet
   - Escape characters by wrapping the write code snippet in back-ticks
   - Revise the node command for write data to prevent printing out the timeout details to prevent confusing the user

**Comment by ChitlangeSahas** [comment]
Closed in https://github.com/influxdata/ui/pull/4470

cc: @hoorayimhelping
