### ISSUE TITLE
firstMile: nodejs - Execute a Simple Query Bugs

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4469]
## Execute a Simple Query (nodejs)

_Bugs discovered on 4/25 during validation of the nodejs onboarding wizard_

**Findings**

        - Bucket name did not automatically get added to the query code snippet. (The wrong bucket name did get automatically added to the code snippet). "fooo" was accidentally hard coded
        - Initialize query with a 'let' not a 'const'

**Comment by ChitlangeSahas** [comment]
Closed in https://github.com/influxdata/ui/pull/4470

cc: @hoorayimhelping
