### ISSUE TITLE
firstMile: nodejs - Execute an Aggregate Bugs

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4471]
## Execute an Aggregate (nodejs) 

_Bugs discovered on 4/25 when validating the nodejs onboarding flow_

ACs

        - Initialize the query with a 'let' not a 'const'

**Comment by ChitlangeSahas** [comment]
Closed in https://github.com/influxdata/ui/pull/4470

cc: @hoorayimhelping 

Note: considering the user will have one file, we do not need `let` in front of the query since it was defined in the Execute a simple query page.
