### ISSUE TITLE
firstMile: nodejs - Final Page Bugs

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4473]
## Final page (nodejs)

Bugs discovered on 4/25 during validation of the nodejs onboarding flow

ACs

         - Do not send "thumbs-up/down" results to the backend more than once in the event the user clicks the thumb more than once. We don't want to skew the data. 
         - Remove the "Sample App" box from nodejs & GO (Just for the first release to production since we don't yet have a sample app prepared for nodejs and GO)

**Comment by hoorayimhelping** [comment]
see https://github.com/influxdata/ui/issues/4474
