### ISSUE TITLE
use a paste-capable time format in Custom Time Range

### ISSUE THREAD

**Issue by rogpeppe** [influxdata/ui#448]
The "Custom Time Range" dialog usefully provides the start and end timestamps
in a textual format, but it would be even more useful if those timestamps were
in RFC3339 format so they could be pasted directly into the Flux script as
described [here](https://docs.influxdata.com/influxdb/v2.0/reference/flux/language/lexical-elements/#date-and-time-literals).

So instead of `2020-12-16 13:01:22.667` it would show `2020-12-16T13:01:22.667Z`.

**Comment by jzahnd** [comment]
We need to investigate where this is formatted and update accordingly.
