### ISSUE TITLE
Library Maintenance: Update package.json's node engine to use current LTS

### ISSUE THREAD

**Issue by jdstrand** [influxdata/ui#4487]
https://github.com/influxdata/ui/pull/4445 updates package.json to use the last LTS (14). This is still supported until April 2023 so there is no immediate urgency, but it would be nice to be on the latest LTS at some point.

Note, there is a dependency on `cypress-slim`s image that is described here: https://github.com/influxdata/ui/pull/4445#issuecomment-1109942632. Essentially, to use the latest node LTS, https://github.com/influxdata/cypress-slim/blob/main/Dockerfile#L2 needs to be updated to use node 16 and then ui's `package.json` should be able to specify node 16 too.

**Comment by kristinarobinson** [comment]
Either team can work on this.
