### ISSUE TITLE
Font Icons - icons aren't being displayed, random text is shown instead

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4506]
hard to reproduce, but, sometimes the subway icons don't load. 

## Screenshot
![image](https://user-images.githubusercontent.com/112978673/189141985-c62ee7a9-7489-46b2-967b-fa143849b5bc.png)

**Comment by ChitlangeSahas** [comment]
I tried a couple times, can't seem to reproduce this.

**Comment by taramk** [comment]
we think one way to trigger this is to enable a feature flag. and if it's the same issue we're seeing elsewhere, it's a global issue not specific to onboarding. @wdoconnell cc @brandenTenbrink

**Comment by taramk** [comment]
<img width="326" alt="image" src="https://user-images.githubusercontent.com/1813419/185469585-b4964d2b-ed00-448b-89e5-0a745782bb7f.png">

See example in this usability video, at about 8 minutes in:
https://influxdata.zoom.us/rec/share/awy83DVxNE0ZaWhGWm7hesyAyd7OjcHU08d02qWROQR5JuCdXVG1lHeVzjOZpEeS.tl1f5Pt5sYDhk5G9 Password: han7%X^m

**Comment by hoorayimhelping** [comment]
These characters can be seen in the following video around the 9 second mark. They display briefly before the icon fonts pop in. I screenshoted the before and after as well.

https://user-images.githubusercontent.com/146112/189995844-2e4817d6-9a5c-40a2-af10-d2fa78e1a83d.mov

### Before
![before](https://user-images.githubusercontent.com/146112/189995885-e3624abb-5805-4fb2-84f8-0dc0246a440a.png)

### After
![after](https://user-images.githubusercontent.com/146112/189995907-6fd113a8-6d60-47be-830a-91ae0cb1bb1a.png)

**Comment by hoorayimhelping** [comment]
This means there's an issue loading the icon fonts. This only shows up under local dev situations when the browser is instructed to disable caching on network requested resources. This implies that when people see the issue in prod, the font loading has failed for some reason probably related to caching.

**Comment by ALuckette** [comment]
FYI @brandenTenbrink

**Comment by gunnaraasen** [comment]
I keep running into this. I see these errors in the console that seem related, but they also pop up when the font icons render correctly.

```
Failed to decode downloaded font: <URL>
members:1 Failed to decode downloaded font: https://eastus-1.azure.cloud2.influxdata.com/d4dcdc1a67.woff2
...
OTS parsing error: invalid sfntVersion: 1008821359
members:1 OTS parsing error: invalid sfntVersion: 1008821359
```

**Comment by hoorayimhelping** [comment]
So it doesn't get lost, I found this SO question that appears to be having the exact same issue: https://stackoverflow.com/questions/56800083/browser-sometimes-uses-the-wrong-font-to-render-icons-resulting-in-garbled-text

**Comment by ChitlangeSahas** [comment]
I dug a bit into this, the issue is basically the parsing of `scss` files. Most of the times the parsing is done right and we have normal looking fonts. But every now and then the unicode characters are parsed incorrectly, specially in chrome. 

This leads to an incorrect value in the end css file that the browser references. 

For example, here I simulate the conversion of SCSS to CSS file gone wrong, by manually changing the content value. We can see that the characters go wild.

https://user-images.githubusercontent.com/18511823/191674735-7668f960-6acc-464b-8292-223123389aa4.mov

My proposed solution is to use CSS file instead, I will run this by design team, but since the tool we use to generate these files gives us CSS output, I think it's a worthwhile try!

**Comment by hoorayimhelping** [comment]
The first attempt to fix this didn't work - there are still examples happening in the wild. After more digging, it seems this is a bug in Chromium when it comes to rendering unicode characters. Attempting this solution next: https://stackoverflow.com/questions/69466120/troubles-with-webpack-sass-and-fontawesome
