### ISSUE TITLE
Basic Schema Browser

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#4510]
## User Story

<p></p>

As a user, I want to be able to see the buckets, measurements, fields, tag keys, and tag values that are available to me to query so that I understand the shape of my data and I know what I can use in my query.

<p></p>

## Acceptance Criteria

<p></p>

- Schema Browser will show a list of buckets available to the user

- Schema Browser will allow one (and only one) bucket to be selected from the list

- Schema Browser, upon bucket selection, will show a list of measurements to the user; this will be a list not bound by the time range selection

- Schema Browser will allow the user to select one (and only one) measurement

- Schema Browser, upon measurement selection, will show a list of fields, and tag keys to the user

- Schema Browser will allow an expansion of Tag keys into a list of tag values

- Schema Browser will allow the one or more tag values to be selected

- The first 10 items (or less if less than 10 exist) in any list (buckets, measurements, fields, tag keys, tag values initially so that the user sees there are more types of things to choose from

- When there are more than 10 items in any list, then the user will be shown a "Load More" entry where they can choose to load more

- When Load More is chosen, up to 25 additional entries will be shown to the user; if more than 25 more exists in the list, the user will again have the option to load more which will result in an additional 25

- User will be able to "search" buckets which will then filter the list of buckets dynamically to match what has been entered into the search area (for instance, if "b" is entered - then the list will only show buckets that start with b" - if "bl" is entered, then only buckets that start with "bl" will be shown

- User will be able to search measurements, fields, tags, and tag values in the same fashion

- Schema browser will be shown within the "Try new Data Explorer" view

- Schema browser will be hold the far left side of the interface

- Schema browser will be vertically scrollable

- Schema browser will not be horizontally scrollable, but the size of the schema browser can be resized larger and smaller horizontally

- Schema browser will have a basic tree structure indentation to show a hierarchical view of their data:  Bucket at the top level, then measurements, then fields and tag keys, then tag values under tag keys

- A title will appear above the various lists/selection area to clearly show the user what those elements are:  Bucket, Measurements, Fields, and Tag Keys (tag values will appear only as the values themselves under the tag key - so no additional title necessary)

- For fields and tag values, a "select all" option will appear at the top of the list that can be selected

- For bucket, measurement, field, and and tag keys, and information button will be available next to the title that can be selected to provide an overlay description of the element and link to documentation for it (content to be defined separately, for this story - placeholder text can be used)

- Only one bucket can be selected and when selected, the selection is shown and the list is collapsed

- Only one measurement can be selected and when selected, the selection is shown and the list is collapsed

<p></p>

## Notes

<p></p>

The story does not include requirements for injection of the selections into a flux script; that will be done in a separate story

<p></p>

## UI Design

<p></p>

<p></p>

See the data selection section from this FIGMA mockup:

<p></p>

<https://www.figma.com/proto/0qAntPk5LVangAHguWT74X/Query-Experience-Project?page-id=191%3A13710&node-id=567%3A21115&viewport=241%2C48%2C0.15&scaling=min-zoom&starting-point-node-id=567%3A21115>

<p></p>

Note:  The selection checkboxes shown here are no longer required and don't need to be included:

![](https://pb-files.s3.amazonaws.com/production/attachments/af9ca9a8b17997153fc1184ceb4f3c5d249e9213be085ed8f6244cb6a3b5136a/image.png)

<p></p>

<p></p>

<p></p>

<p></p>

<p></p>

<p></p>

<p></p>

<p></p>

**Comment by influx-product-manager** [comment]
Link to subfeature: https://influxdata.productboard.com/feature-board/planning/features/13130222

**Comment by garylfowler** [comment]
This is part of EPIC #4287
