### ISSUE TITLE
Flux function search breaks on periods

### ISSUE THREAD

**Issue by sanderson** [influxdata/ui#4524]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Go to the Data Explorer
2. Search for any function in a package (`usage.from` for example)
3. When you enter the period to delimit the package from the function, no results are returned

**Expected behavior:**
I would expect results for an exact string match if it is an exact string match.

**Actual behavior:**
The search returns no results after entering a period.

**Visual Proof:**
![Kapture 2022-04-29 at 08 20 56](https://user-images.githubusercontent.com/181484/165963431-c82c1643-7d69-47e3-8c5b-684c5cae501d.gif)

## About your environment

**Environment info:**

- InfluxDB version: InfluxDB Cloud
- Other relevant environment details: Production

**Comment by TCL735** [comment]
So, I don't think this is a bug per se.

The user can search for function name **_OR_** package name, but not as a combination. Granted, the UI doesn't make this clear. So maybe we need something in there, placeholder text perhaps, to communicate that they can search for either function name or package name but not both at the same time.

**Comment by blegesse-git** [comment]
I like that idea. We can add a placeholder that says '_Filter by package or name_'
![Screen Shot 2022-05-10 at 10 44 58 AM](https://user-images.githubusercontent.com/66275100/167668971-0901d271-77b7-4565-8374-b4845dd9cc44.png)
