### ISSUE TITLE
Flux Editing Window

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#4529]
## User Story

<p></p>

As a user, I want to be able to edit my flux script directly when doing any query, without having to switch to a separate script editor, so that I can use both visual tools and do manual editing all at the same time.

<p></p>

## Notes

<p></p>

- For right now, this can simply be the same editing window that exists in the script editor in the current DE & Notebooks when you switch to it

- Eventually, we will want to incorporate the LSP changes and have it be a part of this; if we are ready for that - we can implement them here - but there is not a requirement for it at this time

- Run button and other options will be defined in a separate story

<p></p>

## Acceptance Criteria

<p></p>

- A flux editing window will be available on the "Try new Data Explorer" screen

- A flux editing window will be available just to the right of the schema browser on the top half of the window

- The flux editing window will allow users to type flux scripts inside of it

- The flux editing window can be re-sized

- The flux editing window is scrollable when the script won't fit on the top half of the window

<p></p>

See link for prototype showing location of flux window in "Try new Data Explorer" screen.

<p></p>

<https://www.figma.com/proto/0qAntPk5LVangAHguWT74X/Query-Experience-Project?page-id=191%3A13710&node-id=567%3A21115&viewport=241%2C48%2C0.15&scaling=min-zoom&starting-point-node-id=567%3A21115>

<p></p>

<p></p>

**Comment by influx-product-manager** [comment]
Link to subfeature: https://influxdata.productboard.com/feature-board/planning/features/13145167

**Comment by garylfowler** [comment]
This is part of EPIC: https://github.com/influxdata/ui/issues/4287

**Comment by wiedld** [comment]
Done.
