### ISSUE TITLE
SPIKE: RBAC the UI

### ISSUE THREAD

**Issue by asalem1** [influxdata/ui#4541]
With roles being an upcoming app-wide concern, we should explore the level of effort required for segmenting the application and allowing for RBAC in the UI

**Comment by drdelambre** [comment]
these aren't defined in the data models yet, what would the spike be about?

**Comment by asalem1** [comment]
> these aren't defined in the data models yet, what would the spike be about?

It could be helpful for us to take a look at how granular we can get to segmenting the UI. Whether we want entire parts of the app to be off-limits based on mocked roles, or add restrictions to API requests from being made based on user permissions / prevent DOM elements from being rendered for the same qualifiers. 

All those are really vague, but it's more of an exploration on how we might want to segment the app based on:

1. Access to resources based on permissions (for now just has access / doesn't have access)
2. Access to DOM elements (conditionally rendering buttons, for example) based on access restrictions (again, assuming an all or nothing approach)
3. Access to API endpoints via the UI (ideally this would be guarded in the API, but it might be worth seeing how useful / feasible it would be to have overarching permission checks on the function calls prior to making them on the UI)

**Comment by ALuckette** [comment]
There is now a dedicated initiative for Roles and Permissions. This is being led by @evinaku and being worked across three teams (API, AIM, + Dumplings)

Closing this ticket.
