### ISSUE TITLE
ColorBlind hex colors

### ISSUE THREAD

**Issue by zoesteinkamp** [influxdata/ui#4549]
## ACs
- colorblind-friendly option added to the dropdown of color options per graph
- User can change the line graph display per graph to be colorblind-friendly using this newly defined pallet: 

export const LINE_COLORS_BLIND = [
  {
    type: COLOR_TYPE_SCALE,
    hex: '#000000',
    id: nanoid(),
    name: 'Color Blind Friendly',
    value: 0,
  },
  {
    type: COLOR_TYPE_SCALE,
    hex: '#E69F00',
    id: nanoid(),
    name: 'Color Blind Friendly',
    value: 0,
  },
  {
    type: COLOR_TYPE_SCALE,
    hex: '#56B4E9',
    id: nanoid(),
    name: 'Color Blind Friendly',
    value: 0,
  },
  {
    type: COLOR_TYPE_SCALE,
    hex: '#009E73',
    id: nanoid(),
    name: 'Color Blind Friendly',
    value: 0,
  },
  {
    type: COLOR_TYPE_SCALE,
    hex: '#F0E442',
    id: nanoid(),
    name: 'Color Blind Friendly',
    value: 0,
  },
  {
    type: COLOR_TYPE_SCALE,
    hex: '#0072B2',
    id: nanoid(),
    name: 'Color Blind Friendly',
    value: 0,
  },
  {
    type: COLOR_TYPE_SCALE,
    hex: '#D55E00',
    id: nanoid(),
    name: 'Color Blind Friendly',
    value: 0,
  },
  {
    type: COLOR_TYPE_SCALE,
    hex: '#CC79A7',
    id: nanoid(),
    name: 'Color Blind Friendly',
    value: 0,
  },
]

## Proposal
Add a colorblind palette for the options in graphColorPalettes.ts 

**Current behavior:**
We currently have no colorblind-friendly color palette 

**Desired behavior:**
An option for colorblind-friendly

**Options**
Where in the app would the colors, shades, & shapes templates apply? 
- Graphs
- Graph type [tables, lines] may determine what is better (colors, shades, shapes)

## Info
It looks like we now only feed three hex colors into the colors array, I assume that's in case we have a ton of lines we can just have multiple color shades. Do we have a maximum amount of lines we display? So we could set the array of colors to be ex: 8? If not the colorblind option will have to an extent a limit in the fact that for color-blind people some shades can be hard to differentiate. I am using a code example of the wong color palette, [info can be found here](https://davidmathlogic.com/colorblind/#%23D81B60-%231E88E5-%23FFC107-%23004D40)

**Comment by Luckette** [comment]
Thank you @zoesteinkamp !!!
