### ISSUE TITLE
Bug: Cancel Account Data Collection, Data Routing, & Analytics

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4561]
**Problem**
The data-flow on the cancellation page is broken. Either take it down or make sure the data gets routed somewhere. 

**Findings**
This is what we collect when a user cancels their account:
- _start
- _stop
- _time
- _value
- _field
- _measurement
- alternativeProduct
- email
- env
- org
- org (account_type)
- org (hide_upgrade_cta)
- orgID
- reason
- role
- suggestions
- tier
- userEmail
- userID
- version

Here is the modal that displays to users when they choose to cancel their account: 
![Image](https://user-images.githubusercontent.com/98195941/181107701-5d4b0fca-d9cb-467b-a3d5-a1dffaec65f7.png)

Sample record: 
- 2022-07-15T20:07:36.534097443Z
- 2022-07-22T20:07:36.534097443Z
- 2022-07-20T11:46:07.944Z
- ui
- source
- Delete Org Executed
- sebastian.ziemann@welect.de
- ip-10-153-10-205.eu-central-1.compute.internal
- 5f1bb9afd8cf9fc7
- free
- 5f1bb9afd8cf9fc7
- Other reason
- frontend-services
- free
- sebastian.ziemann@welect.de
- 44009bfb10db9f53
- c9592531e2128fbdb23b66524d2c8f08da3bcab8

**Comment by Luckette** [comment]
@moreainflux may have more details.

**Comment by moreainflux** [comment]
Adding comments: This is a marketo form but the data doesn't seem to be going through the form at all. Form script might have been wrongly copied. 

<script src="//get.influxdata.com/js/forms2/js/forms2.min.js"></script>
<form id="mktoForm_2625"></form>
<script>MktoForms2.loadForm("//get.influxdata.com", "972-GDU-533", 2625);</script>

FYI @tcrumpler

**Comment by Luckette** [comment]
@gunnaraasen Does your team own this?

**Comment by kristinarobinson** [comment]
Bucky, please reach out to Morea in order to repro

**Comment by moreainflux** [comment]
@kristinarobinson I dont think Bucky was tagged

**Comment by veereshhosakere** [comment]
++ @hoorayimhelping ^

**Comment by Luckette** [comment]
@moreainflux @mona-influx I added some findings to this ticket. The UI is collecting data when users cancel their accounts.

**Comment by chenningma** [comment]
@chenningma will look into cancel UI events data

**Comment by chenningma** [comment]
new cancel service UI dashboard: https://influxdata.domo.com/page/1571532743
It does look like there's been a big drop off in events (cancel_service_executed) between May and June
<img width="1661" alt="Screen Shot 2022-08-15 at 1 41 53 PM" src="https://user-images.githubusercontent.com/74034904/184696135-666d5981-6c1e-4413-a4fb-1e3dcd4e412b.png">

**Comment by chenningma** [comment]
Maybe someone can confirm that 'cancel_service_initiated' was firing incorrectly? And that 'cancel_service_initiation_event' is the more correct event to track? The first one was firinging 1000+ time before June. The second event is firing at a more reasonable count per month

**Comment by ALuckette** [comment]
This is done. Closing this ticket. @chenningma created a Domo chart to show cancellations based on UI eventing that's properly in place. Thanks all. 

FYI @kristinarobinson
