### ISSUE TITLE
Error screen upon user signup

### ISSUE THREAD

**Issue by sridhareaswaran** [influxdata/ui#4574]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. ...
2. ...
3. ...

**Expected behavior:**

**Actual behavior:**

**Visual Proof:**

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by asalem1** [comment]
@sridhareaswaran, thanks so much for reporting this bug. This seems to have been an issue that was rolled out to production, but has since been resolved. Try and hard refresh the page / logging in through an incognito window and let me know if it's still an issue
