### ISSUE TITLE
Commas in strings break table visualization rendering

### ISSUE THREAD

**Issue by sanderson** [influxdata/ui#4583]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Go do the **Data Explorer**.
2. Select the **Table Visualization**.
3. Switch to the **Script Editor**.
4. Enter and run the following query:

```javascript
import "array"

array.from(rows: [
    {col1: "This string does not have a comma and renders correctly", col2: "This is col2"},
    {col1: "This string has a comma, so this part is rendered in a cell that it shouldn't be", col2: "This is col2"},
])
```

**Expected behavior:**
The table should render something like this:

| col1                                                                                   | col2         |
| :------------------------------------------------------------------------------------- | :----------- |
| This string does not have a comma and renders correctly                                | This is col2 |
| This string does have a comma, so this part is rendered in a cell that it shouldn't be | This is col2 |

**Actual behavior:**
The table gets rendered like this:

| col1                                                    | col2                                                    |
| :------------------------------------------------------ | :------------------------------------------------------ |
| This string does not have a comma and renders correctly | This is col2                                            |
| This string does have a comma                           | so this part is rendered in a cell that it shouldn't be |

**Visual Proof:**
_Raw data view_: Notice that the Page column has valid URLs to link to.
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/181484/168615554-57ae60a5-5d9f-476f-ab2f-15b6f5703d11.png">

_Table visualization_: The Page column contains two rows that pull in text that should be in the feedback column. The text that gets pulled in follows a comma.
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/181484/168615676-7ccf9723-2684-4ef9-bcfd-9912da86e7cd.png">

**Comment by kristinarobinson** [comment]
Root cause is ui#2068.
