### ISSUE TITLE
Multi Org - Update polling /me endpoint (to be deprecated) to /identity endpoint

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#4587]
Currently there exists in the UI a polling request every 60 secs that returns valid session/user account data from the /idpe/me endpoint.  That endpoint is being deprecated, and should be replaced with the new /quartz/identity endpoint.

**Comment by wdoconnell** [comment]
Testing to make sure access permissions still work after making board private.

**Comment by Luckette** [comment]
#6207

**Comment by Luckette** [comment]
Heads up, @eatondustin1

**Comment by wdoconnell** [comment]
@eatondustin1 FYI - note that this is still partially feature flagged. In the cloud, IDPE `/me` isn't used for polling anymore - as long as the user has access to quartz, quartz endpoints are used instead. 

But until the `quartzIdentity` flag is on for all users in the UI, `/quartz/me` will still be used in prod.

**Comment by eatondustin1** [comment]
Awesome thanks for the heads up Bill, just let us know when the FF is removed and we'll remove our `/me` endpoint!

**Comment by abshierjoel** [comment]
@wdoconnell 
Hi Bill, I just wanted to check if this FF was now fully enabled? I checked configCat and it looks like `quartzIdentity` is on for all users now.

**Comment by wdoconnell** [comment]
@abshierjoel Correct, the FF has been on now in prod without issue for 10 days. Let me check with the team re: how much longer before we rip out the dead code behind the flag on the UI side, which will unblock you all on removing the dead `/quartz/me` code on your end.
