### ISSUE TITLE
Bug Duty: query explorer showing "no results" even when data is returned

### ISSUE THREAD

**Issue by gabotechs** [influxdata/ui#4609]
While playing with the query explorer I noticed that given a specific `range` in the flux query which displays correct results, if I push the start limit in the `range` function a little further (ex: from -3h to -4h) I get a "no results" display in the UI.

In my case, for the query that is displayed correctly, the http response body from influx is:
```csv
#group,false,false,false,false
#datatype,string,long,long,string
#default,_result,,,
,result,table,_time_reverse,_value
,,0,-1652888700000000000,"[2022-05-18 15:45:00 UTC] @Benzinga: 👇👇👇
https://t.co/o3wHrXw6Cq"
,,0,-1652889073000000000,[2022-05-18 15:51:13 UTC] @Benzinga: @BillyM2k Yes :')
,,0,-1652889550000000000,"[2022-05-18 15:59:10 UTC] @Benzinga: Active chatroom, college-style classroom, homework/quizzes, Trade ideas, and more!

Sign up for your 7-day trial for $7 today!
https://t.co/7dHO4vKQJn"
```
The query with a slightly incremented `range` looks like this:
```csv
#group,false,false,false,false
#datatype,string,long,long,string
#default,_result,,,
,result,table,_time_reverse,_value
,,0,-1652887800000000000,"[2022-05-18 15:30:00 UTC] @Benzinga: NASDAQ: $EZFL EzFill, an on-demand fueling service operating in several sectors, released Q1 earnings last week. Check out this interview with Mike McConnell, EzFill CEO, to get the full rundown. Visit https://t.co/L64iQ98BFy to stay updated.

#ad #earnings #ezfill #fuel #energy https://t.co/3GykcCJ8fY"
,,0,-1652887811000000000,"[2022-05-18 15:30:11 UTC] @NYT Business: Sanctions on Russia in response to its invasion of Ukraine have grounded Moscow’s ambitions to be a power in liquefied natural gas. The country’s prospects across a wide spectrum of energy are now deeply uncertain too, analysts say. https://t.co/VrtewI9zw1"
,,0,-1652888700000000000,"[2022-05-18 15:45:00 UTC] @Benzinga: 👇👇👇
https://t.co/o3wHrXw6Cq"
,,0,-1652889073000000000,[2022-05-18 15:51:13 UTC] @Benzinga: @BillyM2k Yes :')
,,0,-1652889550000000000,"[2022-05-18 15:59:10 UTC] @Benzinga: Active chatroom, college-style classroom, homework/quizzes, Trade ideas, and more!

Sign up for your 7-day trial for $7 today!
https://t.co/7dHO4vKQJn"
```

Notice the combination of a line jump and a # symbol in `#ad #earnings #ezfill #fuel #energy https://t.co/3GykcCJ8fY"`.

If I post-process the text before sending it to influx removing all line jumps, both results are displayed correctly.

My strong guess is that the line `#ad #earnings #ezfill #fuel #energy https://t.co/3GykcCJ8fY"` is being parsed as a comment when it is actually just part of the previous cell, and it is breaking the response parsing. Or maybe every line starting with # is just being removed (removing also the trailing `"` in that line)

**Comment by kristinarobinson** [comment]
@garylfowler can you have someone on the qx team take a look?
