### ISSUE TITLE
Giraffe fonts are reverting to Times

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#4619]
### Background
Clockface 4 changed our UI fonts from from `Rubik` to `Promixa Nova` and our monospace fonts from `IBM Plex Mono` to `Roboto Mono`.

Giraffe doesn't appear to be able to use the new fonts. After the update, the graph fonts from Giraffe are reverting to Times New Roman.

![Image](https://user-images.githubusercontent.com/146112/169317305-cf0f553f-0187-4bca-98c1-4985ab781b11.png)

### Acceptance Criteria
- Make giraffe axes and legends use Proxima Nova

**Comment by hoorayimhelping** [comment]
Locally, I've tried changing [these lines](https://github.com/influxdata/ui/blob/master/src/shared/constants/index.ts#L119-L121) from `Rubik` to `Promixa Nova` and it stays as Times/serif.

```ts
tickFont: "500 11px Proxima Nova",
```
still shows the Times/serif system font.

```ts
tickFont: "500 11px 'Proxima Nova', Helvetica, Arial, Tahoma, Verdana, sans-serif",
```
doesn't show Times/serif, but it doesn't show `Proxima Nova`, it's either `Helvetica` or `Arial`.

**Comment by TCL735** [comment]
Changing the values of https://github.com/influxdata/ui/blob/master/src/shared/constants/index.ts#L119 and https://github.com/influxdata/ui/blob/master/src/shared/constants/index.ts#L121 will affect the font of the graph. For example, with `500 14px Arial` and `14px Arial` we see:

<img width="1728" alt="Screen Shot 2022-05-19 at 5 23 03 PM" src="https://user-images.githubusercontent.com/10736577/169424837-6a8fe321-ab91-442a-bd20-c21112edfdcc.png">

**Comment by TCL735** [comment]
Clearly, Giraffe is still respecting the values passed into the `config`. But whenever the font does not appear to change, the passed in value is either invalid or something that isn't loaded properly (ie, there is no font file where this code is being called).

**Comment by TCL735** [comment]
The fonts are not loaded properly in the UI. In the console do this:
```
document.fonts.forEach(font => { console.log(font) })
```

There will be output of all of the FontFace available. Expand each one to see the status. They show as "unloaded".
