### ISSUE TITLE
Show default grouping, and enable users to turn off grouping in data explorer

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#4635]
This has been requested by Solana. They have a tag (host_id) with 1500 values, and when they use the data explorer, the series comes back grouped by host_id, so they get 1500 series back.  They want to get back a single series and do not know how to change the flux to do that.

The proposed approach is to change the UI to a) show you what tags are being included in the group, and b) allow the user to deselect all the tags so that the data is no longer grouped.

So, in the screenshot below, host_id would be checked (as it is in the default group) and if you uncheck it, we would no longer group by host_id.
<img width="1050" alt="image (8)" src="https://user-images.githubusercontent.com/13143006/169619219-2430f4d0-0dff-4041-b762-9502e33a294f.png">

**Comment by deanasheehan** [comment]
Discussed this with Joe @ Solana and he approved of the change.
By default - in that image above then the natural group for Solana would be _measurement, _field and host_id - all checked BUT given they have a single upstream predicate on _measurement and _field that wouldn't be checked. If the user didn't _mesaurement filter or (unusually) had accounts_db_flush_acc and accounts_db-stores checked then _measurement in the Group would be checked and would allow the user to uncheck and the correct ( |> group(columns:[ ??? ] ) to be generated.

Never simple is it.

**Comment by wiedld** [comment]
Note: the solution merged only applied to DataExplorer and Dashboard, (not notebooks). Fyi.
