### ISSUE TITLE
Query Controls

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#4637]
## User Story

<p></p>

As a user, I want a way to run and stop my query, see query status and select a time range and result limit for my query so that I can quickly control my query experience.

<p></p>

## Background

<p></p>

As part of the QX project, a schema browser, flux editing window, and an injection will be in place - which means the user should have a working flux script/query to run.  This story adds the UI elements to trigger that query to run or be stopped.

<p></p>

## Acceptance Criteria

<p></p>

**Run/Stop Button**

- When script has a bucket and measurement selection, a run option (button, etc.) will be available in the UI

- When a query is running, the run option wont be available, instead a stop button will be available

- If a query is running, but at the point where cancel is not available, the button will not be able to be clicked

- If a query is stopped, the query will be canceled and the run button will become available again

**Query Status indicator**

- The user will see some sort of indication in the UI when a query is running (either through the status of the run/cancel button or some other visualization

- Not A/C but would be interesting to track the query time and show that as an indicator that it is running (the time incrementing)

<p></p>
<s>
**Relative Time Range Selection**

- A relative time range selector will be available in the UI.  

- The time range will have the same options as the existing Visual builder:

- Past 1 Minute

- Past 5 Minutes

- Past 15 Minutes

- Past Hour

- Past 12 Hours

- Past 24 Hours

- Past 2 Days

- Past 7 Days

- Past 30 Days

<p></p>

**Custom Time Range Selection**

- A custom time range selector will be available in the UI

- When custom time range is selected, the user will be able to choose a date/time for both the starting and ending time range; preferably from a date picker

- User will have the option to input relative times in addition to picking custom date ranges (i.e -1h -4d, etc.)

- When relative times are chosen, they are reflected int he custom date range selection boxes

**Local Time Zone Selection**

- The user will have the ability to choose from using their local time zone or for choosing UTC time
</s>

**Download Option**

- The user will have the option to download the results of their query (versus display or visualize them)

<p></p>

<p></p>

## Notes

<p></p>

If the download option is selected, the results view will not be shown, only a download of the data when the query is completed.  In this scenario, there will be no need to parse the CSV in the browser.

<p></p>

<p></p>

**Comment by influx-product-manager** [comment]
Link to subfeature: https://influxdata.productboard.com/feature-board/planning/features/13491862

**Comment by garylfowler** [comment]
Basic controls are in, moved time selection to different story.
