### ISSUE TITLE
Windows Period v. parameters not getting calculated correctly.

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#4646]
While investigating a customer issue, @nathanielc found that the UI was not correctly injecting the v.windowPeriod when working with non simplified flux queries (for instance, ones that had multiple from range filters).

@wiedld  investigated and found problems with both the calculation and injection of v.windowPeriod.  

This issue is to track the work associated with that problem identification.

**Comment by wiedld** [comment]
Status update. We have a WIP in progress to fix this issue. It's a bit lower priority at the moment, but is moving forward. Code is mostly done...but there are a few sticking points to figure out. (And it's a pretty big diff, so I anticipate code review will take awhile.)

**Comment by wiedld** [comment]
## Current errors in the windowPeriod calculation:
* The `v.windowPeriod` is not calculated, unless a timeRange is coded into the flux query.
    * Requirement for time range:
        * https://github.com/influxdata/ui/blob/582e53c01d2a2460e0825ad60b4536d9894cf58b/src/shared/utils/getMinDurationFromAST.ts#L32-L36
    * Only provide timeRange variables, if they are used:
        * https://github.com/influxdata/ui/blob/582e53c01d2a2460e0825ad60b4536d9894cf58b/src/variables/utils/getWindowVars.ts#L126
* Additionally, the timeRanges are then used to calculate the windowPeriod using this set of rules:
    * Summarized steps:
        * Grab all `start` and `stop` across the entire query.
        * Takes the minimum possible windowPeriod as a cartesian product.
            * This answer is only correct when there is only 1 timeRange.
    * Comment and key code:
        * https://github.com/influxdata/ui/blob/582e53c01d2a2460e0825ad60b4536d9894cf58b/src/shared/utils/getMinDurationFromAST.ts#L26-L30
        * https://github.com/influxdata/ui/blob/582e53c01d2a2460e0825ad60b4536d9894cf58b/src/shared/utils/getMinDurationFromAST.ts#L38-L40
* Finally, the `findNodes()` method simply returns all node which match a given condition.
    * There is no scoping. Everything is effectively global (if it’s found).

**Comment by wiedld** [comment]
We are testing a new approach which re-thinks the use of windowPeriod. Will build/test in the new QX lLuxBuilder first, before porting elsewhere in the UI.

**Comment by TCL735** [comment]
The `getWindowPeriodFromVariables` function is giving bad results by sending back `null` on complex queries that use variables in the `from` parameter of function calls.

For example:

```
    truncated = date.truncate(t: v.timeRangeStop, unit:1m)
    splitPoint = experimental.subDuration(d: 10m, from: truncated)
```

Using that snippet in a query will cause `getWindowPeriodFromVariables` because an error is thrown while trying to get the durations from the AST.

The error is:
`Error: unexpected CallExpression`

**Comment by wiedld** [comment]
Team decided not to fix the incorrect windowPeriod, rather to scope changes to only remove the undefined use cases.
