### ISSUE TITLE
Forced Measurement & Showing All MetaData - Success Tracking

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#4647]
## User Story

<p></p>

As a software provider, I want to know if what impact to the query experience I have made by adding forced measurement selection and showing all metadata (not timebound) during the visual query builder process so that I can measure my success.

<p></p>

## Acceptance Criteria

<p></p>

- A mechanism for measuring the time differences of the before and after (of the implementation of forced measurement and showing all metadata stories) will exist

## Notes

<p></p>

- A solution proposed by Adam is simply to measure the time from the launch of the query builder to the time the user hits run

- We can that gather some data for a time period before the feature flag for these features are put into production and then compare them afterward and see if we see an overall trend of improvement.

<p></p>

**Comment by asalem1** [comment]
I don't seem to have access to the productboard so I'd love a little context as to what this issue is trying to determine w/r/t a success criteria for forced measurement selection. Is this specifically for the query builder in the current notebooks and data explorer experience? Is this for the upcoming work that's being worked on by the query experience team?

**Comment by garylfowler** [comment]
FYI:  there isn't any different info in Productboard than what is in the GitHub issue.

This is to determine if the changes made in data explorer and notebooks (not the upcoming QX work) has had any positive impact on query performance.

**Comment by asalem1** [comment]
> FYI: there isn't any different info in Productboard than what is in the GitHub issue.
> 
> This is to determine if the changes made in data explorer and notebooks (not the upcoming QX work) has had any positive impact on query performance.

Got it. So the barometer for success in this case is to compare how long it takes a user to build and run a query successfully when comparing the impact of this feature before and after the forced measurement flag? I guess I’m not sure if we have that level of granularity w/r/t the speed with which one event occurs after another.

**Comment by garylfowler** [comment]
Agree, which is why we opened a ticket for this.  We can discuss Adam's idea around this with him next week or during IPM.
