### ISSUE TITLE
You asked for the circumstances of seeing 404 page.

### ISSUE THREAD

**Issue by lukeschantz** [influxdata/ui#467]
_Describe the issue here._
Clicked on Influx documentation link new dashboard panel.  Took me to 404 page 

##### Relevant URLs
- _Provide relevant URLs_

**Comment by kelseiv** [comment]
Thank you, @lukeschantz!

Team, please update the following links to drop “getting-started”:

From:
docs.influxdata.com/influxdb/v2.0/query-data/get-started/getting-started
docs.influxdata.com/influxdb/cloud/query-data/get-started/getting-started


To:
docs.influxdata.com/influxdb/v2.0/query-data/get-started
docs.influxdata.com/influxdb/cloud/query-data/get-started

**Comment by sjwang90** [comment]
Hi @lukeschantz, this should be fixed in influxdata/docs-v2#2022. Can you confirm you're no longer receiving the 404 error?

**Comment by sjwang90** [comment]
@lukeschantz Looks like you're using Grafana. 

influxdata/docs-v2#2022 fixed everything on our end. I opened an issue on their repo (https://github.com/grafana/grafana/issues/30149)  and will reach out to their team to get it fix. Please provide any updates on that ticket.

Thanks!

**Comment by lukeschantz** [comment]
not using grafana, actually.
