### ISSUE TITLE
Basic Injection of Flux Selections into Flux Editor

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#4709]
## User Story

<p></p>

As a flux developer user, I want to be able to select flux functions and have them inject into my script so that I can more quickly develop flux code.

<p></p>

## Acceptance Criteria

<p></p>

- Functions selected from a flux search get injected into flux script, as is done with current DE (no new requirements, for now)

## Notes

<p></p>

- This will be the same behavior as before, but we need to work out where this is shown in the UI

<p></p>

<p></p>

**Comment by influx-product-manager** [comment]
Link to subfeature: https://influxdata.productboard.com/feature-board/planning/features/13145386

**Comment by wiedld** [comment]
Already done.
