### ISSUE TITLE
Epic: firstMile: InfluxCLI Onboarding Experience

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4729]
As a Builder using the InfluxCLI in InfluxDB Cloud, I want to write and query my data in less than 5 minutes so that I can quickly learn the basic functionality of InfluxDB Cloud without spending excess time heads-down in the documentation. 

## Figma Prototype
[InfluxCLI Onboarding Design](https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=1140%3A6177)

## Business Goal
[Product Brief](https://docs.google.com/document/d/1DX694KomEeJqEXkJBwme3uAQGOH7BAeOqKyiI7I7Hm8/edit#)

## Target Audience
- Builders using InfluxCLI to set up their environment, write, query from both plain .csv data from a URL & from a downloaded annotated .csv file

## Core Team
- Design Lead: Tara Kirkland, Andy Moon
- Engineering Lead: Bucky Schwarz (Lead), Kristina Robinson (Manager)
- Product Lead: Amy Luckette

## Extended Team
- Analytics: Mona Sami, Favian Tirado, grace Ma
- Support: Marc Kaplan, Veeresh Hosakere
- Marketing: Brian Mullen, Chris Churillo
- Pricing/Offers/Vendor Relationships: Rob Kramer
- Documentation: Kelly Seivert, Nora Mullen
- Community/Developer Advocates: Michael Hall, Zoe Steinkamp
- Growth: Jill Guest & Stefany Mantilla
- Design: Daniel Campbell, Tara Kirkland, Andy Moon
- Product: Amy Luckette, Balaji Palani
- Engineering: Kristina Robinson & Bucky Schwarz

## User Stories & Acceptance Criteria

**User Story: Home Page** 

        ACs
        - The CLI UI component on the Home Page should be renamed to "InfluxCLI"
        - The text underneath "InfluxCLI" should say "Write and query data using the Influx Command Line Interface. Supports CSV and Line Protocol."
        
        Dev Notes
        - Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=1137%3A5331  
        
**User Story: InfluxCLI Wizard Structure**

        ACs
        - The basic wizard structure should be set up with the same usability as the python, GO, and node.js wizards. (Highlight when selected, checkmark when complete/proceeded, icons)
        - The wizard steps for InfluxCLI are different than the other onboarding wizards. InfluxCLI steps: Overview, Install Dependencies, Initialize Client, Write Data, Execute a Flux Query, Execute Aggregate, Finished!
        - The wizard icons should match what's in the Figma (Same as other wizards except single step/page dedicated to tokens)
        
       Dev Notes
        - Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=1137%3A5331
        
**User Story: InfluxCLI Onboarding Navigation**

        ACs
        - The wizard on the left side of the screen should allow users to navigate forward/backward through the wizard steps
        - The "Previous" and "Next" buttons should allow the user to navigate backward/forward through the wizard
        - The Finished page should display confetti similar to the other wizards
        
        Dev Notes
        - Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=1137%3A5331    
           
**User Story: InfluxCLI Overview Page**

        ACs
        - Overview page should match the overview page on the previous wizards exactly...same text, same, video, same links. See previous onboarding wizards (Python, Go, node.js)

        Dev Notes
        - Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=1137%3A5331
**User Story: InfluxCLI Install Dependencies - MAC OS Flow**

        ACs
        - Install Dependencies page should include three tabs underneath the "Install Dependencies" text specific to the user's operating system (MAC OS, WINDOWS, LINUX). See Figma
        - Depending on which OS tab the user clicks, the install information below will change accordingly. The selected Tab should highlight blue and the text should be white. 
        - For MAC OS, the next sub-step on the Install Dependencies page should be "Use Homebrew" with the copy code snippet "brew install influxdb-cli"
        - Text underneath the Homebrew code snippet should be "If you prefer to manually download and install the CLI package, follow our documentation."
        - The word "documentation" should be hyperlinked (https://docs.influxdata.com/influxdb/cloud/tools/influx-cli/)
        - The next sub-step in the MAC OS flow for Instal Dependencies should be "Useful InfluxCLI Commands"
        - Text underneath "Useful InfluxCLI Commands" should be "To invoke a command, use the following format in the command line: influx <command>" (See Figma)
        - In the "Useful InfluxCLI Commands" sub-step/section should be a table of useful commands and their definitions. (bucket, export, help, help <command>, query, and write)
        - Underneath the table of useful commands should be the following text and link "A full list of InfluxCLI Commands is available in our documentation." The word documentation should be hyperlinked to:(https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/)        
       
       Dev Notes
       -  If URL to the InfluxCLI is used, use the URL with "latest" in the title - assuming that the edge/cli team finished their ticket (https://github.com/influxdata/influx-cli/issues/394)  
        -  Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=1137%3A5331       
    
**User Story: Install Dependencies WINDOWS Flow**

        ACs
        - Install Dependencies page should include three tabs underneath the "Install Dependencies" text specific to the user's operating system (MAC OS, WINDOWS, LINUX). See Figma
        - Depending on which OS tab the user clicks, the install information below will change accordingly. The selected Tab should highlight blue and the text should be white.         
        - For WINDOWS, the next sub-step on the Install Dependencies page should be "Download the CLI package"
        - Text underneath the "Download the CLI package" should be "Download via our documentation" The entire text should be hyperlinked to: https://docs.influxdata.com/influxdb/cloud/tools/influx-cli/?t=Windows
        - The next sub-step should be "Expand the downloaded archive"
        - The text underneath "Expand the downloaded archive" should be "Expand the downloaded archive into C:\Program Files\InfluxData\ and rename if desired"
        - Display the copy/code snippet to expand the downloaded archive (See Figma)
        - The next sub-step should be "Grant network access (optional)"
        - Text underneath "Grant network access (optional)" should be: "To grant network access to the InfluxCLI, do the following: 1. Select Private networks, such as my home or work network. 2. Click Allow access.
        - The next and last sub-step in the WINDOWS flow should be "Useful CLI Commands."
        - Text underneath "Useful InfluxCLI Commands" should be "To invoke a command, use the following format in the command line: influx <command>" (See Figma)
        - In the "Useful InfluxCLI Commands" sub-step/section should be a table of useful commands and their definitions. (bucket, export, help, help <command>, query, and write)
        - Underneath the table of useful commands should be the following text and link "A full list of InfluxCLI Commands is available in our documentation." The word documentation should be hyperlinked to:(https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/)         

        Dev Notes
        - If URL to the InfluxCLI is used, use the URL with "latest" in the title - assuming that the edge/cli team finished their ticket (https://github.com/influxdata/influx-cli/issues/394)    
        - Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=1137%3A5331
**User Story: Install Dependencies LINUX Flow**

        ACs
        -Install Dependencies page should include three tabs underneath the "Install Dependencies" text specific to the user's operating system (MAC OS, WINDOWS, LINUX). See Figma
        - Depending on which OS tab the user clicks, the install information below will change accordingly. The selected Tab should highlight blue and the text should be white. 
        - For LINUX, the first sub-step should be "Download from the command line." Copy/Code snippet should match what's in the Figma. (If the URL containing "lastest is available for use by the CLI team, display it in the code snippet)
        - Text underneath the copy/code snippet should say "If you prefer to manually download the CLI package, see our documentation. The word "documentation" should hyperlink to: https://docs.influxdata.com/influxdb/cloud/tools/influx-cli/?t=Linux        
        - The next sub-step should be "Place the executable in your $PATH (optional)"
        - Text underneath "Place the executable in your $PATH (optional)" should read "If you do not move the influx binary into your $PATH, prefix the executable ./ to run it in place." Then display the Copy/Code snippet of how to place the executable in a path (See Figma)
        - The next sub-step should be "Useful InfluxCLI Commands"
        - Text underneath "Useful InfluxCLI Commands" should be "To invoke a command, use the following format in the command line: influx <command>" (See Figma)
        - In the "Useful InfluxCLI Commands" sub-step/section should be a table of useful commands and their definitions. (bucket, export, help, help <command>, query, and write)
        - Underneath the table of useful commands should be the following text and link "A full list of InfluxCLI Commands is available in our documentation." The word documentation should be hyperlinked to:(https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/)              
        
        Dev Notes
        - If URL  to the InfluxCLI is used, use the URL with "latest" in the title - assuming that the edge/cli team finished their ticket (https://github.com/influxdata/influx-cli/issues/394)  
        - Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=1137%3A5331     
                  
**User Story: InfluxCLI Initialize Client**

        ACs
        - The Initialize Client page in the InfluxCLI onboarding wizard will have three sub-steps on the page: (Create a token, Configure an InfluxDB profile, and Create a bucket)
        - The first substep should be "Create a token"
        - Text underneath "Create a token" should say "First we'll create a token. A token is used to authenticate API process." bold the word 'token'
        - Copy/Code snippet should match Figma (influx auth create -o <org-name> --all-access.
        - Automatically put the user's org-name in the copy code snippet so that they don't have to. 
        - Text underneath copy/code snippet should say "Note: We've created an all-access token here for simplicity, but we recommend using a token with more specific permissions in the long-term. You can edit your tokens anytime from the UI." 
        - The next sub-step should be "Configure an InfluxDB profile"
        - Text underneath "Configure an InfluxDB profile" should say "Next, we'll need to configure the client and its initial connection to InfluxDB. The snippet below creates a configuration profile named onboarding. You may choose a different name if you'd like. You'll likely create another profile using a different token for working with your own data." Italicize the word 'onboarding'
        - Copy/Code Snippet should match the Figma 
        
            influx config create --config-name onboarding \
               --host-url <region> \
               --org name <your-org> \
               --token <your-auth-token> \
               --active
               
        - Automatically insert the user's region, org name, and token into the code snippet so that they don't have to.  
        - The next sub-step on this page should be "Create a bucket"
        - Text underneath "Create a bucket" should say " Now we'll create a bucket. A bucket is used to store time-series data. We'll link the bucket to the profile you created. Bold the word 'bucket'
        - Copy/code snippet should match the Figma:
             
              influx bucket create sample-bucket -c onboarding
 
        Dev Notes
        - Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=1137%3A5331
                 
**User Story: Write Data - LOCAL CSV**

        ACs
         - The InfluxCLI Write Data page will have two user flows. Depending on the 'data source' tab selected by the user, the UI will display different content.         
         - The first sub-step for BOTH flows should be "Choose your sample data source"
         - Text underneath "Choose your sample data source" should say "We recommend choosing an option that most closely matches how you will write your actual data." 
         - The Tabs should display underneath that text and say: "URL TO FILE" and "LOCAL CSV"    ... Highlight the selected tab so that it turns blue and the text turns white.          
         - The next sub-step should be "Download sample data"
         - Text underneath "Download sample data" should say "We'll use this data to guide you through writing data to a bucket, and then querying that data. Our sample data is fictional bee and ant census data." (Note, the engineering team is welcome to choose different sample data)
         - Underneath that text, display a "DOWNLOAD SAMPLE .CSV" button
             When the button is clicked, point to a sample csv file that initiates a download. 
         - Underneath the "DOWNLOAD SAMPLE .CSV" button should be text that says "The sample file is an Annotated CSV. The InfluxCLI supports both annotated and standard CSV formats. Annotated CSVs contain metadata about the data types in the file, which allows for faster write performance." Hyperlink "Annotated CSVs" to: https://docs.influxdata.com/influxdb/v2.2/reference/syntax/annotated-csv/          
        - Display a small sample of the csv data in table format the UI in the "Download sample data" sub-step section (see figma)
        - The next sub-step should be "Review data concepts" ...this should section display a brief overview of Field, Measurement, and Tag. (See Figma)
        - The next and last sub-step should be "Write Data"
        - Underneath "Write Data" should be text that says "Copy the script below into your CLI, and update the path to the downloaded file. Then run the snippet to write the data to your bucket."
        - Then display a copy/code snippet that matches the Figma
                
                influx write --bucket sample-bucket --file path/sample.csv
            
        - The sample .csv file name must match the sample .csv file in the code snippet (and vice versa, just make sure it matches)
        - Next, display text underneath the code snippet that says "Once the data is finished writing, you will see a confirmation below.
        - Insert the "Listening for data" UI Component and indicate to the user when their data has successfully written to their bucket.
    
        Dev Notes
        - Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=1137%3A5331 
               
**User Story: Write Data - URL TO FILE**

        ACs
        - The InfluxCLI Write Data page will have two user flows. Depending on the 'data source' tab selected by the user, the UI will display different content.         
         - The first sub-step for BOTH flows should be "Choose your sample data source"
         - Text underneath "Choose your sample data source" should say "We recommend choosing an option that most closely matches how you will write your actual data." 
         - The Tabs should display underneath that text and say: "URL TO FILE" and "LOCAL CSV"    ... Highlight the selected tab so that it turns blue and the text turns white.     
         - The next sub-step for the "URL TO FILE" flow should be "Review sample data"
         - Underneath "Review sample data" place a link to the URL (engineering to create a URL of plain csv data for use during this onboarding flow)
         - Text underneath URL should say "This file is an unannotated plain CSV. The InfluxCLI supports both annotated and standard CSV formats. Annotated CSVs contain metadata about the types in the file, which allows for faster write performance." Hyperlink "Annotated CSVs" to: https://docs.influxdata.com/influxdb/v2.2/reference/syntax/annotated-csv/  
         - The next sub-step should be "Review data concepts" ...this should section display a brief overview of Field, Measurement, and Tag. (See Figma)         
         - The next and last sub-step should be "Write Data"
        - Underneath "Write Data" should be text that says "Run the following code in the InfluxCLI to write the data to your bucket."
        - Then display a copy/code snippet that matches the Figma
                
                influx write --bucket sample-bucket --url https://<sample data url>
            
        - The sample data URL file name that we choose must match the sample data URL in the code snippet (and vice versa, just make sure it matches)
        - Next, display text underneath the code snippet that says "Once the data is finished writing, you will see a confirmation below.
        - Insert the "Listening for data" UI Component and indicate to the user when their data has successfully written to their bucket.   
                           
        Dev Notes
        - Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=1137%3A5331
                           
**User Story: InfluxCLI - Execute a Flux Query**

        ACs
        - Header/Title of this page should be "Execute a Flux Query"
        - Text underneath "Execute a Flux Query" should be "Now let's query the data we wrote into the database. We use the Flux scripting language to query data. Flux is designed for querying, analyzing, and acting on data." 
        - Hyperlink the word 'Flux' to: https://docs.influxdata.com/influxdb/v2.2/reference/syntax/flux/  
        - Text continues..."Here's an example of what a Flux script looks like:
        
                from(bucketL "bucket-name")
                    |> range(startL -10m)
                    |> filter(fn: (r) => r._measurement == "census")
                    
        - Text continues... "Let's write a Flux query in the InfluxCLI to read back all of the data you wrote in the previous step. Copy the code snippet below into the InfluxCLI."
        - Copy/code snippet should be match Figma
         
                 influx query 'from(bucket:"sample-bucket") |> range(start:-10m)' --raw
                          
        Dev Notes
        - Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=1137%3A5331
        
**User Story: InfluxCLI - Execute a Flux Aggregate Query**

        ACs
        - The header/title of the page should be "Execute a Flux Aggregate Query"
        - The text underneath the title should say: "An aggregate function is a powerful method for returning combined, summarized data about a set of time-series data."
        - Text continues... "In the example below, we use the mean() function to calculate the average number that we recorded in the last 10 minutes."
        - Text continues..."In the InfluxCLI, run the following:"
                
                display copy/code snippet: 
                
                influx query 'from(bucket:"example-bucket") |> range(start: -10m) |> mean()' --raw
                
        - Text underneath copy/code snippet should read "This will return the mean of the data values."

        Dev Notes
        - Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=1137%3A5331

**User Story: InfluxCLI - Finished**

        ACs
        - Title of the page should be "Congrats!"
        - Text underneath title should be "You completed setting up, writing, and querying data.
        - Display Thumbs-up/Thumbs-down component "What did you think about the setup process?"
        - Display text "Curious to learn more? Try these next steps!" 
        - Add a panel for Key Concepts, links to the following in a new tab: https://docs.influxdata.com/influxdb/v2.2/reference/key-concepts/        
        - Add a panel for CLI Commands, links to the following in a new tab: https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/        
        - Add a panel for InfluxDB University, links to the following in a new tab: https://university.influxdata.com/        
        - Match the spacing and stying (including icons) that are shown in the figma.  

        Dev Notes
        - Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=1137%3A5331
        
**User Story: Measure Launch Success (Setup UI Eventing)**

      ACs
      - Track # accounts per next step selection 
      - Track the time to completion per account
      - Track % accounts complete wizard (% accounts complete setup)
      - Track time per step so that we can see where users are getting "Stuck" 
      - Track how many times the user clicks the "previous" button per session
      - Track if a user clicks the documentation link per step/screen
      - Track if a user clicked on the copy/code snippet per step/screen; where applicable
      - Track Upgrade Now clicks before vs after completing the wizard
      - All eventing for the previous and next buttons needs to specify the page on which it was clicked, not just the language.
      - Track if the user clicked the time series video on the overview page
     
      Dev Notes
        - Eventually, this should end up in Domo for PM and Analytics to create visuals

**User Story: Add Deep Link for InfluxCLI Onboarding**

        ACs
        - There should be one new deeplink for the InfluxCLI setup flow. The deeplink should be as follows:

             /me/setup-cli: /new-user-setup/cli
                 
**User Story: End to End Testing**

**User Story: Managed by Feature Flag**

**User Story: Setup User Pilot Survey**

**User Story: Remove Feature Flag**

**Comment by Luckette** [comment]
FYI @taramk @kristinarobinson @hoorayimhelping This is the Epic for the InfluxCLI Onboarding Epic. I'd like to get out first round of ACs in here on Wednesday morning June 8th. That's my goal.

**Comment by wdoconnell** [comment]
This feature has been added and the FF removed.

https://github.com/influxdata/ui/pull/5896
