### ISSUE TITLE
Script editor not working

### ISSUE THREAD

**Issue by vital-agro** [influxdata/ui#4739]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Click on data explorer
2. Select a bucket
3. Click on script editor

**Expected behavior:**
Script editor opens and allows editing of query

**Actual behavior:**
Error message appears
![influx_error](https://user-images.githubusercontent.com/65984278/171924932-723b25f8-eac7-4cf7-b446-d3187bd2d449.PNG)

**Visual Proof:**

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by kristinarobinson** [comment]
Closing due to lack of communication.  Please re-open if you have further concerns.
