### ISSUE TITLE
firstMile: InfluxCLI Onboarding - Overview Page

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4764]
ACs
    - Overview page should match the overview page on the previous wizards exactly...same text, same, video, same links. See previous onboarding wizards (Python, Go, node.js)

   Dev Notes
    - Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding-Exploration?node-id=1137%3A5331

**Comment by kristinarobinson** [comment]
Closing, no changes required.
