### ISSUE TITLE
Optionally Reissue query on zoom in/out

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ui#4790]
**Proposal:**

Create a toggle or optional setting that changes the behavior of the UI when zooming in or out of data to reissue the query with the new time range and new window period. The result of this will be that more detailed can be returned for that time range if an aggregate query is being used. 

**Current behavior:**

Currently the data is redraw without issuing a new query. This is good behavior and should be maintained as the default. This is why the new behavior should some how be opt-in.

**Desired behavior:**

When enabled a new query is run with the new time range and new window period.

**Alternatives considered:**

Perhaps instead of reissuing the query on zoom in/out there could be a button to explicitly rerun the query for the new time range determined by the currently selected time range.

**Use case:**

When working with high resolution raw data its common to use an `aggregateWindow` query return less data to the UI to visualize the general behavior of the data. When something interesting is noticed in the data you can zoom in. However this just redraws the data closer, but its the same data so not much more information can be learned. However is there was a way to re run the query on this smaller time range with a smaller window period then higher resolution data can be returned and visualized, thus returning new data and possibly valuable information to the user.

**Comment by deanasheehan** [comment]
To add some context for this request.

When doing ad-hoc data exploration, or if the exploration is promoted to a dashboard cell, the natural query that comes out of using the query builder will be `range(<the time range of the data explorer or dashboard>) |> aggregateWindow(every:<v.windowPeriod that is calculated by the UI based on the time range>)`

If you select a wide time range, let's say 2d, the window period is 1m - you will get 1 min averages return to the UI.

If you then select a range of the drawn graph (maybe picking 15 minute time window) then the UI will zoom into the data it has available (1 minute averages, so 15 data points). 

However, if (for example) the underlying query was re-executed then a higher resolution v.windowPeriod would have been calculated (I believe it would be 10s for a 15 min time range) and more points (in this case 90) would be available.  A much higher fidelity data set.

There is also no easy way I know of of zooming back out.

If the UI (optionally) re-executed the query when a zoomed range was selected then a new query with new time range and potentially different window period would be supplied.

This would allow wide time range data exploration to be rapid (large window period) and as you narrow in then the query will still execute fast as the higher resolution (window period) would be offset by the reduction in time range.

You could look at increasingly detailed data.

It is a bit like optical zoom v digital zoom on cameras.

If you then couple with with the power of Flux it is possible to construct Flux queries that actually pick different buckets of data based on the time range and window period to potentially use downsampled data where possible (for super fast responses) and raw data when the resolution is high (in excess of the downsampling frequency) but the time range is small.

**Comment by TCL735** [comment]
This is completed. The feature is called Adaptive Zoom. The "Customize" button can turn this feature on and off. The default is ON. The feature should work on any rendered line graph. Please report it as a bug if there is an example of a line graph that does not have this feature enabled by default.
