### ISSUE TITLE
Resolve linter warnings re: react-hooks/exhaustive-deps

### ISSUE THREAD

**Issue by wdoconnell** [influxdata/ui#4815]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Run eslint on current UI build

**Expected behavior:**
No warnings from linter.

**Actual behavior:**
Over 100 warnings of the form shown below.

**Visual Proof:**
`157:6  warning  React Hook useMemo has missing dependencies: 'data' and 'update'. Either include them or remove the dependency array                react-hooks/exhaustive-deps`

## About your environment

**Environment info:**
N/A (any build, or CI-CD)

**Config:**
N/A

**Logs:**
N/A

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by kristinarobinson** [comment]
Break this down into smaller chunks by feature.

**Comment by wdoconnell** [comment]
Updated the description here to avoid suggesting that `// eslint-disable-line exhaustive-deps` could be a solution, which it really shouldn't be unless it's absolutely required, or the code is truly too complex or risky to refactor.

Here's [a helpful discussion](https://github.com/facebook/react/issues/14920#issuecomment-471070149) of why it's usually a bad idea, and recommendations about how to fix the useEffect hooks without disabling the linter warning.

**Comment by wdoconnell** [comment]
Closing based on priority.
