### ISSUE TITLE
bucket location doesn't change after editing Telegraf config 

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/ui#4818]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Create a telegraf configuration 
2. Edit it and change the bucket
3. Change isn't reflected in the UI 
4. Especially problematic if you copied a telegraf config with an environment variable. The UI then can't find the bucket and yields:
`Failed to create a new Telegraf API Token: there is no bucket present with name $INFLUX_BUCKET`

**Expected behavior:**
The change in the config changes the bucket in the UI

**Actual behavior:**
No change 

**Visual Proof:**
<img width="1161" alt="Screen Shot 2022-06-14 at 11 52 06 AM" src="https://user-images.githubusercontent.com/30506042/173670026-d655be5e-b153-40a8-8282-0b4c2e492d7c.png">
<img width="1078" alt="Screen Shot 2022-06-14 at 11 49 46 AM" src="https://user-images.githubusercontent.com/30506042/173670072-394a3a33-5122-4a65-b6ce-de972dc338ac.png">

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by TCL735** [comment]
@Anaisdg how did you create a telegraf configuraton with the bucket called `$INFLUX_BUCKET`? Is this an actual name of one of your buckets? Please be more detailed with the steps of the telegraf configuration creation. At a minimum please list the steps in creating the configuration and screenshots of each step, including a screenshot of the list of buckets. A video recording of this would be best, although not necessary.

**Comment by TCL735** [comment]
Also, I don't think this is a bug. It's more a design oversight or a feature request.

Sure, the UI sets the bucket name once on the configuration card and it never changes. But the telegraf configuration still works as long as the configuration itself is valid, including the bucket name and the token.
