### ISSUE TITLE
Improved Time Range Selection

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#4828]
## User Story

<p></p>

As a user, I want an improved time range selector that makes it easy for me to both choose a relative time range (including manually entering a range) and a specific custom range with a calendar/date picker so that it is easy for me to define my range visually.

<p></p>

## Acceptance Criteria

<p></p>

- Julia has created a new UI design for this; this ticket is for the implementation of that design (see attached)

<p></p>

<https://www.figma.com/file/0qAntPk5LVangAHguWT74X/Query-Experience-Project?node-id=1125%3A44592>

<p></p>

<p></p>

<p></p>

**Comment by influx-product-manager** [comment]
Link to subfeature: https://influxdata.productboard.com/feature-board/planning/features/13868716

**Comment by garylfowler** [comment]
![image](https://user-images.githubusercontent.com/97983559/173914104-72676f80-cc37-484e-8bd8-f7c0febcd460.png)

**Comment by garylfowler** [comment]
I am not 100% sure I know Julia's expectation, but this is what I would envision:

1.  Yes, the time range on the left would get updated based on selections made on the right (or the user could make a manual modification to the left).

2.   The left side would always be the source of truth.

3.  User does need to be able to set the time.  But I think the intention was that they could set it after selecting a date, as by default I think it puts in 00:00 for the time and then you could modify it manually by typing in the box and replacing 00:00 with the time desired.  I don't think a selection of the time from a list of times was in this design, and I agree with Julia - probably not needed - even though we had it in the old picker."

4.  Yes, I would say that it gets overwritten in this case.

**Comment by juliajames12** [comment]
What I had in mind is aligned with what @garylfowler said above. I just wanted to note that when a user types within the From or To fields and applies that updated time range (after having initially selected from the list on the right side), the list item should no longer be selected.
