### ISSUE TITLE
Data Sources: Add CSV/LP file upload

### ISSUE THREAD

**Issue by sjwang90** [influxdata/ui#485]
**Proposal:**
With the addition of the CSV uploader #421, I intuitively went to the Data Sources page to find it. Currently there is no way or information on uploading a file (Besides the Telegraf plugins) directly from the data sources page. 

**Current behavior:**
No info on LP/CSV file upload on Data Sources page. Have to go to a bucket and add it from there.
![fileupload](https://user-images.githubusercontent.com/32681364/103828249-6e59dc80-502f-11eb-8a65-02f580d16923.gif)

**Desired behavior:**
Be able to upload LP/CSV file upload on Data Sources page. Perhaps a "File Upload" section with a CSV icon and an LP icon? @alexpaxton may have better ideas

**Alternatives considered:**
Currently upload csv/LP files in buckets tab under a bucket.

**Use case:**
Why is this important (helps with prioritizing requests)?
CSV uploader in the UI is a huge thing. Wanna make sure our users can find it :)

**Comment by juliajames12** [comment]
![CSV Icon.svg](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/5fbed24e-a691-441a-ad87-f9f7a4d42589)![Line Protocol Icon.svg](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/d9374de3-5115-4380-adc4-0b41d3bba88e)

Here are the csv and lp icons. Kept it pretty simple by using the file icons with the file type for now.

**Comment by Asalem1** [comment]
Thanks for these!
