### ISSUE TITLE
Query Zoom-In: Apply zoomed in start and end dates to new query

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#4855]
When the Zoom click drag action is performed, and the query zoom in feature flag is on, 
then apply the zoomed start and end dates as the time range for the new query that will be re-executed.

**Comment by TCL735** [comment]
This should also apply to the window period, so that a refresh of the query will use a more detailed (smaller) window period. Both time range and window period should be adjusted upon zoom.
