### ISSUE TITLE
ResourceCard in Onboarding: reset to default styles

### ISSUE THREAD

**Issue by taramk** [influxdata/ui#4892]
In the new onboarding flows, we are using the [ResourceCard component](https://influxdata.github.io/clockface/?path=/story/components-cards-resourcecard-family--resourcecard) on the last page of the flow to indicate next steps. 

To view: Homepage > Python > Finish in subway nav

**Existing behavior**
Those cards appear to have some custom styles applied, namely, a gradient on the header, and a different font weight and font size on the body text (ResourceCardDescription).

**Desired behavior**
We should remove the custom styles so that the ResourceCard adheres to the default as much as possible.

Screenshot of application below.
![image](https://user-images.githubusercontent.com/1813419/175613879-05abba7f-c58c-430b-b710-f26a9f6b0c6c.jpeg)

_This update should be made for all onboarding flows._

**Comment by wdoconnell** [comment]
Closing due to priority.
