### ISSUE TITLE
firstMile: UI Eventing - Add eventing to the Load Data > Sources page

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4902]
**Request**
Add UI eventing to every option on the load data > sources page so that we can find out what the most commonly clicked options are. The majority of users are going to the "more" button on the new homepage. I want to know what users do after clicking "more" on the homepage. This ticket is quite large, so, it's understandable if it takes multiple sprints. 

**ACs**

**ACs for File Upload Events**
- UI Event for user clicked Flux Annotated CSV
- UI Event for user clicked Line Protocol
- UI Event for user clicked CSV Data (CLI)

**ACs for Client Library Events**
- UI Event for user clicked Arduino
- UI Event for user clicked C#
- UI Event for user clicked Dart
- UI Event for user clicked GO 
- UI Event for user clicked Java
- UI Event for user clicked JavaScript/Node.js
- UI Event for user clicked Kotlin
- UI Event for user clicked PHP
- UI Event for user clicked Python
- UI Event for user clicked R
- UI Event for user clicked Ruby
- UI Event for user clicked Scala
- UI Event for user clicked Swift

**ACs for Telegraf Plugin Events**
- UI Event for user clicked ActiveMQ
- UI Event for user clicked Aerospike
- UI Event for user clicked Alibaba (Aliyun) CloudMonitor Service Statistics
- UI Event for user clicked Amazon CloudWatch Statistics
- UI Event for user clicked Amazon ECS
-  UI Event for user clicked AMQP Consumer
-  UI Event for user clicked Apache
-  UI Event for user clicked APCUPSD
-  UI Event for user clicked Arista LANZ Consumer
-  UI Event for user clicked Aurora
-  UI Event for user clicked Azure Storage Queue
-  UI Event for user clicked bcache
-  UI Event for user clicked Beanstalkd
-  UI Event for user clicked Beat
-  UI Event for user clicked BIND 9 Nameserver Statistics
-  UI Event for user clicked Bond
-  UI Event for user clicked Burrow Kafka Consumer Lag Checking
-  UI Event for user clicked Cassandra
-  UI Event for user clicked Ceph Storage
-  UI Event for user clicked CGroup
-  UI Event for user clicked chrony
-  UI Event for user clicked Cisco Model-Driven Telemetry (MDT)
-   UI Event for user clicked ClickHouse
-   UI Event for user clicked Conntrack
-   UI Event for user clicked Consul
-   UI Event for user clicked Couchbase
-   UI Event for user clicked CouchDB
-   UI Event for user clicked Counter-Strike: Global Offensive (CSGO)
-   UI Event for user clicked CPU
-   UI Event for user clicked Data Plane Development Kit (DPDK)
-   UI Event for user clicked DC/OS
-   UI Event for user clicked Directory Monitor
-   UI Event for user clicked Disk
-   UI Event for user clicked DiskIO
-   UI Event for user clicked Disque
-   UI Event for user clicked DMCache
-   UI Event for user clicked DNS Query
-   UI Event for user clicked Docker
-   UI Event for user clicked Docker Log
-   UI Event for user clicked Dovecot
-   UI Event for user clicked Elasticsearch
-   UI Event for user clicked Elasticsearch Query
-   UI Event for user clicked Ethtool
-   UI Event for user clicked Event Hub Consumer
-   UI Event for user clicked Exec
-   UI Event for user clicked Execd
-   UI Event for user clicked Fail2ban
-   UI Event for user clicked Fibaro
-   UI Event for user clicked File
-   UI Event for user clicked Filecount
-   UI Event for user clicked Filestat
-   UI Event for user clicked Fireboard
-   UI Event for user clicked Fluentd
-   UI Event for user clicked GitHub
-   UI Event for user clicked gNMI (gRPC Network Management Interface)
-   UI Event for user clicked Google Cloud PubSub
-   UI Event for user clicked Google Cloud PubSub Push
-   UI Event for user clicked GrayLog
-   UI Event for user clicked HAProxy
-   UI Event for user clicked Hashicorp Consul Agent Metrics
-   UI Event for user clicked Hashicorp Nomad
-   UI Event for user clicked Hashicorp Vault
-   UI Event for user clicked HDDtemp
-   UI Event for user clicked HTTP
-   UI Event for user clicked HTTP JSON
-   UI Event for user clicked HTTP Listener v2
-   UI Event for user clicked HTTP Response
-   UI Event for user clicked Hugepages
-   UI Event for user clicked Icinga2
-   UI Event for user clicked InfiniBand
-   UI Event for user clicked InfluxDB
-   UI Event for user clicked InfluxDB Listener
-   UI Event for user clicked InfluxDB V2 Listener
-   UI Event for user clicked Intel Performance Monitoring Unit
-   UI Event for user clicked Intel PowerStat
-   UI Event for user clicked Intel RDT
-   UI Event for user clicked Internet Speed
-   UI Event for user clicked Interrupts
-   UI Event for user clicked IPMI Sensor
-   UI Event for user clicked Ipset
-   UI Event for user clicked Iptables
-   UI Event for user clicked IPVS
-   UI Event for user clicked Jenkins
-   UI Event for user clicked Jolokia
-   UI Event for user clicked Jolokia2
-   UI Event for user clicked JTI OpenConfig Telemetry
-   UI Event for user clicked Kafka Consumer
-   UI Event for user clicked Kafka Consumer Legacy
-   UI Event for user clicked Kapacitor
-   UI Event for user clicked Kernel
-   UI Event for user clicked Kernel VMStat
-   UI Event for user clicked Kibana
-   UI Event for user clicked Kinesis Consumer
-   UI Event for user clicked KNX
-   UI Event for user clicked Kubernetes
-   UI Event for user clicked Kubernetes Inventory
-   UI Event for user clicked LeoFS
-   UI Event for user clicked Linux Sysctl FS
-   UI Event for user clicked LM Sensors
-   UI Event for user clicked Logical Volume Management
-   UI Event for user clicked Logparser
-   UI Event for user clicked Logstash
-   UI Event for user clicked Lustre
-   UI Event for user clicked Mailchimp
-   UI Event for user clicked MarkLogic
-   UI Event for user clicked Mcrouter
-   UI Event for user clicked Mdstat
-   UI Event for user clicked Memcached
-   UI Event for user clicked Memory
-   UI Event for user clicked Mesos
-   UI Event for user clicked Minecraft
-   UI Event for user clicked Mock
-   UI Event for user clicked Modbus
-   UI Event for user clicked MongoDB
-   UI Event for user clicked Monit
-   UI Event for user clicked MQTT Consumer
-   UI Event for user clicked Multifile
-   UI Event for user clicked MySQL
-   UI Event for user clicked NATS
-   UI Event for user clicked NATS Consumer
-   UI Event for user clicked Neptune Apex
-   UI Event for user clicked Net
-   UI Event for user clicked Net Stat
-   UI Event for user clicked Network Response
-   UI Event for user clicked NFS Client
-   UI Event for user clicked Nginx
-   UI Event for user clicked Nginx Plus
-   UI Event for user clicked Nginx Plus API
-   UI Event for user clicked Nginx Stream STS
-   UI Event for user clicked Nginx Upstream Check
-   UI Event for user clicked Nginx Virtual Host Traffic (VTS)
-   UI Event for user clicked NSD
-   UI Event for user clicked NSQ
-   UI Event for user clicked NSQ Consumer
-   UI Event for user clicked Nstat
-   UI Event for user clicked ntpq
-   UI Event for user clicked Nvidia System Management
-   UI Event for user clicked OPC UA Client
-   UI Event for user clicked OpenLDAP
-   UI Event for user clicked OpenNTPD
-   UI Event for user clicked OpenSMTPD
-   UI Event for user clicked OpenStack
-   UI Event for user clicked OpenTelemetry
-   UI Event for user clicked OpenWeatherMap
-   UI Event for user clicked Passenger
-   UI Event for user clicked PF
-   UI Event for user clicked PgBouncer
-   UI Event for user clicked PHP-FPM
-   UI Event for user clicked Ping
-   UI Event for user clicked Postfix
-   UI Event for user clicked PostgreSQL
-   UI Event for user clicked PostgreSQL Extensible
-   UI Event for user clicked PowerDNS
-   UI Event for user clicked PowerDNS Recursor
-   UI Event for user clicked Processes
-   UI Event for user clicked Procstat
-   UI Event for user clicked Prometheus
-   UI Event for user clicked Proxmox
-   UI Event for user clicked PuppetAgent
-   UI Event for user clicked RabbitMQ
-   UI Event for user clicked Raindrops
-   UI Event for user clicked RAS Daemon
-   UI Event for user clicked RavenDB
-   UI Event for user clicked Redfish
-   UI Event for user clicked Redis
-   UI Event for user clicked Redis Sentinel
-   UI Event for user clicked RethinkDB
-   UI Event for user clicked Riak
-   UI Event for user clicked Riemann Listener
-   UI Event for user clicked ROCm System Management Interface (SMI)
-   UI Event for user clicked S.M.A.R.T.
-   UI Event for user clicked Salesforce
-   UI Event for user clicked SFlow
-   UI Event for user clicked SNMP
-   UI Event for user clicked SNMP Legacy
-   UI Event for user clicked SNMP Trap
-   UI Event for user clicked Socket Listener
-   UI Event for user clicked SocketStat
-   UI Event for user clicked Solr
-   UI Event for user clicked SQL
-   UI Event for user clicked SQL Server
-   UI Event for user clicked Stackdriver Google Cloud Monitoring
-   UI Event for user clicked StatsD
-   UI Event for user clicked Suricata
-   UI Event for user clicked Swap
-   UI Event for user clicked Synproxy
-   UI Event for user clicked Syslog
-   UI Event for user clicked sysstat
-   UI Event for user clicked System
-   UI Event for user clicked systemd Units
-   UI Event for user clicked Tail
-   UI Event for user clicked TCP Listener
-   UI Event for user clicked Teamspeak 3
-   UI Event for user clicked Telegraf Internal
-   UI Event for user clicked Temperature
-   UI Event for user clicked Tengine
-   UI Event for user clicked Tomcat
-   UI Event for user clicked Trig
-   UI Event for user clicked Twemproxy
-   UI Event for user clicked UDP Listener
-   UI Event for user clicked Unbound
-   UI Event for user clicked uWSGI
-   UI Event for user clicked Varnish
-   UI Event for user clicked VMware vSphere
-   UI Event for user clicked Webhooks
-   UI Event for user clicked Windows Eventlog
-   UI Event for user clicked Windows Performance Counters
-   UI Event for user clicked Windows Services
-   UI Event for user clicked Wireguard
-   UI Event for user clicked Wireless
-   UI Event for user clicked x509 Certificate
-   UI Event for user clicked XtremIO
-   UI Event for user clicked ZFS
-    UI Event for user clicked Zipkin
-    UI Event for user clicked Zookeeper

**Comment by blegesse-git** [comment]
events are already being captured for all listed items. 
`event('Load data client library clicked', {type: item.name})` - Client Libraries 
`event('Load data file upload clicked', {type: item.name})` - File Upload Section 
`event('Load data Telegraf Plugin clicked', {type: item.name})` - Telegraf plugins
