### ISSUE TITLE
flux query builder: frozen view options

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#4906]
a user should be able to edit the view options of their visualization and see the result immediately. this is not currently the behavior in production.

**Comment by wiedld** [comment]
Assessment done in new DataExplorer (new QX FluxBuilder). Not the rest of the application.
In the graph customization options.
Breakdown per section.

Working:
* Data
* Y Axis Domain
* Hover Legend
  * Opacity 

Not always working. (Can get out of sync.):
* Options (a.k.a. Interpolation, LineColors)
* X axis
* Y Axis
* Positioning
* Hover Legend
  * Show/Hide
  * Horizontal/Vertical
  * Colorize rows

Cannot see the static legend, when requested to show.

**Comment by drdelambre** [comment]
solution potentially closes #4941
