### ISSUE TITLE
Flaky test in Flux Query Builder

### ISSUE THREAD

**Issue by appletreeisyellow** [influxdata/ui#4907]
The cypress test for Flux Query Builder (`fluxQueryBuilder.test.ts`) is flaky. The tests passes on local machines, but fail on CI. 

It may related to local storage and/or cypress parallelization.

Here is one of the failed monitor CI tests:
https://app.circleci.com/pipelines/github/influxdata/monitor-ci/12801

**Comment by wiedld** [comment]
On UI master branch today:

https://app.circleci.com/pipelines/github/influxdata/monitor-ci/13206
<img width="493" alt="Screen Shot 2022-07-07 at 12 53 22 PM" src="https://user-images.githubusercontent.com/10232835/177860707-2194dfae-e6fa-43fa-bfff-1e06d81b6e3d.png">

https://app.circleci.com/pipelines/github/influxdata/monitor-ci/13201
<img width="539" alt="Screen Shot 2022-07-07 at 12 55 42 PM" src="https://user-images.githubusercontent.com/10232835/177860839-1313dc50-5a08-4177-b06d-ec06e8d22f0a.png">
