### ISSUE TITLE
New Data Explorer: Fix sample data so it produces results

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#4983]
When running sample data in the new query experience, it doesn't produce results because it's using a from statement instead of an import statement. Let's update it to use the import statement so users are able to play around and see results using the sample data.

https://user-images.githubusercontent.com/81173353/177802256-151d311e-dfa6-4aa1-8f99-778a6e7213cb.mov

**Comment by hralexander** [comment]
For the time being we will remove sample data from the new data explorer. Design and product can re-evaluate where and how sample data should be brought into the new flux query builder.

**Comment by wiedld** [comment]
This ticket is about a sample data bucket, versus sample data from a csv (e.g. imported via flux statement).

We are sticking with bucket schema browsing only.
