### ISSUE TITLE
Query Zoom (GA) - Display Window Period on Graph per Cell

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4989]
**ACs**
- If the period is the same per yield, show it at the cell level. 
- @taramk has a Figma for this scenarios (Show upon hover)

**Design**
![Image](https://user-images.githubusercontent.com/112978673/189173481-3a379e1b-1b69-42c5-ad54-f9a098c4eaff.png)

**Comment by Luckette** [comment]
@taramk has a design for this that's ready. See her figma.

**Comment by taramk** [comment]
Show window period on chart tooltip if there are multiple window periods in the same chart:
https://www.figma.com/file/9iaD83d0YkKDYBEms5YKGM/windowPeriod-dropdown?node-id=342%3A971

Show window period on hover on the x-axis if there is one window period in the chart:
https://www.figma.com/file/9iaD83d0YkKDYBEms5YKGM/windowPeriod-dropdown?node-id=343%3A980

Let me know if you have any questions!

**Comment by ALuckette** [comment]
@TCL735 "If the period is the same per yield, show it at the cell level."

**Comment by TCL735** [comment]
Instead of on hover, the window period will be persistent in the Cell's header, on the right hand side, next to the settings wheel.
