### ISSUE TITLE
Query Zoom (GA) - Adaptive Zoom Tooltip Message

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4990]
ACs
~~- Provide an error message explaining that if a user wants to toggle ON adaptive zoom, then they need to use the v.window period variable rather than a hard-coded value (using the dropdown).~~
~~- Display the error message if the user tries to enable adaptive zoom when their window period is hard-coded.~~

- Update the adaptive zoom informational tooltip to show that it works with both auto and custom window periods.

**Comment by taramk** [comment]
Figma:
https://www.figma.com/file/9iaD83d0YkKDYBEms5YKGM/windowPeriod-dropdown?node-id=369%3A1534

**Comment by Luckette** [comment]
Awesome!!! Thank you @taramk !

**Comment by TCL735** [comment]
Since adaptive zoom works with both auto and custom window periods, we are updating this issue to be simply to update the tooltip to reflect the correct functionality.

No error messaging is needed.
