### ISSUE TITLE
Save Query/Script Option

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#5004]
## User Story

<p></p>

As a user, I want to be able to save the query/script I am working on so that I can come back to it later and re-load it and edit or use it again in the future.

## Acceptance Criteria

<p></p>

- When editing a query/script, a save option will be available to the user

- When the user clicks on the save option, they will be given the option to rename the file from the original/preselected name, if they have not already saved it- Once saved, the query/script will be available later to load

<p></p>

## Notes

<p></p>

Versioning and labels will come in future stories and is not expected for this particular story.

<p></p>

Reference:  Proposal on behavior:  <https://docs.google.com/document/d/13C6JZ7CscZMTIzG_3WMCgnOCCjtZYkGKNDUgSh0YiPw/edit#heading=h.mm433mqts43v>

<p></p>

<p></p>

**Comment by influx-product-manager** [comment]
Link to subfeature: https://influxdata.productboard.com/feature-board/planning/features/14244881

**Comment by juliajames12** [comment]
FIgma with Save button and modal design: https://www.figma.com/file/0qAntPk5LVangAHguWT74X/Query-Experience-Project?node-id=1588%3A65842

**Comment by wiedld** [comment]
Already done. Closing.
