### ISSUE TITLE
New Query/Script Option

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#5005]
## User Story

<p></p>

As a user, I want to be able to start a brand new query/script so that I can start something new, even if I was working on a different query/script.

<p></p>

## Acceptance Criteria

<p></p>

- An option will be available to start a new script/query

- When selected, if a query is in draft state, the user will be given the option to discard or save the script/query they are working on

- When selected, any bucket, measurement, tag, or field selection in the schema browser will be removed and the user will be back at bucket selection in that browser

- When selected, the flux editing window will be reset to blank

- When selected, any table or graph results that were previously generated will be wiped out

- When starting a brand new session, and navigating to the Data Explorer, he user will be shown an option to start a new query/script

- When navigating away from and back to the data explorer within the same session, the user will be shown the data explorer state as it was last in before they left it (different from first use in new session)

- New query/script will have the name “New Query/Script (Draft)”

- The user will be able to rename this new query/script something else

- Upon rename, the query will be saved (see save user story)

<p></p>

## Notes

<p></p>

Reference:  Proposal on behavior:  <https://docs.google.com/document/d/13C6JZ7CscZMTIzG_3WMCgnOCCjtZYkGKNDUgSh0YiPw/edit#heading=h.mm433mqts43v>

**Comment by influx-product-manager** [comment]
Link to subfeature: https://influxdata.productboard.com/feature-board/planning/features/14285793

**Comment by juliajames12** [comment]
@garylfowler @hralexander @drdelambre Here's the design for the new button. Keep in mind we'll have other file actions in this section.

![Image](https://user-images.githubusercontent.com/81173353/180845384-b960b6e0-4305-4fdd-a73c-11a598c3708b.png)

**Comment by juliajames12** [comment]
@garylfowler  Also, since we don't have the Save feature yet, I didn't include the confirmation modal in which you can save and name the previous script first. So essentially right now clicking "New Script" would wipe out your script. Let me know if you want a confirmation modal as an interim way to warn the user before we work on the Save feature.
