### ISSUE TITLE
Load Query/Script Option

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#5006]
## User Story

<p></p>

As a user, I want to be able to load a query/script that I had previously saved, so that I can run/view or edit again.

<p></p>

## Acceptance Criteria

<p></p>

<p></p>

- An option will be available to open or load an existing query/script within data explorer

- When selected, the user will be shown a list of previously saved scripts to choose from

- When shown a list of scripts, the user will be able to select one to load

- Once the user selects a script, it will be loaded and available to them in data explorer

- For now, the user will only be shown queries/scripts that they have created

<p></p>

## Notes

<p></p>

Versioning, labels/organization, and sharing are not expected for this story (those will be captured in future stories)

<p></p>

Reference:  Proposal on behavior:  <https://docs.google.com/document/d/13C6JZ7CscZMTIzG_3WMCgnOCCjtZYkGKNDUgSh0YiPw/edit#heading=h.mm433mqts43v>

<p></p>

**Comment by influx-product-manager** [comment]
Link to subfeature: https://influxdata.productboard.com/feature-board/planning/features/14285804

**Comment by garylfowler** [comment]
@juliajames12 - can you please update this ticket with your design?   Daniel told me today you had something ready for this.

**Comment by juliajames12** [comment]
Here's the Figma for this feature: https://www.figma.com/file/0qAntPk5LVangAHguWT74X/Query-Experience-Project?node-id=1711%3A72060

We have two options depending on time to implement:
Option 1: Save script as is (without tags and description)
Option 2: Save script with tags and description

**Comment by wiedld** [comment]
Already done. Closing.
