### ISSUE TITLE
Epic: Multi Org Phase 2 - Add Orgs & Edit Org Members

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#5011]
## Figma Prototype
https://www.figma.com/file/fvVSKwnepmRWvzFlIxCWCe/Multi-org?node-id=944%3A8136

**User Story: PAYG Only - Create an Organization**

    ACs
    - For PAYG Users, display a "Create Organization" option in the global header organization dropdown. 
    - There should be a "+" sign icon to the left of the "Create Organization" option in the org dropdown
    - For Free users, display an "Add More Organizations" upgrade button (since free users cannot create orgs)
    - If the user clicks the "Create Organization" option in the org dropdown on the global header, then redirect users to the AIM "create an organization" page and displays the page content inside a modal. ( Modal should match the design in Figma: https://www.figma.com/file/fvVSKwnepmRWvzFlIxCWCe/Multi-org?node-id=964%3A9688 )       
    - Org names must be unique per region (for now...). So, if the user types an org name that already exists, display an error message. (See Figma: https://www.figma.com/file/fvVSKwnepmRWvzFlIxCWCe/Multi-org?node-id=1639%3A11096 )
    - The first org created in an account should be the user's 'default' org 
    - unless the user manually changed their default org.
    - Once the new org is created, redirect the user to the same app page they're currently on, but in their new org. 
    - Once the new org is created, display a toast-like message stating that the new org was successfully created. 

    Implementation
    - Where in the code base does this exist on the AIM side? Has this been created/updated yet? Has it been updated to include the org name entry field? Who is responsible for creating and maintaining this? @randycoulman @alejom99 @kristinarobinson 

**User Story: Edit Org Members Page - Adding People to Org**

    ACs
    - Top of org members should say "Add Teammates to [Organization Name]"
    - Text below that should say "Teammates added will have owner access to the organization's resources"
    - Below that should be an input email address field. In that field display "name@company.com"
    - The email address field should be predictive text so that members that are already part of the account auto-finish
    -  To the right of the input email address field should be an Add button
    - under that, users can search the existing org members list (search bar, predictive text)
    - The 'org members' list should contain the following columns: Email, Role, Status (active, invitation expires...), a button to resent the invitation to members that haven't yet accepted, and a delete button. 
    - If a user has already accepted Terms & Conditions in any account or any region, then automatically set the user as 'active' once added to the org (no need to wait for the user to accept an invitation).
    - If a user has not accepted Terms & Conditions in any account or any region, then send the user an invitation and only add them to the org once the invitation is accepted. Display as "invitation expires xx/xx/xxx"
    - If T&Cs still need to be accepted by the user invited, after adding a user to the org, display a toast-like message stating "email sent to [email] to join [org]"
    - If T&Cs are already accepted, after adding a user to the org, display a toast-like message stating "[Email] has been added to [org]" 
    - The 'org members' list should be paginated. 

**User Story: Edit Org Members Page - Remove People From Org**

    ACs
    - User can click the trash can icon per member (row) on the org members list to remove the teammate
    - Upon clicking the trash can, display a modal (see Figma: https://www.figma.com/file/fvVSKwnepmRWvzFlIxCWCe/Multi-org?node-id=1412%3A10037 )
    - Top of the modal should display a warning message stating that "When you remove a teammate from an organization, you need to transfer their tokens and alerts to another teammate so scripts are uninterrupted."
    - Next, allow the user to select a user to transfer tokens and alerts to (Typeahead dropdown of all active users in the org) 
    - The "Remove Teammate" button on the modal should be disabled until they've chosen a teammate to transfer their tokens and alerts to. 
    - Display a toast-like notification when a user is removed from org stating "‘user@company.com’ successfully removed from [Organization Name]. API tokens and alerts transferred to ‘user@company.com’        
    - Match colors, icons, etc. that are in the Figma.

**Comment by Luckette** [comment]
Note: In April of 2022, @gunnaraasen mentioned that allowing users to "delete organizations" should be taken out of phase 2 of multi-org. We can continue to have conversations about 'delete org' requirements, but it doesn't have to delay the phase 2 launch. 

FYI - @alejom99 @kristinarobinson @juliajames12 @randycoulman @hoorayimhelping

**Comment by wdoconnell** [comment]
This work was completed by #6454 and #6531
