### ISSUE TITLE
Error and help message display

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#5014]
When a user runs a query that results in an error, we need to display the error message in an easy-to-read location so it can be quickly read and resolved. 

Right now we've placed the error message below the query controls. Sometimes this message pushes the controls to be outside of the viewport which causes the user to have to reload the page to get those controls back.

![Image](https://user-images.githubusercontent.com/81173353/178273362-79554b89-0854-44df-a779-088f5d28cf2b.png)

We'd like to move the error messaging up to right below the Monaco editor since the error is directly related to the script they've written. The error message should wrap so is doesn't close panels or move controls off the page. 

Also, we'd like to introduce a help message for scripts that produce no results because the metrics chosen don't included values within the chosen time range. 

Figma: https://www.figma.com/file/0qAntPk5LVangAHguWT74X/Query-Experience-Project?node-id=1509%3A57098

Design:
https://user-images.githubusercontent.com/81173353/178779257-57774a31-059a-4d56-9de8-76f1ab7f8690.mov

**Comment by drdelambre** [comment]
here's an example of a long error message


![Image](https://user-images.githubusercontent.com/1434802/178526967-871ba896-d52e-4c53-b279-91ec59c1efb2.png)
