### ISSUE TITLE
Tweak telegraf events to avoid an explosion of unique events

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#5015]
### Background
The events in [the telegrafs thunks file](https://github.com/influxdata/ui/blob/master/src/telegrafs/actions/thunks.ts) are structured in such a way that events are named uniquely, which causes an explosion of events that look like unique actions, when in fact they are the same action being performed on different resources.

Example:

```ts
event(`telegraf.config.${normalizeEventName(name)}.delete.success`, {id})
```
will create a new event in our system for every unique `name`

### Acceptance Criteria
- Change the events so that the name of the telegraf config being evented on is moved into the `fields` object (the third argument of the `event` method) and out of the measurement name.

**Comment by kristinarobinson** [comment]
Favian posted a spreadsheet with all events in the ui-channel
