### ISSUE TITLE
Multi Org Phase 1 - Remove existing Navigation Menu / Avatar

### ISSUE THREAD

**Issue by ChitlangeSahas** [influxdata/ui#5016]
After Multi org feature flag is turned on, we would no longer need the old menu that is in the Nav bar:

![Image](https://user-images.githubusercontent.com/18511823/178336171-40375458-b135-4496-921c-0f74ed918343.png)

The new global header handles all of this.

**Comment by wdoconnell** [comment]
Duplicate of UI issue #5564 

Resolved by UI PR #5572
