### ISSUE TITLE
Multi Org Phase 1 - User Pilot Callout to highlight new global header

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#5017]
Since there will be new header navigation soon in production, the idea is to add callouts in the UI drawing the user's attention to the new components w/ a brief blurb of what each new component is for.

**Comment by Luckette** [comment]
@juliajames12 - Can you help me figure out the design for this? Also, I think this is something that design can implement w/o engineering using user-pilot. @taramk is familiar with user-pilot. The intention here is to draw attention to the new global header so that it doesn't shock users once launched.

**Comment by wdoconnell** [comment]
@juliajames12 completed this, and it was launched yesterday with the globalheader in all prod environments.
