### ISSUE TITLE
Multi Org Phase 1 - switch to using quartz in lieu of IDPE for auth once orphaned user/org backfill completes

### ISSUE THREAD

**Issue by wdoconnell** [influxdata/ui#5022]
In [UI #4896](https://github.com/influxdata/ui/pull/4896/) we are reverting to using `idpe/me` for periodic polling to check session validity, since there are still some cloud users that cannot hit quartz endpoints. 

Once [quartz #6362](https://github.com/influxdata/quartz/issues/6362) is complete, we should go return to using quartz endpoints for those users, so that we can complete the move away from `idpe/me` in the cloud.

**Proposal:**
Return to polling `quartz` endpoints for session validity in lieu of `idpe` endpoints.

**Current behavior:**
Use `idpe/me` for auth polling after login.

**Desired behavior:**
Use `quartz` for auth polling after login.

**Use case:**
Part of multi-org epic.

**Comment by Luckette** [comment]
@randycoulman @alejom99 Can you let us know when AIM is done w/ the backfills?

**Comment by randycoulman** [comment]
https://github.com/influxdata/quartz/issues/6463

**Comment by randycoulman** [comment]
@Luckette @wdoconnell We finished the consolidation work this morning, so this should be good to go now.

**Comment by wdoconnell** [comment]
Note #5021 is the PR where we reverted the prior change due to the c2usage login issues.
