### ISSUE TITLE
Increase Measurement limit to 1000

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#5047]
## Task Description

<p></p>

Currently, we limit the number of measurements that can be displayed in the Data Explorer to 200.  There is a feature flag that can raise it to 500, but that feature flag is turned off in all environments currently.

<p></p>

Because of recent front and back end performance improvements, we believe this limit can be increased (and eventually removed all together with some additional work).   There is already a feature flag that enables you to increase the limit to 500.  

For now, we would like to increase this limit to 1000 and then turn on the feature flag in monitor301, tools, and production environments.

<p></p>

<p></p>

**Comment by appletreeisyellow** [comment]
The code is merged into master. It's still in the process of deploying to different environment. Once the code is deployed to all the environment, I will turn the feature flag on.

**Comment by philjb** [comment]
> we believe this limit can be increased (and eventually removed all together with some additional work).

Pagination is best approach here. What if there is a million or a billion measurements?

**Comment by garylfowler** [comment]
@philjb - yes, that was Ari's recommendation and what I was referring to by stating some "additional work).

**Comment by appletreeisyellow** [comment]
The feature flag `increasedMeasurmentTagLimit` is turned on for all environments
