### ISSUE TITLE
Error messages different between old/new data explorer

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/ui#5057]
in the old data explorer, a certain erroring query results in a meaningful error message.  in the new, the error message seems unrelated to the query problem.  

![Image](https://user-images.githubusercontent.com/25036188/179008769-c79e2b12-f86d-44c0-b0c2-887ff0817bf4.png)

![Image](https://user-images.githubusercontent.com/25036188/179008817-b0833b66-cffb-4d74-af74-2450de5d6010.png)

**Comment by drdelambre** [comment]
looks confusing, but this is the flux wasm's way of saying that there is a known issue with parsing the query. i cant remember if we added code for getting better error messages out of those libraries, or if we just talked about it, so i'll look into why we're not exposing it to the user before attempting to send the query

**Comment by aanthony1243** [comment]
here's the query text if it helps: 

```
import "date"
import "experimental"


    // So if 10s window then we don't need to aggregateWindow, the data in the 10sg bucket is already 10s mean
truncated = date.truncate(t:v.timeRangeStop,unit:1m)
splitPoint = experimental.subDuration(d: 10m, from: truncated)
truncatedStop =  date.truncate(t:v.timeRangeStop,unit:v.windowPeriod)
from(bucket: "AlertSeries")
// NOTE: if we use v.timeRangeStop in this function, v.windowPeriod is injected
  |> range(start: v.timeRangeStart, stop: truncated)
  |> filter(fn: (r) => r["_measurement"] == "gateway_error_threshold")
  |> filter(fn: (r) => r["_field"] == "n_above")
  |> filter(fn: (r) => r["env"] == "prod01-eu-central-1")
  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)
  |> yield(name: "last")
```

**Comment by wiedld** [comment]
Even more explicit. For this exact example, where in the shared QueryContext is failing:
1. AST parsed by wasm is fine.
2. Fails here (in UI code): https://github.com/influxdata/ui/blob/master/src/shared/contexts/query.tsx#L242
3. Then returns the empty string.

**Comment by wiedld** [comment]
So for this exact example, you have two things:
* windowPeriod failing:
     *  in shared QueryContext. which has it's own copy/paste of the windowPeriod code from the rest of the UI application.
* mismatched error messaging:
    * because shared QueryContext handles variables differently.

**Comment by aanthony1243** [comment]
Whether the fix is in the LSP or the UI QueryContext, the query has a valid error message that is getting lost in the new explorer.  Please focus on the bug of correctly surfacing that error message one way or another, either by fixing the QueryContext or reverting to the old DataExplorer query handler.  This is a blocker for releasing this feature to users, and should be prioritized.
