### ISSUE TITLE
Bug: Adaptive Zoom resets upon cell refresh

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#5058]
## Problem
Adaptive zoom resets upon cell refresh. In the event a user has set a granular cell refresh rate (ex: 10 sec), then the user's zoom will reset every 10s, which can be frustrating. 

## Steps to Reproduce
1. Set a custom auto-refresh rate on a cell to 10s
2. Use the adaptive zoom capability to reduce time between points (window period)
3. Once 10s pass, your zoom will reset and you'll lose context of what you were just doing... (frustrating)

## Screenshots

![Image](https://user-images.githubusercontent.com/98195941/179028096-4779bf15-4c47-473b-9dbb-a734c71c177b.png)

![Image](https://user-images.githubusercontent.com/98195941/179028120-e7f8de2f-4e7c-4aeb-8871-6cf62d9b8cae.png)

![Image](https://user-images.githubusercontent.com/98195941/179028143-ff47093f-f370-489b-a094-ea8979f616cd.png)

**Comment by kristinarobinson** [comment]
Auto refresh goes away once the PUSH model of retrieving data from storage.
