### ISSUE TITLE
Query/Script Asset Management (Load/Save)

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#5081]
# Initiative Product Brief

<p></p>

## Problem(s)

<p></p>

**Lack of consistent save/load capabilities for our query/script/task assets**

<p></p>

Currently, we have inconsistent ways of saving and managing queries/flux scripts in the Cloud2 Platform:

<p></p>

- The current data explorer only lets you save queries as a dashboard, notebook, or task. You can have multiple tabs and give them names, but you can't load/save those tabs (they are only good for that browser/session).

- The queries inside of dashboards can only be saved and used for dashboards (without cutting and pasting them somewhere else) and you can't reference queries created somewhere else

- The queries inside of tasks and alerts are only good for tasks/alerts and you can't reference queries created somewhere else

- Notebooks has a save feature, but to "load" a new notebook you have to re-navigate to the notebook panel and select another one, which is a clunky exchange (to re-select notebooks navigation when you are already in notebooks).

<p></p>

**Lack of ability to organize query/script/task assets**

<p></p>

In addition, there are limited ways to organize these assets, even for the areas where you do have some save capability.  Notebook lists are a complete long flat list.  Dashboards are a long card list (with some labeling capability).  While this works ok for a single user, single organization implementation - this quickly gets difficult to manage for larger organizations with multiple users.  Even medium size organizations, like InfluxData for instance, can quickly end up with a large list of resources.  We know of customers that have several thousand tasks, all just in a long list.  It is difficult for them to sort through and find the task that they are looking to find.

<p></p>

**Lack of any permissions on visibility**

<p></p>

There currently is a complete lack of permissions capability for the assets of any of the areas that involve queries/scripts/tasks/alerts.  While this Product Brief doesn't attempt to fully address that, pending an RBAC type implementation,  there is a need to at least establish "my" assets vs. organization "assets", in other words, shared vs. unshared with others.

<p></p>

**Lack of any versioning capability**

<p></p>

Finally, we have limited versioning in place for our query assets.  Notebooks has a revision/publishing history feature, but no other type of asset has this.  While the need here will vary based on the function, at least some versioning mechanism needs to be put in place.

<p></p>

**Lack of Ability to manage Invocable Scripts or Re-use scripts in any way**

<p></p>

Currently, we have the capability to use a script as an invocable script that can be called from a client library or other API request.  But we don't really have a way to edit/manage those invocable scripts.  While the new Data Explorer/Flux Script Editor may be a great way to edit those scripts, it would be useless for this purpose unless it has a way to save those scripts and give them a name that can be used when making the API call. 

<p></p>

There is currently no way to re-use scripts/queries that are created in one area of the software to be used in a different area of the software without a copy and paste..  Changes then to one or the other don't get automatically made to the other area (sometimes good and sometimes bad) and are difficult to maintain.  We want to be able to re-use queries created in data explorer to be referenced in dashboards, and tasks and alerts.

<p></p>

**Lack of ability to manage flux modules**

<p></p>

The flux team is working on flux modules feature.  This will be difficult to use without a way to manage those assets, including load/save/edit and versioning.

## Hypothesis & Data

<p></p>

We believe that making queries/scripts easier to save and re-use will drive more queries (less time re-creating a previously built query) and making them re-usable in tasks and alerts has the opportunity to drive more recurring tasks, which drives usage even quicker.

<p></p>

It is also believed that this will improve retention and customer satisfaction as the lack of save option in Data Explorer has been a common complaint.

<p></p>

Notebooks are very commonly saved.  The usage between Data Explorer and Notebooks is not that far away from 50/50.  But yet we have no save function in Data Explorer.  This has been a paint point for even internal users of the cloud UI.

## Proposed Solution

<p></p>

There were many problems outlined above that we are trying to solve here.  It is NOT expected that we need to solve all of these problems all at once.    The most fundamental need and short term use case here is simply the ability to load and save queries.    However, in any design and architecture, we should keep all of these problems in mind for the future possibility of solving.

<p></p>

The desired solution will provide the **minimum** following capabilities:

<p></p>

**Basic Load/Save & Asset Storage Organization**

<p></p>

- Load & Save a Query in Data Explorer

- Load & Save a Query in Data Explorer in an organized way (folder/label/tree type organization)

- Ability to load or select a query in other parts of the UI, for example, tasks and alerts (the actual work to make tasks/alerts use saved queries as invocable scripts is in a different initiative - this is just to enable the data explorer to save them in such a way they can be referenced by tasks/alerts

- The ability to add/delete labels or folders so the user can self-organize 

- The ability to retain last modified & created dates and user who created/modified them

- Ability to give a query/script a description in addition to the name

<p></p>

These capabilities are highly desired:

<p></p>

**Auto-Save**

<p></p>

- Auto-save of unsaved script changes to temporary name/location - only visible to author

<p></p>

**Copying and Moving**

<p></p>

- Ability to copy/clone and re-label/move

<p></p>

**Flux Module and Versioning Support**

<p></p>

- Ability to assign a property or flag to a script indicating it is a flux module

- Ability for that flux module to be referenced then in other scripts or in some cases, from the flux function selection

- Ability for basic versioning of any script 

- Ability for advanced versioning of any script set as a flux module (major and minor version support)

- Revision History Saving and Selection

<p></p>

**Basic Visibility**

<p></p>

- Ability to assign a property or flag to a script/query indicating its visibility (visible just by the author, or ability to be seen by all users of the organization)

<p></p>

**Invocable Script Support**

<p></p>

- Ability to designate a query/script as an invokable script (unsure if this is needed, needs discussion)

<p></p>

## Projected Impact & Evidence

<p></p>

The bet here is that having this capability will:

<p></p>

1) Increase new customer adoption

2) Drive additional usage

3) Aid in Customer Retention

<p></p>

There is no hard evidence to support this projection; but it seems like at least the load/save is an MVP type feature that was previously missed and we need to correct.

<p></p>

<p></p>

## Appendix

<p></p>

Link to discussion document about load/save states

<p></p>

<https://docs.google.com/document/d/13C6JZ7CscZMTIzG_3WMCgnOCCjtZYkGKNDUgSh0YiPw/edit#heading=h.z6ne0og04bp5>

<p></p>

<p></p>

<p></p>

**Comment by influx-product-manager** [comment]
Link to feature: https://influxdata.productboard.com/feature-board/planning/features/13782592

**Comment by garylfowler** [comment]
We likely won't end up doing this EPIC with the direction we took so far, but the next stories related to this will be Cloning a script and script visibility.

**Comment by wiedld** [comment]
Parts we planned to do, are already done (or in separate tickets). Closing.
