### ISSUE TITLE
Feature Flag Cleanup: paginatedTokens

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#5089]
### Acceptance Criteria
- Remove `paginatedTokens` feature flag
- Remove old non-paginated tokens that are no longer in use
- Rename PaginatedTokens components to be like the now-removed non-paginated tokens

**Comment by blegesse-git** [comment]
@hoorayimhelping Palak removed this ff from the UI codebase 6 months ago according to [this](https://github.com/influxdata/ui/pull/3713) pr.
