### ISSUE TITLE
Bug: firstMile - Boilerplate App Link broken on node.js finish page

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#5105]
**Problem**
Daniel Campbell and Gary Fowler get a 404 error when trying to navigate to the node.js Boilerplate app. I (Amy) do not get this error, but this could be because I have access to the repo. Are we sure that all the links on the Finish pages are **public**? 

**More info Needed**
- What happened when the error occurred?
- How to reproduce it?
- Are you using our Cloud or OSS product?  
- What version?
- What browser are you using?

**Screenshot**
![Image](https://user-images.githubusercontent.com/98195941/179796676-da02b821-7e04-4923-ad03-f85ab5c5db17.png)

**Comment by Luckette** [comment]
Waiting for more information from @garylfowler & @mavarius

**Comment by kristinarobinson** [comment]
Fixed.
