### ISSUE TITLE
error with query...

### ISSUE THREAD

**Issue by p-hu** [influxdata/ui#5106]
## About the bug

**Steps to reproduce:**

I tried to execute this query. SUN_PERCENT is float, sun is int. I don't see any issue with the query, they work each separately when each of them is in a separate query AND only one of them is visible. If I set both as visible, I get the same error. So I tried to combine both queries but got the same error in the web view.

from(bucket: "Energy")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "meteo-forecast")
  |> filter(fn: (r) => r["_field"] == "SUN_PERCENT")
  |> drop(columns: ["age_h"])
  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)
from(bucket: "Energy")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "meteo-forecast")
  |> filter(fn: (r) => r["_field"] == "sun")
  |> drop(columns: ["event"])
  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)
  |> yield(name: "mean")

**Expected behavior:**

display data in web view.

**Actual behavior:**

an influxDB error has occurred...

**Visual Proof:**

## About your environment

**Environment info:**

web interface:
https://europe-west1-1.gcp.cloud2.influxdata.com/orgs/1b9fe685fd63ca1e/data-explorer

**Config:**

**Logs:**

**Comment by drdelambre** [comment]
can you try and at a `|> yield(name: "sunPercent")` to the end of your first query? does that make the error go away?

**Comment by p-hu** [comment]
Yes, it works!

Sorry, I am new to the flux syntax and keep on struggling :-) There are not so many examples in the net yet.

Thanks!

 
 

Gesendet: Dienstag, 19. Juli 2022 um 23:47 Uhr
Von: "Alex Boatwright" ***@***.***>
An: "influxdata/ui" ***@***.***>
Cc: "p-hu" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [influxdata/ui] error with query... (Issue #5106)


 

can you try and at a |> yield(name: "sunPercent") to the end of your first query? does that make the error go away?

**Comment by kristinarobinson** [comment]
User corrected flux and issue is now resolved.
