### ISSUE TITLE
[bug] Explorer Page: "An InfluxDB error has occurred. Please report the issue here." on 

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#5127]
## About the bug

Visiting the explorer page causes an error (in monitor301).

```
[Error] TypeError: undefined is not an object (evaluating 'e.retentionRules.find')
l — buckets.ts:12
processStrategy — buckets.ts:31
(anonymous function) — normalizr.es.js:170
map
C — normalizr.es.js:515
(anonymous function) — buckets.tsx:93
Fu — react-dom.production.min.js:262:359
(anonymous function) — scheduler.production.min.js:18:343
bu — react-dom.production.min.js:243
bu
(anonymous function) — react-dom.production.min.js:123:115
(anonymous function) — scheduler.production.min.js:18:343
Ko — react-dom.production.min.js:123
Qo — react-dom.production.min.js:122:428
Ne — react-dom.production.min.js:292:101
Kt — react-dom.production.min.js:73:355
Kt

	cs (32.7179099427.js:2:2666474)
	(anonymous function) (32.7179099427.js:2:2668904)
	mi (32.7179099427.js:2:2632660)
	vs (32.7179099427.js:2:2670150)
	Mu (32.7179099427.js:2:2686756)
	Mu
	(anonymous function) (32.7179099427.js:2:2706025)
	Iu (32.7179099427.js:2:2683495)
	bu (32.7179099427.js:2:2679606)
	bu
	(anonymous function) (32.7179099427.js:2:2629167)
	(anonymous function) (32.7179099427.js:2:2706025)
	Ko (32.7179099427.js:2:2629113)
	Qo (32.7179099427.js:2:2629048)
	Ne (32.7179099427.js:2:2699850)
	Kt (32.7179099427.js:2:2607703)
	Kt
```

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Visit explorer page

**Expected behavior:**
no error - or at least an error message that tells me how to possibly resolve it.

**Actual behavior:**
error

**Visual Proof:**

<img width="1131" alt="Screen Shot 2022-07-20 at 12 05 00 PM" src="https://user-images.githubusercontent.com/13472206/180062261-abc9c883-e53a-4a3e-9406-bc4c79a8401d.png">

## About your environment

**Environment info:**
cloud2

**Config:**

**Logs:**

see above

**Performance:**
na

**Comment by kristinarobinson** [comment]
@philjb - is this using the NEW data explorer page or the default one?

**Comment by aanthony1243** [comment]
@hralexander can you track this?

**Comment by philjb** [comment]
The current explorer page (not the new one).

**Comment by drdelambre** [comment]
a commit went out yesterday to potentially address this. @philjb can you still reproduce it?

**Comment by philjb** [comment]
I cannot - but that doesn't mean much as it occurred sporadically.

**Comment by drdelambre** [comment]
imma close this then with the full expectation that it might get opened again if the issue re-emerges
