### ISSUE TITLE
Export graphs as bitmaps

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#514]
### User Story
As a person who visualizes data in a team environment, I'd like to share specific pieces of data with my teammates in an easily shareable, and easily consumable format.

### Background
Inspired by the success of the graph bitmap hackathon project, we're going to make exporting a bitmap / screenshot of the graph a first class feature.

Currently all this functionality lives on the frontend as an aspect of [the Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API).

**Comment by hoorayimhelping** [comment]
>It would also be amazing if we can include a png of a graph. Would be a huge benefit in pagerduty alerts like:
- Derek

>I want thisssss
- Steven Soroka

https://influxdata.slack.com/archives/C02GAR82Q/p1614101619361300

**Comment by mnorriswalker** [comment]
Merged into https://app.zenhub.com/workspaces/all-products-5d8d0c5340a79000013f1eba/issues/influxdata/ui/14
