### ISSUE TITLE
[bug] New Data Explorer: `Unexpected identifier "undefined"`

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#5166]
## About the bug
When navigating the new data explorer tag and field picker, sometimes clicking on a tag or field value doesn't produce new flux in the query editor. The console shows this error.

```
[Error] SyntaxError: JSON Parse error: Unexpected identifier "undefined"
parse
o — utils.ts:3
promiseReactionJob

	o (0.worker.b91cd30775a7627bcb0c.js:1:100965)
	promiseReactionJob
```
![Screen Shot 2022-07-22 at 4 06 02 PM](https://user-images.githubusercontent.com/13472206/180579336-5f7c25ce-cd4c-4efc-ad4d-43e6d689e5df.png)

**Steps to reproduce:**
Use the new data explorer

**Expected behavior:**
no errors

**Actual behavior:**
flux doesn't automatically populate

**Visual Proof:**

see above

## About your environment

**Environment info:**
cloud2

**Config:**

na

**Logs:**

na

**Performance:**
na

**Comment by wiedld** [comment]
Already fixed. https://github.com/influxdata/ui/pull/5299
