### ISSUE TITLE
Operator Page:  Search is not case insensitive, space is suppressed.

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#5168]
see https://github.com/influxdata/EAR/issues/3468

## About the bug
Resource search in case sensitive, which means it doesn't handle case (upper, camel, capitalized) when matching for search results.  

List the minimal actions needed to reproduce the behavior.

1. Go to operator page
2. Search account list, using camelCase

**Expected behavior:**
returns matches regardless of case

**Actual behavior:**
does not return a match, and suppresses space in space bar

**Visual Proof:**
see screenshots from EAR

## About your environment

cloud 2 operator page

**Comment by ChitlangeSahas** [comment]
I've reached out to the AIM team, this might not be possible without an API change. `getOperatorAccounts` API seems to be case sensitive.

**Comment by ChitlangeSahas** [comment]
https://github.com/influxdata/quartz/issues/6646 made the change on the API side, this should be fixed 👍
