### ISSUE TITLE
CSV Uploader

### ISSUE THREAD

**Issue by sjwang90** [influxdata/ui#517]
- [ ] Usage Measurement: track usage for CSV uploader
  - Amount of data written in via CSV uploader
  - Number of clicks in Google Analytics
- [ ] Add CSV upload (and Line Protocol)  tile to "Data Sources" Page

**Comment by Asalem1** [comment]
@sjwang90 we should be able to setup a dashboard based on some of the eventing we have around the CSV uploader. We can try to set that up and close this out unless you wanna track the number of submission clicks with google analytics

**Comment by sjwang90** [comment]
Let do the eventing with CSV uploader. That will give us a better depiction of of how it's being use. 

And then we should be all good 💥
