### ISSUE TITLE
Flaky Test: fluxQueryBuilder detached DOM element

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#5171]
Reference pipeline:
https://app.circleci.com/pipelines/github/influxdata/monitor-ci/13760/workflows/cf6740d0-8fad-4e73-af1c-7573f17a2e9a/jobs/850970

Error:
> CypressError: Timed out retrying after 10000ms: "cy.trigger()" failed because this element is detached from the DOM.
> "<button class="tag-selector-value--load-more-button" data-testid="tag-selector-value--load-more-button">+ Load ...</button>"
> Cypress requires elements be attached in the DOM to interact with them.
> The previous command that ran was:
>   "cy.should()"
> This DOM element likely became detached somewhere between the previous and current command.

Fix:
move the commands on lines 138-160 into a .then() so the functions on those lines will wait for click() to finish rendering.

**Comment by blegesse-git** [comment]
.then() solution didn't work. I also tried intercepting the post request when `tag-selector-value--header` is clicked to make cypress wait for the new page to load before accessing DOM elements. This seems to fix the `can't find load button` issue but now cypress can't find `tag-selector-value--list-item--selectable`
