### ISSUE TITLE
Transfer Tokens/Alerts From Removed User

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#5207]
**ACs**

- User can click the trash can icon per member (row) on the org members list to remove the teammate
- Upon clicking the trash can, display a modal (see Figma: https://www.figma.com/file/fvVSKwnepmRWvzFlIxCWCe/Multi-org?node-id=1412%3A10037 )
- Top of the modal should display a warning message stating that "When you remove a teammate from an organization, you need to transfer their tokens and alerts to another teammate so scripts are uninterrupted."
- Next, allow the user to select a user to transfer tokens and alerts to (Typeahead dropdown of all active users in the org) 
- The "Remove Teammate" button on the modal should be disabled until they've chosen a teammate to transfer their tokens and alerts to. 
- Display a toast-like notification when a user is removed from org stating "‘user@company.com’ successfully removed from [Organization Name]. API tokens and alerts transferred to ‘user@company.com’        
- Match colors, icons, etc. that are in the Figma.

**Comment by wdoconnell** [comment]
Converting the context menus to a modal will be completed by UI #5206, but the tokens/alerts transfer is blocked and cannot be completed without additional quartz work.

There is an [idpe endpoint](https://github.com/influxdata/openapi/blob/master/src/cloud/schemas/ProvisionUserDeleteRequest.yml) to handle transfer of tokens and alerts. After testing in remocal and discussion with @gavincabbage, my understanding is that this is implemented in a way that could be called by quartz using an operator token, but cannot be called by Cloud2 UI users.
