### ISSUE TITLE
firstMile: Arduino - UI Eventing

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#5219]
**ACs**
   - See our UI Eventing Dictionary here: https://influxdb.atlassian.net/wiki/spaces/IPO/pages/2530574337/UI+Eventing+Dictionary
   
**Dev Notes**

- Send events to Snowflake to eventually be consumed by Domo.

**Comment by Luckette** [comment]
@ChitlangeSahas - I'm adding the proposed Arduino event names to the UI Eventing Dictionary today 8/18/22.

https://thenewstack.io/monitoring-air-quality-with-influxdb-and-telegraf/

**Comment by ChitlangeSahas** [comment]
Events were already shipped with previous PR's so we'll close this. New event names can be shipped as part of a new epic to refactor UI events in accordance with the new format.
