### ISSUE TITLE
firstMile: Arduino - Sample IoT App

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#5223]
**ACs**
- Work w/ the docs team (Sunbrye & Kelly) to determine who should create the sample IoT app written in Arduino. 
- Match the sample IoT app to the other sample IoT apps at the end of the other wizards.

**Comment by Luckette** [comment]
@sunbryely-influxdata Do ya'll have a sample IoT app written in Arduino by any chance?

**Comment by sunbryely-influxdata** [comment]
> @sunbryely-influxdata Do ya'll have a sample IoT app written in Arduino by any chance?

@Luckette Unfortunately we do not
