### ISSUE TITLE
eslint warnings relating to useEffect hook dependencies in writeData pages

### ISSUE THREAD

**Issue by alexjw3** [influxdata/ui#5248]
This is a subset of issue https://github.com/influxdata/ui/issues/4815, which is being chunked into smaller, logical units so that it can be analyzed in greater detail by a few members of the team.

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.
1. run `yarn eslint` in ui root directory
2. receive warnings from React hooks with missing dependencies in `writeData` directories

**Expected behavior:**
Eslint warnings for missing dependencies either do not exist, or (where appropriate) are suppressed.

**Actual behavior:**
Eslint warnings like the following, as shown in the attached file. `warning React Hook useEffect has a missing dependency: 'dispatch'. Either include it or remove the dependency array`

**Visual proof**
Sample of `eslint` log

![Image](https://user-images.githubusercontent.com/13280708/181828826-838d63b7-78f3-4820-8970-30ad5dc26990.png)

See https://github.com/influxdata/ui/issues/4900#issuecomment-1167437264 for guidance.

**Comment by wdoconnell** [comment]
Not a priority at this time. Closing.
