### ISSUE TITLE
Use separate redux statuses for getting identity, currentBillingProvider, and orgDetails

### ISSUE THREAD

**Issue by wdoconnell** [influxdata/ui#5268]
Since `identity`'s properties don't map 1:1 onto `quartzMe`, that data now comes from three endpoints - /quartz/identity, /quartz/accounts/:accountId, and /quartz/orgs/:orgId. They are sharing the same `status` in redux state, so one can overwrite the other. This is blocking some optimizations to the data flow when loading the app.

Might be able to remove one of these calls with the [new identity route that includes regionBeta information.](https://github.com/influxdata/ui/issues/4823)

**Comment by kristinarobinson** [comment]
Not needed.
