### ISSUE TITLE
Some dashboard scatter plot graphs data is missing 

### ISSUE THREAD

**Issue by mkm-influx** [influxdata/ui#5288]
![Screen Shot 2022-08-03 at 1 57 48 PM](https://user-images.githubusercontent.com/53878892/182711412-8c78fade-1513-443d-b100-2538108ed64b.png)

## About the bug

**Steps to reproduce:**
The above graph illustrates a phenomena of not seeing all the data when one hovers over a data point in the graph with the solid blue color.
1. ...Go to https://us-east-1-2.aws.cloud2.influxdata.com/orgs/5d59ccc5163fc318/dashboards/09aca43525a23000?lower=now%28%29+-+7d
2. ...Hover over the solid blue scatter plot graph.
3. ...Observe data points (see video below)

**Expected behavior:**

We expect to see scatter plot graph in Storage Pod 6 to be a multi-colored scatter plot graph, and illustrates all data associated with like when viewing in raw csv data table. 
**Actual behavior:**

A solid blue scatter plot graph only shows timestamp and value.
**Visual Proof:**

https://user-images.githubusercontent.com/53878892/182722584-04bc2957-f302-4268-9b88-85185df76101.mp4

## About your environment

**Environment info:**
Go to https://us-east-1-2.aws.cloud2.influxdata.com/orgs/5d59ccc5163fc318/dashboards/09aca43525a23000?lower=now%28%29+-+7d<!--

**Comment by TCL735** [comment]
What we need: the flux response which is the comma separated string that comes back over the network from making a query.

Can we please get the flux response payload from the graph with the issue? This can be found under the "Network" tab in the console of the browser by clicking on the query from the affected cell.

Also, as a control, can we also get the flux response from a graph that is working correctly.

Thanks.

**Comment by TCL735** [comment]
@mkm-influx is this still an issue? Seems like it was just bad data coming back from the backend. But please let us know if you are still having a problem with Scatter plots.
