### ISSUE TITLE
Schema Composition:  design middleware layer between LSP and monaco-editor client.

### ISSUE THREAD

**Issue by wiedld** [influxdata/ui#5305]
## Problem

The monaco-editor and the LSP have a direct communication channel, which the UI does not currently listen into. What this means is that any LSP response/event sent to the monaco-editor client, must result in a monaco-editor action which provides the behavior we want. If we want any UI action (in response to the LSP), outside of the monaco-editor....then we currently cannot do so.

### Example use case: Composition event fails
1. user starts a schema composition
2. user asks for an LSP schema event
    * e.g. user adds a field
3. the UI (not the monaco-editor client) then:
    * triggers a json-rpc message to the LSP
    * adds the `field X` badge to the UI
4. the LSP returns some form of failure event
    * monaco-editor client gets the response.
    * UI itself (outside the editor) does not get the response.
6. monaco-editor can take actions, but those are limited.
    * e.g. `window/showMessage` only surfaces in the browser console. Not to the user.
7. if we have the UI listening to this traffic in some way:
    * remove the `field X` badge. Because the addition of the field filter was a failure.
    * also can surface to the user a notification, for any other failure case

### Other use cases:
* with the async nature of events, we can have a race condition with user-triggered events.
   * client requests, server responds, client applies changes:
        * each executeCommand (a.k.a. request for composition change), gets an applyEdit response.
        * response is an atomic operation to be performed
        * client performs the change
   * it takes time for the client to apply the change.
        * During this time, if another executeCommand is issued, the applyEdit response will be based on previous/old state. Before the last applyEdit was performed.
   * solution needs:
       * something listening to request/response
       * something which queues our executeCommand requests, and only sends the next request after the previous applyEdit completes.
       * something which updates the UI is the server response is a failure. 

### Current setup
* monaco-editor and LSP has a communication channel, via the monaco-languageclient
* the ways that we can interface with this channel, does not fulfill our needs.
  * see here: https://github.com/influxdata/ui/pull/5289

## Proposed solution

Build our own middleware between the workers, and the monaco-languageclient channel. This middleware will be on the level of the worker post/send with the buffer streams, which is lower down (used by) to the monaco-languageclient. In this way, we can be unconstrained in the middleware abilities, rather than relying on the interfaces provided by monaco-languageclient channel.

### Proposed implementation layer:
We already have that layer of abstract for the fallback worker. Likely will do a similar pattern around the worker and fallback worker.
https://github.com/influxdata/ui/blob/master/src/languageSupport/languages/flux/lsp/monaco.flux.lsp.ts#L73-L86

### Ramifications of design:

This would allow us to do more division of responsibilities, to the most enabled part of the code:
* allow us to do more flux editing (injected etc) in the UI via clicking buttons etc. 
* with the LSP still ensuring correctness (a.k.a. all actions being requests to the LSP).
* all updates to the flux script itself, is still done by the editor (e.g. injection in response to LSP applyEdit)
* all additional UI interactions (e.g. show message, show failure, add/remove widget) is handled in the UI javascript code.

**Comment by wiedld** [comment]
Immediate, additional use case:
*  LSP can decide to turn off the schema sync. Then the UI will receive the message, and handle the change to session store.

**Comment by rockstar** [comment]
> the best solution to a problem is eliminating the conditions that create that problem rather than adding another solution that creates new unique problems

In this specific case, I think the middleware, as a proposal, isn't the right direction to go. For more granularity on how we should solve this, see the specific details in #5575

**Comment by wiedld** [comment]
Equivalent created. Closing.
