### ISSUE TITLE
Login with Google NO ACCOUNT?!

### ISSUE THREAD

**Issue by Bra1nsen** [influxdata/ui#5308]
I need urgent help,

i would like to export data from influxdb to grafana, i need username and password for that, but i always login via google. Do I have a user? In any case, it is not my Google login data.

Going to my googlemail forgot my password doesn't help either. What to do?

-LOGIN WITH GOOGLE
![Screenshot 2022-08-05 150510](https://user-images.githubusercontent.com/58213050/183084162-b7f8f166-b564-4494-a2cb-de1fb7ce6268.png)
-MY ACCOUNT
![Screenshot 2022-08-05 150548](https://user-images.githubusercontent.com/58213050/183084192-fd61aaac-67b8-4066-ad4d-fe5b27255ef7.png)
- NO ACCOUNT LOGIN DATA
![Screenshot 2022-08-05 150632](https://user-images.githubusercontent.com/58213050/183084227-fae70e3b-2442-412b-bc6c-f98d838986c5.png)

**Comment by kristinarobinson** [comment]
@Bra1nsen -- I'm sorry you're experiencing this.

Our Google SSO should match directly with the Google account you signed up with.  Do you have multiple Google Accounts, such that you might have chosen a different one?  We directly interact with Google for authentication.

When you sign in to your Cloud account (with Google), click on the Nav Bar, and then your profile.  That will tell you your username (which should be your google email address).  To be honest, I'm not that familiar with Grafana, so I'm not sure how our Google integration for signon plays with Grafana.

I will ask our Accounts team for further information.

**Comment by Bra1nsen** [comment]
![Screenshot 2022-08-10 201714](https://user-images.githubusercontent.com/58213050/183987085-c55123d0-de52-4820-a4de-6136bf94f977.png)

cant login with google account.. so how do i login without using the google button?

**Comment by gspletzer** [comment]
@Bra1nsen I don't believe you can login directly since it is already set up as an SSO login. 
Regarding the issue connecting to Grafana, per @randycoulman `According to the Grafana docs, the password field should be their token, not their actual password.` See https://grafana.com/docs/grafana/latest/datasources/influxdb/#influxql-classic-influxdb-query
