### ISSUE TITLE
Reorder tabs in account and org settings pages

### ISSUE THREAD

**Issue by wdoconnell** [influxdata/ui#5309]
Tab order in the account and org settings pages is:

1. Account - Billing, Settings
2. Organization - Members, Settings, Usage

And per the figma, the account order for the globalheader is: 

1. Account - Settings, Billing
2. Organization - Settings, Members Usage.

Order for these two should be the same for consistency. @Luckette : @juliajames12 's recommendation is to change the order of the pages, since having 'Settings' first is probably more logical.

**Comment by hoorayimhelping** [comment]
While we're changing ordering, can have the urls match the headings? Org members and settings go to `users` and `about`, respectively

**Comment by Luckette** [comment]
@blegesse-git Thanks for your work on this so far. I agree w/ Bucky's advice to make the URLs match the headings. :)
