### ISSUE TITLE
Operator Page: OrgOverlay has hard-coded URL to Old Tools

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#5311]
ui/operator/OrgOverlay.tsx contains a link to the Usage Dashboard for a given org.  That link is hardcoded to Old Tools on line 111:

> href={`https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/0649b03029c49000?vars%5Borgid%5D=${orgID}`}

This URL should be replaced with either a relative reference or hard-coded new Tools URL: Check with e-commerce team about what this setting should be.

**Comment by randycoulman** [comment]
It should be the hard-coded new tools URL: `https://us-east-1-2.aws.cloud2.influxdata.com/` with the same path as before.
