### ISSUE TITLE
Standardize search fields across app

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#5312]
**Is your feature request related to a problem? Please describe.**
There are several different variations of the search bar throughout our platform. Some of the variations include:

- eye glass icon/no eye glass icon
- "Search" vs. "Filter"
- phrasing (ie. "Search for a bucket" vs. "Search buckets")
- inclusion and exclusion of an ellipses

**Describe the solution you'd like**
In all cases that include a search bar (not filter), we should use the following format:
- Include eye glass icon
- Use phrasing "Search" then the plural form of the item the user can search
- No ellipses
<img width="430" alt="Screen Shot 2022-05-25 at 11 50 41 AM" src="https://user-images.githubusercontent.com/81173353/170304475-62dbb4bc-da6c-42b9-aaa5-c3834d724ce0.png">

**Outstanding decision:**
What colors should we use for the icon and text in the default state? Can we make sure that is standardized that as well?

**Comment by wdoconnell** [comment]
Closing due to priority.
