### ISSUE TITLE
Injecting two fields from new schema browser creates a query that will always have 0 results 

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/ui#5314]
Problem:  in the new schema browser, if I select two different fields for inclusion in my query, they are added as separate filters, which is implicitly an AND condition.  This results in a query in which 0 rows match both field names (by definition of the datamodel).   

<img width="892" alt="Screen Shot 2022-08-05 at 2 16 46 PM" src="https://user-images.githubusercontent.com/25036188/183137344-b3c74820-f0fb-492c-8076-24e437416acf.png">

Expect: fields should be collected using a single filter line that is appended with OR conditions, as in: 

 |> filter(fn: (r) => r._field == "kafka_under_replicated_partitions"  or  r._field == "volume_usage_percent")

Note that this is not a generalized union of all possible filter conditions.  This is specifically a disjunction of field name equality conditions and represents the correct way to pull out multiple fields in a single query.

**Comment by wiedld** [comment]
Already solved with schema composition.
