### ISSUE TITLE
too many error messages in new data explorer corrupts layout

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/ui#5316]
I had a query with many error messages, which prevented me from seeing the code and fixing the problems: 
<img width="1223" alt="Screen Shot 2022-08-05 at 4 34 12 PM" src="https://user-images.githubusercontent.com/25036188/183158778-f3f1dc9a-a02a-42e2-8c58-80deebd5a582.png">

The panel should have a fixed size and be scrollable

**Comment by drdelambre** [comment]
@juliajames12 aren't you working on the next iteration of this?

**Comment by wiedld** [comment]
This was just brought up again by @jdstrand . Moving onto our board.
