### ISSUE TITLE
Schema Composition: explanation/instructions to user?

### ISSUE THREAD

**Issue by wiedld** [influxdata/ui#5340]
Instructions via comments, in flux script?
* On new session, make placeholder query:
    * Schema builder on left.
    * Function injection on right.
* On first session composition:
    * Does some intro into what the composition does.
    * Explains the sync button.
    * States when we’ll turn off sync for you. (e.g. once you type in the composition block.)

**Comment by wiedld** [comment]
With the patch being merged now, we may be able to do it.

**Comment by appletreeisyellow** [comment]
Julia has a [mock up](https://www.figma.com/file/0qAntPk5LVangAHguWT74X/Query-Experience-Project?node-id=1719%3A82252) of instructions in the Monaco editor to let users know how to start. Is it what do mean?

![Image](https://user-images.githubusercontent.com/14298407/189437944-02fb684f-2d5b-4ad7-9c86-6c0fdb5f63b6.png)
