### ISSUE TITLE
As a user, I can see metric selector schema in constant time

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#539]
Notebooks metric selector crashes with large data sets/high cardinality data sets

We want to fetch metadata not parse actually data to derive the schema

The principle of contact time is applicable because we're using a single metadata query even if the list grows to be a million items long, that operation will always require a single step to get

https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb-schema/

**Comment by drdelambre** [comment]
we were told that this is impossible
