### ISSUE TITLE
firstMile: CLI - Return results in table form for a cleaner look rather than --raw

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#5392]
Return results in table form for a cleaner look rather than --raw

![Image](https://user-images.githubusercontent.com/98195941/184426952-a42c2d3f-fad1-40e9-8b3b-23257e834630.png)

**Comment by ChitlangeSahas** [comment]
Our client libraries don't have a way to print the output as a pretty table. We could ask for it to be added to the libraries befre we can bring this into the wizards. 

I was only able to implement the CLI wizard.
