### ISSUE TITLE
Notebooks: I can see data type for measurement, fields and tags in the metric selector

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#540]
As a InfluxDB Cloud user, I can see `data type` from in the InfluxDB schema in the metric selector so that I can:
- Know that I'm selecting the right data
- Troubleshoot compatibility between different `datatypes` and aggregations

Given
When
Then

### Technical Notes
`Data Type `should be available in the following service:
https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/influxdb-schema/

See implementation:
https://github.com/influxdata/idpe/issues/9686

**Comment by drdelambre** [comment]
not doing
