### ISSUE TITLE
firstMile: Native MQTT - User Navigation

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#5412]
**ACs**

- Pass a parameter that indicates that the flow is the onboarding flow vs the native flow.
- Refactor the existing code to use the firstMile next and previous button navigation style
- The wizard step icons should indicate when the user progresses to the next step via the wizard
- The wizard icons should turn blue and contain a white checkmark once completed
- See Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding?node-id=1810%3A10781

**Dev notes**

- Coordinate w/ Helen as needed

**Comment by Luckette** [comment]
@taramk and @sjwang90 will work w/ DA to match the nav behavior of the other onboarding flows (next buttons, separate pages)

**Comment by sjwang90** [comment]
From @helenosheaa on https://github.com/influxdata/data-acquisition/issues/502#issuecomment-1227547181:

----

we seem to be going back and forth between how we want this feature to be interacted with -- see history:

we previously implemented a three page design for the subscriptions feature: see figma [here](https://www.figma.com/file/kv0BxWc1vv6X3w7LK5UjyD/MQTT-Cloud-Native-Data-Ingest?node-id=110%3A2839)

once it was out built in the UI we got feedback that the edit/ details view was confusing and hard to interact with issue https://github.com/influxdata/data-acquisition/issues/240

see new single page figma design which was provided [here](https://www.figma.com/file/kv0BxWc1vv6X3w7LK5UjyD/MQTT-Cloud-Native-Data-Ingest?node-id=449%3A3385)

we then implemented a single page design for the details/edit view which we put behind a feature flag https://github.com/influxdata/ui/pull/4390

we then were told to make the create page a single page as well as it was inconsistent with the edit/details view https://github.com/influxdata/ui/pull/4886

at that point we removed the flag as we received feedback that people were happy with the design/interaction

before we do more work to go back to an older design i'd like to understand the reasons why and make sure we are accounting for the confusion / difficulties of use with the multi-page design. this would be a non-trivial amount of work to make the changes for onboarding, create, details and edit views.

**Comment by barbaranelson** [comment]
Please hold on this one. Thanks.
