### ISSUE TITLE
firstMile: Native MQTT - Overview Page

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#5413]
**ACs**

- Reuse the same overview page components as the previous wizards
- Everything should remain the same EXCEPT:

        The text under the welcome statement should say "In the next 5 minutes, you will connect to your MQTT data and define parsing rules."    
        The user won't need to see a "next" button to proceed, they can simply scroll down or use the wizard to proceed to next. 
    
**Dev Notes**

- See Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding?node-id=1810%3A10781

![Image](https://user-images.githubusercontent.com/98195941/184758847-b450826a-fc42-49b7-8f15-e284137a2371.png)

**Comment by Luckette** [comment]
@taramk and @sjwang90 will work w/ DA to match the nav behavior of the other onboarding flows (next buttons, separate pages)

**Comment by sjwang90** [comment]
https://github.com/influxdata/data-acquisition/issues/502
