### ISSUE TITLE
Native MQTT - Offer Next Steps at the end of the user flow

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#5415]
**ACs**

- Finish page should have similar components as the other wizards (Congrats, Confetti, Thumbs up / Thumbs down component, Key Concepts, and InfluxDB University)
- Text underneath "Congrats" should say "You completed connecting to your MQTT broker and writing data to InfluxDB Cloud"
- One of the UI boxes should be the option to see an "MQTT Blog Article" and should send the user to an MQTT Blog in a new tab. Blog: https://www.influxdata.com/integration/mqtt-native-collector/
- See Figma: https://www.figma.com/file/JfGYCOb7ZyQ8JHSqeu4fma/Onboarding?node-id=1810%3A10782
    
**Dev Notes**

- We're still waiting on the MQTT Blog Article to be published. Gary Fowler drafted the blog on 8/15/22. 
- See Blog referenced in this ticket: https://github.com/influxdata/ui/issues/5510

![Image](https://user-images.githubusercontent.com/98195941/184759363-d3fdd094-cca1-4a83-ad09-f974d83d35e2.png)

**Comment by ALuckette** [comment]
@sjwang90 Do you want to move this to your team's board?

**Comment by sjwang90** [comment]
The data acquisition team isn't doing any new work and fits better for onboarding not necessary in the general subscriptions. I can close this for now and we can address it if we ever decide to do Native MQTT onboarding.
