### ISSUE TITLE
firstMile: InfluxCLI Onboarding - Download windows package automatically

### ISSUE THREAD

**Issue by david-rusnak** [influxdata/ui#5436]
Instead of taking users to the docs page and leaving them to find the windows download, they should have the option to download it straight from the onboarding so they do not have to look for the link.

**Comment by ChitlangeSahas** [comment]
The only concern I have on this is that we'd then have to manually update the Download link with the latest package. I've asked the docs team if they have a link that always downloads the latest package, then this can be easily implemented.

**Comment by ALuckette** [comment]
^ FYI @noramullen1

**Comment by wdoconnell** [comment]
Closed due to priority, and for the reasons Sahas identifies above.
