### ISSUE TITLE
firstMile: InfluxCLI Onboarding - Windows install dependency updates

### ISSUE THREAD

**Issue by david-rusnak** [influxdata/ui#5462]
Once/If the CLI package is added to `winget` we will need to change the Install dependencies flow for `Windows` to match it. We can also create an issue in the docs for this when done.

**Comment by Luckette** [comment]
@taramk - FYI - our intern left this for us to consider.

**Comment by taramk** [comment]
@Luckette thanks for the heads up! what are next steps for this?

**Comment by ALuckette** [comment]
Chatted with @ChitlangeSahas  - design not needed. FYI @taramk

**Comment by wdoconnell** [comment]
Closing, since this ticket is a hypothetical - it's conditional on the cli being added to winget.
