### ISSUE TITLE
Schema Composition: UI element changes

### ISSUE THREAD

**Issue by hralexander** [influxdata/ui#5471]
Implement the below list of UI changes as demonstrated in the figma from Julia:
https://www.figma.com/file/0qAntPk5LVangAHguWT74X/Query-Experience-Project?node-id=1719%3A71011
referenced from issue:
https://github.com/influxdata/ui/issues/5338

- [x] #5495
- [x] #5529
     * have checkbox on/off be wired to session state. Specifically for fields, and tagValues. See https://github.com/influxdata/ui/issues/5351.

* "Flux Sync"
     - [x] #5501
       * this is in the schema browser. Not the editor block button.
       * have this read sync state from the session.
     - [x] #5536
     - [x] #5539

* Schema Composition Code Block styling 
    - [x] #5544 
    - [x] Remove the Schema Composition Code Block styling when the user makes a code edit to the composition block.

**Comment by appletreeisyellow** [comment]
Closed by a mistake. Reopen again
