### ISSUE TITLE
Multi Org Phase 2 - Delete Org

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#5477]
For multi-org, once users can create new organizations, we anticipate the lack of ability to delete organizations will lead to many new support cases and EARs to clean up organizations that were created unintentionally. Therefore, we want to include org deletion in the scope of the phase 2 work.

[Corresponding quartz epic](https://github.com/influxdata/quartz/issues/6843)

[Delete organization design (Figma)](https://www.figma.com/file/fvVSKwnepmRWvzFlIxCWCe/Multi-org?node-id=1944%3A14887)

Key highlights:
- Update the "delete organization" section for PAYG users to match the delete org button that already exists for annual users. 
- Clicking on the button brings up a pop-up modal with information on the deletion, a confirmation checkbox, and a button to trigger org deletion. See modal design here: https://www.figma.com/file/fvVSKwnepmRWvzFlIxCWCe/Multi-org?node-id=1944%3A14887
- Clicking the confirmation button will make an org delete request to quartz.
- After clicking the confirmation button, the button will display a spinner until the org delete request returns with success or failure. Display spinner from clockface. 
- If the request fails, the error is displayed to the user. see message here: https://www.figma.com/file/fvVSKwnepmRWvzFlIxCWCe/Multi-org?node-id=1944%3A14557
- If successful, switch the user to their default organization (or new default org) and provide a notification that the organization has been deleted.
- In the organization list, the deleted organization should be shown as "Deletion in progress" with a tooltip that the organization can be recovered by reaching out to support.
- After seven days, the organization moves to a "deleted" state and the org is deleted in IDPE and will no longer show up in the organization list.

Implementation:

- [ ] TBD

**Comment by Luckette** [comment]
@gunnaraasen This is the UI ticket for the delete org experience. We don't have concrete requirements or designs yet.

**Comment by hoorayimhelping** [comment]
Blocked on backend API work

**Comment by wdoconnell** [comment]
Delete button needs to function as follows.



![Image](https://user-images.githubusercontent.com/91283923/204342793-c8726ff1-f0dd-46fe-9216-350568e4c19c.png)
