### ISSUE TITLE
Resolve pushing into frozen array error in src/variables/selectors/index.tsx

### ISSUE THREAD

**Issue by wdoconnell** [influxdata/ui#5523]
## About the bug

`variables/selectors/index.tsx` can throw an error related to trying to push into a frozen array intended to contain the currently selected variable (`vari.selected`). We're seeing this issue specifically in monitor301.

The variables (`vari`) object is taken directly from redux state, which means that the variables object is frozen via `immer`. The variables object (`vari`) is then cloned, but using the spread operator, not a recursive deep cloning method. As a result, any attempts to push into arrays that are properties of the originally frozen object fail.

A fix would be to deep clone `vari` instead of cloning it using the spread operator, so that arrays that are properties of the variables object are extensible. But also need to investigate root cause to see why this block of code is even hit. 

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Log in to `monitor301`
2. Browse to dashboard that uses variables

**Expected behavior:**
Dashboard loads

**Actual behavior:**
Sometimes throws error `can't define array index property past the end of an array with non-writable length` or `Cannot add property 0, object is not extensible`.

Error sometimes fixed by clearing the cache.

**Visual Proof:**
![frozen array](https://user-images.githubusercontent.com/91283923/186459906-0376704a-7442-4499-ad7d-30338ed2be65.png)

**Comment by cannonpalms** [comment]
When I experienced this last night, I saw that the exception was being thrown when a variable named `node_id` was being processed. Not sure why it wasn't an issue for other variables, but I'm guessing it has something to do with the predicate that encapsulates the offending line of code. 

There is additional context on the exact `state` that was resulting in the error in [this slack thread](https://influxdata.slack.com/archives/CLHATC50E/p1661299308854909?thread_ts=1660833756.695399&cid=CLHATC50E)
