### ISSUE TITLE
Edit Schema Browser such that when "Flux Sync" is disabled the schema browser enters a read only state (nothing can be injected) but the buckets and measurements can still be changed so the user can browse their schema.

### ISSUE THREAD

**Issue by appletreeisyellow** [influxdata/ui#5539]

**Comment by wiedld** [comment]
I feel like we need to chat a bit about this one. We have 3 parts:
* schema browser local state
* schema session state
* composition state

When sync is turned on, we then have the composition state also syncing to the session state.
When sync is turned off, the composition ignores the session state.

What about when the sync is off? 
* Do we still want the session state to be updated, such that when we turn back on sync...it updates the composition to match the latest schema browser?
* Or do we not update the session? And have non-sync'ed schema browser state only be local?

**Comment by appletreeisyellow** [comment]
> What about when the sync is off?

My understanding is that we only update the schema browser local state, and don't update the session state.

When the sync is off (i.e. "Flux Sync" toggle is off), the fields and tag values are non-selectable, so what left for users to select are buckets and measurements. Users can change to different buckets and measurements, and only the schema browser local state get updated. Once the user turns on the "Flux Sync" toggle, the selected bucket and measurement will change back to whatever is in the session state to match with the query in text editor. 

---

I think for this issue, the schema browser becomes ready-only when `diverged` is set to `true` and users cannot toggle on the "Flux Sync" button anymore. So selecting bucket and measurement will only update schema browser local state, but not schema session state. Fields and tag values won't be able to be selected.

**Comment by wiedld** [comment]
Guess I imagined it as this:
* if !diverged, then always update session store
* if synced, then have the LspConnectionManager update the composition block (sync messages with the LSP).

I think that where we want the "sync" to occur, depends on what behavior we want when we make changes (while unsynced) --> and then turn back on the sync.

This means that in the following scenario:
1. user makes a composition
2. turn off sync
3. does further browsing and changes things (e.g. measurement, add/remove fields or tagValues)
4. turn back on sync
5. now we have two options:
  * do we want the composition block to now update to match the current schema browser selection?
      * if yes --> then we do want the session updated, even when not synced. 
      * But the composition subscription will ignore the session when not synced.
  * do we want the schema browser selections (local state) to revert back to matching the current composition block in the editor?
      * if yes --> then we do not want the session to be updated.
      * instead, unsync means local component state only.
      * When sync is turned back on --> local state (in the browser selector) is synced back to the component.

**Comment by appletreeisyellow** [comment]
Agreed. I'd like to hear what Gary would suggest.

**Comment by wiedld** [comment]
Group discussion result:
* we don't know the final decision.
* going to do initial user testing with the 1st option (a.k.a. keep the schema browser always updating the session)
