### ISSUE TITLE
Change wording for Tick Mark generation

### ISSUE THREAD

**Issue by sjwang90** [influxdata/ui#557]
Change wording on Tick generation to provide clarity - the word "Tick" on its own can be confusing. Also would be helpful to add tooltips with explanations. 

Existing >> New (suggested from docs team)

`X Axis Tick Generator` >> `Generate X Axis tick marks`
`Total Ticks` >> `Total Tick Marks`
(**field text**: max # <if there is a max>)
(**tooltip**: Enter the total number of tick marks. )
`Tick Start` >> `Start Tick Marks At` 
(field text: RFC timestamp)
(tooltip: Enter the time to add the first tick mark. )
`Tick Step` >> `Tick Mark Interval`
(tooltip: Enter the interval of time between tick marks.)
(field text: milliseconds) 

`Y Axis Tick Generator` >> `Generate Y Axis tick marks`
`Total Ticks` >> `Total Tick Marks`
(**field text**: max # <if there is a max>)
(**tooltip**: Enter the total number of tick marks. )
`Tick Start` >> `Start Tick Marks At` 
(**tooltip**: Enter the value to add the first tick mark. )
`Tick Step` >> `Tick Mark Interval`
(**tooltip**: Enter the interval between tick marks.)

**Comment by sjwang90** [comment]
![image](https://user-images.githubusercontent.com/32681364/107677932-a0261a80-6c4f-11eb-8e76-ff80c082aa9c.png)

Can you capitalize "Generate Y-Axis Tick Marks" and "Generate X-Axis Tick Marks" to be consistent with the rest of the UI?

Also technically throughout the UI it should be "X-Axis" with a `-`. Same for "Y-Axis"

**Comment by sjwang90** [comment]
Some tight text here too for "Total Tick Marks" (X/Y-Axis > Generate X/Y-Axis Tick Marks > Total Tick Marks)
![Screen Shot 2021-02-11 at 10 16 22 AM](https://user-images.githubusercontent.com/32681364/107680737-1bd59680-6c53-11eb-823b-7f4d9ec0eb32.png)

Spotted this "Shade Area Below Lines" above being pretty tight too under Options
![image](https://user-images.githubusercontent.com/32681364/107680865-3f98dc80-6c53-11eb-99b3-817ccc2252d5.png)

**Comment by sjwang90** [comment]
![image](https://user-images.githubusercontent.com/32681364/107705218-41729800-6c73-11eb-8cde-d8569127a9d9.png)

Suggestion is `X & Y Axis` should be `X-Y Axis`

**Comment by sjwang90** [comment]
A couple things from the different chart types.

Graph + Single Stat: X-axis tick configuration does isn't consistent with the rest. Isn't under it's own heading but under options
![image](https://user-images.githubusercontent.com/32681364/107807827-97037f00-6d1d-11eb-8d95-bf8e5a55fd64.png)

Scatterplot: has X/Y Tick Prefix/Suffix and no other chart type has it. Is this supposed to be "X Axis Prefix" not Tick?
![image](https://user-images.githubusercontent.com/32681364/107812458-8f93a400-6d24-11eb-983b-9a31c7bbf369.png)

**Comment by TCL735** [comment]
@sjwang90 i think the Graph + Single Stat and Scatterplot issues are separate from tick generation. Could we move them out to another issue? Something like, "graph types have weird options and inconsistent header labels"

cc @joelfried
