### ISSUE TITLE
Browser crashes in New Tools when toggle on raw data

### ISSUE THREAD

**Issue by sjwang90** [influxdata/ui#5590]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Go to Data Explorer
2. Run this query in Query Builder or Flux
```
from(bucket: "apps")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "http_write_request_bytes")
  |> filter(fn: (r) => r["_field"] == "counter")
```
4. Wait a little bit for chart to view
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/32681364/187314642-e22d7d38-c812-4de6-93dc-314079f88649.png">

6. Click Raw Data tab - browser crashes
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/32681364/187317343-ea3d2909-8c64-4e9a-b2b8-d43b5a5e28f5.png">

**Expected behavior:**
View Raw Data

**Actual behavior:**
Browser crashes

**Visual Proof:**

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/32681364/187317343-ea3d2909-8c64-4e9a-b2b8-d43b5a5e28f5.png">

## About your environment

**Environment info:**
InfluxDB Cloud New tools: https://us-east-1-2.aws.cloud2.influxdata.com/

**Config:**

**Logs:**

```csv
#group,false,false,false
#datatype,string,long,string
#default,_result,,
,result,table,_value
,,0,_field
,,0,_measurement
,,0,env
,,0,response_code
,,0,service
,,0,threshold
```

```
#group,false,false,false
#datatype,string,long,string
#default,_result,,
,result,table,_value
,,0,gateway_error_threshold
```

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by TCL735** [comment]
This is the same issue as https://github.com/influxdata/ui/issues/5692

Closing this in favor of that one.
