### ISSUE TITLE
Visualization options: Orientation threshold and opacity design and usability

### ISSUE THREAD

**Issue by noramullen1** [influxdata/ui#560]
https://github.com/influxdata/ui/pull/95 added a "rotation threshold"  and opacity slider for the legend in query cells. While documenting this, I noticed some issues that I've verified with @sjwang90. Happy to hop on a call to demo if anything below isn't clear. 

## Orientation 

At X columns, the legend rotates from horizontal to vertical:

![image](https://user-images.githubusercontent.com/42354779/105895299-33ade900-5fca-11eb-80eb-5bc2adc47388.png)

It would be much simpler to have a vertical/horizontal orientation toggle option. The number of columns in the query isn't going to change unless they change the query, so setting a threshold is unnecessarily complicated because all they're be doing is switching the orientation for that specific cell. I don't see any use case where having a threshold set at the cell/query level would be useful (let me know if I'm missing something). 

## Opacity

The opacity slider determines how opaque the legend appears. 

![image](https://user-images.githubusercontent.com/42354779/105895805-d5353a80-5fca-11eb-93ea-b0d8042199d0.png)

A couple suggestions for design improvements here:

- It should show opacity as a percentage, not a proportion of 1 (aka 55 instead of .55 in the example above).
- There's no need to have numbers on either side of the slider. Similar slider UIs on instagram, etc. just show total opacity as you adjust the slider. See a good example from Capture One [here](https://support.captureone.com/hc/en-us/articles/360002615497-Opacity-slider-effect-in-the-Layers-tool).

**Comment by TCL735** [comment]
Excellent suggestions. Thank you.

**Comment by jrenee42** [comment]
@noramullen1 : is this the opacity slider style you want? 
![Screen Shot 2021-01-28 at 11 42 46 AM](https://user-images.githubusercontent.com/3900960/106170015-01cd8b80-615e-11eb-95ec-09558e97cb6b.png)

**Comment by noramullen1** [comment]
@jrenee42 Looks good to me!
