### ISSUE TITLE
Schema Composition: when Flux Sync is off or disabled, fields and tag values should be non-selectable

### ISSUE THREAD

**Issue by appletreeisyellow** [influxdata/ui#5616]
## About the bug

According to #5338, when "Flux Sync" is off or disabled, fields and tag values should be non-selectable, i.e, no checkboxes

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Turn on feature flag `schemaComposition`
2. Select a bucket and measurement
3. Turn off the "Flux Sync" toggle

**Expected behavior:**
Fields and tag values doesn't have checkboxes and they are non-selectable

**Actual behavior:**
Fields and tag values have checkboxes and can be selected

**Visual Proof:**
<img width="1153" alt="Screen Shot 2022-08-31 at 4 23 00 PM" src="https://user-images.githubusercontent.com/14298407/187789042-3d508444-1ebf-46e6-a883-7f905abdd371.png">

**Comment by wiedld** [comment]
We changed the requirement per discussion, but we did not document it anywhere. The updated consensus (in a meeting on 2022-08-19) was to have the left hand browser still be selectable etc, and still update the session store when unsynced. Then once sync is turned back on, schema composition reads from the session.

We had decided to punt the final decision on what sync behavior is, until after we got user feedback.

**Comment by appletreeisyellow** [comment]
Ah! Got it. Thanks for explaining!

**Comment by appletreeisyellow** [comment]
Reopen since we may want to re-visit this in the future

**Comment by wiedld** [comment]
Already done. CLosing.
