### ISSUE TITLE
Schema Composition: the highlight code block is shown up in notebook editor

### ISSUE THREAD

**Issue by appletreeisyellow** [influxdata/ui#5617]
## About the bug

When the feature flag `schemaComposition` is on, the highlight code block is shown up in notebook editor

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Turn on feature flag `schemaComposition`
2. Go to Notebooks and create a new one
3. Select a bucket, a measurement, and a field
4. Click the `...` button and select "Convert to |> Flux"

**Expected behavior:**
No highlight code block

**Actual behavior:**
A blue highlight code block is shown

**Visual Proof:**

https://user-images.githubusercontent.com/14298407/187792511-499e73ab-7bb6-419b-91da-a6883ed40bb3.mov

**Comment by wiedld** [comment]
It's the `isFluxQueryBuilder`.
Gets set to true when we navigate to the new DataExplorer.
Stays as true, while navigating back to notebooks.
