### ISSUE TITLE
Rename a Script

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#5694]
## User Story

<p></p>

As a user, I want to be able to rename a script I have saved to a completely different name so that I can correct an error or change to a name that makes more sense related to the script as it changes over time.

<p></p>

## Acceptance Criteria

<p></p>

- An option will be available to rename a script from one name to another

- A warning will be given to the user if this script is set to be an invocable script

<p></p>

## Notes

<p></p>

- We may want to sequence this just after, or along with the story to expose the Invocable Script URL.

<p></p>

**Comment by influx-product-manager** [comment]
Link to subfeature: https://influxdata.productboard.com/feature-board/planning/features/15251603

**Comment by wiedld** [comment]
Already done.
