### ISSUE TITLE
Delete a Script

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#5695]
## User Story

<p></p>

As a user, I want to be able to delete a script that I have created when I do not need it anymore so that it doesn't clutter up my list of scripts and that it doesn't get used accidentally.

<p></p>

## Acceptance Criteria

<p></p>

- An option will be available to delete a script

- The user will be warned when that script is tagged as an invocable script (see "share a script" user story)

<p></p>

## Notes

<p></p>

- This will need to be done in sequence after, or along with the story for sharing a script in order to be able to do the warning message

<p></p>

**Comment by influx-product-manager** [comment]
Link to subfeature: https://influxdata.productboard.com/feature-board/planning/features/15251741

**Comment by wiedld** [comment]
Already done.
