### ISSUE TITLE
Bug - All Onboarding Wizards - Write Data - Awaiting Connection/Connection Found Behavior upon scroll

### ISSUE THREAD

**Issue by ALuckette** [influxdata/ui#5705]
The connection found indicator on the write data page of the onboarding wizards sometimes requires a screen refresh to properly display. It would be nice to allow the connection found to properly display upon scrolling down to that UI component without needing to refresh the screen.

**Comment by ChitlangeSahas** [comment]
This happened because we separated the listener component and the bucket selector into two pages. Fix coming soon!
