### ISSUE TITLE
Multi Org Phase 2 - UI Eventing

### ISSUE THREAD

**Issue by ALuckette** [influxdata/ui#5707]
Add eventing for Phase 2 features. 

## UI Eventing Dictionary
https://influxdb.atlassian.net/wiki/spaces/IPO/pages/2530574337/UI+Eventing+Dictionary

**Comment by wdoconnell** [comment]
Before beginning this ticket, sync with @ALuckette on event names and ensure they're added to the dictionary. Blocked until create-org, delete-org, add-teammates, remove-teammates features are complete.
