### ISSUE TITLE
Multi Org Phase 1 - When a page returns 404, we should not show the global header

### ISSUE THREAD

**Issue by ChitlangeSahas** [influxdata/ui#5750]
If a page does not exist and we redirect to 404 page, we shouldn't show the global header.

![Image](https://user-images.githubusercontent.com/18511823/190017532-655dad9f-dfd7-4461-b69d-193587027fe5.png)

**Comment by wdoconnell** [comment]
@subirjolly @ChitlangeSahas Is anyone able to reproduce this outside of remocal?  In cloud, I don't see this behavior on a `404`:
![Screen Shot 2022-09-14 at 1 54 19 PM](https://user-images.githubusercontent.com/91283923/190227502-f903dedb-ca52-4e7f-bdaa-c662ef2c28be.png)

**Comment by ChitlangeSahas** [comment]
![Image](https://user-images.githubusercontent.com/18511823/192397701-a98177ea-3b03-49b1-90e7-2777163c2da1.png)

i do see it in cloud..

**Comment by wdoconnell** [comment]
I saw it when Subir and I were pairing today too, so we should definitely keep it open.
