### ISSUE TITLE
Update the draggable resizer component to use the latest version with the collapse/open feature

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#5757]
We've recently updated the draggable resizer component in clockface to include a collapse/open feature. We'd like to update that component in the new script editor for that enhanced interaction.

https://influxdata.github.io/clockface/?path=/story/layout-draggable-resizer-examples--4-panels&knob-glyph=FolderOpen&knob-style={%22color%22:%22#6BDFFF%22,%22fontSize%22:%2260px%22}

![Image](https://user-images.githubusercontent.com/81173353/190203918-1aa65c07-8843-41a7-8746-b930296be8f6.png)

In an effort to better separate panels within the script editor experience, I'd liked to add an outline to these components. This is what it would look like with the outline and additional changes to the corner radius (in a separate ticket). 

<img width="1512" alt="Data Explorer" src="https://user-images.githubusercontent.com/81173353/190249129-5cab5c9f-63e8-4356-8e9f-c7c53dc05a69.png">

**Comment by appletreeisyellow** [comment]
There is a bug on the clockface draggable resizer component. See the video below. I filed an issue here influxdata/clockface#834. Once it is fixed, we can move forward with this ticket. 

https://user-images.githubusercontent.com/14298407/190729444-07e6327c-cd10-4ed3-8677-e6c7cf6b339c.mov
