### ISSUE TITLE
Notebooks: panel -> clipboard interface

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#576]
so get this....

for any panel in a notebook, we can get the flux used to generate it's results.
also
we have the ability to copy code snippets to a user's clipboard, by clicking on a button

so why can't I have an experience within notebooks that is similar to the following feature available in chromium browsers?
![Peek 2021-01-29 10-12](https://user-images.githubusercontent.com/1434802/106312099-02782780-621b-11eb-8f91-091644126f81.gif)

add a button to the panel header somewhere that lets you select a target and generates a code snippet for you in your clipboard.

initial targets i can think of off the top of my head:
 - curl
 - fetch
 - python (check out the initialize and execute sections in the data sources interface for python)
 
 weird things to watch out for:
  - we might need to allow the user to specify a token before generating the code
  - a query's orgid is determined by the query text (look at the query context for more info)
 - we gotta use absolute addresses to capture the domain that the user is currently on (us-west vs us-east needs to be baked into the generated url)

### Design Notes
Design Lead @juliajames12 

Given: A Flux script notebook panel is active
And: I can see the panel menu
When: I click Export As > Client Library
Then: I can see a sub-menu with all 11 client library options:

- Go
- Arduino
- C#
- Java
- Kotlin
- PHP
- Ruby
- Scala
- Swift
- JavaScript
- Python

When: I click Python or any of the client libraries
Then: I see a modal with code to Install Package, Initialize Client, and Execute Flux

Working File: https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=2512%3A480

Prototype: https://www.figma.com/proto/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=2512%3A480&scaling=min-zoom&page-id=1915%3A0

**Comment by russorat** [comment]
IMO, Postman does a great job of code gen for tons of languages.

**Comment by juliajames12** [comment]
@jzahnd @drdelambre @russorat updated with the wireframe.

Open Questions:
- Should we include all 11 client libraries, or just the top four most popular (Python, Node.js, Line Protocol, MQTT)?
- What's the interaction when the user selects View As > Python? Do they see the generated code (like in a modal)? Or just copied to clipboard? downloaded? What are we aiming to do technically?

**Comment by russorat** [comment]
We should include: Curl, Python, Node.js and Golang

They should see the generated code (via a modal probably) with an easy way to copy the code to their clipboard. I'm not sure if downloading a file is very useful here, so maybe copy to clipboard is good enough.

**Comment by mnorriswalker** [comment]
Update note: we're doing a single string replacement and offering all client libraries:

- Go
- Arduino
- C#
- Java
- Kotlin
- PHP
- Ruby
- Scala
- Swift
- JavaScript
- Python

**Comment by barbaranelson** [comment]
When we have this ready to test, let me know and I can have Bonitoo (who authored most of these client APIs) test that the code we generate is valid.

**Comment by juliajames12** [comment]
@barbaranelson Just wanted to double check to see if these have been tested with the Bonitoo team before we push this feature to production.

**Comment by barbaranelson** [comment]
No, sorry. I never heard back so I never followed up with Bonitoo on this. I can talk to them next week, and have them do a quick check.

**Comment by barbaranelson** [comment]
Bonitoo is looking at this - see https://github.com/influxdata/ui/issues/2075.
