### ISSUE TITLE
Improve Profile Popover Visuals

### ISSUE THREAD

**Issue by brandenTenbrink** [influxdata/ui#5762]
Thank you for suggesting an idea to improve InfluxData UI.

**Proposal:**
Improve the visuals for the Profile Popover & Move the component over to the UI repo if it isn't already (@wdoconnell suggestion). 

Part of this issue is a discussion to better understand what needs to be done here.

**Current behavior:**
This is what I was sent from Daniel:

![image](https://user-images.githubusercontent.com/15152523/190242613-2be4fe31-5e00-435f-8d0b-a7aab297abeb.png)

**Desired behavior:**
On the surface level it seems to be:

1) Make the popover less wide
2) Remove the box hover state
3) Tentative: Move the component to UI unless it already is?

**Alternatives considered:**
Describe other solutions or features you considered.

**Use case:**
Why is this important (helps with prioritizing requests)?

**Comment by wdoconnell** [comment]
Popover works correctly in all browsers. See https://github.com/influxdata/ui/pull/6006. Remaining proposed visual changes not a priority.
