### ISSUE TITLE
"Paste" swallows the following word

### ISSUE THREAD

**Issue by RAYZ50** [influxdata/ui#5768]
## About the bug

**Steps to reproduce:**

1. copy some text (A)
2. paste the text at the start of another word (B)
3. ...

**Expected behavior:**  Expected to see AB

**Actual behavior:**  Only see A   (B has disappeared)

**Visual Proof:**

![Bug](https://user-images.githubusercontent.com/113571333/190310285-dd57b019-0797-4d7e-868f-1360ebf71daa.jpg)

## About your environment

**Environment info:**

Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz   1.90 GHz
16.0 GB (15.9 GB usable)
64-bit operating system, x64-based processor
Windows 11 Pro
Version	21H2
OS build	22000.978
SSD 500G

**Comment by ChitlangeSahas** [comment]
@RAYZ50 could you please tell us where are you trying to paste that text?

**Comment by wdoconnell** [comment]
Closing due to absence of a response from submitter.
