### ISSUE TITLE
Dashboard - Table Formatting causes react error

### ISSUE THREAD

**Issue by jbp4444** [influxdata/ui#5774]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Download/install the attached dashboard -- uses the generate package to fill in some dummy data
2. Enter the dashboard, click on "Configure" for the cell (only one cell in dashboard)
3. Click on "Customize" for the table options to appear
4. Click on "Add A Threshold"
5. In some cases, it takes a second or two for React to re-render the screen -- click on "Submit" if it doesn't immediately throw an error in the console

**Expected behavior:**

The system should add a new threshold and alter the color of the table entries

**Actual behavior:**

React crashes and the browser hangs.  

**Visual Proof:**

Browser dev console shows multiple errors like:
errors.ts:63 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at hl (react-dom.production.min.js:237:48)
    at Pa (react-dom.production.min.js:170:408)
    at r (usePlotEnv.ts:26:5)
    at useMountedEffect.ts:20:12
    at jl (react-dom.production.min.js:262:359)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Vo (react-dom.production.min.js:122:325)
    at Rl (react-dom.production.min.js:261:308)
    at bl (react-dom.production.min.js:243:50)
    at react-dom.production.min.js:123:115

## About your environment

**Environment info:**

Linux 5.19.8-200.fc36.x86_64 x86_64
Influx CLI 2.4.0 (git: 5c7c34f) build_date: 2022-08-18T19:26:48Z
Chrome - Version 105.0.5195.125 (Official Build) (64-bit)

**Config:**

**Logs:**

Nothing in influxdb or chronograf logs

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt

# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

Dashboard json config:

[dummy2.json.txt](https://github.com/influxdata/ui/files/9576847/dummy2.json.txt)

**Comment by jbp4444** [comment]
Might be worth noting that the dashboard json file was created by Influx but includes some cruft from when I was interactively building the initial query -- there are extra variables listed in the "fieldOptions" array that are not actually in the code anymore.

**Comment by jbp4444** [comment]
... uname above is for the system running the browser (Fedora) ... the influx db is running on Rocky 8.5 (==Linux 4.18.0-348.el8.0.2.x86_64 x86_64)

**Comment by ChitlangeSahas** [comment]
I can't seem to import that dashboard, but trying with my own dashboard, I still can not reproduce it. Can you please post a screen capture of the issue, @jbp4444 ?

Thanks.

**Comment by jbp4444** [comment]
[Screencast from 09-30-2022 11:23:00 AM.webm](https://user-images.githubusercontent.com/5089518/193303589-510b112c-845f-47ab-9047-423969f7d242.webm)

Full walk-through; configure --> add threshold --> submit --> console shows the errors

**Comment by ChitlangeSahas** [comment]
@jbp4444 Could you please post the CSV of this data?

**Comment by jbp4444** [comment]
It's autogenerated, so it should "just work"

**Comment by TCL735** [comment]
Hi @jbp4444 - i also could not import the dashboard. However, based on your video and the data in the dashboard template, i was able recreate the dashboard and cell manually.

Then, I tried the steps to reproduce the console error. For me, there was no console error and no crash. Adding a threshold appears to work normally. I made a video, see below, showing my test.

This ticket is over 2 weeks old, and perhaps there have been recent changes or fixes that may have addressed the underlying issue that you experienced. So, for now I am closing this issue. Please let me know, or file another issue if you continue to experience this problem.

https://user-images.githubusercontent.com/10736577/197305233-19c89ef0-b23c-4c0e-a79b-82dfc53a4db6.mp4
