### ISSUE TITLE
Header should collapse into hamburger menu in smaller windows

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/ui#5779]
On smaller screen sizes, we progressively collapse the lefthand navigation into a hamburger dropdown in the header. The new header should also adapt to smaller screen sizes.

## About the bug

**Steps to reproduce:**

1. Use a small window size
2. Turn on multi org 

<img width="656" alt="image" src="https://user-images.githubusercontent.com/628831/190473146-42f686de-3a1f-47d5-a4de-c8f5bc26b367.png">

**Comment by ALuckette** [comment]
This is smooth, thank you!
