### ISSUE TITLE
Add metrics to understand how often the Fallback worker gets used rather than the Worker api

### ISSUE THREAD

**Issue by rockstar** [influxdata/ui#5780]
[Web workers have had support in all the major browsers since 2012](https://caniuse.com/webworkers). The browsers that seem to have partial support for other workers (shared web workers, service workers) are all mobile browsers, which Monaco editor explicitly does not support. While [the Web Worker Mozilla docs specify checking for support](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#worker_feature_detection), I'm not sure the `Fallback` shim is all that necessary. As web workers have their own event loops, i.e. they have to be their own thread/process, I worry that trying to do the same in the web browser itself is going to lead to async event loop blocking on sufficiently complex flux; using the `Fallback` might be creating bugs.

**Comment by wiedld** [comment]
💯 agreed with putting in this metric.

Used to be a thing to disable web workers (through browser security settings), if the user was super stringent with their privacy. Given how much the modern web crashes if you do this approach...it's unclear if it's still a thing. Let's get numbers to see.

**Comment by rockstar** [comment]
None of the builtin workers for Monaco (css, html, json, typescript) have the check to see if web workers are supported in the browser, so I suspect that Monaco just doesn't work at all if you disable web workers.

**Comment by rockstar** [comment]
I went to experiment with this, which meant I needed to figure out how to turn of web workers. It can't be done from Firefox, Chrome, or Safari (service workers can be disabled, but not web workers). Either the browser supports it now, or it doesn't. I guess we want to find out where the browser doesn't support it.

**Comment by wiedld** [comment]
> None of the builtin workers for Monaco (css, html, json, typescript) have the check to see if web workers are supported in the browser, so I suspect that Monaco just doesn't work at all if you disable web workers.

Valid point. If the super security conscious person has already disabled it, then the editor won't work well anyways (due to the monaco-editor worker).

I'm guessing the metrics returned will be little-to-no-users in that level of stringency. Then we can consciously decide to remove the check.
