### ISSUE TITLE
Resizing window to small size makes main elements disappear 

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/ui#5805]
https://user-images.githubusercontent.com/25036188/190674062-6dc61885-320a-4a0f-93af-89c76820cc7e.mov

## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Log in
2. Reduce size of window until elements are lost.  

**Expected behavior:**
the elements don't disappear

**Actual behavior:**
the elements disappear

**Visual Proof:**

**Comment by ChitlangeSahas** [comment]
This was fixed in https://github.com/influxdata/ui/pull/5651
