### ISSUE TITLE
fonts are corrupted 

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/ui#5806]
I logged in and found irregular fonts throughout the menus in the UI.  refreshing the page didn't fix it. 

<img width="1512" alt="Screen Shot 2022-09-16 at 11 24 16 AM" src="https://user-images.githubusercontent.com/25036188/190674807-5adb6291-3772-4f9e-ba5c-120dd4e59a20.png">

**Comment by hoorayimhelping** [comment]
duplicate of https://github.com/influxdata/ui/issues/4506
