### ISSUE TITLE
New Data Explorer - Renaming Scripts

### ISSUE THREAD

**Issue by hralexander** [influxdata/ui#5836]
Implement UI functionality to facilitate renaming scripts within the new data explorer. The service that stores scripts
checks for the following conditions:
a- Name should be unique.
b- Name must be less than 256 characters.
c- Names can't include unicode characters.

**Comment by juliajames12** [comment]
Here's the design for the first two conditions listed. Do we need an error message for the third one?

This script name already exists. Please choose a different name.

<img width="1788" alt="Save Script Modal (Unique name error message)" src="https://user-images.githubusercontent.com/81173353/191549459-86236bae-9494-4cf5-83d7-a608ddb81dc6.png">

You’ve reached the max length of 256 characters.

<img width="1788" alt="Save Script Modal (Max length error message)" src="https://user-images.githubusercontent.com/81173353/191549470-050b8440-c438-45cd-999b-209672d5549b.png">
