### ISSUE TITLE
Save Script Dialog Updates

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#5837]
We want to change the dialog slightly when prompted for save when you select new script or load.  See designs from Julia attached.

**Comment by juliajames12** [comment]
Here's the design: 
<img width="1788" alt="New Script (Save Modal - When user selects New Script or Open after working on a previously saved script)" src="https://user-images.githubusercontent.com/81173353/191326295-ead918e0-ec0c-4c7e-8615-55a75571b0c8.png">
<img width="1788" alt="New Script (Save Modal - When user selects New Script or Open after starting an unsaved script)" src="https://user-images.githubusercontent.com/81173353/191326299-26dd1654-4e74-49ae-b7a1-d0b2d718b190.png">
