### ISSUE TITLE
Unable to save band plot to dashboard cell

### ISSUE THREAD

**Issue by abalone23** [influxdata/ui#585]
**Steps to reproduce:**
1. Add cell to dashboard
2. Create a flux query with max/min/median values
2. Select `Band` / `Customize`
3. Under `Aggregate Functions`, enter Upper/Main/Lower Column Names
4. Click green checkbox to save to cell.

Note that the band plot displays correctly before saving to cell.

**Expected behavior:**
Band plot should display in cell

**Actual behavior:**
Band plot doesn't display in cell

**Environment info:**
InfluxDB Cloud: https://us-central1-1.gcp.cloud2.influxdata.com/

**Comment by TCL735** [comment]
This was fixed as part of the rendering pipeline change.

:fire: All credit goes to Alex Boatwright :fire:
