### ISSUE TITLE
 unsupported input type for mean aggregate: string

### ISSUE THREAD

**Issue by Luis0725** [influxdata/ui#5856]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. ...
2. ...
3. ...

**Expected behavior:**

**Actual behavior:**

**Visual Proof:**

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by kristinarobinson** [comment]
This error occurs when the values selected from the query are strings, and an aggregate function is applied (e.g. mean, max, min).  To remove this error, uncheck all functions in the `Aggregate Function` area in the Query Builder OR if using the Script Editor, remove any references to the `aggregateWindow` or `aggregate` function.

If you have further questions, please let us know.
