### ISSUE TITLE
Update Notebooks icon

### ISSUE THREAD

**Issue by taramk** [influxdata/ui#5887]
In https://github.com/influxdata/ui/issues/4976, the icon for Notebooks in the navigation was supposed to be updated from BookPencil -> BookCode. Instead it got replaced with the pencil icon.

Please apply the correct icon replacement: the icon for Notebooks should be BookCode.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/1813419/192335886-fb302e9e-2d8e-4118-b8f3-fa71415820d9.png">

**Comment by wiedld** [comment]
Already done.
