### ISSUE TITLE
Multi Org Phase 2 - Update Org Settings page for PAYG users so that users can delete an org - only if they have more than 1 org.

### ISSUE THREAD

**Issue by ALuckette** [influxdata/ui#5918]
Update Org Settings page for PAYG users so that users can delete an org - only if they have more than 1 org.

## Delete Org Component
![Image](https://user-images.githubusercontent.com/112978673/192623424-81acc416-f025-41b6-b4d0-6aa778abce02.png)

## Implementation
- we just need to allow `account.type === ‘pay_as_you_go’` to the check for whether the button displays

**Comment by wdoconnell** [comment]
The conditional check for PAYG also needs to include a caveat that the delete button won't display if there's only one PAYG org.

**Comment by wdoconnell** [comment]
Closing as duplicative of #5477
