### ISSUE TITLE
Create UI to enable the lsp to present the user with messages

### ISSUE THREAD

**Issue by rockstar** [influxdata/ui#5925]
The [LSP specification describes a "show message" notification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showMessage) that can be used by the LSP server to present messages to the user on the client side. @juliajames12 has done some work already to present these messages to the user (mostly errors, last time I saw the design). We should listen for these `window/showMessage` notifications and hook them into our UI.

DOD:
  - when the LSP fires a `window/showMessage` notification, that message is presented to the user

**Comment by wiedld** [comment]
Already done.
