### ISSUE TITLE
Connect to the log trace lsp notifications and present them in the browser console

### ISSUE THREAD

**Issue by rockstar** [influxdata/ui#5926]
While doing some quick browsing in the LSP spec for #5925, I realized that [we could be using `window/logMessage` to present information in the browser console](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_logMessage), which would be super powerful for debugging. Once we have addressed #5925, all the plumbing should be in place to do something like the following:

```javascript
import {LogMessageNotification, MessageType} from 'vscode-languageserver-protocol';

connection.onNotification(LogMessageNotification, (rawMessage: string) => {
    const message = JSON.parse(rawMessage);
    if (message.type == MessageType.Error) {
        console.error(message.message)
    }
});
```

This API is just a guess, but a lot of this would be sorted out by solving #5925 first. [See this file for more information](https://github.com/microsoft/vscode-languageserver-node/blob/2e889fbffaccee0d054dc8af1feb356b27dc2873/protocol/src/common/protocol.ts)

DOD:
  - When the LSP sends an error message through to the client, it is visible in the browser console.

**Comment by wiedld** [comment]
Turns out that we don't need this fix. Once the wasm panics (from logging) was removed, we also used a fix which now surfaces the wasm logging into the browser console.
