### ISSUE TITLE
Multi Tag Value Selection Handling

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#5949]
## User Story

<p></p>

As a user in the new script editor, I don't want to always have any empty return set when I select more than one tag value in the same tag key\.

<p></p>

## Acceptance Criteria

<p></p>

- A user will be able to select multiple tag values within the same tag key

- The query will run this as an OR query

- If a user tries to select a tag value from a different key, the previous key's selection will be removed

<p></p>

## Notes

<p></p>

This would match the behavior of the old DE, which doesn't let you select values from two different tag keys\.

<p></p>

A more elaborate solution that would allow for an AND of tag keys and ORs for values within those keys is also acceptable, but not required if it adds complexity to the issue\.

<p></p>

**Comment by influx-product-manager** [comment]
Link to subfeature: https://influxdata.productboard.com/feature-board/planning/features/15613017

**Comment by garylfowler** [comment]
I really think that even with a combination of tag values and fields, the default operator should be OR instead of AND.

**Comment by appletreeisyellow** [comment]
@garylfowler @rockstar Just to confirm is this what we are decide to have?

## Adding tag value `tagValue2` with the same tag key `tagKey1`

**Before**
```
from(bucket: "an-composition")
        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
        |> filter(fn: (r) => r._measurement == "anMeasurement")
        |> filter(fn: (r) => r.tagKey1 == "tagValue1")
        |> yield(name: "_editor_composition")
```

**After**
```
from(bucket: "an-composition")
    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
    |> filter(fn: (r) => r._measurement == "anMeasurement")
    |> filter(fn: (r) => r.tagKey1 == "tagValue1" or r.tagKey1 == "tagValue2")
    |> yield(name: "_editor_composition")
```

## Adding new tagset `tagKey2` and `tagValue2`

**Before**
```
from(bucket: "an-composition")
        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
        |> filter(fn: (r) => r._measurement == "anMeasurement")
        |> filter(fn: (r) => r.tagKey1 == "tagValue1")
        |> yield(name: "_editor_composition")
```

**After**
```
from(bucket: "an-composition")
    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
    |> filter(fn: (r) => r._measurement == "anMeasurement")
    |> filter(fn: (r) => r.tagKey1 == "tagValue1")
    |> filter(fn: (r) => r.tagKey2 == "tagValue2")
    |> yield(name: "_editor_composition")
```
