### ISSUE TITLE
Flux Sync should turn off automatically once the Flux script has changed beyond scope of sync

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ui#5951]
## About the bug

**Steps to reproduce:**

1. Open new Data Explorer
2. Use schema browser to enter a query
3. Use Flux text editor to select all contents and delete
4. Type a new query i.e. `import "http"`
5. Click on anything in the schema browser (i.e. a new field)

**Expected behavior:**

Nothing happens or an error about the sync being broken should be displayed

**Actual behavior:**

The new query that was typed in step 4 is removed and replaced with the `from|> range |> filter` of the schema browser

**Visual Proof:**

After step 3
![image](https://user-images.githubusercontent.com/3771906/193317588-b37ab23e-2663-4a74-a959-d5d9b0c3c17f.png)

After step 4
![image](https://user-images.githubusercontent.com/3771906/193317640-16a10e91-eae1-476e-a7a7-f7f8095f822b.png)

Notice the sync button is still highlighted even though the entire query has been edited.

After step 5
![image](https://user-images.githubusercontent.com/3771906/193317695-4acb10d6-8b97-4b25-906d-94f2fcbda0f7.png)

## About your environment

Cloud Account at URL us-west-2-1.aws.cloud2.influxdata.com

**Comment by wiedld** [comment]
Coincidentally, I've been just writing tests which define when divergence currently occurs. This behavior above is a feature...but perhaps should not be. We can change this contract, based upon what we want.

Here's the current divergence behavior:
https://github.com/influxdata/ui/blob/204b56b06aaa8da8e4d4e6d4a3b08e18f51cf312/cypress/e2e/shared/fluxQueryBuilder.test.ts#L348-L437

**Comment by wiedld** [comment]
Divergence is now removed with yieldless composition. Closing this issue.
