### ISSUE TITLE
Extra parenthesis are added by code injected via the Schema Browser

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ui#5953]
## About the bug

1. Open new Data Explorer
2. Select a bucket and measurement
3. Select at least three fields

The same is true of adding tags, extra parenthesis are added and should not be.

**Expected behavior:**

Fields are added without parenthesis as they are not needed and seeing the editor add them makes users question if they really are needed.

```js
from(bucket: "test")
    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
    |> filter(fn: (r) => r._measurement == "cpu")
    |> filter(
        fn: (r) =>
            r._field == "usage_idle" or r._field == "usage_iowait" or r._field == "usage_irq",
    )
    |> yield(name: "_editor_composition")
```
**Actual behavior:**

This script is produced

```js
from(bucket: "test")
    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
    |> filter(fn: (r) => r._measurement == "cpu")
    |> filter(
        fn: (r) =>
            r._field == "usage_idle" or (r._field == "usage_iowait" or r._field == "usage_irq"),
    )
    |> yield(name: "_editor_composition")
```

**Visual Proof:**
![image](https://user-images.githubusercontent.com/3771906/193320691-49a89f73-88c5-405e-a15d-2aaf3927ef5c.png)

## About your environment

Cloud Account at this URL https://us-west-2-1.aws.cloud2.influxdata.com/

Aside: I recognize this might really be a `flux-lsp` bug but since it shows up to the user here I figured this is the best place to track it.

**Comment by wiedld** [comment]
Already fixed. Closing.
