### ISSUE TITLE
remove `quartzIdentity` flag check from code and tests

### ISSUE THREAD

**Issue by subirjolly** [influxdata/ui#5997]
`quartzIdentity` flag code is live in production and the flag itself has been removed from `configCat`. So, remove this flag's usage from code/tests.

**Comment by wdoconnell** [comment]
The flag has not been removed from configCat yet, as we need to wait on the IDPE PR.

The quartzIdentity flag was already [removed everywhere in the UI code by this PR](https://github.com/influxdata/ui/pull/5847/files) and [removed from all tests by this PR](https://github.com/influxdata/ui/pull/5952).

**Comment by subirjolly** [comment]
i stand corrected. `shared` wasn't selected, so couldn't find it. thanks @wdoconnell
