### ISSUE TITLE
UI Access to Plan Options - Display Side-By-Side Plan Options upon clicking "Upgrade Now" prior to checkout

### ISSUE THREAD

**Issue by ALuckette** [influxdata/ui#6030]
## ACs
- When the user clicks on the "Upgrade Now" button in the top right of the screen, display the side-by-side plan options for the user to read. 
- The side-by-side plan options UI should display key selling points of each plan as shown in the Figma.
- The PAYG plan option should have a button that sends the user to the existing checkout page
- The Annual option should have a button that sends the user to a Marketo form that gets routed to sales

**Comment by ALuckette** [comment]
FYI @juliajames12

**Comment by ALuckette** [comment]
We should run this idea by Jill Guest for approval prior to implementation.

**Comment by wdoconnell** [comment]
Closing, as this proposed change has been deprioritized.
