### ISSUE TITLE
Off by one in table count

### ISSUE THREAD

**Issue by nathanielc** [influxdata/ui#6040]
## About the bug

**Steps to reproduce:**

1. Run a Flux query that returns only a single table, (i.e use `|> group()` at the end)

**Expected behavior:**
Table count shows 1

**Actual behavior:**
Table count shows 0

**Visual Proof:**

![image](https://user-images.githubusercontent.com/3771906/195410870-e28cebed-2525-48d0-b28b-8d1de657e529.png)

## About your environment
 
 Cloud

**Comment by wiedld** [comment]
Looks like the fix, which went out 5 days ago, it's in monitor301 yet. So that's why this bug still occurs there.

**Comment by wiedld** [comment]
Issue is fixed. Closing.
