### ISSUE TITLE
File Upload Experience - csv upload UI Design Changes TBD

### ISSUE THREAD

**Issue by ALuckette** [influxdata/ui#6041]
## Design Requests
- Reduce the likelihood of csv upload failures
- Offer csv annotation/parser tooling in the UI
- Reduce the need for users to spend hours heads-down in documentation
- Improve in-app education about required annotations and their implications

## Top three reasons for failed csv uploads:
- “raw” for csv that is not expected to have annotations.“,69
- must provide csv raw text or filename”,49
- wrong number of fields”,21 - each row doesn't have the same number of fields when it should. It's comparing the # of fields on each line, expecting it to be the same as the lines before it.

The first one we can detect raw vs annotated within the code.
The second one will not be an issue due to the drag and drop of the file
We can definitely help users with the last one.

**Comment by ALuckette** [comment]
@taramk Here are some sample annotated CSVs:

- https://influx-testdata.s3.amazonaws.com/air-sensor-data-annotated.csv
- https://influx-testdata.s3.amazonaws.com/bitcoin-historical-annotated.csv
- https://influx-testdata.s3.amazonaws.com/noaa-ndbc-latest-observations-annotated.csv
- https://influx-testdata.s3.amazonaws.com/usgs-earthquake-all-week-annotated.csv

**Comment by wdoconnell** [comment]
Closing this ticket, as this proposed change has been deprioritized.
