### ISSUE TITLE
Manually changing the cluster url to a different cluster routes the user to the no-orgs page

### ISSUE THREAD

**Issue by wdoconnell** [influxdata/ui#6042]
When logged into one cluster, if the user manually changes the URL to point to a different cluster, they're routed to the no-orgs page. Credit to @cannonpalms for finding this behavior.

See corresponding quartz ticket #6903

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Log into a cluster (tested with staging us east 1-4)
2. Enter the URL for another cluster (tested with staging us east 1-3)
3. User will be waved into the app, but hit the no-orgs page

Behavior only occurs with manual url changes, not when using the in-app button for switching accounts or orgs.

**Expected behavior:**
User is either logged out immediately; or waved into the app to the account's default org in the new cluster.

**Actual behavior:**
No-orgs page

**Visual Proof:**
Will post screenshots in the corresponding quartz ticket.

**Observations**
When we try to hit the new cluster, we get a `200` from identity, but the response relates to the cluster from which the user just navigated. We then get `401`s from flags, orgs, and idpe-me, and then a `401` from identity (this second call is going away based on an optimization Bucky’s implementing).

The initial `200` from identity from the other cluster waves us into the app, but when we get there, we don’t have any orgs in our org array due to the `401` from the idpe orgs endpoint, so the SetOrg component sends us to the no-orgs page.

**Comment by wiedld** [comment]
Should have been fixed already. https://github.com/influxdata/quartz/issues/6997

**Comment by donstephan** [comment]
Having an issue logging into the cloud instance and it might be related to this.

My account is currently stuck in this loop on the cloud instance and I can't login to any of my orgs. Below is the network flow:

1. Attempt to login using OAuth on cloud login page
2. POST to /api/v2/quarts/identity (200)
3. POST to /api/v2/me (401)
4. Logged out back to cloud login page

I can manually hit the /api/v2/quartz/identity endpoint with the generated SID but all the other endpoints fail to validate with that token.
