### ISSUE TITLE
Remove calls to /api/v2/orgs from Cloud2 UI

### ISSUE THREAD

**Issue by wdoconnell** [influxdata/ui#6052]
For cloud users, remove calls to the /api/v2/orgs endpoint. Data previously provided by this endpoint should be sourced from the corresponding quartz/identity, /quartz/accounts/:accountId/orgs, or /quartz/orgs/:orgId endpoints, as needed.

The path used in OSS for retrieving organization data should not be disturbed.

**Comment by hansenreid** [comment]
Closing as not planned.
