### ISSUE TITLE
Changing "from" time range manually causes influxDB error

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#6058]
When doing a query in the new script editor, I tried to change from searching for the past 24 hours to the last 48 by changing -24h to -48h in the custom time range.  When running this query, it failed with an InfluxDB error.  Reloaded the page and ran it again, same thing.  Reloaded again and changed back to past 24 hours from the drop down and it worked ok.  See attached video.

**Comment by garylfowler** [comment]
Note:  it doesn't matter what value is put in, it is always dying when trying to choose a custom range, even if entering one of our stock ranges.

**Comment by TCL735** [comment]
If you type in `now() -1h` in the From field the app does not crash. However, the query will return a 400 error. So, it's definitely expecting `now() -1h` in the input field but needs to be changed to something else before injecting it into the query for this to work.

**Comment by TCL735** [comment]
@garylfowler @asalem1 - i think i found the issue...

A custom time range must be a valid argument for the `new Date()` constructor for both the "upper" and "lower" time range properties, which comes from the To and From input fields.

Having `now()` in either of these properties will not work. There is a missing conversion of `now()` into the current time in the `NewDatePicker` component.

**Comment by TCL735** [comment]
i am removing Team Dumplings from this issue. But please let us know if you need further assistance. Would be happy to help.
