### ISSUE TITLE
Allow double-click to Open a Script

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#6064]
## User Story

<p></p>

As a user, I want to be able to double\-click on a script name when opening a script so that it behaves similarly to all the other software I work with and so I don't have to  move my mouse and make another click,\.

<p></p>

## Acceptance Criteria

<p></p>

- In the script\-open dialog, double\-clicking on a script name will result in the script being opened\.

<p></p>

## Notes

<p></p>

- Requested by Adam

<p></p>

<p></p>

**Comment by influx-product-manager** [comment]
Link to feature: https://influxdata.productboard.com/feature-board/planning/features/15847483

**Comment by garylfowler** [comment]
Closing as won't do
