### ISSUE TITLE
Checkout Form Validation Disconnected With FormInput `required` Attribute

### ISSUE THREAD

**Issue by subirjolly** [influxdata/ui#6072]
Checkout formValidation currently has hard-coded fields in the context function `handleFormValidation`. The `required` field is passed to `FormInput` and it has effect in UI and shows a `*` for required field. But, it isn't connected to the fields which actually need to be validated in `handleFormValidation` function. So, if we need to add or remove required functionality, we have to change in 2 places.
1. Add/Remove `required` field
2. Update `handleFormValidation` with the hard-coded form elements

The solution is to connect the `required` field with `context` so that `FormInput` is responsible to tell context that it needs to be handled for validation.

## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. ...
4. ...
5. ...

**Expected behavior:**

**Actual behavior:**

**Visual Proof:**

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by wdoconnell** [comment]
This ticket is being closed as a nice-to-have that has since been deprioritized.
