### ISSUE TITLE
IOx - SPIKE - Identify potential Cloud UI changes given IOx's unlimited cardinality

### ISSUE THREAD

**Issue by ALuckette** [influxdata/ui#6074]
Implementation

To check if an organization is an IOx org, you can use this selector https://github.com/influxdata/ui/blob/master/src/organizations/selectors/index.ts#L11, which will run after GetOrganizations.tsx is rendered (so basically it will work anywhere that isn't Setup.tsx, Authenticate.tsx, or GetFlags.tsx)

**Comment by wdoconnell** [comment]
This has been completed by the PRs linked in this AIM ticket: https://github.com/influxdata/quartz/issues/7046
