### ISSUE TITLE
IOx - SPIKE - Identify potential visualization updates given new IOx data

### ISSUE THREAD

**Issue by ALuckette** [influxdata/ui#6077]
Implementation

To check if an organization is an IOx org, you can use this selector https://github.com/influxdata/ui/blob/master/src/organizations/selectors/index.ts#L11, which will run after GetOrganizations.tsx is rendered (so basically it will work anywhere that isn't Setup.tsx, Authenticate.tsx, or GetFlags.tsx)

**Comment by wiedld** [comment]
Already done.
