### ISSUE TITLE
Customer issue: Page crashes when switching between `tasks` and `explorer` tabs

### ISSUE THREAD

**Issue by scbrickley** [influxdata/ui#608]
Customer describes issue in this slack thread from the community channel: https://influxcommunity.slack.com/archives/CJ2NXC6A2/p1612424925036400?thread_ts=1611629245.010900&cid=CJ2NXC6A2

They claim it is the same error that caused the crash seen here: https://www.youtube.com/watch?t=1790&v=DdrxMCd_dTY&feature=youtu.be

This issue is one of two that they reported. Other is here: https://github.com/influxdata/ui/issues/609

**Comment by kristinarobinson** [comment]
Sean, can you follow up with the customer and find out if there is any way to reproduce.  We have been unable to do so.

**Comment by scbrickley** [comment]
Started a new thread with the customer here: https://influxcommunity.slack.com/archives/CJ2NXC6A2/p1613162559055400

**Comment by drdelambre** [comment]
fixed with: https://github.com/influxdata/ui/pull/534
