### ISSUE TITLE
Right click menu for the Flux editor has disappeared in Cloud

### ISSUE THREAD

**Issue by scbrickley** [influxdata/ui#610]
**Expected behavior:**
When right clicking on the flux editor, this menu should pop up where I clicked:

![rightclick](https://user-images.githubusercontent.com/18431450/106933741-41a8eb80-66e7-11eb-8d31-9c839aeccb00.png)

**Actual behavior:**
The default right click menu for my browser shows up instead

**Environment info:**

Only appears to be a problem in cloud. OSS is unaffected.

**Comment by hoorayimhelping** [comment]
did some digging, [this PR,](https://github.com/influxdata/ui/commit/3641fc84bf5fbf86f637af4bc9f77c1f3c80a425) which lazy loads monaco, appears to have broken it.
