### ISSUE TITLE
Error highlighting (red squiggly lines) doesn't go away in tools, even when there is no error present.

### ISSUE THREAD

**Issue by scbrickley** [influxdata/ui#611]
**Steps to reproduce:**

1. Open up the data explorer in the tools cluster.
2. Type some flux with a simple syntax error to get some red squiggly lines under your code.
3. Resolve the syntax error. The red lines should persist. When you hover your mouse over the indicated text, no error message will appear
4. Refresh the page. Now typing *any* flux code should result in red squiggly lines that do not go away.

**Expected behavior:**
Error highlighting appears when there's an error. When you hover your mouse over the red lines, you get an error message. When you resolve the error, the highlighting goes away.

**Actual behavior:**
Error highlighting does not go away, and when you hover your mouse over the lines, no error message appears.

**Environment info:**
Can reproduce in tools

Cannot reproduce in us-central-1-gcp

It may or may not be in other cloud environments

OSS is unaffected

**Additional details:**

Behavior was first reported in InfluxData's internal slack on Monday 2/1/2021. It was originally thought to be an LSP issue because it coincided with a new LSP release. While that may still be the case, two pieces of evidence indicate that this may be on the UI end of things:

1. In the past, when we've seen this kind of behavior with the LSP (highlighting a flux error and then never updating once the error has been resolved) it's been because the LSP has crashed and is no longer sending or receiving messages. In this case, the LSP is still running, i.e. autocomplete, syntax highlighting, etc. still work.
2. The timing coincides with some other bug reports regarding recent weirdness in the flux editor, which may or may not be related:

- https://github.com/influxdata/ui/issues/610
- https://github.com/influxdata/ui/issues/609

If, after digging into this, we can confirm that the problem is not with the UI but with the LSP, please open an issue in https://github.com/influxdata/flux-lsp

**Comment by russorat** [comment]
https://github.com/influxdata/influxdb/issues/18965

caused by variables with a hyphen in them.

**Comment by scbrickley** [comment]
For the sake of clarity for whoever picks up this issue: 

Seems like the fix here involves adding a guard against including invalid input in the prelude sent by the UI to the LSP.

Relevant line of code here: https://github.com/influxdata/influxdb/blob/master/ui/src/external/monaco.flux.server.ts#L273

**Comment by TCL735** [comment]
I requested a feature in clockface to handle pre-validation of inputs so that a user can rename variables that are flagged as having bad names. Originally, we were not going to wait for the feature, and just make a workaround in the UI for now.

However, it looks like the feature can be implemented in clockface with just a minor tweak. We are waiting on: https://github.com/influxdata/clockface/pull/592

**Comment by TCL735** [comment]
Tests are passing. But we are still holding off on review for now, because we have a pending redesign of the alert that should be included.

We are waiting on the review of: https://github.com/influxdata/clockface/pull/595#issuecomment-801515079

**Comment by TCL735** [comment]
Updated to consume Clockface's new Resource state and error messaging.

Reviewers assigned.
