### ISSUE TITLE
Improve GroupBy component useEffect dependency list

### ISSUE THREAD

**Issue by appletreeisyellow** [influxdata/ui#6116]
The GroupBy component has a useEffect function. The dependency list doesn't include two functions `getGroupKeys()` and `setSelection()` to avoid infinite loop. We might want to investigate into the code to see what causes the infinite loop and how we can eliminate that. 

Part of #5761, follow up of #6099

**Comment by hralexander** [comment]
Review https://github.com/influxdata/ui/issues/5685 for additional context.
