### ISSUE TITLE
Add search bar to the group option dropdown

### ISSUE THREAD

**Issue by appletreeisyellow** [influxdata/ui#6117]
Part of #5761

The current UI of the group option dropdown doesn't have a search bar because it is using a clockface component [MultiSelectDropdown](https://influxdata.github.io/clockface/?path=/story/components-dropdowns-composed--multiselectdropdown). 

@ChitlangeSahas has updated the clockface component to have the options to add search bar in influxdata/clockface#885

## Current UI
<img width="1487" alt="Screen Shot 2022-10-18 at 4 42 38 PM" src="https://user-images.githubusercontent.com/14298407/196551942-a4090943-50ad-4ae6-aa70-6eee96e440bb.png">

## Design (Expected UI)
<img width="237" alt="Screen Shot 2022-10-18 at 4 43 10 PM" src="https://user-images.githubusercontent.com/14298407/196551948-1b8b3264-73a0-4a0c-b789-8c7608047d7f.png">

**Comment by kristinarobinson** [comment]
@hralexander We are adding this ticket to our board to update the clockface component.  Do we need to create a separate ticket for this work, such that the QX team can do the updating to the component?

**Comment by appletreeisyellow** [comment]
Reopen this issue for the QX team to update the component in new script editor
