### ISSUE TITLE
Notebooks: I can export tasks that will run without errors

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#613]
As a notebooks user, i can export a task from a notebook, so that the task will execute at the given interval without errors.

_Exporting to a task should remove UI variables from the task_ 

When we export the task from the Flow, the UI variables stored in the `v` object are no longer relevant. We should replace those with the hardcoded values if we can.

If replacing the actual values in the script is too hard, then we need to ensure the `v.windowPeriod` is in the `v` object inserted at the top of the script. 

for example, the task script currently generated looks like this:
```
option v = {
  timeRangeStart: -1m,
  timeRangeStop: now()
}

option task = { 
  name: "Downsampling task",
  every: 1m,
  offset: 0s
}

from(bucket: "telegraf") 
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) 
  |> filter(fn: (r) => r["_field"] == "usage_user") 
  |> filter(fn: (r) => r["cpu"] == "cpu-total") 
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) 
  |> to(bucket: "mnorriswalker+awsusw's Bucket")
```

but fails because `v.windowPeriod` is not defined in the `option v` block.

**Comment by mnorriswalker** [comment]
@russorat - what's the user value here? thanks in advance for explaining! Can we do a `As a ___, I can ___ so that ___` format?

**Comment by russorat** [comment]
user value is that exporting a task doesn't work today in notebooks and this would fix that :)

as a task builder, i can export a task from a notebook, so that the task will execute at the given interval without errors.

**Comment by mnorriswalker** [comment]
Great find. I've exported lots of tasks but I failed to check to see if they were working. Oops!
