### ISSUE TITLE
Make $250 Credit Permanent for All Non-Marketplace Free Users

### ISSUE THREAD

**Issue by ALuckette** [influxdata/ui#6152]
## ACs
- Make $250 Credit Permanent for all non-marketplace Free users upon converting to PAYG
- Turn the flag on for all nonmarketplace free users - instead of removing the flag. 
- Remove the experiment wrapper.

## Related work for AIM
- Automatically apply the $250 credit in zuora. Credit should be effective on the date that the user signed up for the credit (when the user converted to PAYG). This requires creating a new zuora rate plan of type "Credit" and attaching it to the existing subscription.

**Comment by ALuckette** [comment]
@bpalani - How can we automate the credit limits?

**Comment by ALuckette** [comment]
@alejom99 Would the "automatically apply credit in zuora" portion of work be implemented in the AIM code base? If so, would you prefer AIM to work on that part or is it ok for dumplings to implement? 

FYI @kristinarobinson

**Comment by ALuckette** [comment]
FYI @mavarius

**Comment by gunnaraasen** [comment]
We're going to create a script to make the application of the credit in Zuora easier to do at the end of the month.
