### ISSUE TITLE
Query Builder: Creating a new query leaves the old query builder state around

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#617]
### Background
Creating a new query through the query builder, then going elsewhere in the app, then coming back to query builder shows the previous query builder state.

### Expected Behavior
I'd expect after saving a query using the builder that the state would reset.

### Reproduction Steps
1. Create a query through the builder
1. Save it and add it to a dashboard
1. Go somewhere else, like the dashboard you just created
1. Go back to query builder - the state is still around

**Comment by russorat** [comment]
I'd like to see some feedback from users about https://github.com/influxdata/ui/pull/595 before prioritizing this work.
