### ISSUE TITLE
QX - MVP - Navigation Method from New Data Explorer to Tasks UI

### ISSUE THREAD

**Issue by ALuckette** [influxdata/ui#6173]
## Request
- Provide users a way to navigate to the tasks UI after saving a script in the new data explorer UI. 

## ACs
- A "Schedule button" (per Julia's design) will be available from within the new Script Editor
- A "Save and Schedule Button" will be available within the the save dialog within the new Script Editor
- When the schedule button is selected, if the script is not already saved, a save dialog will be shown to the user; After the user completes the save dialog, the user will be redirected to the Create Tasks Page with the name of the saved script
- When the schedule button is selected, if the script is already saved, the user will be redirected to the Create Tasks Page with the name of the saved script
- When the "Save and Schedule Button" is selected, the user will be directed to the Create Tasks Page with the name of the saved script
- An analytic UI Event will be generated each time either of these buttons is pressed

## Notes

- No additional logic is necessary for processing the button click, it is simply used to redirect the user back to the tasks page

## Design
- Consult with @mavarius and @juliajames12 on design details

**Comment by ALuckette** [comment]
FYI @juliajames12 and @mavarius

**Comment by ALuckette** [comment]
Closing this ticket as a duplicate of https://github.com/influxdata/ui/issues/6071

**Comment by ALuckette** [comment]
Reopening to capture the MVP version of what was requested in #6071

**Comment by juliajames12** [comment]
Here's the current design: https://www.figma.com/file/r91KxurPL3VQ7JMqc9Ldqo/New-Tasks-Experience?node-id=1669%3A38682

**Comment by wiedld** [comment]
We are no longer integrating Scripts (as a resource) with Tasks.
