### ISSUE TITLE
Query Builder: Saving query UX improvements

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#618]
### Background
Selecting a dashboard to save the query to is a wonky experience - the dropdown doesn't go away after selecting a dashboard from it.

![1.gif](https://images.zenhubusercontent.com/5c33b08d24dda4712ef4ae10/d00af664-f628-40d3-b90d-4f14efb12c15)

### Acceptance Criteria
- Selecting a dashboard makes the select box go away

**Comment by ShmuelLotman** [comment]
I think that this is due to the ability to select multiple dashboards. If it disappeared after each one, it might be a worse UX than what it is now. It's a very quick fix if thats still the desired behavior, so let me know. Happy to take care of this if needed, @hoorayimhelping
