### ISSUE TITLE
Using InfluxData schemas with SQL querying. (a.k.a. special identifiers needed)

### ISSUE THREAD

**Issue by wiedld** [influxdata/ui#6183]
## Scope of problem:
This addresses an issue concerning the querying of influxdata schemas in iox using SQL. Cross-team discussion will hopefully help: (1) scope the problem, (2) decide what is the reasonable amount of change, which  translates into (3) where those changes will occur (a.k.a. in UI, or in flux, or elsewhere).

## Problem:
tl;dr -- influxdata schema rules on WRITE, sql schema rules on READ.

We are going to be taking an influxdata schema, writing/migrating it into iox, and then querying with SQL. This means that users who are querying using sql, need to make sure to use special identifiers. This includes SQL in all the various interfaces, including the use of SQL within `iox.sql()`.

Specifically:
* in IOX only.
* once migrating influxdata schemas onto iox:
  * influxdata schemas have case sensitivity, and allow whitespace.
  * e.g. measurement names `airSensors` and `quarry blast` 
* SQL querying is case insensitive and does not accept whitespace, unless using special identifiers
  * so it needs to be double quoted
  * e.g. `select * from \"airSensors\"` 
* currently, queryd is not surfacing the errors.
  * this means that if we don't use the special identifiers, we get an obtuse 500 error.
  *   https://github.com/influxdata/idpe/issues/16129

## Re-creating the issue:

Made an iox lighthouse account, then populated my bucket using our sample_data on S3 (same task we run in remocal local dev). I got these case-sensitive and whitespace-containing identifiers:

<img width="600" alt="Screen Shot 2022-10-27 at 2 07 38 PM" src="https://user-images.githubusercontent.com/10232835/198399339-d8506d38-4624-446f-ac8a-c99ae1d50eb7.png">

Then on querying, the user just needs to remember to use special identifiers. (Or perhaps should we have better error codes that state that?)

<img width="526" alt="Screen Shot 2022-10-27 at 2 19 01 PM" src="https://user-images.githubusercontent.com/10232835/198400525-94c87d2f-5a27-43a7-83a4-331ffc87efd0.png">

## Scope of this ticket:

Is to address whether we need to: (1) message this need for special identifiers, to the users, and/or (2) do anything automatic escaping within flux's `iox.sql()`, and/or (3) add this messaging/hints in the error responses.

**Comment by rockstar** [comment]
I'm not quite understanding the issue. Is it that you have to put your names in double quotes in certain circumstances? Or is it that the user needs to know to escape those double quotes?

**Comment by wiedld** [comment]
Made ticket for work in docs.
Updating for this ticket to close, once SQL composition merges.
