### ISSUE TITLE
Query Builder: Feature Request: Clear query builder state

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#619]
### Background
~There's no quick way to reset the query builder's state to new. You have to individually close query builder tags.~

~Having this could provide a good escape hatch for users if something happens in the cache that causes an undesirable state.~

Clicking a bucket will clear the state. As evidenced by this ticket, it's not obvious that is a feature.

**Comment by drdelambre** [comment]
instructions unclear

**Comment by hoorayimhelping** [comment]
This was a small enhancement request we're not going to do
