### ISSUE TITLE
Add function to New Script Editor toggle when it's turned off to trigger the VWO survey

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#6216]
In order to trigger the VWO survey after a user has turned off the New Script Editor, we need to include the logic in that specific slide toggle component to trigger the survey. 

Here is the code we need to add to onClick prop of the New Script Editor slide toggle: 
`executeTrigger();`

**Comment by wiedld** [comment]
Specifics on request:
* trigger only on toggle off
* trigger only once per session
* in the VWO dashboard, can then set total max surveys (across sessions) to 3.

**Comment by wiedld** [comment]
Not pursuing anymore. Closing.
