### ISSUE TITLE
Redirect to quartz with path

### ISSUE THREAD

**Issue by gunnaraasen** [influxdata/ui#6217]
**Proposal:**

When a session is expired, the UI redirects to cloud2.influxdata.com for the user to login, before quartz redirects the user back to the appropriate cluster. To send the user to the page they originally requested, we need to send the path to cloud2.influxdata.com (quartz will handle the routing from there).

**Current behavior:**

The UI currently redirects to `cloud2.influxdata.com` with a `redirectTo` query parameter.

**Desired behavior:**

The UI should redirect to `cloud2.influxdata.com/<original-req-path>` with the path from the original request to the cluster URL.

**Alternatives considered:**

Using the query parameter would require quartz to parse the URL and extract the path, which is a potential security issue.

**Use case:**

We expect these types of redirects to be more common once Cloud supports multiple organizations.

**Comment by ALuckette** [comment]
@ChitlangeSahas @kristinarobinson This is blocking AIM from enabling the removal of IDPE logins in prod, which is ultimately blocking universal login. Sharing for awareness. I put this in our current sprint.

FYI @gunnaraasen
