### ISSUE TITLE
Documentation Link below the main page is broken, Also Need Help Docs on How to Build

### ISSUE THREAD

**Issue by weedkiller** [influxdata/ui#622]
Can you please add help docs on the steps to build and customize

**Comment by kristinarobinson** [comment]
Can you send a screenshot of where the broken link is?

**Comment by weedkiller** [comment]
Hello, attached is the picture.

![image](https://user-images.githubusercontent.com/21086190/107865352-6b72b880-6e33-11eb-921a-2714289c8259.png)

- [ ] Working Build, and New build directions/documentation is needed. WIki link at the bottom of the page was broken
- [ ] Can you please add some clear instructions on how to build and run.
- [ ] Also, include some sample data sets to do a dashboard-bi-demo easily on the frontend to see how the timeseries DB can bubble up data quickly.

**Comment by weedkiller** [comment]
No help on how to start the development /dev server locally

![image](https://user-images.githubusercontent.com/21086190/107865679-22bcfe80-6e37-11eb-9f07-d31737f900c1.png)

**Comment by weedkiller** [comment]
Does NOT Work, going back to MongoDB
