### ISSUE TITLE
Epic: Operator Page Updates

### ISSUE THREAD

**Issue by ALuckette** [influxdata/ui#6222]
Operator Page updates are needed in support of Multi-Org. 

Design and ACs TBD.

**Comment by ALuckette** [comment]
After consulting with @alejom99, I learned that the internal enablement team does not have the capacity to take on updates to the operator page in support of MultiOrg. 

Creating this epic to track operator changes that are needed in support of multi org. @juliajames12 @kristinarobinson

**Comment by wdoconnell** [comment]
The operator changes for multi-org have been completed by these tickets. Closing as duplicative of: #6488  #6326
