### ISSUE TITLE
Adaptive Zoom - value axis should not reset after a new query when zoomed in

### ISSUE THREAD

**Issue by TCL735** [influxdata/ui#6228]
### Currently
With the adaptive zoom feature, whenever the user zooms in on the value axis, no query is made (as designed).

Only when the user zooms in on the time axis, is a query made. Additionally, when the time axis zoom makes the query, the graph will also refit to see the new data. The refitting will have the time range selected by the user's mouse action on the time axis, and the value range of the new data within that time range. **Any existing value range is not respected.**

### Proposal
Zooming in on the time axis should: 1) refit the graph for the time range selected, and 2) should not adjust the value range of the graph when the value axis is zoomed in. When the value axis is not zoomed in, then a query from a zoom should refit both axes.

**Comment by TCL735** [comment]
This issue came up while addressing EAR 3724. After the EAR was fixed, the customers expressed surprise that a time axis zoom-in will reset the value axis. They had mistakenly thought that the value axis would remain as-in. The advantage being they can apply multiple zoom-ins both horizontally and vertically in succession and in any order without the graph unexpectedly resetting on them in either axis.

**Comment by ALuckette** [comment]
Hi, 

Thanks for surfacing this. 

This is not a priority at this time. 

Workaround: Zoom horizontally first, then vertically zoom. 

@btasker @TCL735 @kristinarobinson

**Comment by wdoconnell** [comment]
Closing as work has been de-prioritized per comment above.
