### ISSUE TITLE
Visualization Options not Available when editing SQL Script

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#6240]
When editing a SQL script, the graphic/visualization customization options are not available.  This is because the flux function panel has been removed from the SQL view; but that area also was used for showing the visualization options.  We need to find a way to expand that panel and show the visualization customization options and collapse it back when the user is finished.

**Comment by wiedld** [comment]
Also want the collapsing and expansion of the rightmost options panel, to be controlled by the FluxQueryBuilder parent. Such that we can expand and collapse as needed, for the SQL-specific language UX.

**Comment by wiedld** [comment]
Fixed as part of [this epic on SQL graph visualization](https://github.com/influxdata/ui/issues/6482).
