### ISSUE TITLE
Script Editor SQL Adjustments

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#6242]
**Task Description**

<p></p>

We need to do some UI Re-Design to make the script editor SQL experience better:

<p></p>

1 \- Separate the Bucket Selection from the rest of the schema browser so it is more obvious to the user that the bucket selection is required, and that the schema browser is informational only \(see design from Julia\)\.

<p></p>

2 \- Change the text wording to indicate that the user needs to select a database\/bucket first\.  See design from Julia\.

<p></p>

3 \- When a user runs a SQL query without a bucket selected, the user will be shown an error message that tells them they must select a database\.

<p></p>

4 \- The raw text that is in the editor should go away once the user clicks into the box and starts typing \(they shouldn't have to delete it manually\)\.

<p></p>

5 \- Remove the time range selection as it will not apply to SQL queries right now\.

### Figma
https://www.figma.com/file/0qAntPk5LVangAHguWT74X/Query-Experience-Project?node-id=2651%3A112467&t=tGT6F3oSYXF2KSZz-1

**Comment by influx-product-manager** [comment]
Link to feature: https://influxdata.productboard.com/feature-board/planning/features/16202009

**Comment by garylfowler** [comment]
Julia started a design with this and that I believe Daniel had collaborated on.  I'll check with Daniel to see if he can find Julia's design and complete it.

**Comment by appletreeisyellow** [comment]
@garylfowler @mavarius I checked the design in the above Figma link and I saw different versions of design. Which one should I use?
