### ISSUE TITLE
feat: display switch org actionable toast after creating org

### ISSUE THREAD

**Issue by subirjolly** [influxdata/ui#6268]
When you create a new organization with the modal from #5899 
we need to display an `Actionable` toast notification as displayed in the following image.
![image](https://user-images.githubusercontent.com/1637395/200383807-2ceaede0-55fc-4e57-8295-d5ce824896a4.png)

We don't need the 2 toasts(Blue and Red) as those cases are already handled in the Create Org Modal. We just need to display the green toast so that the users can switch the org, if they need to.

**Comment by wdoconnell** [comment]
This ticket was also completed in #6327 . 

As the issue explains, the red and blue toasts were superseded in the Figma design with a loading spinner and an in-overlay error message, as typical network delays are not longer enough to warrant separate toast notifications when org creation is 'pending'.
