### ISSUE TITLE
Operator Page - Remove cardinality limit from operator page for all IOx orgs.

### ISSUE THREAD

**Issue by ALuckette** [influxdata/ui#6274]
## ACs

- Edit the modal that pops up upon clicking the org ID so that the title is "Organization Details" instead of the Org ID. 
- If it's an IOx organization, then display "N/A - IOx" in grey text underneath the "Series Cardinality" field. 

## Design

- Figma: https://www.figma.com/file/fvVSKwnepmRWvzFlIxCWCe/Multi-org?node-id=2680%3A18233

**Comment by ALuckette** [comment]
FYI @taramk & @juliajames12

**Comment by blegesse-git** [comment]
Do we want to disable Series Cardinality input field for IOx orgs? Can users with read-write permission edit iox cardinality value?

**Comment by blegesse-git** [comment]
after a discussion with @wdoconnell, we're going forward with disabling the Series Cardinality field for iox orgs so it can't be edited. The field will show `N/A - IOx` and will be the only field that can't be edited.

**Comment by blegesse-git** [comment]
closing because it has been decided Operator page org overlay will not show cardinality limit for iox orgs at all.

**Comment by blegesse-git** [comment]
New AC: 

- [ ] According to [figma](https://www.figma.com/file/fvVSKwnepmRWvzFlIxCWCe/Multi-org?node-id=2680%3A18233), add title ("Organization Details") to the org overlay.
