### ISSUE TITLE
SQL Select Composition

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#6313]
## User Story

<p></p>

As a user, I would like the selections that I make in the Schema Browser to be used to formulate my basic SQL Select Statement so that I can easily start queries\.

<p></p>

## Acceptance Criteria

<p></p>

- An "Add" or "Inject" type function \(needs Daniel Design\) will be available in the schema browser after bucket, measurement, and at least one field or tag has been selected\.

- Upon initiating the function, the SQL select statement will be formulated and added to the SQL editing window

- It is NOT expected that there will be any synchronization capability; the function will always just be an add \(the user will have to manually delete when needed\)

<p></p>

## Notes

<p></p>

- While this may seem like just a "nice\-to\-have" feature, I am advocating for it for multiple reasons:

    - If we do not do this, then we will be forced to do some other re\-design work as the schema browser interaction is a confusing user experience with SQL in its current state \(remember, this was only a work\-in\-progress feature\)\.  Somehow we have to represent to the user that bucket selection is required, but that all other selections have no consequence, even though they are somewhat prompted to enter them\.  We can re\-design the schema browser to make this more apparent and solve this issue \- but it is a trade\-off of providing this feature as that will also require development time

    - Users will most likely know SQL, so yes, they can build a select statement\.  But users may have experience with date and time columns, they may not always have experience with timestamps\.  Getting a time range on their queries will be important and they may not know how to formulate the right "where" clause for the timestamp\.  Especially relative time\.  By showing them this, at least once, we get them on the right track and help prevent non\-time bound queries that would have a high cost to us

    - SQL is going to be the most performant query type in the IOx world; I don't want users to pick the flux editor solely because it helps them graphically build their query; so we really want them to want to use the SQL editor

    - We want users to be able to build queries quickly and iterate quickly \(largely for their benefit, but also it is a PAYG metric\)

    - We will get this feature request almost immediately if we don't have it\.  It doesn't mean we will have to do it, but if we are choosing other work that could be avoided if we do this, then we will already have this feature when the time comes  

- Sample Implementation for reference for representational purposes only:

<p></p>

<p></p>

```
# This is a function to build a single SQL Select Statement based on schema browser selections
def build_sql_statement(measurement, field_selections, tag_selection, timeindex):
    # Measurement - pass as a string
    # field_selections - pass as a list of strings
    # tag_selection - pass as a tagkey, tagvalue (only 1 tag key/value pair supported)
    # timeindex - pass as an integer containing index value for time_options:
    time_options = ["time > now() - interval \'5 minutes\'",
                    "time > now() - interval \'15 minutes\'",
                    "time > now() - interval \'30 minutes\'",
                    "time > now() - interval \'1 hour\'",
                    "time > now() - interval \'4 hours\'",
                    "time > now() - interval \'8 hours\'",
                    "time > now() - interval \'12 hours\'",
                    "time > now() - interval \'1 day\'",
                    "time > now() - interval \'2 days\'",
                    "time > now() - interval \'7 days\'",
                    "time > now() - interval \'14 days\'",
                    "time > now() - interval \'30 days\'",
                    "time > now() - interval \'60 days\'"]
    # Initialize select statement
    if len(field_selections) > 0:
        sql_statement = "select time, "
    else:
        sql_statement = "select * "
    # add field selections to select statement
    for index, item in enumerate(field_selections):
        if index != len(field_selections) - 1:
            sql_statement = sql_statement + item + ", "
        else:
            sql_statement = sql_statement + item + " "
    # add table/measurement selection to select statement
    sql_statement = sql_statement + "from " + measurement + " "
    # add tag selections to select statement
    if len(tag_selection) > 0:
        sql_statement = sql_statement + "where " + tag_selection[0] + " = " + tag_selection[1]
    # add time selection to select statement
    if 'where' not in sql_statement:
        sql_statement = sql_statement + "where "
    else:
        sql_statement = sql_statement + " and "
    sql_statement = sql_statement + time_options[timeindex]
    #print(sql_statement)
    return(sql_statement)

# testing and demonstration

# Example #1:  Passing measurement, 2 field selections, and 1 tag value with time option 1 (15 minutes)
returned_sql = build_sql_statement("climate",["temperature, humidity"],["location","\'Outside\'"],1)
print(returned_sql)
# Example #2: Passing measurement, no field selections, and 1 tag value with time option 1 (15 minutes)
returned_sql = build_sql_statement("climate","",["location","\'Outside\'"],1)
print(returned_sql)
# Example #3: Passing measurement, 1 field selection, and 1 tag value with time option 5 (8 hours)
returned_sql = build_sql_statement("climate",["temperature"],["location","\'Outside\'"],5)
print(returned_sql)
# Example #4: Passing measurement, 1 field selection, no tag key/values, and time option 5 (8 hours)
returned_sql = build_sql_statement("climate",["temperature"],"",5)
print(returned_sql)
```

<p></p>

**Comment by wiedld** [comment]
Assume [this issue, of needing special identifiers](https://github.com/influxdata/ui/issues/6183), will be resolved with customer education via the SQL composition.
