### ISSUE TITLE
SQL by Default

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#6314]
## User Story

<p></p>

As an IOx service provider, I want to emphasize my new SQL capabilities and the performance benefits it brings, so I want it to be the default script editor when in an IOx enabled org\.

<p></p>

## Acceptance Criteria

<p></p>

- When a user logs into an IOx enabled org and runs the new script editor, SQL editing will be the default view

## Notes

<p></p>

<p></p>

<p></p>

**Comment by influx-product-manager** [comment]
Link to feature: https://influxdata.productboard.com/feature-board/planning/features/16424772

**Comment by gavincabbage** [comment]
Looks like https://github.com/influxdata/ui/pull/6323 will satisfy this

**Comment by garylfowler** [comment]
Can you explain how?

**Comment by garylfowler** [comment]
Thanks, some additional code was already added to do it, thank you.  I
didn't realize you were doing any other work besides removing the feature
flag.

Thanks again!
