### ISSUE TITLE
Bug caused by switching from Flux to SQL editor after configure a graph for IOx users

### ISSUE THREAD

**Issue by appletreeisyellow** [influxdata/ui#6325]
## About the bug

This is an edge case bug. It only occurs when an IOx user configures the graph that generated by flux, and this user decides to switch to SQL editor without closing the graph configuration option. See the video below

https://user-images.githubusercontent.com/14298407/202485092-5519f2f7-7d36-49f0-a2ee-76ca4e0bfde3.mov

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Use an IOx org account
2. Go to new Script Editor
3. Start with the Flux editor
4. Select a bucket and a measurement, or write your own flux query
5. Click "RUN" button
6. Click "GRAPH" button
7. Click "CUSTOMIZE" button
8. Click "+ New Script" button and pick "SQL"
9. Click "NO, DISCARD"

**Expected behavior:**
Switch to SQL editor and the side bar is cleared (since there is nothing by default in the side bar for SQL editor)

**Actual behavior:**
Black error screen

**Comment by wiedld** [comment]
This bug was fixed with an PR merged yesterday (related to SQL graphing). Closing.
