### ISSUE TITLE
Remove preview option from notebooks

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#633]
Right now, the preview option is misleading because a flux query could write data via a to() function, that would stick around after the query has completed. Also, as we add other cell types (e.g. python), we cannot guarantee that they won't have impact.

To reliably deliver this feature, the platform needs to provide a query-preview option that doesn't cause any impact after the query has completed. When that is available, we can re-introduce the preview option to notebooks.  For now, we should just provide the 'run' option and we can guide the users on how to test their notebooks.

Ref: https://github.com/influxdata/idpe/issues/9779

**Comment by russorat** [comment]
chatted with team on this. we agreed the preview capability is useful in the tool and going forward, we will work to ensure that capability existings in the APIs. For the scenarios with custom code, we will look for ways to highlight in the FAQ or UI that there may be side effects when using custom scripts.

Closing this for now but keeping the related issue open.
