### ISSUE TITLE
Cant download data older than 30 days

### ISSUE THREAD

**Issue by Bra1nsen** [influxdata/ui#6331]
STORAGE DATA FOREVER:

![image](https://user-images.githubusercontent.com/58213050/202742440-106747ca-a191-495b-b8fc-29b5311689f0.png)

CAN ONLY DOWNLOAD DATA FROM LAST 30 DAYS
![image](https://user-images.githubusercontent.com/58213050/202742514-1d9fe95c-0032-4f32-b4a0-df970de73df3.png)

Question: How can one download data older than 30 days? (e.g. as .csv)

**Comment by wiedld** [comment]
@Bra1nsen The datePicker includes a `Custom Time Range` as the first option on that dropdown. You can use that option to get data older than 30 days.
