### ISSUE TITLE
Qx Builder: use new csv download approach (full dataset bypassing browser memory).

### ISSUE THREAD

**Issue by gavincabbage** [influxdata/ui#6354]
Is basically the solution from [here](https://github.com/influxdata/ui/pull/6062).
* reuse same server worker
* feel free to extract DRY common code, if it's not gnarly.
* basic UI rule:
  * when no service worker --> don't even have the download button
  * if have worker (so can download) --> have button, but with optional disabled state (e.g. if no query written yet).
  *  That's^^ the general rule in the old data explorer. Feel free to suggest/improve on this UX decision.

**Comment by wiedld** [comment]
@appletreeisyellow for a higher-level overview on why this approach, and what it does, please see t[he detailed comments in this code](https://github.com/influxdata/ui/blob/193b27b1e12fadeec52c7d31f62cfe43b9d86852/src/shared/workers/downloadHelper.ts).

**Comment by appletreeisyellow** [comment]
Blocked by a bug in old Data Explorer. Here is an EAR for it https://github.com/influxdata/EAR/issues/3809
