### ISSUE TITLE
InfluxDB Explorer: Unable to export data (export CSV)

### ISSUE THREAD

**Issue by EdmanJohan** [influxdata/ui#6375]
Seems like I'm currently unable to export any data (as CSV) from the InfluxDB Data Explorer.
When exporting the data the following error is given in the browser:

```json
{ 
   "code": "invalid", 
   "message": "invalid: unsupported Content-Type header value"
}
```

Version: (1ec080e)

Not sure what other information there is to supply.

**Comment by wiedld** [comment]
Thanks for letting us know. [Fixed](https://github.com/influxdata/ui/pull/6377).
