### ISSUE TITLE
Default "Website Monitoring Bucket" Doesn't Show Up in Dashboards Bucket Listing

### ISSUE THREAD

**Issue by subirjolly** [influxdata/ui#638]
We can't get sample data from the default monitoring bucket.

![image](https://user-images.githubusercontent.com/1637395/107286975-4cd58180-6a2f-11eb-8e7f-3aced75005f4.png)

I created basic variables and a cell. When I go to the dashboard after that, and click on the dropdown for the buckets, I am not seeing default bucket.

**Comment by drdelambre** [comment]
i looked into this and it's just because we have a super weird way of defining what sample data is. so it will never show up in a query, because it is defined within an org that the query will never be scoped to. fun right?
