### ISSUE TITLE
Data Table: I can page through a list of results

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#639]
As a InfluxDB Cloud user, I can page through a list of query results so that I can see the rows of data that are returned.

### Scenario: Show paginated results
Given: I have notebook 
When: I select metrics in the metric selector
And: I click `preview`
Then: I see results from MOST RECENT to LATEST
And: A data table with my paginated results based on available view port size

When: click on a page number
Then: I go to that page number

### Scenario: No Results
Given: I have a notebook with a metric selector in it but the query returns no results
When: I click preview
Then: Show No Data Returned

### Design Notes
- Use the new Clockface pagination component
  - https://github.com/influxdata/clockface/pull/569
- Mockup
  - https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=1635%3A10213

**Comment by mnorriswalker** [comment]
Need to add a blocked on - https://github.com/influxdata/clockface/pull/569, will probably need to make an issue that is closed by the PR to track

**Comment by barbaranelson** [comment]
We need to get the developer of the pagination component to sign a CLA before we can incorporate their code.
