### ISSUE TITLE
Data Table: I can download the raw query results as a csv file

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#640]
As a InfluxDB Cloud user, I can download the raw flux results so that I can view the data in a local csv editor like Excel.

### Scenario: Success
Given: I have a raw data view open and results shown
When: I click the `download CSV` button
Then: I see a loading spinner indicating that the query is being executed instead of the download csv button

When: the query is executing for more than a few seconds
Then: a cancel button is displayed to the user

When: the cancel button is clicked
Then: the query is cancelled and the file stops downloading

When: Results start being returned from the query
Then: A file download from the browser is initiated with the query results
Then: The file name is `influxdb_results_<timestamp of when the file was created>.csv`

When: The query times out from the request
Then: A message is displayed to the user indicating that partial results were returned and the resulting csv file is not complete

### Technical Notes
  - This download CSV will download the full query results, not just the limited results we see in the browser
  - This should not be subject to the 27mb limit in cloud. It will still be subject to any api or queryd timeouts.

### Design Notes
- Mockup
  - https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=1635%3A10213

**Comment by jzahnd** [comment]
Needs to launch its own request and not use the current mechanism that uses what is currently in memory.

**Comment by drdelambre** [comment]
and a way to handle failure in cases where a `|> limit(n: 100)` might pass, but the raw query wouldn't
