### ISSUE TITLE
InfluxDB UI 2.6.1 Error after Login "An InfluxDB error has occurred. Please report the issue here"

### ISSUE THREAD

**Issue by Starfoxfs** [influxdata/ui#6445]
## About the bug
I updated my InfluxDB from 2.6.0 to 2.6.1. After this update i get a Error Screen on my Browser after login to InfluxDB UI
If i press F5 to reload the Browserpage its gone.
These Error Screen occurs after each new login and after each complete new access to the InfluxDB UI Page.

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Open the Influx UI with Browser and Login
2. The first you see is "An InfluxDB error has occurred. Please report the issue here"
3. After reload the page with F5 the error is gone and shows the normal Influx UI
4. This error occurs every time the page is accessed newly

**Expected behavior:**
Login to InfluxDB UI without an Error Message

**Actual behavior:**
Error Message after Login to InfluxDB UI

**Visual Proof:**

![2](https://user-images.githubusercontent.com/62878094/210389107-b6b4fcb0-4c36-4584-b5a5-7b4b571a7206.jpg)

## About your environment

**Environment info:**

- System info: Linux 5.15.76-v8+ aarch64
- InfluxDB version: InfluxDB v2.6.1 (git: 9dcf880fe0) build_date: 2022-12-29T15:52:06Z
- Other relevant environment details: Raspberry Pi4B latest Debian (Bullseye 11) 64bit

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by jeffreyssmith2nd** [comment]
Just to check the easy stuff first, can you do a hard refresh in your browser (one that clears the cache)? There were some changes between 2.6 and 2.6.1, and while ideally a cache clear shouldn't be required, it has resolved some issues for people.

**Comment by Starfoxfs** [comment]
Hi Jeffrey,

it´s gone, i have restarted my Raspberry Pi4B a second time then the Error was gone.

Don´t know why. 

The Browser Cache was not the Problem here, i have cleared it first i have seen this Error.

I Think some internal Raspberry Pi Caches was cleared with the restart and then it was fine.

**Comment by jeffreyssmith2nd** [comment]
Interesting, the session caches are in memory so a reboot would definitely clear that cache. I'm going to close the issue, if you re-encounter it feel free to reopen.
