### ISSUE TITLE
Use is_valid_flux() in ui, instead of the improper use of parse().

### ISSUE THREAD

**Issue by wiedld** [influxdata/ui#6447]
The contract of `parse()` versus `is_valid_flux()` is [documented in the LSP tests](https://github.com/influxdata/flux-lsp/blob/fc06b38e3d889974f72e9d133817eafda9c901dc/integration/lsp.test.ts#L168-L190).

We are currently, in the UI, using parse() incorrectly. We assume that any time there is a successful parse, it's therefore a vald flux query. This is incorrect.

**Comment by appletreeisyellow** [comment]
Here are the places that uses `parse()`. I'm planning to replace them in separate PRs:

- [ ] Old Data Explorer: src/timeMachine/actions/queries.ts
- [ ] Variables:
    - src/variables/utils/getWindowVars.ts
    - src/variables/utils/astim.ts
- [ ] Shared: src/shared/contexts/query/preprocessing.ts
- [ ] Write Data: src/writeData/components/ClientCodeQueryHelper.tsx
- [ ] Language support: src/languageSupport/languages/flux/parser/index.ts
- [ ] Tasks: src/tasks/actions/thunks.ts
- [x] ~~Notebooks~~ (Notebooks is going to be deprecated, so not updating it)

**Comment by wiedld** [comment]
Looks like we have a bunch of unit test fixtures which don't use valid flux.
* [hydrate vars](https://github.com/influxdata/ui/blob/master/src/variables/utils/hydrateVars.test.ts) unit tests.
* [exportVariables](https://github.com/influxdata/ui/blob/master/src/variables/utils/exportVariables.test.ts) unit tests.
* [filterUnusedVars](https://github.com/influxdata/ui/blob/master/src/shared/utils/filterUnusedVars.test.ts) unit tests.
* And a [single test](https://github.com/influxdata/ui/blob/master/src/timeMachine/components/SubmitQueryButton.test.tsx#L72) for the submit query button.

For the monitor-ci e2e tests, there was a bad remocal-deploy build (which is why everything failed) -- so restarted that workflow from the beginning. But there are [many oss-e2e failures](https://app.circleci.com/pipelines/github/influxdata/monitor-ci/18627/workflows/9ead852d-0cb2-4f42-9c64-3a118e851c70/jobs/1319255), and I suspect many are also from invalid flux.

Now the question is whether or not it's worthwhile to fix all of these test fixtures.

Maybe instead of running the validation check before each parse()...it's more worthwhile to only check flux queries before they are persisted? So before the task, check, notification, script, or dashboard cell is persisted? What do you think?

**Comment by appletreeisyellow** [comment]
Seems like `is_valid_flux()` doesn't give a pass for the queries generated by the old data explorer, see this commit (https://github.com/influxdata/ui/commit/a34f37424fc2617c8d426f9e4b7f3a46e6f13dbe) in the draft PR https://github.com/influxdata/ui/pull/6467

Here is a failure on my local machine:

https://user-images.githubusercontent.com/14298407/211350092-9bcbd056-2128-450e-bc8d-2ffeee6fc1ec.mov


I haven't look deep into why. I'm guessing we either need to update the `is_valid_flux()` in flux-lsp, or update the query builder in the old data explorer. 

Considering we are moving away from the old data explorer and de-emphasizing flux, what is the priority of this issue?

**Comment by gavincabbage** [comment]
Will timebox some pairing to investigate this issue. If no quick solution is found we'll leave the use of `parse` in old Data Explorer.

**Comment by wiedld** [comment]
Paul Hummer removed some of the invalid uses of `parse()` (quite correctly, I might add). So the main point is to make sure that we have valid flux, BEFORE we persisted that flux in the backend.

Therefore, let's re-define the scope of this ticket. Flux is persisted here:
* scripts crud endpoint
* tasks crud endpoint
* checks crud endpoint
* notifications crud endpoint


 Let's make sure `is_valid_flux()` is run before persistence.

**Comment by appletreeisyellow** [comment]
The `is_valid_flux()` function keeps returning false for valid flux queries. Here is what I tried:

1. Console the result of `is_valid_flux()` in the function `handleSaveScript` in file SaveAsScript.tsx. [Here](https://github.com/influxdata/ui/pull/6467/commits/667685cd3880c76b1d063a02a185ac238ea411b1) is an example.

2. Compose a flux query either by auto composition or manual input. Here is an example flux:

```
from(bucket: "sample_data")
    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
    |> filter(fn: (r) => r._measurement == "average_temperature")
```

3. Click `SAVE` button and you will see the evaluation of `is_valid_flux()` returns false for valid flux queries. 

Next step:

We might want to enhance the `is_valid_flux()` function on the flux-lsp side in order to continue the usage of it in ui.

**Comment by wiedld** [comment]
As @appletreeisyellow already figured out (I'm just documenting here) -- it's the lack of the extern, defining the `v.<variableName>` which is causing the validation failure. Therefore, we just need to provide the extern within the validation check.
