### ISSUE TITLE
Single Stat Graph won't allow strings (previously it would)

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#645]
### Steps to Reproduce
1. Go to Data Explorer and select single stat graph
1. Write a query that creates a string value
    1. I used `defbuck` -> `docker_container_status` -> `container_id` and `last` as the aggregate query function
1. observe error

![Screen Shot 2021-02-08 at 6 18 18 PM](https://user-images.githubusercontent.com/146112/107306640-15200700-6a3a-11eb-9b55-1d014ae2b215.png)

### Context for Bug Squasher
When I (Bucky) was exploring this, I checked around this line: https://github.com/influxdata/ui/blob/master/src/visualization/components/View.tsx#L48-L51.

I logged out the values of `hasResult` and `result?.table`. They were initially `false` and `undefined` until the very last render, when they were the correct values. By this time, the error message had already been rendered on the screen. That was as far as I was able to get before packing it up for the night.

**Comment by drdelambre** [comment]
closed by https://github.com/influxdata/ui/pull/649
