### ISSUE TITLE
Update New Script Editor Toggle and Feedback Link/Survey

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#6461]
Now that the new Script Editor is going to be the new default editor as part of IOx, we want to update the text and boolean to reflect this.  So we want to make the following changes:

- [x] Change the text "Try new Script Editor" to "Switch to old Data Explorer"
- [x] Reverse the On/Off for the toggle as "ON" should now be the old Data Explorer and "Off" should be the New Script Editor https://github.com/influxdata/ui/pull/6480
- [x] Remove the "Provide Feedback" Link as that is no longer being monitored https://github.com/influxdata/ui/pull/6469 https://github.com/influxdata/idpe/pull/16882
- [x] ~~Remove the trigger of survey asking why it is being turned off (Denise will know the details on this)~~ This survey is never implemented FYI https://github.com/influxdata/ui/issues/6216

This change can be for all users of all orgs (not just IOX orgs) and can happen before Jan 31, but we do want to give Customer Success the heads-up when we think the change is going to go live.

Key AC:  The user's current setting, if they have toggled this should retain.  Not the display to still say the old text; but if they had not switched to the New Data Explorer (their toggle was off), their toggle should now be "On" for "Switch to old Data Explorer"; and vice versa.

**Comment by appletreeisyellow** [comment]
@garylfowler There is a PR ready to close this issue. Once you give Customer Success the heads-up, I'll merge the PR and the change is going to go live.
