### ISSUE TITLE
SPIKE:  Explore Query via Native SQL

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#6479]
This is a spike to determine feasibility and options for updating the Cloud UI to make calls directly to IOx in the SQL Editor instead of encapsulating the SQL query in a Flux function and calling flux.

The original decision to encapsulate the Query and utilize a flux function was made for  speed of implementation; it was also made before the decision to background flux.  

As we enable 3rd party tooling via FlightSQL, etc - the output format may then be inconsistent with what is received from the flux level.  In addition, queries may have at least a tiny bit of overhead from this level - so it makes sense to do an investigative spike to see what other options could be possible, and if they are desirable options.

The spike objective would be to determine what options would be available for doing IOx queries from the UI (like using FlightSQL in the way a 3rd party app might or calling the same APIs that the flux level currently does after extracting the SQL statement from the flux statement) and providing pros and cons to each approach in comparison with the current method.

**Comment by hansenreid** [comment]
@garylfowler is there any push for this still? If not, I will close out the issue.

**Comment by garylfowler** [comment]
I believe at least part of the work to do this has been done already - so you can definitely close this out.
