### ISSUE TITLE
Directed Region Selection

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#6499]
## User Story

<p></p>

As a service provider, I want to show my users only the options that I am offering during the sign\-up process so that it makes the process easier for them\.

<p></p>

## Acceptance Criteria

<p></p>

- During the time period where we are only support AWS East and EU Central \(until we move the other regions over\) from IOx, the user will only see these two region options \(with no provider selection\)

- UI Will follow the attached FIGMA design

<p></p>

## Notes

<p></p>

- UI Design:  [https:\/\/www\.figma\.com\/file\/Ry1K1Ez18WSEvIvUZG1OD4\/IOx?node\-id=209%3A1312&t=hAk4PaKKfz8rTpFG\-1](https://www.figma.com/file/Ry1K1Ez18WSEvIvUZG1OD4/IOx?node-id=209%3A1312&t=hAk4PaKKfz8rTpFG-1)

- Note the word "name" has been added to the Account and Organization boxes in this design

- Map Images Attached

<p></p>

**Comment by influx-product-manager** [comment]
Link to feature: https://influxdata.productboard.com/feature-board/planning/features/17509297

**Comment by alejom99** [comment]
Even though the design looks great, it won't fit on how the change was implemented. The regions being displayed in the page are dynamic based on the `iox_region = true/false` attribute that was added to our clusters configuration. So, as soon as we convert another region to IOx, we will have to re-work this page. I don't think having to refactoring the page every time we introduce a new cluster adds any value.

**Comment by hansenreid** [comment]
Closing as not planned.
