### ISSUE TITLE
Add "IOx" Designator to Version Number

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#6533]
## User Story

<p></p>

As a customer support representative, I want to be able to find out if the user I am trying to help is using the IOx version of InfluxDB Cloud or if they are on TSM so I know what options should be available to them; so I want a designator next to the version on my home page that will show this\.

<p></p>

## Acceptance Criteria

<p></p>

- The word "IOx" will be added to the right of the version number on the home page; the whole version string \(including the new IOX wording\)  will be centered in the column for orgs that are on IOx

- No IOx will be listed for orgs that are still on TSM

## 

<p></p>

<p></p>

<p></p>

**Comment by influx-product-manager** [comment]
Link to feature: https://influxdata.productboard.com/feature-board/planning/features/17702551

**Comment by garylfowler** [comment]
See non-centered example (center it please) in bottom right of attached image:

<img width="1273" alt="IOx_In_Version" src="https://user-images.githubusercontent.com/97983559/214944104-65709bb2-81ee-4612-a3fd-98a040b65f34.png">

**Comment by garylfowler** [comment]
Update:  Use "InfluxDB IOx" instead of "IOx".
