### ISSUE TITLE
Write tests to cover incident inc-ui-rendering-probl-6022bdba scenarios.

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#656]
https://github.com/influxdata/ui/pull/648 -- Reenable tables
https://github.com/influxdata/ui/pull/649 -- Reenable strings for single stat

Write unit tests and/or E2E tests to cover fixes in PRs above.

To reproduce:
#648 -- Create a table and drop the _values column.  Ensure that the table renders without error
#649 -- Create a single stat plot with a string _value.  Ensure that the table renders without error

**Expected behavior:**
Tables and Single Stat plots render without error.

**Actual behavior:**
Table without _value column and Single Stat with string value displays an error.

**Environment info:**
All Cloud env in Production, Tools

The PRs listed above have FIXED the issue.  Please create tests to validate the same scenarios so testing will catch future problems.

**Comment by TCL735** [comment]
Too old. No further action needed.
