### ISSUE TITLE
Get e2es working on iox

### ISSUE THREAD

**Issue by wiedld** [influxdata/ui#6562]
Follow up to the excellent repair job (to get our iox e2es running again). Here are all the [skipped tests](https://github.com/influxdata/ui/pull/6561).

Please update below as you grab a test to enable.
Please screenshot a passing `yarn test:e2e:remocal:iox` for the test fixed!

## Fixes done/in-progress:
- [x] cypress/e2e/shared/editor.test.ts  :hamster: DLW  
- [x] cypress/e2e/cloud/helpBar.test.ts  📋 BL
- [x] cypress/e2e/cloud/communityTemplates.test.ts    BL
- [x] cypress/e2e/cloud/dashboardsView.test.ts :hamster: DLW
- [x] cypress/e2e/shared/adaptiveZoom.test.ts :hamster: DLW
- [x] cypress/e2e/shared/annotations.band.test.ts :hamster: DLW
- [x] cypress/e2e/shared/annotations.range.test.ts :hamster: DLW
- [x] cypress/e2e/shared/annotations.singlestat.test.ts :hamster: DLW
- [x] cypress/e2e/shared/annotations.xy.test.ts :hamster: DLW
- [x] cypress/e2e/shared/checks.test.ts  📋 BL
- [x] cypress/e2e/shared/dashboardsIndex.test.ts :hamster: DLW
- [x] cypress/e2e/shared/dashboardsRefresh.test.ts :hamster: DLW
- [x] cypress/e2e/shared/dashboardsVariables.test.ts :hamster: DLW
- [x] cypress/e2e/shared/dashboardsView.test.ts 📋 CY + :hamster: DLW
- [x] cypress/e2e/shared/legends.test.ts - BOCO
- [x] cypress/e2e/shared/loadDataSources.test.ts 📋 BOCO
- [x] cypress/e2e/shared/nav.test.ts - :hamster: DLW
- [x] cypress/e2e/shared/notificationEndpoints.test.ts  📋 BL
- [x] cypress/e2e/shared/notificationRules.test.ts 📋  BOCO
- [x] cypress/e2e/shared/queryBuilder.test.ts 📋 CY
- [x] cypress/e2e/shared/scriptQueryBuilder.flux.test.ts 📋 CY
- [x] cypress/e2e/shared/scriptQueryBuilder.results.test.ts 📋 CY
- [x] cypress/e2e/shared/scriptQueryBuilder.sql.test.ts 📋 CY
- [x] cypress/e2e/shared/simpleTable.test.ts 📋 CY 
- [x] cypress/e2e/shared/tasks.test.ts 📋 BOCO
- [x] cypress/e2e/shared/variables.test.ts  📋 BL

~~The following `explorer` tests need some functions (like `scriptsLoginWithFlags()`) from [this PR](https://github.com/influxdata/ui/pull/6540), so work on them after this PR is merged.~~ No need to wait since we can just use the existing function `cy.setFeatureFlags()` for the following tests
- [x] cypress/e2e/cloud/explorer.test.ts 📋 CY
- [x] cypress/e2e/shared/explorer.queries.graphs.test.ts 📋 CY
- [x] cypress/e2e/shared/explorer.test.ts 📋 CY
- [x] cypress/e2e/shared/explorerVisualizations.test.ts 📋 CY

**Comment by wdoconnell** [comment]
Before we close this out, let's run a search for `.skip` in the codebase and see if there is anything we skipped within the last two weeks that should be unskipped.

**Comment by wdoconnell** [comment]
Closing this, as all tasks are now complete.
