### ISSUE TITLE
SQL editor issues with 'Display Static Legend'

### ISSUE THREAD

**Issue by jdstrand** [influxdata/ui#6598]
In the SQL editor, I noticed a couple of things regarding the 'Display Static Legend':
1. if the editor is about 50% the window height or so, when you click 'Show' to display the static legend, it is not viewable until I make the editor vertically smaller. This might be because of '2', below
2. The 'Height' field under Display Static Legend seems to default to 5%. Even with the editor closed, that isn't a usable height (see no entries, just the header). Maybe 15% is a better default?
3. when sliding the Height, the displayed graph gets resized, but the contents get messed up until I run 'Run' again

I'm told that these issues are in the legacy/shared code. I wonder if setting the default height to 15% would be enough to close 1 and 2 with minimal effort? 3 can be worked around by clicking 'Run' again (though one has to know to do that).

**Comment by wiedld** [comment]
The actual default per `STATIC_LEGEND_HEIGHT_RATIO_NOT_SET` is zero. can update to 15%, assuming is okay with @wdoconnell too.
