### ISSUE TITLE
Feature Request: Task ID in Task tab

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/ui#660]
Experience/Scenario: I want to create a check to monitor a mission critical task and be alerted when it fails. I can use the data in the "_tasks" bucket to create this task. However, I don't know what my task ID is, so I can't filter for failed runs from that bucket. I have to click on the "export task" button to find the task ID in the UI. 
<img width="1559" alt="Screen Shot 2021-02-10 at 11 52 01 AM" src="https://user-images.githubusercontent.com/30506042/107551262-a6f15680-6b97-11eb-8782-eb77c74e9e31.png">

Expectation: Ability to view the task ID under the task name in the task tab. 

Thank you!

**Comment by russorat** [comment]
Let's have the same experience we have in the buckets page:

![image](https://user-images.githubusercontent.com/4805997/110369638-87ffac00-7fff-11eb-81a5-92d0c1316a18.png)
