### ISSUE TITLE
Notebooks: Column mapping panel

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#662]
Add a panel that can do these things to any of the columns:
- drop a column from the result -https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/built-in/transformations/drop/#columns
- rename a column - https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/built-in/transformations/rename/
- cast the type of a column into something else
This list shouldn't be considered exhaustive, we just want something that'll allow us to do explicit base level transformations against tabular data, go nuts

**Comment by mnorriswalker** [comment]
Note to self: Possibly look at including the map function (https://docs.influxdata.com/influxdb/cloud/reference/flux/stdlib/built-in/transformations/map/)

**Comment by mnorriswalker** [comment]
Deprioritizing for flux and tasks in notebooks
