### ISSUE TITLE
Notebooks: Introduce Side Effects

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#663]
we have a run vs preview button. the intent of this pattern is to ensure that the user doesn't make any permanent changes to their data / infrastructure while solving a problem, or exploring their database. If your notebook has a toBucket on it, but you're iterating on a visualization within the notebook, you dont want to be writing all that data. Or say it's an email notification in the same circumstance. No one wants a million "CRITICAL INFRASTRUCTURE CRUMBLING [testing]" emails to show up in their inbox.

But we don't have a clear way of illustrating to the user what a side effect is in our system and how they're controlled.

For many following the query -> visualization pattern... they wont ever need to know this distinction, and the run vs preview button is arbitrary.

...until they add another panel

then we've built up a bad habit / mental model within the user that these distinctions are meaningless, and they send a hundred emails directly to the CTO, find themselves looking for a job in a pandemic, really swearing our name. all because we failed to teach them that distinction.

so.. a proposal, stab in the dark, lets see how it tests, is to remove the distinction until the user adds a panel that might introduce a side effect. We'll have to change some code interfaces to explicitly expose which panels might have side effects, but the ux will look something like....

one button, where our current run vs preview button lives, that says "Run"
... if a user selects a panel that creates side effects ....
an unselected checkbox appears underneath that button, with some text that says "enable running with side effects". dont sweat the text too much, people will hate whatever it is, then someone from docs will come save us.
any time i navigate to a notebook, it should default into being unselected, so dont go adding it to the data structure.

we can iterate on how to expose this information to the user on panel creation / browsing in another ticket (eg: all panels that create side effects are purple instead of grey, and you can hover over a special corner to see what it does when you run with sideeffects, idk.. spit balling). This one is just for updating that button and dropping in those data schema contract changes

**Comment by barbaranelson** [comment]
I really like the idea of only introducing the concept of preview versus run when the user gets to a cell where it might warrant a change in behavior.  I'm not entirely sure that 'writing to a bucket' should be seen as a side-effect, but we can debate that separately.  I suspect the text may need to be specific to each cell type -e.g. 'Just previewing or do you want to write to the bucket?' or 'Just previewing or do you want to send the email?'.  I don't think the users will understand the generic concept of something having a side-effect, particularly if it is the intended purpose of the cell - e.g. the cell is to write to a bucket, so it isn't a side-effect that it actually writes to the bucket.

**Comment by juliajames12** [comment]
@mnorriswalker and I propose we defer this until we discover a user problem. Right now, the data in Google Analytics shows people can switch between Run/Preview and we see a nice ratio of Previews to Runs. Low estimate: April 1-26, 2,064 Previews vs. 286 Runs

We're also breaking out a Side Menu where we will have more space for options per notebook cell. Once that exists, and there's a validated user problem, then we can add Run (or other side effects) at the cell-level.

@jzahnd @russorat move out of Triaging?

**Comment by russorat** [comment]
i'm fine to defer for now.

**Comment by barbaranelson** [comment]
Closing this out as we have removed the 'preview' option for now. At some stage, the flux API will allow us to enable/disable side-effects and when that happens, we can revisit the UI.
