### ISSUE TITLE
Save ordering of variables in a dashboard

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#667]
**Proposal:**
In the Data Explorer, when any Dashboard is viewed, the display order of the variables and their value inputs should be saved.

**Current behavior:**
In the Data Explorer, when any Dashboard is viewed, the list of variables for that Dashboard can rearranged.  However, when a user logs out, any reordering of the displayed list is not retained.

**Desired behavior:**
In the Data Explorer, when any Dashboard is viewed, the list of variables for that Dashboard can rearranged.  Save the display order with each Dashboard, so that after log out, the reordering of the displayed list is retained.

**Use case:**
InfluxData Support team has requested this.  They work with dashboards that contain many variables, and would like to have more frequently changed variables to be grouped together.
Another use case, order of variables displayed may matter.  For example, if one has a variable distance and another variable units ie km|mi, it would make sense for units to always come right after distance.
Another use case is where one variable dynamically populates another variable. In that situation, the dynamically generate variable should always come right after the variable that it’s based off of. Like a clusters variable and a hosts variable in the selected cluster.

**Comment by drdelambre** [comment]
all ordering is currently being handled in local storage. this will require a new api to allow the order to persist.
