### ISSUE TITLE
when pressing the 'data' button,web interface crushes.

### ISSUE THREAD

**Issue by tornshaw** [influxdata/ui#6685]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. ...
2. ...
3. ...

**Expected behavior:**

**Actual behavior:**

**Visual Proof:**

![898a8d676f18a167b2fcb34cc184d35](https://user-images.githubusercontent.com/39145280/236100019-e793b2a2-3744-4803-9416-3c8f3b547c8e.png)

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by zoesteinkamp** [comment]
Let me know if this is still an issue. Closing for now, please reopen if you have some more details.
