### ISSUE TITLE
Cell w/Banded Graph Will Not Render After Saving

### ISSUE THREAD

**Issue by reidkaufmann** [influxdata/ui#6805]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. "Add a cell"
2. Select data to graph
3. Choose Banded visualization - set Upper and Lower Column (use one or more lines; I didn't try all three)
4. Observe that graph is rendered in edit mode
5. Save
6. Dashboard shows error and will not render, even if you return to edit mode (configure)

**Expected behavior:**
After saving, I expect the same thing I saw in edit mode to be rendered. WYSIWYG

**Actual behavior:**
Error message that prompted me to file this defect

**Visual Proof:**
Creating new cell:
![image](https://github.com/influxdata/ui/assets/73494261/3644998c-df06-4b7d-89b5-d04f8bda276f)

Saved:
![image](https://github.com/influxdata/ui/assets/73494261/bf640f19-1b90-4c8f-8023-77a7ede6235c)

Editing:
![image](https://github.com/influxdata/ui/assets/73494261/5ef59dab-7329-4b03-92ec-e51aa0dd605a)

## About your environment

**Environment info:**
Cluster: `prod101-us-east-2`  https://us-east-1-2.aws.cloud2.influxdata.com
Org: 5d59ccc5163fc318 "InfluxData"  (yes, I named it that generically)

Query:
```
data = from(bucket: "cam")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "latency_ms")
  |> filter(fn: (r) => r["_field"] == "sql_128row_query")
  |> filter(fn: (r) => (r["cluster"] == "eu-central-1-1.aws.cloud2.influxdata.com" and r["src"] == "pa-cam-vm3"))
  
data |> aggregateWindow(every: 20m, fn: max) |> yield(name: "us_max")
data |> aggregateWindow(every: 20m, fn: mean) |> yield(name: "us_mean")
```

Client info
```
Linux 6.2.0-32-generic x86_64
Ubuntu 23.04
Firefox 117.0.1 (64-bit)
```

**Comment by appletreeisyellow** [comment]
Browser console shows that the bug comes from giraffe, some where near [this line](https://github.com/influxdata/giraffe/blob/776f0eab7aebeb4efacb302f0df0487caba7e26c/giraffe/src/utils/legend/band.ts#L56)

![Screenshot 2023-09-15 at 9 07 01 AM](https://github.com/influxdata/ui/assets/14298407/c756d537-9472-48b1-8cf5-2fe2dbee1cc1)

Chatted off line with @reidkaufmann, a work around is to use "Graph" instead of "Band"

**Comment by garylfowler** [comment]
I would close it as "will not fix".
