### ISSUE TITLE
Nicht autorisiert {"log_id": "0kfcYVl0000", "error": "Sitzung nicht gefunden"}

### ISSUE THREAD

**Issue by Anton05032011** [influxdata/ui#6814]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. ...
2. ...
3. ...

**Expected behavior:**

**Actual behavior:**

**Visual Proof:**

## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

2023/10/04 21:22:30 | stdout | 2023-10-04T19:22:30.747039Z info Nicht autorisiert {"log_id": "0kfcYVl0000", "error": "Sitzung nicht gefunden"}
-- | -- | --
2023/10/04 21:08:15 | stdout | 2023-10-04T19:08:15.927538Z info Löschprüfung der Aufbewahrungsrichtlinie (Ende) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "Ende", "op_elapsed": "0.123ms"}
2023/10/04 21:08:15 | stdout | 2023-10-04T19:08:15.927445Z info Löschprüfung der Aufbewahrungsrichtlinie (Start) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "start"}
2023/10/04 20:38:15 | stdout | 2023-10-04T18:38:15.942770Z info Löschprüfung der Aufbewahrungsrichtlinie (Ende) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "Ende", "op_elapsed": "15.580ms"}
2023/10/04 20:38:15 | stdout | 2023-10-04T18:38:15.942694Z info Löschprüfung der Aufbewahrungsrichtlinie (Start) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "start"}
2023/10/04 20:08:15 | stdout | 2023-10-04T18:08:15.927622Z info Löschprüfung der Aufbewahrungsrichtlinie (Ende) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "Ende", "op_elapsed": "0.121ms"}
2023/10/04 20:08:15 | stdout | 2023-10-04T18:08:15.927527Z info Löschprüfung der Aufbewahrungsrichtlinie (Start) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "start"}
2023/10/04 19:38:15 | stdout | 2023-10-04T17:38:15.942448Z info Löschprüfung der Aufbewahrungsrichtlinie (Ende) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "Ende", "op_elapsed": "15.246ms"}
2023/10/04 19:38:15 | stdout | 2023-10-04T17:38:15.942382Z info Löschprüfung der Aufbewahrungsrichtlinie (Start) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "start"}
2023/10/04 19:08:15 | stdout | 2023-10-04T17:08:15.927387Z info Löschprüfung der Aufbewahrungsrichtlinie (Ende) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "Ende", "op_elapsed": "0.177ms"}
2023/10/04 19:08:15 | stdout | 2023-10-04T17:08:15.927282Z info Löschprüfung der Aufbewahrungsrichtlinie (Start) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "start"}
2023/10/04 18:38:15 | stdout | 2023-10-04T16:38:15.927781Z info Löschprüfung der Aufbewahrungsrichtlinie (Ende) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "Ende", "op_elapsed": "0.219ms"}
2023/10/04 18:38:15 | stdout | 2023-10-04T16:38:15.927644Z info Löschprüfung der Aufbewahrungsrichtlinie (Start) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "start"}
2023/10/04 18:08:15 | stdout | 2023-10-04T16:08:15.927964Z info Löschprüfung der Aufbewahrungsrichtlinie (Ende) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "Ende", "op_elapsed": "0.155ms"}
2023/10/04 18:08:15 | stdout | 2023-10-04T16:08:15.927843Z info Löschprüfung der Aufbewahrungsrichtlinie (Start) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "start"}
2023/10/04 17:38:15 | stdout | 2023-10-04T15:38:15.927975Z info Löschprüfung der Aufbewahrungsrichtlinie (Ende) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "Ende", "op_elapsed": "0.127ms"}
2023/10/04 17:38:15 | stdout | 2023-10-04T15:38:15.927880Z info Löschprüfung der Aufbewahrungsrichtlinie (Start) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "start"}
2023/10/04 17:31:27 | stdout | 2023-10-04T15:31:27.238603Z info Nicht autorisiert {"log_id": "0kfcYVl0000", "error": "token required"}
2023/10/04 17:08:15 | stdout | 2023-10-04T15:08:15.927295Z info Löschprüfung der Aufbewahrungsrichtlinie (Ende) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "Ende", "op_elapsed": "0.115ms"}
2023/10/04 17:08:15 | stdout | 2023-10-04T15:08:15.927226Z info Löschprüfung der Aufbewahrungsrichtlinie (Start) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "start"}
2023/10/04 16:38:15 | stdout | 2023-10-04T14:38:15.926956Z info Löschprüfung der Aufbewahrungsrichtlinie (Ende) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "Ende", "op_elapsed": "0.101ms"}
2023/10/04 16:38:15 | stdout | 2023-10-04T14:38:15.926898Z info Löschprüfung der Aufbewahrungsrichtlinie (Start) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "start"}
2023/10/04 16:08:15 | stdout | 2023-10-04T14:08:15.927938Z info Löschprüfung der Aufbewahrungsrichtlinie (Ende) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "Ende", "op_elapsed": "0.109ms"}
2023/10/04 16:08:15 | stdout | 2023-10-04T14:08:15.927871Z info Löschprüfung der Aufbewahrungsrichtlinie (Start) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "start"}
2023/10/04 15:38:15 | stdout | 2023-10-04T13:38:15.927160Z info Löschprüfung der Aufbewahrungsrichtlinie (Ende) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "Ende", "op_elapsed": "0.140ms"}
2023/10/04 15:38:15 | stdout | 2023-10-04T13:38:15.927053Z info Löschprüfung der Aufbewahrungsrichtlinie (Start) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "start"}
2023/10/04 15:08:15 | stdout | 2023-10-04T13:08:15.927240Z info Löschprüfung der Aufbewahrungsrichtlinie (Ende) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "Ende", "op_elapsed": "0.085ms"}
2023/10/04 15:08:15 | stdout | 2023-10-04T13:08:15.927180Z info Löschprüfung der Aufbewahrungsrichtlinie (Start) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "start"}
2023/10/04 14:38:15 | stdout | 2023-10-04T12:38:15.927024Z info Löschprüfung der Aufbewahrungsrichtlinie (Ende) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "Ende", "op_elapsed": "0.170ms"}
2023/10/04 14:38:15 | stdout | 2023-10-04T12:38:15.926899Z info Löschprüfung der Aufbewahrungsrichtlinie (Start) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "start"}
2023/10/04 14:08:15 | stdout | 2023-10-04T12:08:15.927696Z info Löschprüfung der Aufbewahrungsrichtlinie (Ende) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "Ende", "op_elapsed": "0.176ms"}
2023/10/04 14:08:15 | stdout | 2023-10-04T12:08:15.927597Z info Löschprüfung der Aufbewahrungsrichtlinie (Start) {"log_id": "0kfcYVl0000", "service": "Aufbewahrung", "op_name": "retention_delete_check", "op_event": "start"}
2023/10/04 13:46:53 | stdout | 2023-10-04T11:46:53.238217Z Fehler API-Fehler aufgetreten {"log_id": "0kfcYVl0000", "handler": "Sitzung", "error": "Unbefugter Zugriff"}
2023/10/04 13:42:48 | stdout | 2023-10-04T11:42:48.391568Z info Nicht autorisiert {"log_id": "0kfcYVl0000", "error": "Autorisierung nicht gefunden"}
2023/10/04 13:41:06 | stdout | 2023-10-04T11:41:06.851277Z info Nicht autorisiert {"log_id": "0kfcYVl0000", "error": "Autorisierung nicht gefunden"}
2023/10/04 13:39:26 | stdout | 2023-10-04T11:39:26.383545Z info Nicht autorisiert {"log_id": "0kfcYVl0000", "error": "Autorisierung nicht gefunden"}
2023/10/04 13:39:01 | stdout | 2023-10-04T11:39:01.102833Z info Nicht autorisiert {"log_id": "0kfcYVl0000", "error": "Sitzung nicht gefunden"}
2023/10/04 13:38:17 | stdout | 2023-10-04T11:38:17.375979Z info Beginnend mit {"log_id": "0kfcYVl0000", "service": "Telemetrie", "interval": "8h"}
2023/10/04 13:38:17 | stdout | 2023-10-04T11:38:17.375995Z info Listening {"log_id": "0kfcYVl0000", "service": "tcp-listener", "transport": "http", "addr": ":8086", "port": 8086}
2023/10/04 13:38:16 | stdout | 2023-10-04T11:38:15.928752Z info Konfigurieren des InfluxQL-Anweisungsausführers (Nullen stehen für unbegrenzt). {"log_id": "0kfcYVl0000", "max_select_point": 0, "max_select_series": 0, "max_select_buckets": 0}
2023/10/04 13:38:16 | stdout | 2023-10-04T11:38:15.926878Z info Abfragecontroller starten {"log_id": "0kfcYVl0000", "service": "storage-reads", "concurrency_quota": 1024, "initial_memory_bytes_quota_per_query": 9223372036854775807, "memory_bytes_quota_per_query": 9223372036854775807, "max_memory_bytes": 0, "queue_size": 1024}
2023/10/04 13:38:16 | stdout | 2023-10-04T11:38:15.926730Z info Starten des Precreation-Dienstes {"log_id": "0kfcYVl0000", "service": "shard-precreation", "check_interval": "10m", "advance_period": "30m"}
2023/10/04 13:38:16 | stdout | 2023-10-04T11:38:15.926713Z info Starten des Dienstes zur Durchsetzung der Aufbewahrungsrichtlinie {"log_id": "0kfcYVl0000", "service": "aufbewahrung", "check_interval": "30m"}
2023/10/04 13:38:16 | stdout | 2023-10-04T11:38:15.926678Z info Store öffnen (Ende) {"log_id": "0kfcYVl0000", "service": "storage-engine", "service": "speichern", "op_name": "tsdb_open", "op_event": "Ende", "op_elapsed": "0.082ms"}
2023/10/04 13:38:16 | stdout | 2023-10-04T11:38:15.926597Z info Laden öffnen (start) {"log_id": "0kfcYVl0000", "service": "storage-engine", "service": "speichern", "op_name": "tsdb_open", "op_event": "start"}
2023/10/04 13:38:16 | stdout | 2023-10-04T11:38:15.926577Z info Verdichtungseinstellungen {"log_id": "0kfcYVl0000", "service": "storage-engine", "service": "store", "max_concurrent_compactions": 1, "throughput_bytes_per_second": 50331648, "throughput_bytes_per_second_burst": 50331648}
2023/10/04 13:38:16 | stdout | 2023-10-04T11:38:15.926551Z info Verwenden des Datenverzeichnisses {"log_id": "0kfcYVl0000", "service": "storage-engine", "service": "store", "path": "/var/lib/influxdb2/engine/data"}
2023/10/04 13:38:15 | stdout | 2023-10-04T11:38:15.926399Z info Überprüfung der InfluxDB-Metadaten für frühere Versionen. {"log_id": "0kfcYVl0000", "bolt_path": "/var/lib/influxdb2/influxd.bolt"}
2023/10/04 13:38:15 | stdout | 2023-10-04T11:38:15.258707Z info Geöffnete Ressourcen {"log_id": "0kfcYVl0000", "service": "sqlite", "path": "/var/lib/influxdb2/influxd.sqlite"}

<br class="Apple-interchange-newline">

**Comment by zoesteinkamp** [comment]
Please add more details.
