### ISSUE TITLE
Example code buggy in 'new-user-setup/python' on InfluxDB Cloud Serverless

### ISSUE THREAD

**Issue by pihiandreas** [influxdata/ui#6831]
This issue (2 issues) is related to the quick-start guide on 'new-user-setup/python' in my case running on AWS.

Issue 1 (minor):
Step: 'Execute a SQL Query'
Problem: extra ')' in example Python code

Issue 2:
Step: 'Execute an Aggregate Query'
Problem: the InfluxQL query is broken, not clear what we're trying to achieve.
Error message: '....Error during planning: invalid FROM clause, expected identifier, regular expression or subquery at pos 24...'

##### Relevant URLs
- https://<zone>.aws.cloud2.influxdata.com/orgs/<org>/new-user-setup/python

**Comment by jstirnaman** [comment]
> This issue (2 issues) is related to the quick-start guide on 'new-user-setup/python' in my case running on AWS.
> 
> Issue 1 (minor): Step: 'Execute a SQL Query' Problem: extra ')' in example Python code
> 
> Issue 2: Step: 'Execute an Aggregate Query' Problem: the InfluxQL query is broken, not clear what we're trying to achieve. Error message: '....Error during planning: invalid FROM clause, expected identifier, regular expression or subquery at pos 24...'
> 
> ##### Relevant URLs
> * https://.aws.cloud2.influxdata.com/orgs//new-user-setup/python

@pihiandreas

Thanks for reporting this. There are a few InfluxQL syntax problems in that example. Here's a corrected version of that query:

```python
query = """SELECT mean(count)
FROM "census"
WHERE time > now() - 10m"""
```

- (The reason for the error you're getting): When quoting the table (measurement) name, use double quotes. Single quotes don't work.
- Remove quotes from InfluxQL duration. Durations aren't strings. If using SQL, the interval expression ('10 minutes') would be a string.
- 
I've submitted a PR to fix this example in the InfluxDB UI.
