### ISSUE TITLE
Tasks: Add a button to retry a failed task run

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#685]
It would be really convenient in the UI to have the ability to click a button and retry a failed task run. I'm thinking right next to the "View Logs" button. The link to retry a task is already in the `links` section of the response.

![image](https://user-images.githubusercontent.com/4805997/107805352-1a22d600-6d1a-11eb-9bca-6ee93c714d26.png)

**Comment by barbaranelson** [comment]
@rickspencer3 This feature is now live in prod, if you want to let Nobl9 know.

**Comment by russorat** [comment]
This capability doesn't work. Reopening.

![Kapture 2021-05-20 at 10 17 40](https://user-images.githubusercontent.com/4805997/119021783-b16c7a80-b954-11eb-96cb-3b5b50135d0c.gif)

**Comment by zoesteinkamp** [comment]
interesting, i wonder if there was a swagger change? Let me take a gander russ

**Comment by russorat** [comment]
Also, one enhancement i would make would be that if the retry fails for whatever reason, we should keep the user on the same page, not drop them to the edit task page.

**Comment by hoorayimhelping** [comment]
@russorat can you please make a new ticket for that instead of opening an already closed one?

i'm closing this in favor of this ticket: https://github.com/influxdata/ui/issues/1481
