### ISSUE TITLE
Graph + Single Stat has weird options and inconsistent header labels

### ISSUE THREAD

**Issue by sjwang90** [influxdata/ui#692]
**Graph + Single Stat:** X-axis tick configuration does isn't consistent with the rest. Isn't under it's own heading but under options
![image](https://user-images.githubusercontent.com/32681364/107834376-d72d2680-6d4a-11eb-8b70-3e74fc7660f7.png)

~~**Scatterplot:** has X/Y Tick Prefix/Suffix and no other chart type has it. Is this supposed to be "X Axis Prefix" not Tick?~~
Will remove this "X Prefix" overall - shouldn't exist since X-Axis in these charts is always time

**Comment by sjwang90** [comment]
Just Graph:
![image](https://user-images.githubusercontent.com/32681364/108262388-b6354e80-7119-11eb-8c60-0e4280f0cae7.png)


Band Chart:
![image](https://user-images.githubusercontent.com/32681364/108263252-da455f80-711a-11eb-91f9-e7545786ee07.png)

**Comment by drdelambre** [comment]
i dont understand what is expected here outside of you wanting something changed

**Comment by sjwang90** [comment]
It's just a formatting bug that `Generate X axis tick marks` is under `Options` in the Graph + Single Stat settings. While for other chart types it's under it's own `X-Axis` header.
