### ISSUE TITLE
An InfluxData Error has occurred, please report here

### ISSUE THREAD

**Issue by BernardClabots** [influxdata/ui#695]
---

name: Bug report
about: Create a report to help us improve
title: ''
labels: kind/bug, team/ui
assignees: ''
---Thank you for reporting a bug in InfluxData UI.

- Please ask usage questions on the Influx Community site.
  - https://community.influxdata.com/
- Please add a :+1: or comment on a similar existing bug report instead of opening a new one.
  - https://github.com/influxdata/ui/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+is%3Aclosed+sort%3Aupdated-desc+label%3Akind%2Fbug+
- Please check whether the bug can be reproduced with the latest release.
- The fastest way to fix a bug is to open a Pull Request.
  - https://github.com/influxdata/ui/pulls

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. I run a query on two buckets with similar timestamps and do something with the data including map aggregatewindow truncate and yield
2. I join the two tables
3. Code works, but if I remove yield, I end up here.
4. I noticed that it has nothing to do with removing yield, but it only happens when I do remove yield. It seems to be related to "join". When I do a join on more than 1 column, the issue happens. If I do on just one column (_time) it does not. If I try with a column "zone" were all the points have the same value, it seems to hang forever. Usually, I do a join with a discriminating column (_time) and all the identical column, so that I keep the data without unnecessary duplication of columns.

**Expected behavior:**
remove unneeded trace so I can see what matters to me. Join on several columns and see the magic.

**Actual behavior:**
"an Influxdata error has occured please report here"

**Environment info:**

- System info: CLOUD
- InfluxDB version: 2
- Other relevant environment details: Occurs systematically.
- Version=d743b1fbf6909c75a4f14cfe29aea3765378f2f1

**Config:**
NA

**Logs:**
Include snippet of errors in log.

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

I have the feeling that this error redirects me to the wrong place. I am using influxdata cloud.

**Comment by hoorayimhelping** [comment]
@BernardClabots can you please share the query you're writing please?

**Comment by BernardClabots** [comment]
This is  already handled by Influx Data case 00097197
