### ISSUE TITLE
UI: Add Contact Support link for PAYG users

### ISSUE THREAD

**Issue by bpalani** [influxdata/ui#707]
As a Pay as you go user
When I click on the `Contact Support` link on my Cloud 2 UI
Then: I go to a marketo form where I can add my issue details
And: my org and email are prepopulated

When: I submit the form
Then: the marketo form is sent to `support@influxdata.com`

**Comment by jzahnd** [comment]
@bpalani is this still a priority?

**Comment by wdoconnell** [comment]
This was added in https://github.com/influxdata/ui/pull/4382
