### ISSUE TITLE
Annotations: Add Annotations button

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#730]
### Background
I removed the Add annotation button [here](https://github.com/influxdata/ui/commit/82390639ad3be8d8a4340993890a340e3f543318#diff-2247896cc9fd441f0c090919563197e9050097e94918552cc86f47d98b143ff5L81) because it wasn't really hooked up to a great experience. We want this button to toggle creating annotations. If this button isn't on, clicking on the graph won't create annotations. If it is on, clicking (single-clicking) on the graph will start the annotation creation flow (i.e. it'll launch an overlay)

### Acceptance Criteria
- The `Annotate` button is added back to the `AnnotationsControlBar` and is functional
-  clicking (single click) the `Annotate` button toggles annotate mode, which lets the user annotate the graph by double clicking
  - clicking (single click) on the graph when not in annotate should do the default behavior (which is currently nothing)

- this is for the dashboard. The new button should be in the well that opens when you click on the annotations button

**Comment by russorat** [comment]
to clarify here, we will now have an explicit annotate button in the annotations bar. clicking that annotate button would then allow you to single click on a graph to add an annotation.

there should be no double click behavior for annotations once this is completed.

**Comment by jrenee42** [comment]
to clarify:

when button is on: 

  -a single click on the graph will bring up the 'add annotation' dialog/overlay

 when off:
    -clicking on graph will bpring up the default behavior (currently nothing, correct?)

double clicks won't do anything

@russorat  and @hoorayimhelping

**Comment by hoorayimhelping** [comment]
@jrenee42 I updated the ticket to try to be more precise. But the overall structure is right, the details are slightly off:

> -a single click on the graph will bring up the 'add annotation' dialog/overlay
double clicking, not single clicking.

>double clicks won't do anything
to be more precise: they will revert to default behavior, which is nothing if the graph isn't zoomed. if the graph is zoomed (which you can trigger by clicking and dragging on the graph), double clicking will revert to the original zoom level

**Comment by hoorayimhelping** [comment]
updated once again. it's single clicks not double clicks.
