### ISSUE TITLE
Flows: As a user I can define a bucket output

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#75]
GIVEN that I am editing a flow
WHEN I click the `Insert Cell Button`
THEN I can add a "Output to Bucket" cell

WHEN I add a "Output to Bucket" cell
THEN I can choose a bucket

WHEN I choose a bucket
THEN I can see a dropdown with label "Time" set to `_time`

WHEN I click the time dropdown to change it
THEN I see a dropdown menu with `_time`, `_start`, and `_stop` as options
AND any other columns with type "time"

GIVEN I have a valid bucket and options configured 
WHEN I open the flow again or run the flow
AND the `Run Mode` is set to `Run`
THEN I can see what would have been written to the bucket

GIVEN I have a valid bucket and options configured 
WHEN I open the flow again or run the flow
AND the `Run Mode` is set to `Run with Outputs`
THEN I can see what would have been written to the bucket
AND the data should actually get written to the bucket

This issue is related to https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/influxdb/19694

### Designs

[Design Mock of Cell](https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=940%3A1117)
[Design Mock of option in Insert Cell menu](https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=940%3A759)

### Technical Notes:

- this would add a new cell type for the user to select an output bucket
- we don't do this on a schedule, that comes when you actually create the task
- add field and value to the cell (depends on the way to is used)
- we are building a `to()` function cell https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/outputs/to/

**Comment by mnorriswalker** [comment]
Allow one-time Output to Bucket not on a schedule (if scheduled it's Publish as a Task)

**Comment by drdelambre** [comment]
the work here doesn't involve adding a button to switch between "run with outputs" modes.. that is captured in:
influxdata/influxdb#19694

**Comment by Asalem1** [comment]
Gonna mark this as closed
