### ISSUE TITLE
"all buckets" token doesn't excludes system buckets "_monitoring" and "_tasks"

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/ui#752]
Using OSS 2.0.4.
When creating a token, if you scope it to all buckets, the token excludes the system buckets "_monitoring" and "_tasks". 
If you want to scope a token to specific buckets, you can't select "_monitoring" and "_tasks" because they don't exist in the menu. 

<img width="763" alt="Screen Shot 2021-02-26 at 1 25 11 PM" src="https://user-images.githubusercontent.com/30506042/109345797-4d935380-7836-11eb-95d9-64871b2daa60.png">

Thank you. :)

**Comment by gavincabbage** [comment]
Did a quick search and I believe the system buckets are being filtered from the list here https://github.com/influxdata/ui/blob/a26f29292fb3e0a9f09c74e2e76677f5b3cf9a6b/src/authorizations/components/BucketsTokenOverlay.tsx#L110

**Comment by drdelambre** [comment]
ugh.. we also allow sample data buckets in that list!
