### ISSUE TITLE
Version=65a98d8d943b920c90d5e5da594308c9fd0966e9

### ISSUE THREAD

**Issue by germancorbetta** [influxdata/ui#758]
---

name: Bug report
about: Create a report to help us improve
title: ''
labels: kind/bug, team/ui
assignees: ''
---Thank you for reporting a bug in InfluxData UI.

- Please ask usage questions on the Influx Community site.
  - https://community.influxdata.com/
- Please add a :+1: or comment on a similar existing bug report instead of opening a new one.
  - https://github.com/influxdata/ui/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+is%3Aclosed+sort%3Aupdated-desc+label%3Akind%2Fbug+
- Please check whether the bug can be reproduced with the latest release.
- The fastest way to fix a bug is to open a Pull Request.
  - https://github.com/influxdata/ui/pulls

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. ...
2. ...
3. ...

**Expected behavior:**
Describe what you expected to happen.

**Actual behavior:**
Describe What actually happened.

**Environment info:**

- System info: Run `uname -srm` and copy the output here
- InfluxDB version: Run `influxd version` and copy the output here
- Other relevant environment details: Container runtime, disk info, etc

**Config:**
Copy any non-default config values here or attach the full config as a gist or file.

**Logs:**
Include snippet of errors in log.

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by drdelambre** [comment]
any more context on this one @germancorbetta? what'd you see break?

**Comment by germancorbetta** [comment]
Hi Alex,

The error that I remember was related to the notification rules creation.

I used to have "is equal to = CRITICAL" and then changed to "change from"
approach.

And as far as I remember, I started trying to put OK -> CRIT and another
alarm from CRIT-> OK and I saw an error while trying to put first the
destination status, and then the source status.

Playing a little bit with the OK --> CRIT I was able to raise the error
last time.

I don´t have much more to add really.

Regards,
Germán

**Comment by kristinarobinson** [comment]
Are you able to reproduce this?  If you can, please screenshot the error that occurs, and detail the steps you took to reproduce.

**Comment by germancorbetta** [comment]
Hi Kristina,

I´ve done some quick tests and it´s working fine now. I have been unable to
reproduce it so feel free to close the ticket.

Have a wonderful weekend.

Regards,
Germán

**Comment by barbaranelson** [comment]
Closing as no longer reproducible.
