### ISSUE TITLE
Chore: Remove Unused Parsers

### ISSUE THREAD

**Issue by asalem1** [influxdata/ui#76]
This is the final item of a multi-issue epic that spans unifying the parsers in the UI to use 1 parser as the source of truth.

Once we can successfully determine that the unification work is complete we should remove the following parsers from the UI:

[ ] parseResponse from `src/shared/parsing/flux`
[ ] fromFluxLegacy from `src/shared/utils/fromFlux.legacy.ts`
[ ] fromFluxLegacy from `src/shared/utils/fromFlux.ts`

we should also remove any & all feature flags associated with these.

We should also consider adding the tests that exist for these as tests for the current `fromFlux` function in giraffe (and whatever data transformation layer we are going to use for the RawDataTable

**Comment by jzahnd** [comment]
@asalem1 is this still relevant?
