### ISSUE TITLE
Annotations: Add explanation of Single Click mechanics to the Graph Tips overlay

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#760]
### Background

The Graph Tips overlay lists the ways you can interact with the graph. We'll want to add the single click annotations interaction.
![Screen Shot 2021-03-02 at 9.26.45 AM.png](https://images.zenhubusercontent.com/5c33b08d24dda4712ef4ae10/1ef26179-dded-4c49-8761-5cfc32cf1628)

Text should be:

- `Single Click: Annotate the Graph`

### Acceptance Criteria
- There's a tip for single clicking in annotations mode
  - The tip is only visible if `annotations` is flagged on

**Comment by russorat** [comment]
i don't think this is needed if we have the button to add an annotation.

**Comment by russorat** [comment]
Can we add:

Variables allow you to build dynamic graphs
Annotations help give context to events

Is it possible to link each of those to docs pages? Like this for https://docs.influxdata.com/influxdb/cloud/visualize-data/variables/ and the annotations docs when it's ready?
