### ISSUE TITLE
What time is it?

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#768]
when we have a graph that spans over a large period of time, and the dashboard / time machine is set to displaying in local time, the meridian isn't included when generating axis ticks in locales that favor 12hr time periods (like the US). so i dont know if this graph is showing 4am or 4pm, and that's kind of important info to know

<img width="1277" alt="Screen Shot 2021-03-03 at 11 51 05 AM" src="https://user-images.githubusercontent.com/1434802/109869619-f7e7ee00-7c1d-11eb-9881-836752520d0f.png">

**Comment by TCL735** [comment]
So there are 2 issues here.

1. Meridiem is not selected. It should be (passed as part of the time format with letter 'a').

2. "**hour12**" is not included which defaults to `true` in Giraffe. If a 24 hour clock is desired, "**hour12**" must be explicitly passed in as `false`
