### ISSUE TITLE
Allow text entry in to UI variable selectors as well as drop-downs

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#774]
@8none1 commented on [Thu Nov 26 2020](https://github.com/influxdata/idpe/issues/9284)

A common use case for UI variables is allow dashboards to show information about a specific thing.  

For example:

![image](https://user-images.githubusercontent.com/6552931/100337060-d5b35400-2fce-11eb-9d1b-09a3ad2332ba.png)

In this [dashboard](https://influxdb.aws.influxdata.io/orgs/844910ece80be8bc/dashboards/0649b03029c49000?lower=now%28%29%20-%202d) you can select a customer's `orgId` to have the dashboard show information about that specific org.

The problem with this is that there are 2000+ orgs, all with fairly similar names, finding the correct one in that long list is too hard.

It would be nice to be able to search for a matching `orgId` by typing (or pasting) the `orgId` you were looking for in to that box as well as using the dropdown (combo box style).

While you can shortcut this a bit by alerting the URL to include the `orgId` this is non-obvious.  Proper UI support would be preferable.

**Comment by barbaranelson** [comment]
This is addressed with @jrenee42 variable type-ahead fix. @jrenee42 can you close this when your feature is live in prod? Thanks.

**Comment by jrenee42** [comment]
@barbaranelson  the feature is in prod; but it is behind a feature flag.
so close it now?
 or wait til the flag is gone and it is available by default?

**Comment by barbaranelson** [comment]
I would wait until the flag is gone, so that is is generally available without people needing to know to set the flag.
