### ISSUE TITLE
i would like to add telegraf plugin configurations to a new or existing telegraf configuration

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#784]
we have landing pages for each of the telegraf input plugins. for example: 
![image](https://user-images.githubusercontent.com/4805997/110148591-d7d93b80-7d91-11eb-8f8e-62be889b7da4.png)

We also now have the ability to edit Telegraf Configs in the UI.

I would like a way to easily add the input plugin configuration to an existing telegraf configuration.

### Acceptance Crit
as a user, i would like a way to quickly add an input plugin configuration to an existing telegraf configuration from a plugin landing page

### Notes
 - The telegraf pages are all rendered from a single template: https://github.com/influxdata/ui/blob/master/src/writeData/containers/TelegrafPluginsPage.tsx
 - The default telegraf config is available in the included `<plugin.md>` files
 - The page flow should go from the Telegraf Plugin Details page directly to the "Edit Telegraf Config" modal, so that the user can customize the plugin configuration before saving it.

**Comment by jzahnd** [comment]
Closing due to age
