### ISSUE TITLE
Data Explorer: Tag filters don't work with the forward slash character

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#798]
to repro:

1. open DE, select bucket
2. in the _measurements box, type ` some/thing` in the box
3. notice that the request fails because it is an invalid regex

`message: "compilation failed: error at @7:36-7:46: regex parse error: (?i:some error: unclosed group"`

![image](https://user-images.githubusercontent.com/4805997/110396311-ae840e00-8024-11eb-8d59-4984d5435519.png)

**Comment by TCL735** [comment]
This also fails on other characters.

The cause is a Regex that uses the search term inside of it. Regex has special characters that must be escaped including the forward slash.
