### ISSUE TITLE
Add auto refresh back to dashboards

### ISSUE THREAD

**Issue by desa** [influxdata/ui#8]
# Background

We had originally removed the auto-refresh feature from dashboards because users were racking up large bills. However, as we have recently adjusted the pricing of the cloud product we would like to add the ability to auto-refresh. We would like to add some additional functionality to prompt the user to reconfirm that they want to continue auto-refreshing.

## Acceptance Criteria

GIVEN that I am on a dashboard
WHEN I select an auto-refresh interval
THEN my dashboard should refresh all visible cells on the dashboard

GIVEN that I have a dashboard open
AND that I've selected an auto-refresh interval
WHEN I am on that page for more than 1h
THEN I should be prompted to reconfirm that I want my dashboard to continue to auto-refresh

**Comment by Asalem1** [comment]
Whatever work is done here will need to consider syncing up with the existing query cache
