### ISSUE TITLE
Flows: Metric selector deleteing one tag deletes all tags

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#81]
WHEN i click the delete option on a tag in metrics selector
THEN it should delete only that tag and not all tags

![Kapture 2020-09-21 at 16 03 45](https://user-images.githubusercontent.com/4805997/93830083-13d57580-fc24-11ea-8fb6-15a1cf16bd74.gif)

**Comment by drdelambre** [comment]
multiselect seems to be hardcoded to command select... which isn't available on windows or linux. should clean that up with this bug fix as well
