### ISSUE TITLE
Flows: Metric Selector: As a user, i should be able to see the resulting selection

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#83]
GIVEN i have selected at least a bucket from the metrics selector
WHEN i click the run flow
THEN i am able to see the results of the metric selector as a raw data view

**Comment by alexpaxton** [comment]
Raw data view baked in to every cell

**Comment by drdelambre** [comment]
translated for humans: https://github.com/influxdata/ui/issues/110

**Comment by drdelambre** [comment]
closing this in favor of the other that we introduced this morning
