### ISSUE TITLE
Notebooks: Preview should not be available until the metrics selector has a metric selected

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#840]
clicking preview on a notebook where the metric selector doesn't have a metric selected results in an unresponsive page while we attempt to load way too much data.

We should look for a way to guide people to try to select a metric before running preview. i'm open to options here. we could have a warning shown or we could disable the option completely.

if someone is using a custom script, there isn't much we can do.

**Comment by barbaranelson** [comment]
Closing out as no longer applies (we've gotten rid of the metric selector panel).
