### ISSUE TITLE
Notebooks: merge repeating headers

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#842]
in the simple data view, we repeat the header for every table definition in the result. this is a great, clean abstraction of the underlying data. but it causes a lot of wasted pixels for some types of queries, specifically ones that return limited results within similar series. Looks kind of like this:

![image](https://user-images.githubusercontent.com/1434802/111187312-20061400-8571-11eb-9a52-419fd810a0d7.png)

What we want is to stop generating header rows for tables that have the same column signatures (order, name, type, group, etc). If table `n` has the same header row as `n + 1`... just keep throwing those table rows into the previous table.

This solution should not merge all tables that have the same header row, just if they are sequential

**Comment by russorat** [comment]
Note that the response from Flux does not have duplicated headers, so we are adding them somewhere in the UI codebase.

![image](https://user-images.githubusercontent.com/4805997/111192896-cf91b500-8576-11eb-9376-c7cd446bcfc3.png)

**Comment by russorat** [comment]
is this still an issue? @drdelambre
