### ISSUE TITLE
Format Document option in script editor doesn't do anything

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#843]
in script editor, right clicking and selecting format document on a poorly formatted query doesn't do anything. it used to reformat the query.

![Kapture 2021-03-15 at 09 52 53](https://user-images.githubusercontent.com/4805997/111190377-3feb0700-8574-11eb-974e-85f66f6af5b2.gif)

**Comment by jzahnd** [comment]
Are you still able to reproduce this, looks like it may not be an issue any more?
