### ISSUE TITLE
Remember the filter for the list pages

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#844]
the experience today is that you go to the tasks page (or dashboards page), use the filter to find the tasks you want, then click on one of them. When you click the back button in the browser, you are back to the page with no filters in place.

Users can have 100s of tasks, so i'd love to be able to save that filter and get back to it.

I propose we find a way to keep the filter in place when a user clicks the back button specifically for the tasks page.

**Comment by russorat** [comment]
i think the experience we want here is that if a user clicks the browser back button to return to a list page, then the filter they were using should still be there. if they click forward in the left nav or another part of the app to get to the list page, the filter should be removed.

**Comment by russorat** [comment]
how does an in-app back button change the implementation here? wouldn't you use the same history methods in that back button?

**Comment by subirjolly** [comment]
Will add Dashboards in this issue as well.

**Comment by russorat** [comment]
just to update, we've decided keeping the filter unless you delete or refresh makes sense here.
