### ISSUE TITLE
Annotations End to End test: Do the annotation thing

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#849]
### Background
This is the overall, high level, end to end test.

### Acceptance Criteria
Things to test:
#### Sahas + Slotman
- Stream work
  - Clicking the x on a stream pill removes that pill from the control bar and stops rendering that stream
    - Searching the stream list when a pill has been removed shows the removed stream
      - Clicking the removed stream adds it
  - Searching the stream list when the pill is active doesn't show it

#### Zoe
- With one click annotations enabled
  - Clicking the graph with the control bar open creates an annotation
  - Clicking the graph with the control bar closed creates an annotations
  - The text written is the text that shows up in the tooltip

#### First come, first served
- Clicking the Annotation button next to the variable button toggles the control bar
- Disabling one click annotations disables adding annotations

**Comment by daviddkkim** [comment]
@ChitlangeSahas mic check

**Comment by daviddkkim** [comment]
@ChitlangeSahas mic check back again
