### ISSUE TITLE
Annotations: Consider updating UX of search bar in AnnotationsControlBar

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#857]
### Background
We only have one stream. It's kind of confusing having a search box for the single stream we have. We should figure out how to deal with the search box until we support multiple streams.

Possible ideas:
Change the placeholder text to make it clear you've already enabled the default stream
Shrink the box after the default stream is enabled

**Comment by barbaranelson** [comment]
Could we just hide the search box altogether? Do we need it if we only have one stream?

**Comment by hoorayimhelping** [comment]
Problem has been solved. Closed with: #901
