### ISSUE TITLE
refactor: replace Table graph in UI with Table from Giraffe

### ISSUE THREAD

**Issue by ChitlangeSahas** [influxdata/ui#860]
The goal of this is to replace the Table implementation in the UI with the implementation in the Giraffe library. This will allow us to improve the graph without making the change in two places.

All these changes should be behind the `useGiraffeGraphs` feature flag.

**Comment by zoesteinkamp** [comment]
I thought this was already done? Im going to check and see as this feature flag is already running in prod. So we would need a new one

**Comment by jrenee42** [comment]
apparently this one is stuck in limbo: https://github.com/influxdata/ui/pull/836
