### ISSUE TITLE
Error States when Map is not rendered

### ISSUE THREAD

**Issue by Palakp41** [influxdata/ui#866]
Currently, we have two error states when map is not rendered:
1. When Map service is down or returns an error we display:
    > Map type is having issues connecting to the server. Please try again later.'
2. When data provided is not supported by Maps, for ex: not given lat or lon, we display:
      >  Map type is not supported with the data provided: Missing latitude/longitude values

@kristinarobinson Is this wording right to display in these cases? if not, who do we reach out to get proper decision.

**Comment by daviddkkim** [comment]
@Palakp41 

1. I don't see any glaring problems here. 
I'm no expert in this catagory but how about going along the lines of `We are having issues connecting to the Maps Server. Please try again later`?  Not a big deal at all to go with what we have. It is clear enough! 

2.How about  `Map type is not supported with the data provided. Map type only supports latitude/longitude values ` ?

**Comment by Palakp41** [comment]
@daviddkkim this looks good. I will update it
