### ISSUE TITLE
as a user, i can set auto-refresh and idle timeout configuration options for my organization

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#87]
As an admin user, i would like to set settings at the org level for the other users of my organization.

GIVEN that I am an admin and on the Settings area of the cloud app
WHEN i click on a tab for org settings
THEN I see a setting to enable/disable automatic refreshing for my organization
THEN I see a setting to configure idle logout in minutes for my organization

NOTES: 
- default automatic refresh is on
- the default idle timeout is 30 minutes
- Idle timeout is the amount of time with no input via mouse or keyboard from the user

WHEN i click on the control for enable/disable automatic refresh
THEN refreshing is toggled on or off for the app

WHEN i click in the area of the idle timeout value
THEN I can type in a new idle timeout value

WHEN i click the save button
THEN the settings are saved to my org

**Comment by russorat** [comment]
As an admin user, i would like to set settings at the org level for the other users of my organization.

GIVEN that I am an admin and on the Settings area of the cloud app
WHEN i click on a tab for org settings
THEN I see a setting to enable/disable automatic refreshing for my organization
THEN I see a setting to configure idle logout in minutes for my organization

NOTES: 
- default automatic refresh is on
- the default idle timeout is 30 minutes
- Idle timeout is the amount of time with no input via mouse or keyboard from the user

WHEN i click on the control for enable/disable automatic refresh
THEN refreshing is toggled on or off for the app

WHEN i click in the area of the idle timeout value
THEN I can type in a new idle timeout value

WHEN i click the save button
THEN the settings are saved to my org

**Comment by jzahnd** [comment]
Closing due to age, we can reopen if needed
