### ISSUE TITLE
i can't understand the time displayed in the simple table

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#887]
The timestamp format for the current simple table is in unixtime, which is difficult for humans to understand:
![image](https://user-images.githubusercontent.com/4805997/112360696-d2378d00-8c8f-11eb-80da-2c118d72018f.png)

Let's format this timestamp using the same format returned from the flux query, in UTC timezone.

`2021-03-23T18:00:00Z`

**Comment by mnorriswalker** [comment]
@gefaila tagging you so you can watch this issue. Thanks for raising!
