### ISSUE TITLE
Hide metric selection dropdown when finished selecting

### ISSUE THREAD

**Issue by samhld** [influxdata/ui#891]
**Current behavior:**
When selecting metrics, [all metrics drop down](https://github.com/influxdata/ui/issues/384), but when you're done selecting metrics, the list persists in your view.  This takes up a lot of the available workspace.  When working with notebooks, being able to see context (multiple cells) is important.  With this in the way, that is hindered.  

**Desired behavior:**
I'm of the opinion that it should be hidden/removed when metrics selection is done.  I do, however, think it needs to be possible to make it visible again if you want to make changes.  I think this dropdown should either have a "Hide" button that becomes "Show" when hidden, or simply be part of query cells (with similar behavior to the Data Explorer).  I realize this has been discussed multiple times already so I don't mean to pile on -- just pointing out that specific aspect of the DE is really nice.

**Comment by asalem1** [comment]
Closing this since this feature has been deprecated and not actively being worked on
