### ISSUE TITLE
Add Easy Clearing to Text Input Fields

### ISSUE THREAD

**Issue by jrenee42** [influxdata/ui#898]
Create a text input field that has an 'x' in the right that clears the field on one click.
also allow the user to press 'esc' when the field is focused to clear the field as well.

make sure that the 'esc' doesn't close a dialog (if a dialog is in use); and clears the textfield instead.

this is a UI-only feature, doesn't require any backend work.

idea is to create a new component in clockface, then to use it/enable it one by one in filter positions (especially in the bucket selection field, as requested by @alsargent )

here is a pic of how the input would look  (ignore the field colors/borders,  this is about adding an 'x' in the field)
![Screen Shot 2021-03-18 at 3 14 09 PM](https://user-images.githubusercontent.com/3900960/111684155-ba2dbc80-87fc-11eb-81a7-1d81398ea48a.png)

Here is the first place that would get it
![image](https://user-images.githubusercontent.com/3900960/111683747-4390bf00-87fc-11eb-8916-14a7d08e8496.png)

**Comment by daviddkkim** [comment]
Chatted with Jill but adding comment here for visibility - 

I think I like the idea of the ESC button clearing text.
I'm not a fan of adding the X button to the end of the input.  
My fear is it could make things look a little too crowded in the input while the X wouldn't provide a whole lot of value. 

@jrenee42 could you elaborate on what problem this solves?

**Comment by mavarius** [comment]
I'm with @daviddkkim on this.

The clear button is unnecessary and will present conflict with the password text visibility control. I'm mostly ok with the `esc` key clearing the field but since having `esc` close modals is a common accessibility action for keyboard navigation I can't agree with overwriting that function in favor of clearing the field.

**Comment by jrenee42** [comment]
@mavarius and @daviddkkim  @alsargent  asked for this.

because bucket names are long, and this would speed him up while using our product (especially for tech demos)

@alsargent  said:

>I'm going through the UI to figure this out. One somewhat-related feature request: when I'm searching a field, let me press ESC to clear the contents of a filter field.

For example, here's the Buckets screen. I've typed re. If I press, I'd like the re to go away, and the filtering to go away as well. That'd speed things along a bit when I'm working with the product.

**Comment by jrenee42** [comment]
also, when talking to @barbaranelson  today, when we were using the type-ahead variable dropdown (which utilizes a text input field) she asked: 'how do I clear this?'
an 'x' in the field when it is active would show the affordance for that.  (especially with long text inputs; you have to select it all (ctrl-a); then hit delete.  as opposed to just clicking an 'x'

**Comment by daviddkkim** [comment]
@jrenee42 
Could we make this change in the Clockface input component. We could make this an optional prop and use it for specific inputs (I.E ,long filter inputs for our list pages as we talked about in standup!)

**Comment by russorat** [comment]
adding comments from planning this morning:
- Just add the `x` to clear the text to the text box (no esc key shortcut)
- Add them to the filters on each list page

**Comment by mavarius** [comment]
A few comments on this:
1. This type of change is 100% a clockface component issue so make the change there according to https://github.com/influxdata/clockface/issues/616 and not in the UI repo.
2. People already complain about having to tab once more on the password fields because of the obfuscation control. This will be the same problem because that control will need to be keyboard accessible.

**Comment by kristinarobinson** [comment]
Closing, as this will be address in clockface#616, rather than a ui issue.

**Comment by kristinarobinson** [comment]
work is done, but located in branch and cannot be checked in until https://github.com/influxdata/clockface/issues/616 is completed.
