### ISSUE TITLE
make task and check history pages more accessible and consistent

### ISSUE THREAD

**Issue by genehynson** [influxdata/ui#917]
Currently our task history page is buried in a hidden button's dropdown menu. It's possible to create tasks and never know that this functionality exists. 

![image](https://user-images.githubusercontent.com/6411855/111830261-f0297a00-88aa-11eb-862a-4c0f6087b41e.png)

This page is super critical to the whole concept of running tasks. If I create a task to run routinely, I would certainly want a page to see the history of this task being run!

The same can be said for checks:

<img width="1082" alt="Screen Shot 2021-03-19 at 12 30 39 PM" src="https://user-images.githubusercontent.com/6411855/111833236-223cdb00-88af-11eb-92fd-35fc9687c0d5.png">

I created a check and want to know if it's working - finding this tiny button with no text is very difficult. Also the fact that these buttons are different between the pages is not ideal. And we use this 👁️ icon in other parts of the app to mean "hide this from me". 

Proposal: Bring this page to the forefront of the tasks and checks page. I'm thinking a second column that shows the history of the currently selected task. As you click from one task to the next, the column on the right changes to show the history of the currently selected one. Or perhaps expand/collapse functionality? Or maybe just show the most recent run under the task/check? Or just an easier to find button with some text? Other design options welcome.

**Comment by genehynson** [comment]
Side note: I would love for this task history component to become a notebook "panel" that we can reuse in various places

**Comment by kristinarobinson** [comment]
Fixed.
