### ISSUE TITLE
check/alert status should be available on the homepage

### ISSUE THREAD

**Issue by genehynson** [influxdata/ui#919]
As a user I want to be able to see my checks and their status on the homepage of cloud2 so that when I login, I can immediately know about events that are important to me.

Right now it takes a bunch of clicks to find the status of your checks. You have to 1) go to the alerts page and then FOR EACH alert, 2) click the 👁️ , 3) click "view history". That's an expensive ask for users to do every time they log into cloud2. 

Instead we should present this information front and center when the user logs in. Underneath the typical "getting started" information we should present a list of alerts/checks along with their current status. Each alert should have a deep link to take you to the history page. The user should also have the option to create new alerts from the home page.

User task flow of this new process: 1) login to cloud2 2) eyes are drawn to the ❌  next to one of your checks, 3) view the history and discover why it failed, 4) create an alert based on this check so you know when this event happens again. 

Example dashboard with the status of all your checks: 

![image](https://user-images.githubusercontent.com/6411855/111834146-667cab00-88b0-11eb-989c-cd2fb7d52bba.png)

Example dashboard for overall health of your checks: 

![image](https://user-images.githubusercontent.com/6411855/111834239-89a75a80-88b0-11eb-8a57-c494cff7d199.png)

cc: @rickspencer3

**Comment by rickspencer3** [comment]
May I suggest we include an affordance on the homepage to "create a check" that would then bring up the existing check creation UI, and then we can display the resulting statuses? Ultimately, we could go on to add a "notify me" button to the statuses.

**Comment by subirjolly** [comment]
* What does the UI look like? Is there a section below everything on the Getting Started page?
* Example Dashboards shown in the story. What's the significance of those dashboards? Is that just showing the Status page(where we should land) when you click on one of the alerts/checks listed on the Getting Started page?

**Comment by subirjolly** [comment]
Another question. Is this widget going to be constantly updating? If so, what's the interval?

**Comment by russorat** [comment]
This is blocked until we have someone from design look at it.

- let's put this behind a feature flag
- the UI for this should look very much like the alert history page, which can be found by expanding the left nav and clicking on the "Alert History" page.

![image (68).png](https://images.zenhubusercontent.com/5b3fe490ebfac043864dcd28/4ed7335c-b80c-401e-a5fb-fe6dff6ef02e)
- For now, the widget isn't updating, and the user would refresh the page.
- this would go below the 3vgetting started panels on the homepage.

**Comment by subirjolly** [comment]
this is now behind `alertsActivity` flag
