### ISSUE TITLE
Idea: Stop parsing CSV in the UI

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#920]
We have mechanisms to upload csv data into the UI. We have custom parsers for that code.

This issue it to replace our javascript based parsing with calls to the query api using the `csv.from` and `to` syntax for flux: https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/csv/from/

the experience could be similar to dropping an image into a github issue. User could drop an LP file into our UI, and we upload the file and give it a unique url. then we run `csv.from(url: "that new url")`

We could do that on any code editor in the UI.

**Comment by drdelambre** [comment]
we tried this and ran into an issue where we couldn't upload files that we had _just_ downloaded from the api because of a mismatch between limits on both systems. was this fixed since we release this?

**Comment by russorat** [comment]
which api and system are you referring to?

if it was our own, was there an issue opened to address this?

**Comment by drdelambre** [comment]
offlined: 

i got turned around with having both line protocol and csv in here.

LP has a 10MB upload limit, csvs _may_ not, but that hasn't been confirmed.

it would also be super dope if we could do this without using the `csv.from` mechanism (which implies additional storage costs for keeping replicated data around + tasks for bulk updates). streaming partials to the storage backend would provide better scalability with lower operational cost, but we should also stop writing annotated csv parsers. we're bad at that, so lets try to move any of that logic as close to the subsystem that generates our annotated csvs in the first place (queryd?)
