### ISSUE TITLE
Make save an explicit action in notebooks

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#923]
In notebooks, we auto-save.  This is inconsistent with the rest of the UI (where we have a check to save or an X to discard), and makes it really easy to lose your work. If you go into a notebook and change the query, you can't undo it and go back to what you previously had.

I think it would be preferable to have a cancel/save option on notebooks, just like we do on the data explorer, tasks, checks etc. so that updates to a notebook would be more intentional.

**Comment by mnorriswalker** [comment]
Autosave is what we'd like to do for now and bring forward a history that you could walk back. This is more of cloud UI pattern like (Google Docs) that we're looking to incorporate across the UI.
