### ISSUE TITLE
Update the way Upgrade Now button is rendered

### ISSUE THREAD

**Issue by Asalem1** [influxdata/ui#930]
The UI currently relies on a user being PAYG to not render the Upgrade Now button, but we need to also consider a `free` account in a `beta` region when not rendering that button. That is to say, that if a user has signed up in a beta region with a free account, they should **not** see the Upgrade Now button. This will be blocked on the new /me API being developed by Quartz

**Comment by gunnaraasen** [comment]
The specific cluster URL is europe-west1-1.gcp.cloud2.influxdata.com.

**Comment by Asalem1** [comment]
Waiting on the `/me` endpoint to be created

**Comment by Asalem1** [comment]
This logic should be behind a feature flag since it isn't hasn't been tested live and we don't want to muck up any existing user experiences
