### ISSUE TITLE
Account Deletion - Free single user orgs

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#934]
GIVEN I am a Free user in Cloud 2
WHEN I want to cancel/delete my account
THEN I am given a self-serve option that lets me delete my account
AND my email address is no longer blocked from being added as a user in another Org, or used for creating a new Workplace account

## Acceptance Criteria [User Experience]

-  On the `/About` page we add a new option for 'Delete Organization'
- The 'Delete Organization' option is only visible to FREE accounts
- The 'Delete Organization' button is DISABLED if more than one user is associated with organization
- Clicking the disabled button opens a notification that "All additional Users must be removed from the Organization before the account can be deleted.", along with a link to the `/Users` page
- (if enabled) The 'Delete Organization' button opens a confirmation overlay
- The confirmation dialog displays alert that "This action cannot be undone" and a list of conditions 
- The confirmation overlay displays a toggle button for "I understand and agree to these conditions"
- Selecting the toggle button will enable the button to delete the account
- Clicking the 'delete' button will perform all actions necessary for account deletion
        https://app.zenhub.com/workspaces/applicationecommerce-5cf5c37ac6deac1e99bc6284/issues/influxdata/quartz/4270

- Once account deletion has been completed, redirect the user to a marketing Landing Page for offboarding users
Page url: https://www.influxdata.com/free_cancel/

### Error States
- IF The user clicks the 'Delete' button and the account has more than one user 
- THEN display the warning message "All additional Users must be removed from the Organization before the account can be deleted."

- IF the organization can not be deleted (when the user triggers the deletion)
- THEN display the error message "There was an error deleting the organization, please try again." 

## Design 
https://www.figma.com/file/0gNEHedxD1J0bb1mkie6Aw/Free-Users-Account-Deletion?node-id=57%3A461

## Related Issues
https://github.com/influxdata/quartz/issues/4270

## Team
Design: lead @corriganjohn (secondary @juliajames12 )
Product: @gunnaraasen
Engineering Ecommerce & UI Team: @Asalem1 @alejom99

**Comment by mnorriswalker** [comment]
@jzahnd @russorat - can we unblock this epic? I think we're going to need a release date to coordinate the pieces here. We need inputs from the SFDC Admin Justin, and Marketo Admin Morea, Docs, and then we need to notify support. Any idea on a release date?

**Comment by Asalem1** [comment]
Question about this:

```The 'Delete Organization' button is DISABLED if more than one user is associated with organization

Clicking the disabled button opens a notification that "All additional Users must be removed from the Organization before the account can be deleted.", along with a link to the /Users page```

Seems like an anti-pattern to have a disabled state with a click event (not sure if clockface supports that). Did we want to have an on mouseEnter event trigger this?
