### ISSUE TITLE
I am redirected to the off boarding page after deleting my account

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#936]
## Acceptance Criteria
WHEN a free account user has successfully deleted their account and clicked the confirmation button
THEN they are directed to a landing page - https://w2.​influxdata.​com/free_cancel/
IF no landing page exists THEN redirect to cloud2 signup page

## Design 
https://www.figma.com/file/0gNEHedxD1J0bb1mkie6Aw/Free-Users-Account-Deletion?node-id=57%3A450

**Comment by corriganjohn** [comment]
Marketing page for free account deletion: https://www.influxdata.com/free_cancel/

The Marketo form + SFDC integration will be done by Morea Pollet and Justin Cheverie.

**Comment by Asalem1** [comment]
This is blocked on the site being finished

**Comment by mnorriswalker** [comment]
I don't think this is blocked because we can complete this story by linking to the URL: https://www.influxdata.com/free_cancel/

It's missing an embedded offboarding survey but I've followed up with Morea Pollet and Justin Cheverie for a status update and we can add that to the landing page as soon as we get it.

**Comment by gunnaraasen** [comment]
To unblock this, can we redirect to the sign-up page with a flash notice for now?

**Comment by mnorriswalker** [comment]
This is unblocked. Please link to https://www.influxdata.com/free_cancel/ the page just needs a form embedded which will be done imminently. Embedded the form will be done out of band of engineering by us.

**Comment by mnorriswalker** [comment]
Getting data about why users are cancelling is vital. The page also let's start A/B testing. Please do NOT redirect to signup. Please link to offboarding page https://www.influxdata.com/free_cancel/

**Comment by corriganjohn** [comment]
- Salesforce integration work to create 'reasons for cancellation' is complete
- Marketo integration and updated Marketing page (https://www.influxdata.com/free_cancel/) to be completed by Friday July 16
