### ISSUE TITLE
I see an email confirmation when I delete my account

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#937]
## Acceptance Criteria
WHEN a user successfully deletes their free account
THEN they are sent a confirmation letter that the account has been deleted

## Design
https://www.figma.com/file/0gNEHedxD1J0bb1mkie6Aw/Free-Users-Account-Deletion?node-id=57%3A452

## Email Content

Subject: Your free InfluxDB Cloud account has been successfully deleted
Header: We’re sorry to see you go. 😢
Body: 
Hi {{FirstName}},

You’re receiving this because you recently deleted your free account in <OrgID> for InfluxDB Cloud. We’re sorry to see you go, but we’re hopeful it’s because you just wanted to join an existing Organization or maybe you wanted to sign up again using one of the various **Marketplace** solutions we offer.

In any case, thanks for being with us, and if we can be of any further help please feel free to reach out to us at support@influxdata.com

CTA Button: "Sign Up"

LINKS: 
"Marketplace" links to https://www.influxdata.com/cloud-partners/
CTA: https://cloud2.influxdata.com/signup

**Comment by jzahnd** [comment]
Auth0 might send this confirmation for us?

**Comment by jzahnd** [comment]
Closing due to age, we can bring it up again when / if needed
