### ISSUE TITLE
as a user, i should be logged out after my idle timeout

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#94]
we should respect the idle timeout limits set in the org settings page and log the user out if they have not interacted with our app via the mouse of keyboard.

GIVEN that i have not interacted with the browser window for more than the idle timeout
WHEN I the next call to me is issued
THEN I am logged out of the app

WHEN I try to browse to another page in the app
THEN I am logged out of the app

**Comment by jzahnd** [comment]
Closing due to age, we can reopen if needed
