### ISSUE TITLE
As an owner, I can remove myself from an org

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#949]
Currently, you have to have another owner remove you and you can't remove yourself.

**Comment by barbaranelson** [comment]
This should be tracked separately and shouldn't be in the epic to delete free single-user accounts.  If you are the only user, you can delete the account.

**Comment by mnorriswalker** [comment]
Oops @barbaranelson moved to Multi-Org Deletion https://github.com/influxdata/ui/issues/1012
Blocked by https://github.com/influxdata/ui/issues/934
