### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot set property 'status' of undefined

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#959]
To repro, issue a long query in DE, and click cancel.

![image](https://user-images.githubusercontent.com/4805997/112248133-ab874100-8c12-11eb-95a8-4988e131ea41.png)

**Comment by russorat** [comment]
likely culprit: https://github.com/influxdata/ui/blob/master/src/timeMachine/actions/queries.ts#L210

**Comment by Asalem1** [comment]
So close! https://github.com/influxdata/ui/blob/master/src/timeMachine/actions/queries.ts#L241
