### ISSUE TITLE
Demo data dashboard counts against max number of dashboards

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#974]
If you enable demo data, it creates a dashboard Website Monitoring Demo Data Dashboard, and a bucket Website Monitoring Data, which is labeled as no cost. The bucket is no cost, but the dashboard counts against the maximum number of dashboards I am allowed to have in my free account.

Not sure if this is intentional or not.

**Comment by kristinarobinson** [comment]
We will updating demo data handling.  We will not fix this defect specifically, but it will be addressed when demo data is refreshed.
