### ISSUE TITLE
Adding/removing demo data duplicates demo data dashboard

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#975]
Add demo data from the buckets screen. It will add the bucket and the dashboard.
Delete the bucket and it still keeps the dashboard even though it doesn't have any data.
Add demo data again, and now you'll end up with a duplicate dashboard.

There doesn't seem to be an easy way to remove demo data without knowing what resources it created.

**Comment by kristinarobinson** [comment]
Since we are updating demo data, we will not fix this.
