### ISSUE TITLE
Notebooks: Add ability to pivot in the query builder panel

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#983]
Per @abalone23 It would also be nice to have an additional “Pivot” option in the Query Builder ie FILTER, GROUP, PIVOT. That way I wouldn’t need to add a flux script with `schema.fieldsAsCols()`

![nb1.png](https://images.zenhubusercontent.com/5d928b2631e8dd0001222f82/13b9ec39-3990-4f4f-8f8c-6b1c76adbbad)

**Comment by barbaranelson** [comment]
Update title to make it clearer what needs to be added.

**Comment by jzahnd** [comment]
@barbaranelson @garylfowler is this still a priority?

**Comment by barbaranelson** [comment]
I would let the query folks think about this as part of the query overhaul. It's basically proposing that we be able to do another flux function (pivot) without switching to the raw flux editor. I don't have a strong opinion (I've no idea how commonly pivot is used).  @garylfowler can you bring it up with Nathaniel as to whether this is something that should be incorporated into the query rework when you get that far?

**Comment by garylfowler** [comment]
Will do.

**Comment by garylfowler** [comment]
This naturally came up in our meeting even without asking about it.   No conclusions made (we aren't at that point in the process yet), but seems likely we will do something related to this - but we can hold for now until we are farther along in that process.

**Comment by jzahnd** [comment]
Closing due to age and context
