### ISSUE TITLE
Annotations: I would like an indication that the graph type doesn't support annotations

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#986]
Watched a user enable annotations, then click on a "Graph + Single Stat" graph and nothing happened. Then they clicked many times, and still nothing. They left with the impression that the feature was broken or incomplete.

GIVEN that i have annotations enabled and i am in one click annotation mode
WHEN i click on a graph type that doesn't support annotations
THEN i see some indication that annotations are not supported on the graph type

**Comment by hoorayimhelping** [comment]
![Screen Shot 2021-03-25 at 6.28.06 PM.png](https://images.zenhubusercontent.com/5c33b08d24dda4712ef4ae10/a07d2781-fc55-44bd-ab89-41c60c16242f)

with the text

>Currently, we only support annotations on XY Plots

**Comment by hoorayimhelping** [comment]
already finished
