### ISSUE TITLE
Organization / About page updates : Post UI Unification

### ISSUE THREAD

**Issue by corriganjohn** [influxdata/ui#992]
GIVEN I am a Cloud 2 user and I want to see information related to my ID and my Organization
WHEN I navigate to the Organization / About page
THEN I can see the relevant information
AND I can easily copy to the clipboard

## About
- Use two column responsive layout (collapse to one column at smaller screen size)
   - Column 1: My Data + Application Data
   - Column 2: Organization Data

Three Data Sections:
- My Data (data field / functions)
   - UserId 
   - Name 
   - Email 

- InfluxDB Cloud API Endpoint (copy only)
   - Button to link to the API Documentation
      - "https://docs.influxdata.com/influxdb/cloud/reference/api/" (new window)
   - API Endpoint 

- Organization Data (copy only)
   - OrgName
   - OrgID
   - Cloud Service Provider
   - Cloud Region
   - InfluxDB Cloud URL
   - Danger Zone (highlights that these functions can have wide range effect)
      - Rename Org
      - Delete Org -- ONLY visible to FREE accounts (PAYG accounts must Cancel Service on Billing page)

# Design for About
https://www.figma.com/file/qtdRCOYCRslXJvYIZBhMQi/About-Q2-2021?node-id=1681%3A1

## Design Zenhub Epic
https://app.zenhub.com/workspaces/teamdesign-5f7e450d26b3010018884d96/issues/influxdata/design-resources/38

**Comment by barbaranelson** [comment]
Delete org should only be visible to free single-user accounts. If there is more than one user in the account and one user deletes the org, we create problems for the other users in that account.

**Comment by corriganjohn** [comment]
Removing the EDIT function for the user fields (name and email). Editing these fields is not currently supported

**Comment by jzahnd** [comment]
Closing due to age
