### ISSUE TITLE
Maps: Add the ability to interpret the s2_cell_id from a tag field

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#998]
as a user who has been leveraging the https://github.com/influxdata/telegraf/tree/master/plugins/processors/s2geo telegraf plugin to tag my data with `s2_cell_id` tags, then i would like to be able to leverage that tag value without needing further processing.

**Comment by Palakp41** [comment]
https://app.zenhub.com/workspaces/applicationui-5e3b05772922e316b3a210a4/issues/influxdata/ui/999 being fixed will fix this issue/bug.
