### ISSUE TITLE
Placeholder: add the ability to select the field name to use for lat/lon OR the tag name for s2 cell id

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#999]
as a user with geo data in my instance, the data might be stored as fields with different names than the maps widget expects.

### Lat Lon Stored as Field Values
given i have data with latitude/longitude stored as fields
when I attempt to display that data as a map
then i would like the ability to choose the fields that contain that lat/lon data

~given i have data with latitude/longitude stored as tags~
~when i attempt to display that data as a map~
~then i would like the ability to choose the tags that contain the lat/lon data~

### S2_cell_id stored as tag value
given i have data with the s2_cell_id calculated and stored as a tag value
when i attempt to display that data on a map
then i would like the ability to choose that s2_cell_id to use as the lat and lon values

~given i have data with the s2_cell_id calculated and stored as a field value~
~when i attempt to display that data on a map~
~then i would like the ability to choose that s2_cell_id field to use as the lat and lon values~

**Comment by Palakp41** [comment]
Will break this issue into multiple parts.

**Comment by Palakp41** [comment]
This ticket is just a placeholder for all the broken down stories I have created below:

https://app.zenhub.com/workspaces/applicationui-5e3b05772922e316b3a210a4/issues/influxdata/giraffe/520
https://app.zenhub.com/workspaces/applicationui-5e3b05772922e316b3a210a4/issues/influxdata/idpe/10265
https://app.zenhub.com/workspaces/applicationui-5e3b05772922e316b3a210a4/issues/influxdata/ui/1027
https://app.zenhub.com/workspaces/applicationui-5e3b05772922e316b3a210a4/issues/influxdata/ui/1029

**Comment by russorat** [comment]
@Palakp41 i removed the requirements for lat/lon as tags and s2 cell id as field.

**Comment by kristinarobinson** [comment]
Removing from MVP
